"""
TouchStone v1 — Dispatch Engine
================================
Routes deliverables to the correct agent's dropzone via file-based handoff.
"""

import json
import sys
from pathlib import Path
from datetime import datetime, timezone

TOUCHSTONE_DIR = Path(__file__).resolve().parent
REPO_ROOT = TOUCHSTONE_DIR.parents[1]
MANIFEST_PATH = TOUCHSTONE_DIR / "manifest.json"

OWNER_DROPZONES = {
    "bishop": REPO_ROOT / "BISHOP_DROPZONE" / "TOUCHSTONE_TASKS",
    "knight": REPO_ROOT / "KNIGHT_DROPZONE" / "TOUCHSTONE_TASKS",
    "rook": REPO_ROOT / "ROOK_DROPZONE" / "TOUCHSTONE_TASKS",
    "pawn": REPO_ROOT / "PAWN_DROPZONE" / "TOUCHSTONE_TASKS",
    "founder": REPO_ROOT / "FOUNDER_ACTION_QUEUE",
}


def load_manifest() -> dict:
    return json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))


def dispatch_deliverable(deliverable_id: str) -> dict:
    """Write a task file to the correct agent's dropzone."""
    manifest = load_manifest()

    deliverable = None
    for d in manifest.get("deliverables", []):
        if d["id"] == deliverable_id:
            deliverable = d
            break

    if not deliverable:
        return {"dispatched": False, "reason": f"Deliverable '{deliverable_id}' not found"}

    owner = deliverable.get("owner", "")
    if owner not in OWNER_DROPZONES:
        return {"dispatched": False, "reason": f"Unknown owner: {owner}"}

    dropzone = OWNER_DROPZONES[owner]
    dropzone.mkdir(parents=True, exist_ok=True)

    safe_id = deliverable_id.replace("/", "_").replace("\\", "_")
    if owner == "founder":
        task_path = dropzone / f"TOUCHSTONE_{safe_id}.md"
    else:
        task_path = dropzone / f"{safe_id}.md"

    # Resolve dependency info
    deps_info = []
    for dep_id in deliverable.get("depends_on", []):
        for dd in manifest.get("deliverables", []):
            if dd["id"] == dep_id:
                deps_info.append(f"- **{dep_id}**: {dd.get('title', '?')} (status: {dd.get('status', '?')})")
                break

    # Build the task markdown
    verification_lines = []
    for v in deliverable.get("verification", []):
        verification_lines.append(
            f"- `{v['predicate']}`: `{json.dumps(v['args'])}`"
        )

    task_md = f"""# TouchStone Task: {deliverable.get('title', deliverable_id)}

**ID:** `{deliverable_id}`
**Owner:** {owner}
**Dispatched:** {datetime.now(timezone.utc).isoformat()}
**Status:** {deliverable.get('status', 'pending')}

## Description

Complete this deliverable. When finished, run TouchStone verification to confirm all predicates pass.

## Dependencies

{chr(10).join(deps_info) if deps_info else "None"}

## Verification Predicates (ALL must pass)

{chr(10).join(verification_lines)}

## Notes

{deliverable.get('notes') or 'None'}

## Response Template

When complete, update the manifest status to "completed" and run:
```
python librarian-mcp/touchstone/verify.py {deliverable_id}
```

---
*Generated by TouchStone v1 — {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}*
"""

    task_path.write_text(task_md, encoding="utf-8")

    return {
        "dispatched": True,
        "deliverable_id": deliverable_id,
        "owner": owner,
        "task_path": str(task_path.relative_to(REPO_ROOT)),
    }


def dispatch_all_pending() -> dict:
    """Dispatch all pending deliverables to their owners."""
    manifest = load_manifest()
    dispatched = []
    skipped = []

    for d in manifest.get("deliverables", []):
        if d.get("status") in ("pending", "blocked"):
            result = dispatch_deliverable(d["id"])
            if result.get("dispatched"):
                dispatched.append(result)
            else:
                skipped.append(result)

    return {
        "dispatched_count": len(dispatched),
        "skipped_count": len(skipped),
        "dispatched": dispatched,
        "skipped": skipped,
    }


if __name__ == "__main__":
    if len(sys.argv) > 1:
        result = dispatch_deliverable(sys.argv[1])
    else:
        result = dispatch_all_pending()

    print(json.dumps(result, indent=2, ensure_ascii=False))
