/**
 * FOUNDER SAVINGS DASHBOARD — Phase D, K505
 * ==========================================
 * Private page at librarian.the2ndsecond.com/founder-savings
 * Login-gated to Founder + LB Admin.
 *
 * Shows rolling substrate savings across Bishop, Knight, and Pawn sessions:
 *   - All-time / 7-day / 30-day savings by agent
 *   - Substrate injection overhead (the cost of the substrate itself)
 *   - Cumulative savings over time
 *   - Provisional multiplier flags per K505 Phase E plan
 *
 * Data source: substrate_savings_log.jsonl → aggregated by the
 * `substrate_savings_summary` MCP tool. Since this is a static SPA,
 * the dashboard loads from /founder-savings-data.json (generated by
 * `cd librarian-mcp && npm run generate:savings-snapshot`).
 *
 * If no snapshot exists yet, the page shows onboarding instructions.
 */

import React, { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";

// ── Types ─────────────────────────────────────────────────────────────────────

interface AgentSummary {
  agent: string;
  sessions: number;
  total_input_tokens: number;
  total_output_tokens: number;
  total_actual_cost_usd: number;
  total_counterfactual_usd: number;
  total_savings_usd: number;
  total_substrate_overhead_tokens: number;
  avg_cold_multiplier: number;
}

interface SavingsTotals {
  sessions: number;
  total_actual_cost_usd: number;
  total_counterfactual_usd: number;
  total_savings_usd: number;
  total_substrate_overhead_tokens: number;
}

interface SavingsSnapshot {
  generated_at: string;
  windows: {
    all: { totals: SavingsTotals; by_agent: AgentSummary[]; entries: number };
    "7d": { totals: SavingsTotals; by_agent: AgentSummary[]; entries: number };
    "30d": { totals: SavingsTotals; by_agent: AgentSummary[]; entries: number };
  };
  multiplier_provisional: boolean;
  calibration_note: string;
  earliest_record: string | null;
  latest_record: string | null;
}

// ── Constants ─────────────────────────────────────────────────────────────────

const AGENT_COLORS: Record<string, { bg: string; text: string; border: string }> = {
  BISHOP: { bg: "bg-violet-50 dark:bg-violet-950", text: "text-violet-700 dark:text-violet-300", border: "border-violet-200 dark:border-violet-800" },
  KNIGHT: { bg: "bg-blue-50 dark:bg-blue-950", text: "text-blue-700 dark:text-blue-300", border: "border-blue-200 dark:border-blue-800" },
  PAWN:   { bg: "bg-amber-50 dark:bg-amber-950", text: "text-amber-700 dark:text-amber-300", border: "border-amber-200 dark:border-amber-800" },
  ROOK:   { bg: "bg-emerald-50 dark:bg-emerald-950", text: "text-emerald-700 dark:text-emerald-300", border: "border-emerald-200 dark:border-emerald-800" },
};

const AGENT_DESCRIPTIONS: Record<string, string> = {
  BISHOP: "Letters, communications, patent narratives. Claude Opus 4.7. 3.0× cold mult.",
  KNIGHT: "Tech, code, deployment. Claude Sonnet 4.6. 2.5× cold mult.",
  PAWN:   "Legal review, compliance, QA. Perplexity. 3.5× cold mult. (incl. friction).",
  ROOK:   "Patent extraction, innovation cataloging. 2.5× cold mult.",
};

type Window = "all" | "7d" | "30d";

// ── Sub-components ─────────────────────────────────────────────────────────────

function StatCard({ label, value, sub, accent = false }: {
  label: string; value: string; sub?: string; accent?: boolean;
}) {
  return (
    <div className="bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl p-6 text-center">
      <div className={`text-3xl font-bold mb-1 ${accent ? "text-emerald-600 dark:text-emerald-400" : "text-slate-900 dark:text-slate-100"}`}>
        {value}
      </div>
      <div className="text-sm font-medium text-slate-600 dark:text-slate-400">{label}</div>
      {sub && <div className="text-xs text-slate-400 dark:text-slate-500 mt-1">{sub}</div>}
    </div>
  );
}

function AgentCard({ summary }: { summary: AgentSummary }) {
  const colors = AGENT_COLORS[summary.agent] ?? AGENT_COLORS.KNIGHT;
  const desc = AGENT_DESCRIPTIONS[summary.agent] ?? "";
  const savingsRatio = summary.total_counterfactual_usd > 0
    ? (summary.total_savings_usd / summary.total_counterfactual_usd * 100).toFixed(0)
    : "0";

  return (
    <div className={`${colors.bg} border ${colors.border} rounded-xl p-6`}>
      <div className="flex items-start justify-between mb-3">
        <div>
          <h3 className={`text-lg font-bold ${colors.text}`}>{summary.agent}</h3>
          <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">{desc}</p>
        </div>
        <span className={`text-2xl font-bold ${colors.text}`}>
          ${summary.total_savings_usd.toFixed(2)}
        </span>
      </div>

      <div className="mt-3 mb-2 h-2 bg-slate-200 dark:bg-slate-700 rounded-full overflow-hidden">
        <div
          className="h-full bg-emerald-500 rounded-full transition-all"
          style={{ width: `${Math.min(100, parseFloat(savingsRatio))}%` }}
        />
      </div>

      <div className="grid grid-cols-3 gap-2 text-center text-xs text-slate-600 dark:text-slate-400 mt-3">
        <div>
          <div className="font-bold text-slate-800 dark:text-slate-200">{summary.sessions}</div>
          <div>sessions</div>
        </div>
        <div>
          <div className="font-bold text-slate-800 dark:text-slate-200">${summary.total_actual_cost_usd.toFixed(2)}</div>
          <div>actual</div>
        </div>
        <div>
          <div className="font-bold text-slate-800 dark:text-slate-200">{summary.avg_cold_multiplier}×</div>
          <div>mult.</div>
        </div>
      </div>
    </div>
  );
}

function OnboardingEmpty() {
  return (
    <div className="max-w-2xl mx-auto bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-2xl p-10 text-center mt-10">
      <div className="text-5xl mb-4">📊</div>
      <h2 className="text-2xl font-bold text-slate-900 dark:text-slate-100 mb-3">
        No savings data yet
      </h2>
      <p className="text-slate-600 dark:text-slate-400 mb-6 leading-relaxed">
        Substrate savings tracking is ready. Start logging sessions with the
        <code className="mx-1 px-1.5 py-0.5 bg-slate-100 dark:bg-slate-700 rounded text-sm font-mono">record_substrate_savings</code>
        MCP tool at the end of each Bishop or Knight session.
      </p>
      <div className="bg-slate-50 dark:bg-slate-900 rounded-xl p-5 text-left text-sm font-mono text-slate-700 dark:text-slate-300 space-y-2">
        <div className="text-slate-400 text-xs mb-3">Quick start (Bishop session end):</div>
        <div>{"{"}</div>
        <div className="pl-4">"tool": "record_substrate_savings",</div>
        <div className="pl-4">"agent": "BISHOP",</div>
        <div className="pl-4">"session_id": "B124",</div>
        <div className="pl-4">"input_tokens": 87500,</div>
        <div className="pl-4">"output_tokens": 15200,</div>
        <div className="pl-4">"substrate_overhead_tokens": 12300,</div>
        <div className="pl-4">"substrate_injection_count": 4</div>
        <div>{"}"}</div>
      </div>
      <p className="text-xs text-slate-400 mt-4">
        Then run <code className="font-mono">cd librarian-mcp && npm run generate:savings-snapshot</code> to update this dashboard.
      </p>
    </div>
  );
}

// ── Main Component ─────────────────────────────────────────────────────────────

export default function FounderSavingsDashboard() {
  const [snapshot, setSnapshot] = useState<SavingsSnapshot | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [window, setWindow] = useState<Window>("all");
  const navigate = useNavigate();

  useEffect(() => {
    fetch("/founder-savings-data.json")
      .then((r) => {
        if (!r.ok) throw new Error(`HTTP ${r.status} — run generate:savings-snapshot to create data`);
        return r.json();
      })
      .then((data) => setSnapshot(data))
      .catch((err) => setError((err as Error).message))
      .finally(() => setLoading(false));
  }, []);

  const windowData = snapshot?.windows[window];

  return (
    <div className="min-h-screen bg-slate-50 dark:bg-slate-950 py-10 px-4">
      <div className="max-w-5xl mx-auto">

        {/* Header */}
        <div className="text-center mb-8">
          <div className="inline-flex items-center gap-2 bg-emerald-50 dark:bg-emerald-950 border border-emerald-200 dark:border-emerald-800 rounded-full px-4 py-1.5 mb-5">
            <span className="w-2 h-2 bg-emerald-500 rounded-full" />
            <span className="text-emerald-700 dark:text-emerald-300 text-sm font-medium">
              Founder-private — LB Admin only
            </span>
          </div>
          <h1 className="text-3xl font-bold text-slate-900 dark:text-slate-100 mb-2">
            Substrate Savings Dashboard
          </h1>
          <p className="text-slate-600 dark:text-slate-400 max-w-2xl mx-auto">
            Actual token-cost savings from running Bishop, Knight, and Pawn sessions
            through the Librarian substrate. Honest counterfactuals per R13 baseline.
          </p>
          {snapshot?.generated_at && (
            <p className="text-xs text-slate-400 mt-2">
              Data snapshot: {new Date(snapshot.generated_at).toLocaleString()}
            </p>
          )}
        </div>

        {/* Loading / error */}
        {loading && (
          <div className="text-center py-20 text-slate-400 animate-pulse">Loading savings data…</div>
        )}
        {error && !snapshot && (
          <OnboardingEmpty />
        )}

        {snapshot && (
          <>
            {/* Window selector */}
            <div className="flex justify-center gap-2 mb-8">
              {(["all", "7d", "30d"] as Window[]).map((w) => (
                <button
                  key={w}
                  onClick={() => setWindow(w)}
                  className={`px-4 py-1.5 rounded-full text-sm font-medium transition-colors ${
                    window === w
                      ? "bg-slate-900 dark:bg-slate-100 text-white dark:text-slate-900"
                      : "bg-white dark:bg-slate-800 text-slate-600 dark:text-slate-400 border border-slate-200 dark:border-slate-700 hover:bg-slate-50 dark:hover:bg-slate-750"
                  }`}
                >
                  {w === "all" ? "All time" : `Last ${w}`}
                </button>
              ))}
            </div>

            {windowData && windowData.entries > 0 ? (
              <>
                {/* Top stats */}
                <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-8">
                  <StatCard
                    label="Net savings"
                    value={`$${windowData.totals.total_savings_usd.toFixed(2)}`}
                    sub="after substrate overhead"
                    accent
                  />
                  <StatCard
                    label="Counterfactual"
                    value={`$${windowData.totals.total_counterfactual_usd.toFixed(2)}`}
                    sub="what it would cost cold"
                  />
                  <StatCard
                    label="Actual spend"
                    value={`$${windowData.totals.total_actual_cost_usd.toFixed(2)}`}
                    sub="with substrate"
                  />
                  <StatCard
                    label="Sessions"
                    value={windowData.totals.sessions.toString()}
                    sub={`${windowData.totals.total_substrate_overhead_tokens.toLocaleString()} OH tokens`}
                  />
                </div>

                {/* Savings ratio headline */}
                {windowData.totals.total_counterfactual_usd > 0 && (
                  <div className="bg-gradient-to-r from-emerald-600 to-teal-600 rounded-2xl p-8 text-center text-white mb-8">
                    <div className="text-5xl font-bold mb-2">
                      {((windowData.totals.total_savings_usd / windowData.totals.total_counterfactual_usd) * 100).toFixed(0)}%
                    </div>
                    <div className="text-emerald-100 text-lg">
                      of counterfactual cost saved via substrate — {windowData.entries} sessions
                    </div>
                    <div className="text-emerald-200 text-sm mt-2">
                      R13 baseline: +86.2 pp Caithedral Effect · {snapshot.multiplier_provisional ? "multipliers provisional" : "calibrated"}
                    </div>
                  </div>
                )}

                {/* Per-agent cards */}
                <h2 className="text-lg font-bold text-slate-800 dark:text-slate-200 mb-4">Per-agent breakdown</h2>
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 mb-8">
                  {windowData.by_agent.map((a) => (
                    <AgentCard key={a.agent} summary={a} />
                  ))}
                </div>

                {/* Calibration note */}
                <div className="bg-amber-50 dark:bg-amber-950 border border-amber-200 dark:border-amber-800 rounded-xl p-5 text-sm text-amber-800 dark:text-amber-200">
                  <strong>Provisional multipliers</strong> — {snapshot.calibration_note}
                  {snapshot.earliest_record && (
                    <span className="block mt-1 text-xs text-amber-600 dark:text-amber-400">
                      Data range: {new Date(snapshot.earliest_record).toLocaleDateString()} → {snapshot.latest_record ? new Date(snapshot.latest_record).toLocaleDateString() : "now"}
                    </span>
                  )}
                </div>
              </>
            ) : (
              <OnboardingEmpty />
            )}
          </>
        )}

        {/* Back nav */}
        <div className="text-center mt-10">
          <button
            onClick={() => navigate(-1)}
            className="text-sm text-slate-400 hover:text-slate-600 dark:hover:text-slate-200 transition-colors"
          >
            ← Back
          </button>
        </div>
      </div>
    </div>
  );
}
