"""
handshake_invoker.py — Shadow LB Frame Handshake Wrapper (KN090 / BP011)
=========================================================================
Wraps the LB Frame Handshake CLI (KN086 LANDED @ 232e47e) for Shadow context.

Maps the 5 Handshake phases to Shadow context:
    Phase 1 — Discovery (enumerate substrate + iron tablet root)
    Phase 2 — Familiarize (read existing Shadow state from ledger)
    Phase 3 — Set (apply Shadow defaults: scribe-id, heartbeat interval, lifecycle root)
    Phase 4 — Verify (check Handshake receipt exists; write-authority paths writable)
    Phase 5 — Report (write receipt to Iron Tablet at canonical eblet path)

Receipt is persisted to:
    ~/.claude/state/eblets/BP011/handshake_receipt_<scribe_id>_<timestamp>.eblet.md
"""
from __future__ import annotations

import json
import os
import re
import subprocess
import sys
import tempfile
import threading
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

WORKSPACE_ROOT = Path(__file__).resolve().parents[1]
LB_FRAME_DIR = WORKSPACE_ROOT  # lb_frame_handshake lives at workspace root

# Default eblet root for BP011 receipts
EBLET_BP011_DIR = Path.home() / ".claude" / "state" / "eblets" / "BP011"


@dataclass
class PhaseResult:
    phase: int
    name: str
    status: str   # "pass" | "skip" | "warn" | "fail"
    message: str
    warnings: list[str] = field(default_factory=list)


@dataclass
class HandshakeReceipt:
    scribe_id: str
    lighthouse_position: int
    session_id: str
    ts: str
    phases: list[PhaseResult]
    receipt_path: Optional[Path]
    first_fire_ready: bool
    raw_output: str = ""

    def all_passed(self) -> bool:
        return all(p.status in ("pass", "skip") for p in self.phases)

    def to_eblet_markdown(self) -> str:
        phase_rows = "\n".join(
            f"| Phase {p.phase} — {p.name} | {p.status.upper()} | {p.message} |"
            for p in self.phases
        )
        warn_lines = "\n".join(
            f"- ⚠ {w}"
            for p in self.phases
            for w in p.warnings
        ) or "_none_"
        return f"""---
type: handshake_receipt
scribe_id: {self.scribe_id}
lighthouse_position: {self.lighthouse_position}
session_id: {self.session_id}
ts: {self.ts}
first_fire_ready: {str(self.first_fire_ready).lower()}
---

# LB Frame Handshake Receipt — {self.scribe_id}

| Phase | Status | Message |
|---|---|---|
{phase_rows}

## Warnings
{warn_lines}

## Organism Context
- **Scribe-id:** `{self.scribe_id}`
- **LIGHTHOUSE position:** {self.lighthouse_position} of 8
- **Session:** `{self.session_id}`
- **Timestamp:** `{self.ts}`
- **First-fire ready:** `{self.first_fire_ready}`

_Receipt generated by KN090 handshake_invoker.py (BP011 Pod W Bean 2)._
"""


def _parse_cli_output(output: str, scribe_id: str, lighthouse_position: int, session_id: str) -> HandshakeReceipt:
    """
    Parse the LB Frame Handshake CLI stdout into a HandshakeReceipt.
    Falls back to inferred phases if CLI output is non-standard.
    """
    ts = datetime.now(timezone.utc).isoformat()

    phase_names = [
        "Discovery",
        "Familiarize",
        "Set",
        "Verify",
        "Report",
    ]

    phases: list[PhaseResult] = []
    for i, name in enumerate(phase_names, start=1):
        pattern = rf"Phase {i}"
        if re.search(pattern, output, re.IGNORECASE):
            # If the phase appears in output, check if it mentions warnings
            warn_match = re.findall(r"⚠ (.+)", output)
            phases.append(PhaseResult(
                phase=i,
                name=name,
                status="pass",
                message=f"Phase {i} completed",
                warnings=warn_match if i == 5 else [],
            ))
        else:
            phases.append(PhaseResult(
                phase=i,
                name=name,
                status="skip",
                message="Phase not observed in output",
            ))

    first_fire = "FIRST-FIRE READY" in output and "NOT FIRST-FIRE READY" not in output

    receipt_path_match = re.search(r"Receipt artifact: (.+)", output)
    receipt_path: Optional[Path] = None
    if receipt_path_match:
        receipt_path = Path(receipt_path_match.group(1).strip())

    return HandshakeReceipt(
        scribe_id=scribe_id,
        lighthouse_position=lighthouse_position,
        session_id=session_id,
        ts=ts,
        phases=phases,
        receipt_path=receipt_path,
        first_fire_ready=first_fire,
        raw_output=output,
    )


def run_full_handshake(
    scribe_id: str,
    lighthouse_position: int,
    session_id: str = "KN090",
    dry_run: bool = False,
    timeout_seconds: int = 120,
) -> HandshakeReceipt:
    """
    Invoke the LB Frame Handshake CLI for a given Shadow scribe-id.

    Runs `python -m lb_frame_handshake --session <session_id>` from workspace root.
    Captures all 5 phases. Writes the receipt to the canonical BP011 eblet path.

    Args:
        scribe_id:           e.g. "R11_shadow_alpha"
        lighthouse_position: 1–8
        session_id:          recorded in the receipt (default: "KN090")
        dry_run:             pass --dry-run to Handshake (no writes, all phases run)
        timeout_seconds:     subprocess timeout (default: 120s)

    Returns:
        HandshakeReceipt with all 5 phases and receipt_path.

    Raises:
        TimeoutError if the Handshake subprocess exceeds timeout_seconds.
        RuntimeError if the subprocess exits with a non-zero code and not first-fire ready.
    """
    cmd = [
        sys.executable, "-m", "lb_frame_handshake",
        "--session", session_id,
    ]
    if dry_run:
        cmd.append("--dry-run")

    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=timeout_seconds,
            cwd=str(WORKSPACE_ROOT),
        )
        raw_output = result.stdout + result.stderr
    except subprocess.TimeoutExpired:
        raise TimeoutError(
            f"LB Frame Handshake timed out after {timeout_seconds}s for scribe {scribe_id}"
        )

    receipt = _parse_cli_output(raw_output, scribe_id, lighthouse_position, session_id)

    # Persist receipt to canonical BP011 eblet path
    EBLET_BP011_DIR.mkdir(parents=True, exist_ok=True)
    ts_safe = receipt.ts.replace(":", "-").replace("+", "p")[:24]
    eblet_filename = f"handshake_receipt_{scribe_id}_{ts_safe}.eblet.md"
    eblet_path = EBLET_BP011_DIR / eblet_filename

    if not dry_run:
        eblet_path.write_text(receipt.to_eblet_markdown(), encoding="utf-8")
        receipt.receipt_path = eblet_path

    return receipt


def run_handshake_for_all_shadows(
    session_id: str = "KN090",
    dry_run: bool = False,
    parallel: bool = False,
) -> dict[str, HandshakeReceipt]:
    """
    Run the Handshake for all 8 LIGHTHOUSE Shadows.

    Args:
        session_id: Session identifier written into each receipt.
        dry_run:    Pass --dry-run to all invocations.
        parallel:   Run all 8 in parallel threads (faster; useful for test/deploy).

    Returns:
        dict mapping scribe_id -> HandshakeReceipt for all 8 Shadows.
    """
    from .iron_egiant_promotion import SCRIBE_IDS

    results: dict[str, HandshakeReceipt] = {}
    errors: dict[str, Exception] = {}

    if parallel:
        lock = threading.Lock()
        threads = []

        def _run(scribe_id: str, position: int) -> None:
            try:
                r = run_full_handshake(scribe_id, position, session_id, dry_run)
                with lock:
                    results[scribe_id] = r
            except Exception as exc:
                with lock:
                    errors[scribe_id] = exc

        for pos, scribe_id in enumerate(SCRIBE_IDS, start=1):
            t = threading.Thread(target=_run, args=(scribe_id, pos), daemon=True)
            threads.append(t)
            t.start()
        for t in threads:
            t.join(timeout=180)
    else:
        for pos, scribe_id in enumerate(SCRIBE_IDS, start=1):
            try:
                results[scribe_id] = run_full_handshake(scribe_id, pos, session_id, dry_run)
            except Exception as exc:
                errors[scribe_id] = exc

    if errors:
        msg = "; ".join(f"{sid}: {e}" for sid, e in errors.items())
        raise RuntimeError(f"Handshake failed for {len(errors)} Shadow(s): {msg}")

    return results
