"""
handshake_pawn.py — Pawn Cross-Vendor LB Frame Handshake (KN092 / BP011)
=========================================================================
Cross-vendor variant of the LB Frame Handshake for Pawn (Perplexity).

Since Pawn cannot execute MCP tool calls directly (no MCP client support),
this Handshake runs inside a Bishop- or Knight-orchestrated dispatch script
and probes the Pawn session environment via the Perplexity-compatible gateway.

Five Phases (cross-vendor variant):
    Phase 1 — Discovery    Probe environment: Python version, workspace path,
                           gateway connectivity (GET /health on localhost:8765).
    Phase 2 — Familiarize  Load Ring of Three Golden Eblets from PawnHandoffs.jsonl
                           (the top 3 most recent entries — Pawn's institutional memory).
    Phase 3 — Set          Establish scribe-id `R11_pawn_<dispatch-id>`.
                           Register in wrasse_registry.jsonl.
    Phase 4 — Verify       Smoke-test gateway round-trip: call
                           mcp__librarian__get_canonical_numbers; assert
                           canonical_numbers dict is non-empty.
    Phase 5 — Report       Write handshake_receipt to canonical Eblet via
                           Iron Tablet (if available) or direct file write.

Result is written to:
    ~/.claude/state/eblets/BP011/handshake_receipt_R11_pawn_<id>_<ts>.eblet.md
"""
from __future__ import annotations

import json
import os
import sys
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional
from urllib import request as urllib_request
from urllib.error import URLError

WORKSPACE_ROOT = Path(__file__).resolve().parents[1]
LIBRARIAN_ROOT = WORKSPACE_ROOT / "librarian-mcp"
PAWN_CATHEDRAL_SCRIBES = LIBRARIAN_ROOT / "stitchpunks" / "pawn_cathedral" / "scribes"
PAWN_HANDOFFS = PAWN_CATHEDRAL_SCRIBES / "PawnHandoffs.jsonl"
WRASSE_REGISTRY = LIBRARIAN_ROOT / "stitchpunks" / "wrasse" / "wrasse_registry.jsonl"
EBLET_BP011_DIR = Path.home() / ".claude" / "state" / "eblets" / "BP011"

DEFAULT_GATEWAY_URL = "http://127.0.0.1:8765"


@dataclass
class PhaseResult:
    phase: int
    name: str
    status: str     # "pass" | "skip" | "warn" | "fail"
    message: str
    warnings: list[str] = field(default_factory=list)


@dataclass
class PawnHandshakeReceipt:
    scribe_id: str
    dispatch_id: str
    session_id: str
    ts: str
    phases: list[PhaseResult]
    receipt_path: Optional[Path]
    first_fire_ready: bool
    gateway_url: str = DEFAULT_GATEWAY_URL
    raw_notes: str = ""
    shadow_alpha_paired: bool = False

    def all_passed(self) -> bool:
        return all(p.status in ("pass", "skip") for p in self.phases)

    def to_eblet_markdown(self) -> str:
        phase_rows = "\n".join(
            f"| Phase {p.phase} — {p.name} | {p.status.upper()} | {p.message} |"
            for p in self.phases
        )
        warn_lines = "\n".join(
            f"- {w}" for p in self.phases for w in p.warnings
        ) or "_none_"
        return f"""---
type: handshake_receipt_pawn
scribe_id: {self.scribe_id}
dispatch_id: {self.dispatch_id}
session_id: {self.session_id}
ts: {self.ts}
first_fire_ready: {str(self.first_fire_ready).lower()}
gateway_url: {self.gateway_url}
shadow_alpha_paired: {str(self.shadow_alpha_paired).lower()}
---

# Pawn LB Frame Handshake Receipt (Cross-Vendor) — {self.scribe_id}

| Phase | Status | Message |
|---|---|---|
{phase_rows}

## Warnings
{warn_lines}

## Organism Context
- **Scribe-id:** `{self.scribe_id}`
- **Dispatch-id:** `{self.dispatch_id}`
- **Session:** `{self.session_id}`
- **Timestamp:** `{self.ts}`
- **Gateway:** `{self.gateway_url}`
- **Shadow-alpha paired:** `{self.shadow_alpha_paired}`
- **First-fire ready:** `{self.first_fire_ready}`

## Notes
{self.raw_notes or '_No additional notes._'}

_Receipt generated by KN092 handshake_pawn.py (BP011 Pod W Bean 4)._
"""


# ── Phase implementations ──────────────────────────────────────────────────────

def _phase1_discovery(gateway_url: str) -> PhaseResult:
    """
    Probe environment: Python version, workspace path, gateway connectivity.
    """
    notes = [
        f"Python {sys.version.split()[0]}",
        f"Workspace: {WORKSPACE_ROOT}",
    ]
    # Check gateway health
    try:
        req = urllib_request.Request(f"{gateway_url}/health", method="GET")
        with urllib_request.urlopen(req, timeout=5) as resp:
            body = json.loads(resp.read())
        if body.get("status") == "ok":
            notes.append(f"Gateway: {gateway_url} — REACHABLE")
        else:
            return PhaseResult(
                phase=1, name="Discovery", status="warn",
                message=f"Gateway {gateway_url} returned non-ok: {body.get('status')}",
                warnings=[f"Gateway status: {body.get('status', '?')}"],
            )
    except URLError as exc:
        return PhaseResult(
            phase=1, name="Discovery", status="warn",
            message=f"Gateway {gateway_url} not reachable: {exc}",
            warnings=[
                "Gateway not reachable — Phase 4 Verify smoke-test will be skipped.",
                "Start the gateway with: python -m pawn_iron_egiant.gateway_runner",
            ],
        )
    return PhaseResult(
        phase=1, name="Discovery", status="pass",
        message="; ".join(notes),
    )


def _phase2_familiarize() -> PhaseResult:
    """
    Load Ring of Three Golden Eblets from PawnHandoffs.jsonl.
    """
    if not PAWN_HANDOFFS.exists():
        return PhaseResult(
            phase=2, name="Familiarize", status="warn",
            message="PawnHandoffs.jsonl not found — Pawn Cathedral may not be initialized.",
            warnings=["Run KN092 perplexity_gateway setup to initialize Pawn Cathedral."],
        )
    entries: list[dict] = []
    try:
        with open(PAWN_HANDOFFS, encoding="utf-8") as fh:
            for line in fh:
                line = line.strip()
                if not line:
                    continue
                rec = json.loads(line)
                if rec.get("type") != "header":
                    entries.append(rec)
    except Exception as exc:
        return PhaseResult(
            phase=2, name="Familiarize", status="fail",
            message=f"Error reading PawnHandoffs.jsonl: {exc}",
        )

    ring_of_three = entries[-3:] if len(entries) >= 3 else entries
    summary = "; ".join(
        f"[{e.get('source_session', '?')}] {str(e.get('observation', ''))[:80]}"
        for e in ring_of_three
    ) or "No handoff entries"
    return PhaseResult(
        phase=2, name="Familiarize", status="pass",
        message=f"Ring of Three loaded ({len(ring_of_three)} entries): {summary[:200]}",
    )


def _phase3_set(scribe_id: str, dispatch_id: str, session_id: str) -> PhaseResult:
    """
    Establish scribe-id and register in wrasse_registry.jsonl.
    """
    entry = {
        "scribe_id": scribe_id,
        "dispatch_id": dispatch_id,
        "session_id": session_id,
        "organism_type": "pawn_iron_egiant",
        "lighthouse_position": "pawn",
        "registered_ts": datetime.now(timezone.utc).isoformat(),
        "active": True,
    }
    try:
        WRASSE_REGISTRY.parent.mkdir(parents=True, exist_ok=True)
        with open(WRASSE_REGISTRY, "a", encoding="utf-8") as fh:
            fh.write(json.dumps(entry) + "\n")
    except Exception as exc:
        return PhaseResult(
            phase=3, name="Set", status="warn",
            message=f"Wrasse registry write failed: {exc}",
            warnings=["Scribe-id established in-memory but not persisted to wrasse_registry.jsonl"],
        )
    return PhaseResult(
        phase=3, name="Set", status="pass",
        message=f"Scribe-id '{scribe_id}' registered in wrasse_registry.jsonl",
    )


def _phase4_verify(scribe_id: str, api_key: str, gateway_url: str) -> PhaseResult:
    """
    Smoke-test gateway round-trip: call mcp__librarian__get_canonical_numbers.
    Returns skip if gateway is unreachable.
    """
    if not api_key:
        return PhaseResult(
            phase=4, name="Verify", status="skip",
            message="No API key provided — gateway smoke-test skipped.",
        )

    payload = json.dumps({
        "tool_call": {
            "id": "handshake_smoke_test",
            "type": "function",
            "function": {
                "name": "mcp__librarian__get_canonical_numbers",
                "arguments": "{}",
            },
        }
    }).encode()

    try:
        req = urllib_request.Request(
            f"{gateway_url}/v1/tool_call",
            data=payload,
            method="POST",
            headers={
                "Content-Type": "application/json",
                "Authorization": f"Bearer {api_key}",
                "X-Session-Id": scribe_id,
            },
        )
        with urllib_request.urlopen(req, timeout=10) as resp:
            body = json.loads(resp.read())
    except URLError as exc:
        return PhaseResult(
            phase=4, name="Verify", status="skip",
            message=f"Gateway unreachable — smoke-test skipped: {exc}",
        )
    except Exception as exc:
        return PhaseResult(
            phase=4, name="Verify", status="fail",
            message=f"Gateway smoke-test error: {exc}",
        )

    if body.get("status") != "ok":
        return PhaseResult(
            phase=4, name="Verify", status="fail",
            message=f"Gateway returned error: {body.get('error', body)}",
        )

    # Parse inner result
    result_content = body.get("result", {}).get("content", "{}")
    try:
        inner = json.loads(result_content)
    except json.JSONDecodeError:
        inner = {}

    canonical = inner.get("canonical_numbers", {})
    if not canonical:
        return PhaseResult(
            phase=4, name="Verify", status="warn",
            message="Gateway returned empty canonical_numbers — check canonical_values.yaml.",
            warnings=["canonical_values.yaml may be missing or empty"],
        )

    return PhaseResult(
        phase=4, name="Verify", status="pass",
        message=f"Gateway round-trip OK — canonical_numbers has {len(canonical)} entries",
    )


def _phase5_report(
    receipt: PawnHandshakeReceipt,
    dry_run: bool = False,
) -> PhaseResult:
    """
    Write handshake receipt to canonical BP011 eblet path.
    """
    EBLET_BP011_DIR.mkdir(parents=True, exist_ok=True)
    ts_safe = receipt.ts.replace(":", "-").replace("+", "p")[:24]
    filename = f"handshake_receipt_{receipt.scribe_id}_{ts_safe}.eblet.md"
    eblet_path = EBLET_BP011_DIR / filename

    if not dry_run:
        try:
            eblet_path.write_text(receipt.to_eblet_markdown(), encoding="utf-8")
            receipt.receipt_path = eblet_path
        except Exception as exc:
            return PhaseResult(
                phase=5, name="Report", status="fail",
                message=f"Receipt write failed: {exc}",
            )

    return PhaseResult(
        phase=5, name="Report", status="pass" if not dry_run else "skip",
        message=f"Receipt artifact: {eblet_path}" if not dry_run else "dry-run — no write",
    )


# ── Public API ─────────────────────────────────────────────────────────────────

def run_pawn_handshake(
    dispatch_id: str,
    *,
    session_id: str = "KN092",
    gateway_url: str = DEFAULT_GATEWAY_URL,
    api_key: str = "",
    dry_run: bool = False,
) -> PawnHandshakeReceipt:
    """
    Run the full 5-phase cross-vendor Pawn Handshake.

    Args:
        dispatch_id: Unique Pawn dispatch identifier (e.g. "d7f3a1b2").
        session_id:  Knight session identifier (e.g. "KN092").
        gateway_url: Base URL of the Perplexity Gateway.
        api_key:     Per-dispatch API key for Phase 4 smoke-test.
        dry_run:     Run all phases but skip writes (Phase 5 skipped).

    Returns:
        PawnHandshakeReceipt with all 5 phases completed.
    """
    scribe_id = f"R11_pawn_{dispatch_id}"
    ts = datetime.now(timezone.utc).isoformat()

    receipt = PawnHandshakeReceipt(
        scribe_id=scribe_id,
        dispatch_id=dispatch_id,
        session_id=session_id,
        ts=ts,
        phases=[],
        receipt_path=None,
        first_fire_ready=False,
        gateway_url=gateway_url,
        shadow_alpha_paired=False,
    )

    # Phase 1
    p1 = _phase1_discovery(gateway_url)
    receipt.phases.append(p1)

    # Phase 2
    p2 = _phase2_familiarize()
    receipt.phases.append(p2)

    # Phase 3
    p3 = _phase3_set(scribe_id, dispatch_id, session_id)
    receipt.phases.append(p3)

    # Phase 4
    p4 = _phase4_verify(scribe_id, api_key, gateway_url)
    receipt.phases.append(p4)

    # Phase 5
    p5 = _phase5_report(receipt, dry_run=dry_run)
    receipt.phases.append(p5)

    receipt.first_fire_ready = all(
        p.status in ("pass", "skip", "warn") for p in receipt.phases
    )
    receipt.raw_notes = (
        "FIRST-FIRE READY" if receipt.first_fire_ready else "NOT FIRST-FIRE READY"
    )
    return receipt
