/**
 * TEMPLATE ATTRIBUTION SERVICE
 * ============================
 * Tracks when templates are used and awards Marks to creators.
 * 
 * Marks Earned:
 * - Template selected: 1 Mark
 * - Campaign sent: 2 Marks
 * - Click generated: 0.1 Marks per click
 * - Conversion generated: 1 Mark per conversion
 * - Template copied (derivative): 5 Marks (highest honor)
 * 
 * Attribution Duration:
 * - Marks accrue for the duration of the campaign (typically 24-72 hours)
 * - After campaign ends, final tally is calculated
 * - Creator receives Marks as crystallized (not Shadow)
 */

import { supabase } from '@/integrations/supabase/client';

// ═══════════════════════════════════════════════════════════════════════════════
// TYPES
// ═══════════════════════════════════════════════════════════════════════════════

export interface Attribution {
  id: string;
  template_id: string;
  creator_id: string;
  user_id: string;
  campaign_id: string | null;
  selected_at: string;
  sent_at: string | null;
  clicks_generated: number;
  conversions_generated: number;
  marks_for_selection: number;
  marks_for_send: number;
  marks_for_clicks: number;
  marks_for_conversions: number;
  marks_for_derivative: number;
  total_marks_awarded: number;
  marks_paid_at: string | null;
  is_derivative: boolean;
}

export interface AttributionSummary {
  total_templates_used: number;
  total_marks_earned: number;
  total_clicks_generated: number;
  total_conversions_generated: number;
  top_templates: {
    template_id: string;
    template_title: string;
    uses: number;
    marks_earned: number;
  }[];
}

// ═══════════════════════════════════════════════════════════════════════════════
// ATTRIBUTION FUNCTIONS
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * Record when a user selects a template
 */
export async function recordTemplateSelection(
  templateId: string,
  creatorId: string,
  userId: string,
  campaignId?: string
): Promise<string | null> {
  try {
    const { data, error } = await supabase
      .from('template_attribution')
      .insert({
        template_id: templateId,
        creator_id: creatorId,
        user_id: userId,
        campaign_id: campaignId || null,
        marks_for_selection: 1,
        total_marks_awarded: 1
      })
      .select('id')
      .single();

    if (error) throw error;
    return data.id;
  } catch (err) {
    console.error('Error recording template selection:', err);
    return null;
  }
}

/**
 * Record when a campaign using a template is sent
 */
export async function recordCampaignSent(
  attributionId: string
): Promise<boolean> {
  try {
    const { error } = await supabase
      .from('template_attribution')
      .update({
        sent_at: new Date().toISOString(),
        marks_for_send: 2,
        total_marks_awarded: supabase.rpc('get_attribution_total', { p_id: attributionId })
      })
      .eq('id', attributionId);

    if (error) throw error;
    return true;
  } catch (err) {
    console.error('Error recording campaign sent:', err);
    return false;
  }
}

/**
 * Record clicks generated by a template
 */
export async function recordClicks(
  attributionId: string,
  newClicks: number
): Promise<boolean> {
  try {
    // Get current clicks
    const { data: current, error: fetchError } = await supabase
      .from('template_attribution')
      .select('clicks_generated')
      .eq('id', attributionId)
      .single();

    if (fetchError) throw fetchError;

    const totalClicks = (current?.clicks_generated || 0) + newClicks;
    const marksForClicks = totalClicks * 0.1;

    const { error } = await supabase
      .from('template_attribution')
      .update({
        clicks_generated: totalClicks,
        marks_for_clicks: marksForClicks
      })
      .eq('id', attributionId);

    if (error) throw error;
    return true;
  } catch (err) {
    console.error('Error recording clicks:', err);
    return false;
  }
}

/**
 * Record conversions generated by a template
 */
export async function recordConversions(
  attributionId: string,
  newConversions: number
): Promise<boolean> {
  try {
    // Get current conversions
    const { data: current, error: fetchError } = await supabase
      .from('template_attribution')
      .select('conversions_generated')
      .eq('id', attributionId)
      .single();

    if (fetchError) throw fetchError;

    const totalConversions = (current?.conversions_generated || 0) + newConversions;

    const { error } = await supabase
      .from('template_attribution')
      .update({
        conversions_generated: totalConversions,
        marks_for_conversions: totalConversions
      })
      .eq('id', attributionId);

    if (error) throw error;
    return true;
  } catch (err) {
    console.error('Error recording conversions:', err);
    return false;
  }
}

/**
 * Record when a template is copied as a derivative
 */
export async function recordDerivative(
  templateId: string,
  creatorId: string,
  userId: string
): Promise<string | null> {
  try {
    const { data, error } = await supabase
      .from('template_attribution')
      .insert({
        template_id: templateId,
        creator_id: creatorId,
        user_id: userId,
        is_derivative: true,
        marks_for_selection: 1,
        marks_for_derivative: 5,
        total_marks_awarded: 6
      })
      .select('id')
      .single();

    if (error) throw error;
    return data.id;
  } catch (err) {
    console.error('Error recording derivative:', err);
    return null;
  }
}

/**
 * Finalize attribution and pay out marks to creator
 */
export async function finalizeAttribution(
  attributionId: string
): Promise<number> {
  try {
    const { data: marks, error } = await supabase
      .rpc('award_template_marks', { p_attribution_id: attributionId });

    if (error) throw error;
    return marks || 0;
  } catch (err) {
    console.error('Error finalizing attribution:', err);
    return 0;
  }
}

/**
 * Get attribution summary for a creator
 */
export async function getCreatorAttributionSummary(
  creatorId: string
): Promise<AttributionSummary | null> {
  try {
    const { data: attributions, error } = await supabase
      .from('template_attribution')
      .select(`
        *,
        cue_card_templates (
          id,
          title
        )
      `)
      .eq('creator_id', creatorId);

    if (error) throw error;
    if (!attributions || attributions.length === 0) {
      return {
        total_templates_used: 0,
        total_marks_earned: 0,
        total_clicks_generated: 0,
        total_conversions_generated: 0,
        top_templates: []
      };
    }

    // Aggregate by template
    const templateStats: Record<string, {
      template_id: string;
      template_title: string;
      uses: number;
      marks_earned: number;
    }> = {};

    let totalMarks = 0;
    let totalClicks = 0;
    let totalConversions = 0;

    attributions.forEach(attr => {
      const templateId = attr.template_id;
      const template = attr.cue_card_templates as { id: string; title: string } | null;
      
      if (!templateStats[templateId]) {
        templateStats[templateId] = {
          template_id: templateId,
          template_title: template?.title || 'Unknown',
          uses: 0,
          marks_earned: 0
        };
      }

      templateStats[templateId].uses++;
      templateStats[templateId].marks_earned += attr.total_marks_awarded || 0;
      totalMarks += attr.total_marks_awarded || 0;
      totalClicks += attr.clicks_generated || 0;
      totalConversions += attr.conversions_generated || 0;
    });

    const topTemplates = Object.values(templateStats)
      .sort((a, b) => b.marks_earned - a.marks_earned)
      .slice(0, 5);

    return {
      total_templates_used: Object.keys(templateStats).length,
      total_marks_earned: totalMarks,
      total_clicks_generated: totalClicks,
      total_conversions_generated: totalConversions,
      top_templates: topTemplates
    };
  } catch (err) {
    console.error('Error getting creator summary:', err);
    return null;
  }
}

/**
 * Get attribution summary for a user (templates they've used)
 */
export async function getUserAttributionHistory(
  userId: string
): Promise<Attribution[]> {
  try {
    const { data, error } = await supabase
      .from('template_attribution')
      .select('*')
      .eq('user_id', userId)
      .order('selected_at', { ascending: false });

    if (error) throw error;
    return (data as Attribution[]) || [];
  } catch (err) {
    console.error('Error getting user history:', err);
    return [];
  }
}

// ═══════════════════════════════════════════════════════════════════════════════
// CAMPAIGN INTEGRATION
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * Create a campaign with research commitment
 */
export async function createCampaignWithCommitment(
  userId: string,
  name: string,
  templateIds: string[],
  researchCommitment: boolean,
  expirationHours: number,
  expirationType: string,
  projectId?: string
): Promise<string | null> {
  try {
    const { data, error } = await supabase
      .from('cue_card_campaigns')
      .insert({
        user_id: userId,
        project_id: projectId || null,
        name,
        template_ids: templateIds,
        research_commitment: researchCommitment,
        research_commitment_set_at: researchCommitment ? new Date().toISOString() : null,
        default_expiration_hours: expirationHours,
        expiration_type: expirationType,
        status: 'draft'
      })
      .select('id')
      .single();

    if (error) throw error;
    return data.id;
  } catch (err) {
    console.error('Error creating campaign:', err);
    return null;
  }
}

/**
 * Launch a campaign and satisfy commitment
 */
export async function launchCampaign(
  campaignId: string,
  userId: string
): Promise<boolean> {
  try {
    // Update campaign status
    const { error: campaignError } = await supabase
      .from('cue_card_campaigns')
      .update({
        status: 'active',
        launched_at: new Date().toISOString()
      })
      .eq('id', campaignId);

    if (campaignError) throw campaignError;

    // Satisfy commitment lock
    const { error: lockError } = await supabase
      .rpc('satisfy_commitment_lock', {
        p_user_id: userId,
        p_campaign_id: campaignId
      });

    if (lockError) {
      console.warn('No commitment lock to satisfy:', lockError);
    }

    return true;
  } catch (err) {
    console.error('Error launching campaign:', err);
    return false;
  }
}

/**
 * Complete a campaign and finalize all attributions
 */
export async function completeCampaign(
  campaignId: string
): Promise<{ totalMarksAwarded: number; attributionsFinalized: number }> {
  try {
    // Get campaign
    const { data: campaign, error: fetchError } = await supabase
      .from('cue_card_campaigns')
      .select('*')
      .eq('id', campaignId)
      .single();

    if (fetchError) throw fetchError;

    // Update campaign status
    const { error: updateError } = await supabase
      .from('cue_card_campaigns')
      .update({
        status: 'completed',
        completed_at: new Date().toISOString()
      })
      .eq('id', campaignId);

    if (updateError) throw updateError;

    // Finalize all attributions for this campaign
    const { data: attributions, error: attrError } = await supabase
      .from('template_attribution')
      .select('id')
      .eq('campaign_id', campaignId)
      .is('marks_paid_at', null);

    if (attrError) throw attrError;

    let totalMarks = 0;
    let finalized = 0;

    for (const attr of attributions || []) {
      const marks = await finalizeAttribution(attr.id);
      totalMarks += marks;
      finalized++;
    }

    // Update research pool aggregates if committed
    if (campaign.research_commitment && campaign.commitment_satisfied) {
      await supabase.rpc('update_research_pool_aggregates');
    }

    return {
      totalMarksAwarded: totalMarks,
      attributionsFinalized: finalized
    };
  } catch (err) {
    console.error('Error completing campaign:', err);
    return { totalMarksAwarded: 0, attributionsFinalized: 0 };
  }
}

// ═══════════════════════════════════════════════════════════════════════════════
// EXPORTS
// ═══════════════════════════════════════════════════════════════════════════════

export default {
  recordTemplateSelection,
  recordCampaignSent,
  recordClicks,
  recordConversions,
  recordDerivative,
  finalizeAttribution,
  getCreatorAttributionSummary,
  getUserAttributionHistory,
  createCampaignWithCommitment,
  launchCampaign,
  completeCampaign
};
