# LB Frame Handshake Receipt

**Session**: {session_id}
**Timestamp**: {timestamp_iso}
**Handshake version**: KN086/BP009
**First-fire-ready**: {first_fire_ready}

---

## Phase 1 — Environment Inventory

| Property | Value |
|---|---|
| Claude surface | {environment.surface} |
| OS / shell | {environment.os_shell} |
| MCP servers | {environment.mcp_server_count} connected |
| Hooks registered | {environment.hook_count} |
| Permissions allow | {environment.permission_count} entries |
| Models available | {environment.models_summary} |
| Git available | {environment.git_available} |

**MCP servers detected**: {environment.mcp_servers_list}

---

## Phase 2 — Substrate State

| Component | Status |
|---|---|
| MEMORY.md | {substrate_state.memory_status} |
| Pheromone substrate | {substrate_state.pheromone_status} (records: {substrate_state.pheromone_record_count}) |
| Wrasse registry | {substrate_state.wrasse_status} |
| Catechist state | {substrate_state.catechist_status} |
| Augur Living Gate | {substrate_state.augur_status} |
| Shadow daemon | {substrate_state.shadow_status} |
| CheckBook Suite | {substrate_state.checkbook_status} |
| Stitchpunk Pantheon | {substrate_state.stitchpunk_count} / 24 present |
| Ring of Three | {substrate_state.ring_of_three_status} |
| CANON Eblets | {substrate_state.canon_eblet_count} inventoried |
| Pending Knight prompts | {substrate_state.pending_knight_prompt_count} |

---

## Phase 3 — Settings Applied

### Permissions Added
{settings_applied.permissions_diff}

### Hooks Registered
{settings_applied.hooks_diff}

### Environment Defaults Set
{settings_applied.env_diff}

### File System
- Substrate paths writable: {settings_applied.fs_writability}
- Session state dirs: {settings_applied.session_state_dirs}
- Librarian MCP built: {settings_applied.librarian_mcp}

{federation_section}

---

## Phase 4 — Smoke Test Results

| Test | Result |
|---|---|
| Pre-approved read (brief_me) | {smoke_test_results.smoke_test_1} |
| Pre-approved write (scribe_log) | {smoke_test_results.smoke_test_2} |
| Non-pre-approved (dispatch_pawn) prompts | {smoke_test_results.smoke_test_3} |
| Wrasse pre-injection fires | {smoke_test_results.smoke_test_4} |
| Hook fires on trigger | {smoke_test_results.smoke_test_5} |
| Catechist grade (R01-R10) | {smoke_test_results.catechist_grade} |
| Augur Living Gate state | {smoke_test_results.augur_living_gate_state} |

---

## Warnings

{warnings_section}

---

## First-Fire Signal

**{first_fire_banner}**

{first_fire_detail}

---

*Handshake receipt generated by `lb_frame_handshake` v1.0 (KN086/BP009). Append-only — do not edit. Corrections via supersedes-pointer to new Handshake receipt.*
