// Angel of Death™ · Layer 2 · Google SynthID Detection
// Bishop scaffold BP051 close 2026-05-22 · KniPr implementation TBD
//
// SynthID: Google's imperceptible AI watermark — survives screenshots, crops,
// re-compression, and color filters. 100 billion+ assets watermarked as of May 2026.
// Does NOT carry identity — only "generated by a SynthID-enabled model."
//
// KNIGHT TODO: Evaluate available detection libraries in priority order:
//   1. Google's official open-source SynthID detector (check GitHub google/synthid-text
//      and google-deepmind/synthid-detector — image detector released 2024)
//   2. Hugging Face: google/synthid-detector (HF model hub)
//   3. ONNX-exported version of the detector for local inference
//
// The image watermark detector uses a neural network — run via ONNX Runtime locally
// so it stays fully on-device (member-sovereignty canon).

import type {
  Asset,
  LayerResult,
  LayerRunOptions,
  VerificationLayer,
  SynthIdDetection,
} from '../types';

// ─── Constants ────────────────────────────────────────────────────────────────

const LAYER_NAME = 'synthid';
const LAYER_LABEL = 'Google SynthID Watermark';
const DEFAULT_TIMEOUT_MS = 20_000;

/**
 * SynthID detection threshold.
 * Scores above this are treated as "detected."
 * KNIGHT TODO: Calibrate threshold against the official SynthID model's ROC curve.
 * Google's published threshold is ~0.5 but adjust for local ONNX variant.
 */
const DETECTION_THRESHOLD = 0.5;

// ─── Layer implementation ─────────────────────────────────────────────────────

/**
 * Layer 2: Google SynthID Watermark Detector.
 *
 * Runs the SynthID image detector locally via ONNX Runtime.
 * Returns whether an imperceptible AI-generation watermark was found.
 *
 * Key characteristic: SynthID detection carries NO identity information.
 * A positive hit means "this was generated by a SynthID-participating model"
 * (Google Imagen, Gemini image generation, etc.) — not WHO generated it or WHY.
 *
 * Runs entirely on-device — no network call required.
 * For text assets, SynthID text detection is a separate model — currently out of scope
 * for v1 (image/video focus). KNIGHT: add text detection in a later KniPr.
 */
export class SynthIdLayer implements VerificationLayer {
  readonly name = LAYER_NAME;
  readonly layerLabel = LAYER_LABEL;

  /**
   * KNIGHT TODO: Inject the ONNX Runtime session for the SynthID detector.
   * Load the ONNX model from a bundled asset path so it works offline.
   *
   * Example using onnxruntime-node:
   *   import * as ort from 'onnxruntime-node';
   *   const session = await ort.InferenceSession.create('./models/synthid_detector.onnx');
   *
   * Model file: download from official Google source and bundle with Mnemosyne installer.
   * Place at: amplify-computer/resources/models/synthid_image_detector.onnx
   */
  constructor() {
    // KNIGHT TODO: Initialize ONNX session — lazy-load on first run() call to avoid
    // startup latency. Cache the session after first load.
  }

  async run(asset: Asset, options: LayerRunOptions = {}): Promise<LayerResult> {
    const startMs = Date.now();
    const timeoutMs = options.timeoutMs ?? DEFAULT_TIMEOUT_MS;

    try {
      // SynthID image detector only works on image assets (not video/audio in v1).
      if (!this._isImageAsset(asset)) {
        return this._unavailableResult(
          startMs,
          'SynthID image detection only supports image formats (JPEG, PNG, WebP, AVIF). Video/audio/text detection is out of scope for v1.'
        );
      }

      // KNIGHT TODO: Load asset as image tensor.
      // SynthID detector expects a preprocessed image tensor (typically 224×224 RGB float32).
      const imageTensor = await this._preprocessImage(asset, timeoutMs);

      if (!imageTensor) {
        return this._unavailableResult(startMs, 'Could not preprocess image for SynthID detection.');
      }

      // KNIGHT TODO: Run ONNX inference.
      // Input: preprocessed image tensor
      // Output: detection score (float 0.0–1.0)
      const detection = await this._runDetector(imageTensor, timeoutMs);

      if (!detection) {
        return this._unavailableResult(startMs, 'SynthID ONNX detector is not available. Ensure the model file is bundled and onnxruntime-node is installed.');
      }

      const detected = detection.rawScore >= DETECTION_THRESHOLD;

      return {
        layer: LAYER_NAME,
        layerLabel: LAYER_LABEL,
        verdict: detected ? 'verified-ai-signed' : 'unsigned-ambiguous',
        // SynthID detection has no identity chain — confidence is the raw model score scaled.
        // Cap at 92 even on strong detection to reflect inherent model uncertainty.
        confidence: detected ? Math.min(Math.round(detection.rawScore * 100), 92) : 0,
        attribution: detected
          ? {
              tool: 'SynthID-participating model (Google Imagen / Gemini image generation)',
              synthId: detection,
            }
          : undefined,
        durationMs: Date.now() - startMs,
        rawData: detection,
        explanation: detected
          ? `Google SynthID imperceptible watermark detected (score: ${(detection.rawScore * 100).toFixed(1)}%). This asset was generated by a model that participates in SynthID watermarking. No identity or authorship information is available from this signal alone.`
          : `No SynthID watermark detected. This does not confirm the asset is human-created — it may have been generated by a model that does not use SynthID, or the watermark may have been degraded beyond detection threshold.`,
      };

    } catch (err) {
      return this._unavailableResult(
        startMs,
        `SynthID layer error: ${err instanceof Error ? err.message : String(err)}`
      );
    }
  }

  // ─── Private helpers (all KNIGHT TODO) ──────────────────────────────────────

  /**
   * KNIGHT TODO: Preprocess the asset into the tensor format the SynthID detector expects.
   * Standard preprocessing for the Google SynthID image model:
   *   1. Decode image to RGB
   *   2. Resize to 224×224
   *   3. Normalize pixel values to [0, 1] or [-1, 1] (check model card)
   *   4. Shape to [1, 3, 224, 224] (NCHW) or [1, 224, 224, 3] (NHWC)
   *
   * For Electron: use sharp (bundled) or canvas for image decoding.
   * Return null if preprocessing fails — do not throw.
   */
  private async _preprocessImage(
    _asset: Asset,
    _timeoutMs: number
  ): Promise<Float32Array | null> {
    // TODO: decode → resize → normalize → return Float32Array
    return null; // STUB
  }

  /**
   * KNIGHT TODO: Run the ONNX SynthID detector against the preprocessed image tensor.
   * Return SynthIdDetection or null if the session is not loaded.
   */
  private async _runDetector(
    _tensor: Float32Array,
    _timeoutMs: number
  ): Promise<SynthIdDetection | null> {
    // TODO:
    //   const feeds = { input: new ort.Tensor('float32', tensor, [1, 3, 224, 224]) };
    //   const results = await session.run(feeds);
    //   const score = results['output'].data[0] as number;
    //   return { detected: score >= DETECTION_THRESHOLD, rawScore: score, detectorVersion: 'synthid-v1-onnx' };
    return null; // STUB
  }

  private _isImageAsset(asset: Asset): boolean {
    const imageMimes = [
      'image/jpeg', 'image/png', 'image/webp', 'image/avif', 'image/heic', 'image/heif',
    ];
    if (asset.mimeType) return imageMimes.includes(asset.mimeType);
    // Fallback: check file extension from displayName.
    const ext = asset.displayName.split('.').pop()?.toLowerCase();
    return ['jpg', 'jpeg', 'png', 'webp', 'avif', 'heic', 'heif'].includes(ext ?? '');
  }

  private _unavailableResult(startMs: number, explanation: string): LayerResult {
    return {
      layer: LAYER_NAME,
      layerLabel: LAYER_LABEL,
      verdict: 'detection-unavailable',
      confidence: 0,
      durationMs: Date.now() - startMs,
      explanation,
    };
  }
}
