import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import { SagaAlert } from './saga_alert.js';
import { SagaHealthSignal } from './saga_monitor.js';

const BISHOP_DROPZONE_PATH = path.join(
  os.homedir(),
  '.claude',
  'state',
  'bishop_dropzone_inbox'
);

/**
 * Notify the founder about a saga health alert by writing to Bishop dropzone
 */
export function notifyFounder(alert: SagaAlert, signal: SagaHealthSignal): void {
  try {
    // Ensure the dropzone directory exists
    if (!fs.existsSync(BISHOP_DROPZONE_PATH)) {
      fs.mkdirSync(BISHOP_DROPZONE_PATH, { recursive: true });
    }

    const alertFilename = `SAGA_HEALTH_ALERT_${alert.saga_id}.md`;
    const alertFilePath = path.join(BISHOP_DROPZONE_PATH, alertFilename);

    const alertContent = generateAlertMarkdown(alert, signal);

    fs.writeFileSync(alertFilePath, alertContent, 'utf-8');

    console.log(`[WATCHDOG] Alert notification written to: ${alertFilePath}`);
  } catch (error) {
    console.error('[WATCHDOG] Failed to notify founder:', error);
    throw new Error(`Failed to write alert notification: ${error}`);
  }
}

/**
 * Mark an alert as notified in the system
 */
export function markAlertNotified(alert_id: string): void {
  // In a production system, this would update a database or persistent store
  // For now, we'll log the notification
  console.log(`[WATCHDOG] Alert ${alert_id} marked as notified`);

  // Could extend this to:
  // - Update alert status in a database
  // - Write to a notification log file
  // - Update metrics/monitoring system
}

/**
 * Generate markdown content for the alert notification
 */
function generateAlertMarkdown(alert: SagaAlert, signal: SagaHealthSignal): string {
  const frontmatter = `---
alert_class: ${alert.alert_class}
saga_id: ${alert.saga_id}
timestamp: ${alert.timestamp}
trigger: ${alert.trigger}
---

`;

  const healthLabel =
    signal.health === 'green' ? 'Healthy' :
    signal.health === 'yellow' ? 'Degraded' : 'Critical';

  const body = `# Saga Health Alert: ${alert.alert_class.toUpperCase()}

## Alert Description

**Saga ID:** ${alert.saga_id}
**Alert Class:** ${alert.alert_class}
**Triggered:** ${new Date(alert.timestamp).toISOString()}
**Trigger Condition:** ${alert.trigger}

${alert.details ?? ''}

## Current Saga Health Signal

**Overall Health:** ${healthLabel} (${signal.health})
**Status:** ${signal.status ?? 'unknown'}

### Wave Metrics

- **Waves Total:** ${signal.waves_total}
- **Waves Complete:** ${signal.waves_complete}
- **Waves Errored:** ${signal.waves_errored}
- **SEGs Done:** ${signal.segs_done}
- **SEGs Errored:** ${signal.segs_errored}
- **Saga Wall-Clock:** ${signal.saga_wall_clock_seconds}s (${Math.round(signal.saga_wall_clock_seconds / 60)}m)
- **Avg Wave Wall-Clock:** ${signal.wave_wall_clock_seconds ?? 0}s

### Quality Gates

- **G-Saga-1 (All waves pass G1-G5):** ${signal.g_saga_1_ok ? 'PASS' : 'FAIL'}
- **G-Saga-2 (Wall-clock < 30min):** ${signal.g_saga_2_ok ? 'PASS' : 'FAIL'}
- **G-Saga-3 (Zero errors):** ${signal.g_saga_3_ok ? 'PASS' : 'FAIL'}
- **G-Saga-4 (Bishop curated):** ${signal.g_saga_4_ok ? 'PASS' : 'FAIL'}

## Recommended Action

${getRecommendedAction(alert, signal)}

---

**Generated by:** Librarian Watchdog System
**Notification Time:** ${new Date().toISOString()}
`;

  return frontmatter + body;
}

/**
 * Generate recommended actions based on alert and signal
 */
function getRecommendedAction(alert: SagaAlert, signal: SagaHealthSignal): string {
  const actions: string[] = [];

  switch (alert.trigger) {
    case 'wave_wall_clock_exceeded':
      actions.push('1. Review wave execution times for performance bottlenecks');
      actions.push('2. Check system resources during wave processing');
      actions.push('3. Monitor subsequent waves for continued slowness');
      break;

    case 'saga_wall_clock_warning':
      actions.push('1. Saga is approaching the 30-minute G-Saga-2 wall-clock limit');
      actions.push('2. Review pending waves and estimate remaining time');
      actions.push('3. Consider intervention if timeline cannot be recovered');
      break;

    case 'seg_errored':
      actions.push('1. **IMMEDIATE ACTION REQUIRED** - Investigate errored SEG(s)');
      actions.push('2. Review SEG logs and error details');
      actions.push('3. Determine if saga can continue or requires restart');
      break;

    case 'curation_overdue':
      actions.push('1. Saga completed but G-Saga-4 curation is overdue (>48h)');
      actions.push('2. Bishop synthesis review required to close the saga');
      actions.push('3. Schedule curation session immediately');
      break;

    default:
      actions.push('1. Review saga metrics and recent activity');
      actions.push('2. Investigate trigger condition: ' + alert.trigger);
      actions.push('3. Determine if manual intervention is required');
  }

  if (signal.segs_errored > 0) {
    actions.push('');
    actions.push(`Warning: ${signal.segs_errored} SEG(s) in error state — review error patterns`);
  }

  if (!signal.g_saga_3_ok) {
    actions.push('');
    actions.push('Warning: G-Saga-3 gate failing — errors detected in this saga run');
  }

  return actions.join('\n');
}
