import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import { SagaAlert } from './saga_alert';
import { SagaHealthSignal } from './saga_monitor';

const BISHOP_DROPZONE_PATH = path.join(
  os.homedir(),
  '.claude',
  'state',
  'bishop_dropzone_inbox'
);

/**
 * Notify the founder about a saga health alert by writing to Bishop dropzone
 */
export function notifyFounder(alert: SagaAlert, signal: SagaHealthSignal): void {
  try {
    // Ensure the dropzone directory exists
    if (!fs.existsSync(BISHOP_DROPZONE_PATH)) {
      fs.mkdirSync(BISHOP_DROPZONE_PATH, { recursive: true });
    }

    const alertFilename = `SAGA_HEALTH_ALERT_${alert.saga_id}.md`;
    const alertFilePath = path.join(BISHOP_DROPZONE_PATH, alertFilename);

    const alertContent = generateAlertMarkdown(alert, signal);

    fs.writeFileSync(alertFilePath, alertContent, 'utf-8');

    console.log(`[WATCHDOG] Alert notification written to: ${alertFilePath}`);
  } catch (error) {
    console.error('[WATCHDOG] Failed to notify founder:', error);
    throw new Error(`Failed to write alert notification: ${error}`);
  }
}

/**
 * Mark an alert as notified in the system
 */
export function markAlertNotified(alert_id: string): void {
  // In a production system, this would update a database or persistent store
  // For now, we'll log the notification
  console.log(`[WATCHDOG] Alert ${alert_id} marked as notified`);

  // Could extend this to:
  // - Update alert status in a database
  // - Write to a notification log file
  // - Update metrics/monitoring system
}

/**
 * Generate markdown content for the alert notification
 */
function generateAlertMarkdown(alert: SagaAlert, signal: SagaHealthSignal): string {
  const frontmatter = `---
alert_class: ${alert.alert_class}
saga_id: ${alert.saga_id}
timestamp: ${alert.timestamp}
trigger: ${alert.trigger}
---

`;

  const body = `# Saga Health Alert: ${alert.alert_class}

## Alert Description

**Saga ID:** ${alert.saga_id}
**Alert Class:** ${alert.alert_class}
**Triggered:** ${new Date(alert.timestamp).toISOString()}
**Trigger Condition:** ${alert.trigger}

${alert.description}

## Current Saga Health Signal

**Overall Health Score:** ${signal.health_score.toFixed(2)}
**Status:** ${getHealthStatus(signal.health_score)}

### Health Metrics

- **Activity Level:** ${signal.metrics.activity_level.toFixed(2)}
- **Success Rate:** ${(signal.metrics.success_rate * 100).toFixed(1)}%
- **Error Rate:** ${(signal.metrics.error_rate * 100).toFixed(1)}%
- **Stall Detection:** ${signal.metrics.stall_detected ? '⚠️ STALLED' : '✓ Active'}
- **Last Activity:** ${new Date(signal.metrics.last_activity_ts).toISOString()}

### Performance Stats

- **Total Operations:** ${signal.metrics.total_operations}
- **Successful Operations:** ${signal.metrics.successful_operations}
- **Failed Operations:** ${signal.metrics.failed_operations}
- **Average Operation Time:** ${signal.metrics.avg_operation_time_ms.toFixed(0)}ms

## Recommended Action

${getRecommendedAction(alert, signal)}

---

**Alert ID:** ${alert.alert_id}
**Generated by:** Librarian Watchdog System
**Notification Time:** ${new Date().toISOString()}
`;

  return frontmatter + body;
}

/**
 * Get human-readable health status
 */
function getHealthStatus(healthScore: number): string {
  if (healthScore >= 0.8) return '✓ Healthy';
  if (healthScore >= 0.6) return '⚠️ Degraded';
  if (healthScore >= 0.4) return '⚠️ Poor';
  return '🔴 Critical';
}

/**
 * Generate recommended actions based on alert and signal
 */
function getRecommendedAction(alert: SagaAlert, signal: SagaHealthSignal): string {
  const actions: string[] = [];

  switch (alert.alert_class) {
    case 'HEALTH_DEGRADED':
      actions.push('1. Review recent saga operations for errors or performance issues');
      actions.push('2. Check system resources and dependencies');
      actions.push('3. Monitor saga for recovery or further degradation');
      break;

    case 'HEALTH_CRITICAL':
      actions.push('1. **IMMEDIATE ACTION REQUIRED** - Investigate saga state immediately');
      actions.push('2. Review error logs and recent operations');
      actions.push('3. Consider saga recovery or rollback procedures');
      actions.push('4. Verify system health and resource availability');
      break;

    case 'STALL_DETECTED':
      actions.push('1. Check for blocking operations or deadlocks');
      actions.push('2. Review saga workflow state and pending operations');
      actions.push('3. Verify external dependencies are responding');
      actions.push('4. Consider manual intervention or saga restart');
      break;

    default:
      actions.push('1. Review saga metrics and recent activity');
      actions.push('2. Investigate trigger condition: ' + alert.trigger);
      actions.push('3. Determine if manual intervention is required');
  }

  // Add specific recommendations based on metrics
  if (signal.metrics.error_rate > 0.5) {
    actions.push('');
    actions.push('⚠️ **High error rate detected** - Review error patterns and root causes');
  }

  if (signal.metrics.stall_detected) {
    actions.push('');
    actions.push('⚠️ **Saga appears stalled** - No activity detected in expected timeframe');
  }

  if (signal.metrics.avg_operation_time_ms > 5000) {
    actions.push('');
    actions.push('⚠️ **Slow operations detected** - Review performance bottlenecks');
  }

  return actions.join('\n');
}
