"""
auth.py — Perplexity Gateway Authentication + Scope Enforcement
KN092 / BP011 Pod W Bean 4

Per-Pawn-dispatch API key generated by Bishop via `dispatch_pawn` tool.
Session-id from Pawn dispatch envelope.
Scope-check against safe_tool_list.yaml (three tiers: read_only / write_allowed / not_allowed).

Key store: <workspace>/librarian-mcp/dispatches/pawn/gateway_keys.jsonl
Each line: {"dispatch_id": "...", "api_key": "<sha256-derived>", "scribe_id": "R11_pawn_<dispatch_id>",
            "created_ts": "...", "expires_ts": "...", "active": true}
"""
from __future__ import annotations

import hashlib
import json
import os
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Optional

import yaml

WORKSPACE_ROOT = Path(__file__).resolve().parents[4]   # workspace root
GATEWAY_KEYS_PATH = (
    WORKSPACE_ROOT / "librarian-mcp" / "dispatches" / "pawn" / "gateway_keys.jsonl"
)
SAFE_TOOL_LIST_PATH = Path(__file__).parent / "safe_tool_list.yaml"

# Parsed once at import time (immutable config).
_safe_tool_list: dict[str, list[str]] = {}


def _load_safe_tool_list() -> dict[str, list[str]]:
    global _safe_tool_list
    if _safe_tool_list:
        return _safe_tool_list
    try:
        with open(SAFE_TOOL_LIST_PATH, encoding="utf-8") as fh:
            data = yaml.safe_load(fh)
        _safe_tool_list = {
            "read_only": data.get("read_only", []),
            "write_allowed": data.get("write_allowed", []),
            "not_allowed": data.get("not_allowed", []),
        }
    except Exception as exc:
        raise RuntimeError(f"Cannot load safe_tool_list.yaml: {exc}") from exc
    return _safe_tool_list


# ── Key store helpers ──────────────────────────────────────────────────────────

def _load_key_store() -> list[dict]:
    """Read all active key records from gateway_keys.jsonl."""
    if not GATEWAY_KEYS_PATH.exists():
        return []
    records = []
    try:
        with open(GATEWAY_KEYS_PATH, encoding="utf-8") as fh:
            for line in fh:
                line = line.strip()
                if line:
                    records.append(json.loads(line))
    except Exception:
        return []
    return records


def register_dispatch_key(
    dispatch_id: str,
    *,
    scribe_id: Optional[str] = None,
    ttl_hours: int = 24,
) -> str:
    """
    Generate and register a per-dispatch API key.  Returns the raw key string.
    Caller (Bishop / dispatch_pawn) must deliver the key to the Pawn dispatch script
    via a secure channel (never echoed in chat).
    """
    raw_key = hashlib.sha256(
        f"pawn_gateway:{dispatch_id}:{os.urandom(16).hex()}".encode()
    ).hexdigest()

    if scribe_id is None:
        scribe_id = f"R11_pawn_{dispatch_id}"

    now = datetime.now(timezone.utc)
    record = {
        "dispatch_id": dispatch_id,
        "api_key_hash": hashlib.sha256(raw_key.encode()).hexdigest(),
        "scribe_id": scribe_id,
        "created_ts": now.isoformat(),
        "expires_ts": (now + timedelta(hours=ttl_hours)).isoformat(),
        "active": True,
    }

    GATEWAY_KEYS_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(GATEWAY_KEYS_PATH, "a", encoding="utf-8") as fh:
        fh.write(json.dumps(record) + "\n")

    return raw_key


def revoke_dispatch_key(dispatch_id: str) -> bool:
    """Mark a dispatch key inactive. Returns True if a record was found."""
    if not GATEWAY_KEYS_PATH.exists():
        return False
    records = _load_key_store()
    modified = False
    for r in records:
        if r.get("dispatch_id") == dispatch_id:
            r["active"] = False
            modified = True
    if modified:
        with open(GATEWAY_KEYS_PATH, "w", encoding="utf-8") as fh:
            for r in records:
                fh.write(json.dumps(r) + "\n")
    return modified


# ── AuthResult ─────────────────────────────────────────────────────────────────

class AuthResult:
    def __init__(
        self,
        *,
        ok: bool,
        scribe_id: str = "",
        dispatch_id: str = "",
        error: str = "",
    ) -> None:
        self.ok = ok
        self.scribe_id = scribe_id
        self.dispatch_id = dispatch_id
        self.error = error

    def __repr__(self) -> str:
        if self.ok:
            return f"AuthResult(ok=True, scribe_id={self.scribe_id!r})"
        return f"AuthResult(ok=False, error={self.error!r})"


def authenticate(api_key: str, session_id: str) -> AuthResult:
    """
    Validate `api_key` against the key store.  `session_id` must start with
    ``R11_pawn_`` to match the dispatch key's registered scribe_id.

    Returns AuthResult.ok=True if valid + active + not expired.
    """
    if not api_key:
        return AuthResult(ok=False, error="Missing API key")

    key_hash = hashlib.sha256(api_key.encode()).hexdigest()
    records = _load_key_store()
    now = datetime.now(timezone.utc)

    for r in records:
        if r.get("api_key_hash") != key_hash:
            continue
        if not r.get("active", False):
            return AuthResult(ok=False, error="API key revoked")
        expires_ts = r.get("expires_ts", "")
        if expires_ts:
            try:
                exp = datetime.fromisoformat(expires_ts)
                if now > exp:
                    return AuthResult(ok=False, error="API key expired")
            except ValueError:
                pass
        return AuthResult(
            ok=True,
            scribe_id=r["scribe_id"],
            dispatch_id=r["dispatch_id"],
        )

    return AuthResult(ok=False, error="Unknown API key")


# ── Scope check ────────────────────────────────────────────────────────────────

class ScopeError(Exception):
    """Raised when a tool call is not permitted for the authenticated principal."""


def check_scope(tool_name: str, scribe_id: str) -> None:
    """
    Raise ScopeError if `tool_name` is in the ``not_allowed`` tier or if the
    write-allowed tier is requested by a scribe that isn't an R11_pawn_* scribe.

    A tool not listed in any tier is treated as not_allowed (fail-closed).
    """
    stl = _load_safe_tool_list()
    not_allowed: list[str] = stl.get("not_allowed", [])
    read_only: list[str] = stl.get("read_only", [])
    write_allowed: list[str] = stl.get("write_allowed", [])

    if tool_name in not_allowed:
        raise ScopeError(
            f"Tool '{tool_name}' is in the not_allowed tier — Pawn cannot call this."
        )

    if tool_name in write_allowed:
        if not scribe_id.startswith("R11_pawn_"):
            raise ScopeError(
                f"Tool '{tool_name}' requires a R11_pawn_* scribe-id; "
                f"got '{scribe_id}'."
            )
        return  # permitted

    if tool_name in read_only:
        return  # permitted

    # Not listed anywhere → fail closed
    raise ScopeError(
        f"Tool '{tool_name}' is not in the safe tool list — blocked by default (fail-closed)."
    )


def get_safe_tool_list() -> dict[str, list[str]]:
    """Return the parsed safe tool list (for introspection / tests)."""
    return _load_safe_tool_list()
