// AMPLIFY Computer — Hearth App Builder — Base Electron+SQLite Templates
// B69a — Embedded templates for packaged-app safety (no runtime file reads needed)
// Template vars use {{VAR_NAME}} syntax; render() replaces all occurrences.

export function render(template: string, vars: Record<string, string>): string {
  return template.replace(/\{\{([A-Z_]+)\}\}/g, (_, key) => vars[key] ?? `{{${key}}}`);
}

// ─── package.json ──────────────────────────────────────────────────────────────

export const PACKAGE_JSON = `{
  "name": "{{APP_SLUG}}",
  "version": "0.1.0",
  "description": "{{APP_DESCRIPTION}}",
  "main": "dist/electron/main.js",
  "scripts": {
    "dev": "concurrently \\"vite\\" \\"wait-on http://localhost:5173 && tsc -p tsconfig.electron.json && electron .\\"",
    "build": "vite build && tsc -p tsconfig.electron.json",
    "dist": "npm run build && electron-builder",
    "dist:win": "npm run build && electron-builder --win",
    "dist:mac": "npm run build && electron-builder --mac",
    "dist:linux": "npm run build && electron-builder --linux"
  },
  "dependencies": {
    "better-sqlite3": "^9.4.3",
    "electron-updater": "^6.1.7"
  },
  "devDependencies": {
    "@types/better-sqlite3": "^7.6.8",
    "@types/node": "^20.14.0",
    "@types/react": "^18.3.3",
    "@types/react-dom": "^18.3.0",
    "@vitejs/plugin-react": "^4.3.1",
    "concurrently": "^8.2.2",
    "electron": "^31.0.1",
    "electron-builder": "^24.13.3",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "typescript": "^5.4.5",
    "vite": "^5.3.1",
    "wait-on": "^7.2.0"
  },
  "build": {
    "appId": "com.lianabanyan.hearth.{{APP_SLUG}}",
    "productName": "{{APP_NAME}}",
    "directories": { "output": "release" },
    "files": ["dist/**/*"],
    "win": { "target": "nsis" },
    "mac": { "target": "dmg" },
    "linux": { "target": "AppImage" }
  }
}`;

// ─── tsconfig.json ─────────────────────────────────────────────────────────────

export const TSCONFIG_JSON = `{
  "compilerOptions": {
    "target": "ES2020",
    "useDefineForClassFields": true,
    "lib": ["ES2020", "DOM", "DOM.Iterable"],
    "module": "ESNext",
    "skipLibCheck": true,
    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",
    "strict": true,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "noFallthroughCasesInSwitch": true
  },
  "include": ["src"]
}`;

// ─── tsconfig.electron.json ────────────────────────────────────────────────────

export const TSCONFIG_ELECTRON_JSON = `{
  "compilerOptions": {
    "target": "ES2020",
    "module": "CommonJS",
    "moduleResolution": "node",
    "outDir": "dist/electron",
    "strict": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "resolveJsonModule": true
  },
  "include": ["electron/**/*.ts"]
}`;

// ─── vite.config.ts ────────────────────────────────────────────────────────────

export const VITE_CONFIG = `import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
  base: './',
  build: {
    outDir: 'dist/renderer',
    emptyOutDir: true,
  },
});`;

// ─── electron-builder.yml ─────────────────────────────────────────────────────

export const ELECTRON_BUILDER_YML = `appId: com.lianabanyan.hearth.{{APP_SLUG}}
productName: "{{APP_NAME}}"
directories:
  output: release
files:
  - dist/**/*
  - node_modules/**/*
  - package.json
win:
  target: nsis
  icon: assets/icon.ico
mac:
  target: dmg
  icon: assets/icon.icns
linux:
  target: AppImage
  icon: assets/icon.png`;

// ─── db/schema.sql ────────────────────────────────────────────────────────────

export const DB_SCHEMA_HEADER = `-- Generated by Hearth App Builder (B69)
-- App: {{APP_NAME}}
-- Created: {{CREATED_AT}}

PRAGMA journal_mode=WAL;
PRAGMA foreign_keys=ON;
`;

// ─── db/migrations/0001_init.sql ──────────────────────────────────────────────

export const MIGRATION_INIT_HEADER = `-- Migration 0001 — Initial schema
-- Generated by Hearth App Builder (B69)
-- App: {{APP_NAME}}

`;

// ─── electron/main.ts ─────────────────────────────────────────────────────────

export const ELECTRON_MAIN = `// {{APP_NAME}} — Electron Main Process
// Generated by Hearth App Builder (B69 — Liana Banyan AMPLIFY)

import { app, BrowserWindow, ipcMain } from 'electron';
import { join } from 'path';
import Database from 'better-sqlite3';
import { existsSync, mkdirSync } from 'fs';
import { homedir } from 'os';
import { runMigrations } from './migrations';

const IS_DEV = process.env.NODE_ENV === 'development' || !app.isPackaged;

const DATA_DIR = join(homedir(), '.lb_hearth_apps', '{{APP_UUID}}');
const DB_PATH = join(DATA_DIR, 'data.db');

let db: Database.Database | null = null;
let mainWindow: BrowserWindow | null = null;

function initDatabase(): void {
  if (!existsSync(DATA_DIR)) mkdirSync(DATA_DIR, { recursive: true });
  db = new Database(DB_PATH);
  db.pragma('journal_mode = WAL');
  db.pragma('foreign_keys = ON');
  runMigrations(db);
  console.log('[DB] Ready at', DB_PATH);
}

function createWindow(): void {
  mainWindow = new BrowserWindow({
    width: 1024,
    height: 768,
    title: '{{APP_NAME}}',
    webPreferences: {
      preload: join(__dirname, 'preload.js'),
      contextIsolation: true,
      nodeIntegration: false,
    },
  });

  if (IS_DEV) {
    mainWindow.loadURL('http://localhost:5173');
    mainWindow.webContents.openDevTools();
  } else {
    mainWindow.loadFile(join(__dirname, '../renderer/index.html'));
  }

  mainWindow.on('closed', () => { mainWindow = null; });
}

// ─── IPC handlers ─────────────────────────────────────────────────────────────
{{IPC_HANDLERS}}

app.whenReady().then(() => {
  initDatabase();
  createWindow();
  registerIPC();
});

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') app.quit();
});

app.on('activate', () => {
  if (!mainWindow) createWindow();
});

app.on('before-quit', () => {
  db?.close();
});
`;

// ─── electron/preload.ts ──────────────────────────────────────────────────────

export const ELECTRON_PRELOAD = `// {{APP_NAME}} — Electron Preload
// Generated by Hearth App Builder (B69)

import { contextBridge, ipcRenderer } from 'electron';

contextBridge.exposeInMainWorld('db', {
{{PRELOAD_BRIDGE}}
});
`;

// ─── electron/migrations.ts ───────────────────────────────────────────────────

export const ELECTRON_MIGRATIONS = `// {{APP_NAME}} — DB Migrations
// Generated by Hearth App Builder (B69)

import Database from 'better-sqlite3';
import { readFileSync, existsSync } from 'fs';
import { join } from 'path';

const MIGRATION_FILES = [
  join(__dirname, '../../db/migrations/0001_init.sql'),
];

export function runMigrations(db: Database.Database): void {
  db.exec(\`CREATE TABLE IF NOT EXISTS __migrations (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    filename TEXT NOT NULL UNIQUE,
    applied_at TEXT NOT NULL DEFAULT (datetime('now'))
  );\`);

  for (const file of MIGRATION_FILES) {
    const filename = file.split(/[\\\\/]/).pop() ?? file;
    const already = db.prepare('SELECT 1 FROM __migrations WHERE filename = ?').get(filename);
    if (already) continue;
    if (!existsSync(file)) {
      console.warn('[Migrations] File not found:', file);
      continue;
    }
    const sql = readFileSync(file, 'utf8');
    db.exec(sql);
    db.prepare('INSERT INTO __migrations (filename) VALUES (?)').run(filename);
    console.log('[Migrations] Applied:', filename);
  }
}
`;

// ─── src/App.tsx ──────────────────────────────────────────────────────────────

export const RENDERER_APP_TSX = `// {{APP_NAME}} — React App Shell
// Generated by Hearth App Builder (B69)

import { useState } from 'react';
import './App.css';
{{FORM_IMPORTS}}
{{VIEW_IMPORTS}}

type Tab = 'forms' | 'views';

export default function App() {
  const [tab, setTab] = useState<Tab>('forms');

  return (
    <div className="app">
      <header>
        <h1>{{APP_NAME}}</h1>
        <nav>
          <button className={tab === 'forms' ? 'active' : ''} onClick={() => setTab('forms')}>
            Add Entry
          </button>
          <button className={tab === 'views' ? 'active' : ''} onClick={() => setTab('views')}>
            View All
          </button>
        </nav>
      </header>
      <main>
        {tab === 'forms' ? (
          <div className="forms-panel">
{{FORM_RENDERS}}
          </div>
        ) : (
          <div className="views-panel">
{{VIEW_RENDERS}}
          </div>
        )}
      </main>
      <footer>
        <small>Built with Hearth — Liana Banyan AMPLIFY</small>
      </footer>
    </div>
  );
}
`;

// ─── src/App.css ──────────────────────────────────────────────────────────────

export const RENDERER_APP_CSS = `/* {{APP_NAME}} — App styles */
/* Generated by Hearth App Builder (B69) */

* { box-sizing: border-box; margin: 0; padding: 0; }

body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
  background: #f8f9fa;
  color: #212529;
  line-height: 1.6;
}

.app {
  max-width: 900px;
  margin: 0 auto;
  min-height: 100vh;
  display: flex;
  flex-direction: column;
}

header {
  background: #2c3e50;
  color: white;
  padding: 1rem 1.5rem;
  display: flex;
  align-items: center;
  gap: 2rem;
}

header h1 { font-size: 1.4rem; font-weight: 600; }

nav { display: flex; gap: 0.5rem; }

nav button {
  background: transparent;
  border: 1px solid rgba(255,255,255,0.4);
  color: white;
  padding: 0.3rem 1rem;
  border-radius: 4px;
  cursor: pointer;
  transition: background 0.15s;
}
nav button.active, nav button:hover { background: rgba(255,255,255,0.2); }

main { flex: 1; padding: 1.5rem; }

footer {
  text-align: center;
  padding: 0.75rem;
  color: #6c757d;
  font-size: 0.8rem;
  border-top: 1px solid #dee2e6;
}

/* Form card */
.form-card {
  background: white;
  border-radius: 8px;
  padding: 1.5rem;
  margin-bottom: 1.5rem;
  box-shadow: 0 1px 3px rgba(0,0,0,0.1);
}
.form-card h2 { font-size: 1.1rem; margin-bottom: 1rem; color: #2c3e50; }

.field-group { margin-bottom: 1rem; }
.field-group label { display: block; font-size: 0.85rem; font-weight: 600; margin-bottom: 0.25rem; color: #495057; }
.field-group input, .field-group textarea, .field-group select {
  width: 100%;
  padding: 0.5rem 0.75rem;
  border: 1px solid #ced4da;
  border-radius: 4px;
  font-size: 0.95rem;
}
.field-group textarea { min-height: 80px; resize: vertical; }

.submit-btn {
  background: #2c3e50;
  color: white;
  border: none;
  padding: 0.6rem 1.5rem;
  border-radius: 4px;
  cursor: pointer;
  font-size: 0.95rem;
  transition: background 0.15s;
}
.submit-btn:hover { background: #34495e; }
.submit-ok { color: #28a745; margin-left: 0.75rem; font-size: 0.9rem; }

/* View table */
.view-card {
  background: white;
  border-radius: 8px;
  padding: 1.5rem;
  margin-bottom: 1.5rem;
  box-shadow: 0 1px 3px rgba(0,0,0,0.1);
  overflow-x: auto;
}
.view-card h2 { font-size: 1.1rem; margin-bottom: 1rem; color: #2c3e50; }

table { width: 100%; border-collapse: collapse; }
th { background: #f1f3f5; text-align: left; padding: 0.5rem 0.75rem; font-size: 0.85rem; border-bottom: 2px solid #dee2e6; }
td { padding: 0.5rem 0.75rem; border-bottom: 1px solid #dee2e6; font-size: 0.9rem; }
tr:hover td { background: #f8f9fa; }
.empty-state { text-align: center; color: #6c757d; padding: 2rem; }
`;

// ─── src/index.html ────────────────────────────────────────────────────────────

export const INDEX_HTML = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{{APP_NAME}}</title>
</head>
<body>
  <div id="root"></div>
  <script type="module" src="/src/main.tsx"></script>
</body>
</html>`;

// ─── src/main.tsx ─────────────────────────────────────────────────────────────

export const MAIN_TSX = `import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
);`;

// ─── README.md ────────────────────────────────────────────────────────────────

export const README_MD = `# {{APP_NAME}}

Built with **Hearth** — the Liana Banyan AMPLIFY App Builder.

## Running this app

\`\`\`bash
npm install
npm run dev
\`\`\`

## Building for distribution

\`\`\`bash
npm run dist
\`\`\`

> **Note on code signing:** On Windows you may see a SmartScreen warning on first run.
> Click "More info → Run anyway" to proceed. This is expected until the app reaches
> sufficient install volume or is signed with an EV certificate.
>
> On macOS: right-click the app → Open to bypass Gatekeeper on first launch.

## Data location

Your data is stored locally at: \`~/lb_hearth_apps/{{APP_UUID}}/data.db\`

## Upgrading

Re-open Hearth, select this app, and choose "Re-Generate" to upgrade with your latest spec.
Existing data is preserved during upgrades.

---
*Hearth — Liana Banyan AMPLIFY | "Help each other help ourselves."*
`;
