/**
 * cathedral-export edge function (K438b Phase E)
 * ==============================================
 * Implements #2268 Claim 1(d) export-on-demand. POST { member_id } and
 * the function returns a ZIP bundle (octet-stream) containing the
 * member's entire Cathedral plus the standalone Python reader.
 *
 * Bundle layout (matches cathedral-import + standalone reader expectations):
 *   registry.yaml                           — per-Scribe registry
 *   registry.json                           — same data, JSON form (reader fallback)
 *   scribe_<name>.jsonl                     — one tablet per Scribe (header + entries)
 *   fates_log.jsonl                         — Three Fates routing audit
 *   tidbits.jsonl                           — SP-21 verify-action ledger
 *   member_cathedral.json                   — top-level member_cathedrals row (tier, dates)
 *   README.md                               — schema doc + reader usage
 *   LICENSE                                 — AGPL-3.0 + Pledged Commons grant
 *   liana-companion-standalone-reader.py    — offline reader (no LB deps)
 *
 * Side effect on success: cathedral.member_cathedrals.export_count is
 * bumped via service-role UPDATE and export_last_at is stamped.
 *
 * Auth: caller passes their JWT in the Authorization header (Supabase
 * automatically attaches it for invoke()). The function verifies the JWT
 * matches the requested member_id before proceeding. Service-role is used
 * for the actual cathedral.* reads to bypass column-level GRANT
 * restrictions on the export_count/export_last_at update.
 */
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient, type SupabaseClient } from "https://esm.sh/@supabase/supabase-js@2";
import { zipSync, strToU8 } from "https://esm.sh/fflate@0.8.2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

function json(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });
}

interface Adjacent {
  level: number;
  field: string;
}

interface ScribeRow {
  scribe_id: string;
  member_id: string;
  name: string;
  primary_field: string;
  adjacents: Adjacent[];
  keywords: string[];
  active: boolean;
  share_level: string;
  share_target_id: string | null;
  created_at: string;
  updated_at: string;
}

interface EntryRow {
  entry_id: string;
  scribe_id: string;
  member_id: string;
  ts: string;
  session_id: string | null;
  observation: string;
  source: string;
  canonical_ref: string | null;
  tags: string[];
  shared_level: string;
  shared: boolean;
}

async function loadStandaloneReader(): Promise<Uint8Array> {
  // Read the Python reader sibling-file at runtime. Deno bundles the
  // function directory; this file is shipped alongside index.ts.
  try {
    const url = new URL("./liana-companion-standalone-reader.py", import.meta.url);
    const data = await Deno.readFile(url);
    return data;
  } catch (err) {
    console.error("cathedral-export: failed to load reader.py", err);
    return strToU8("# liana-companion-standalone-reader.py — load failed at deploy time\n");
  }
}

function safeFilename(name: string): string {
  return name.replace(/[^A-Za-z0-9._-]/g, "_").slice(0, 64) || "scribe";
}

function buildRegistryYaml(scribes: ScribeRow[]): string {
  const lines: string[] = [];
  lines.push("# Liana Banyan Cathedral export — registry.yaml");
  lines.push("# Generated by cathedral-export edge function (K438b)");
  lines.push("version: cathedral-export-v1");
  lines.push("scribes:");
  for (const s of scribes) {
    lines.push(`  - id: ${s.scribe_id}`);
    lines.push(`    name: "${escapeYaml(s.name)}"`);
    lines.push(`    primary_field: "${escapeYaml(s.primary_field)}"`);
    lines.push(`    active: ${s.active}`);
    lines.push(`    share_level: ${s.share_level}`);
    lines.push("    keywords:");
    for (const k of s.keywords ?? []) lines.push(`      - "${escapeYaml(String(k))}"`);
    lines.push("    adjacents:");
    for (const a of s.adjacents ?? []) {
      lines.push(`      - level: ${a.level}`);
      lines.push(`        field: "${escapeYaml(a.field ?? "")}"`);
    }
    lines.push(`    created_at: ${s.created_at}`);
    lines.push(`    updated_at: ${s.updated_at}`);
  }
  return lines.join("\n") + "\n";
}

function buildRegistryJson(scribes: ScribeRow[]): string {
  return (
    JSON.stringify(
      {
        version: "cathedral-export-v1",
        scribes: scribes.map((s) => ({
          id: s.scribe_id,
          name: s.name,
          primary_field: s.primary_field,
          adjacents: s.adjacents,
          keywords: s.keywords,
          active: s.active,
          share_level: s.share_level,
          created_at: s.created_at,
          updated_at: s.updated_at,
        })),
      },
      null,
      2,
    ) + "\n"
  );
}

function escapeYaml(s: string): string {
  return String(s).replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

function buildTablet(scribe: ScribeRow, entries: EntryRow[]): string {
  const header = {
    type: "header",
    scribe_id: scribe.scribe_id,
    name: scribe.name,
    primary_field: scribe.primary_field,
    adjacents: scribe.adjacents,
    keywords: scribe.keywords,
    share_level: scribe.share_level,
    opened: scribe.created_at,
    opened_by: "cathedral-export edge function",
  };
  const lines = [JSON.stringify(header)];
  for (const e of entries) {
    lines.push(
      JSON.stringify({
        ts: e.ts,
        session: e.session_id,
        observation: e.observation,
        source: e.source,
        canonical_ref: e.canonical_ref,
        tags: e.tags,
        shared_level: e.shared_level,
      }),
    );
  }
  return lines.join("\n") + "\n";
}

function buildJsonl(rows: unknown[]): string {
  return rows.map((r) => JSON.stringify(r)).join("\n") + (rows.length ? "\n" : "");
}

function buildReadme(opts: {
  member_id: string;
  generated_at: string;
  scribe_count: number;
  entry_count: number;
}): string {
  return `# Your Liana Banyan Cathedral

Generated: ${opts.generated_at}
Member: ${opts.member_id}
Scribes: ${opts.scribe_count}
Entries: ${opts.entry_count}

## What's in this bundle

| File | Description |
|------|-------------|
| \`registry.yaml\` | Your Scribes — primary field, adjacents, keywords |
| \`registry.json\` | Same data in JSON form (used by the standalone reader) |
| \`scribe_<NAME>.jsonl\` | Append-only entries per Scribe (one file each) |
| \`fates_log.jsonl\` | Three Fates routing audit (#2269) |
| \`tidbits.jsonl\` | SP-21 verify-action ledger |
| \`member_cathedral.json\` | Top-level Cathedral metadata (tier, dates) |
| \`liana-companion-standalone-reader.py\` | Offline reader, zero non-stdlib dependencies |
| \`LICENSE\` | AGPL-3.0 + Pledged Commons grant per #2260 |

## How to read your Cathedral offline

\`\`\`bash
python liana-companion-standalone-reader.py consult "your query"
python liana-companion-standalone-reader.py list-scribes
python liana-companion-standalone-reader.py stats
\`\`\`

## How to import this bundle into another Cathedral

POST the ZIP to the LB \`cathedral-import\` edge function with one of:
  \`collision_strategy=merge\` (default — append entries, keep both registries)
  \`collision_strategy=overwrite\` (replace existing same-named Scribes)
  \`collision_strategy=keep_existing\` (skip Scribes that already exist)

## Append-only invariant (#2270 Claim 1(b))

Every entry in every \`scribe_*.jsonl\` is immutable. Re-importing this
bundle never mutates an existing entry. Edits happen by appending a new
entry that supersedes the prior one — the original stays as audit trail.

## Why a standalone reader

Per #2268 Claim 1(d): a Cathedral must remain useful to its member even
if Liana Banyan disappears tomorrow. The standalone reader has zero
non-stdlib Python dependencies and uses the same primary*1.0 +
adjacent*0.5 retrieval scoring as the live platform. Audit it, fork it,
keep it forever.
`;
}

function buildLicense(): string {
  return `Liana Banyan Cathedral export — bundle license
================================================

This Cathedral export bundle is the intellectual property of the member
named in member_cathedral.json. Liana Banyan Corporation makes no claim
of ownership over its contents.

The bundled standalone reader (liana-companion-standalone-reader.py) is
released under the GNU Affero General Public License v3.0 (AGPL-3.0) so
that members can run, modify, and redistribute it freely. The reader's
source is the canonical definition of the export bundle's interpretation
algorithm.

Per #2260 Cooperative Defensive Patent Pledge: any patent claims Liana
Banyan holds that read on the standalone reader's algorithm are pledged
back to the cooperative commons. Members and former members are free to
use, modify, and redistribute the reader without patent encumbrance.
`;
}

serve(async (req: Request) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: corsHeaders });
  if (req.method !== "POST") return json({ error: "method_not_allowed" }, 405);

  const url = Deno.env.get("SUPABASE_URL");
  const serviceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
  if (!url || !serviceKey) {
    return json({ error: "server_not_configured" }, 500);
  }

  let payload: { member_id?: string };
  try {
    payload = await req.json();
  } catch {
    return json({ error: "invalid_json_body" }, 400);
  }
  const memberId = payload.member_id;
  if (!memberId || !/^[0-9a-f-]{36}$/i.test(memberId)) {
    return json({ error: "missing_or_invalid_member_id" }, 400);
  }

  // Verify the caller's JWT matches the requested member_id (prevent the
  // service-role surface from being abused as a cross-member exfil).
  const auth = req.headers.get("Authorization") || req.headers.get("authorization");
  const jwt = auth?.startsWith("Bearer ") ? auth.slice("Bearer ".length) : null;
  if (!jwt) return json({ error: "missing_auth" }, 401);

  const anonKey = Deno.env.get("SUPABASE_ANON_KEY") || "";
  const userClient: SupabaseClient = createClient(url, anonKey, {
    global: { headers: { Authorization: `Bearer ${jwt}` } },
  });
  const userRes = await userClient.auth.getUser(jwt);
  if (userRes.error || !userRes.data.user) {
    return json({ error: "auth_failed", hint: userRes.error?.message }, 401);
  }
  if (userRes.data.user.id !== memberId) {
    return json({ error: "member_id_mismatch" }, 403);
  }

  const admin: SupabaseClient = createClient(url, serviceKey, {
    db: { schema: "cathedral" },
    auth: { persistSession: false, autoRefreshToken: false },
  });

  // Pull member-cathedral row (top-level metadata)
  const mcRes = await admin
    .from("member_cathedrals")
    .select("*")
    .eq("member_id", memberId)
    .maybeSingle();
  if (mcRes.error) return json({ error: "member_cathedrals_query_failed", hint: mcRes.error.message }, 500);

  const memberCathedral = mcRes.data ?? { member_id: memberId };

  const scribesRes = await admin
    .from("member_scribes")
    .select("*")
    .eq("member_id", memberId)
    .order("created_at", { ascending: true });
  if (scribesRes.error) return json({ error: "scribes_query_failed", hint: scribesRes.error.message }, 500);
  const scribes = (scribesRes.data ?? []) as ScribeRow[];

  let allEntries: EntryRow[] = [];
  if (scribes.length > 0) {
    const entriesRes = await admin
      .from("scribe_entries")
      .select("*")
      .eq("member_id", memberId)
      .order("ts", { ascending: true });
    if (entriesRes.error) return json({ error: "entries_query_failed", hint: entriesRes.error.message }, 500);
    allEntries = (entriesRes.data ?? []) as EntryRow[];
  }

  const fatesRes = await admin
    .from("fates_log")
    .select("*")
    .eq("member_id", memberId)
    .order("ts", { ascending: true });
  if (fatesRes.error) return json({ error: "fates_log_query_failed", hint: fatesRes.error.message }, 500);

  const tidbitsRes = await admin
    .from("tidbits")
    .select("*")
    .eq("member_id", memberId)
    .order("ts", { ascending: true });
  if (tidbitsRes.error) return json({ error: "tidbits_query_failed", hint: tidbitsRes.error.message }, 500);

  // Build bundle files
  const files: Record<string, Uint8Array> = {};
  files["registry.yaml"] = strToU8(buildRegistryYaml(scribes));
  files["registry.json"] = strToU8(buildRegistryJson(scribes));
  files["fates_log.jsonl"] = strToU8(buildJsonl(fatesRes.data ?? []));
  files["tidbits.jsonl"] = strToU8(buildJsonl(tidbitsRes.data ?? []));
  files["member_cathedral.json"] = strToU8(JSON.stringify(memberCathedral, null, 2) + "\n");

  const usedNames = new Set<string>();
  for (const s of scribes) {
    let base = `scribe_${safeFilename(s.name)}`;
    let candidate = `${base}.jsonl`;
    let n = 1;
    while (usedNames.has(candidate)) {
      candidate = `${base}_${n++}.jsonl`;
    }
    usedNames.add(candidate);
    const entries = allEntries.filter((e) => e.scribe_id === s.scribe_id);
    files[candidate] = strToU8(buildTablet(s, entries));
  }

  files["README.md"] = strToU8(
    buildReadme({
      member_id: memberId,
      generated_at: new Date().toISOString(),
      scribe_count: scribes.length,
      entry_count: allEntries.length,
    }),
  );
  files["LICENSE"] = strToU8(buildLicense());
  files["liana-companion-standalone-reader.py"] = await loadStandaloneReader();

  const zipBytes = zipSync(files, { level: 6 });

  // Bump export counters (best-effort; failure does not block the download).
  await admin
    .from("member_cathedrals")
    .update({
      export_count: (memberCathedral as { export_count?: number }).export_count
        ? ((memberCathedral as { export_count: number }).export_count ?? 0) + 1
        : 1,
      export_last_at: new Date().toISOString(),
    })
    .eq("member_id", memberId);

  const filename = `cathedral-export-${memberId.slice(0, 8)}-${Date.now()}.zip`;
  return new Response(zipBytes, {
    status: 200,
    headers: {
      ...corsHeaders,
      "Content-Type": "application/zip",
      "Content-Disposition": `attachment; filename="${filename}"`,
      "X-Cathedral-Scribes": String(scribes.length),
      "X-Cathedral-Entries": String(allEntries.length),
    },
  });
});
