// lianabanyan.com React platform adapter — Battery Dispatch SEG-2b
// Writes content route → npm build → Firebase deploy hosting:main
// BP082 · Sonnet 4.6

import { existsSync, readFileSync, writeFileSync } from 'fs';
import { join } from 'path';
import { homedir } from 'os';
import { exec } from 'child_process';
import { promisify } from 'util';
import type { ContentFileMeta, DispatchResult } from './types';

const execAsync = promisify(exec);
const WORKSPACE = join(homedir(), 'Documents', 'LianaBanyanPlatform');
const PLATFORM = join(WORKSPACE, 'platform');
const PUBLIC_ROUTES = join(PLATFORM, 'src', 'routes', 'public.tsx');
const PAGES_DIR = join(PLATFORM, 'src', 'pages');

function slugify(s: string) {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}

function sectionPath(cls: ContentFileMeta['contentClass']): string {
  switch (cls) {
    case 'op-ed': return 'op-eds';
    case 'paper': return 'papers';
    default: return 'articles';
  }
}

function buildReactPage(meta: ContentFileMeta, body: string): string {
  const title = meta.title.replace(/"/g, '\\"');
  const lines = body.split('\n');
  // Convert markdown to JSX paragraphs (simple)
  const paras = lines
    .join('\n')
    .split(/\n{2,}/)
    .filter(Boolean)
    .map((p) => `<p className="leading-relaxed my-5">${p.trim().replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>').replace(/\*(.*?)\*/g, '<em>$1</em>').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')}</p>`)
    .join('\n          ');
  return `// Auto-generated by Battery Dispatch v0.3.0 · BP082 · ${new Date().toISOString().split('T')[0]}
import { useEffect } from "react";
import { Link } from "react-router-dom";
import { ArrowLeft } from "lucide-react";

export default function Page_${slugify(meta.title).replace(/-/g, '_')}() {
  useEffect(() => { document.title = "${title} — Liana Banyan"; }, []);
  return (
    <div className="min-h-screen bg-background text-foreground">
      <div className="border-b border-border/40 px-4 py-3">
        <Link to="/" className="inline-flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground transition-colors">
          <ArrowLeft className="h-3.5 w-3.5" /> lianabanyan.com
        </Link>
      </div>
      <article className="mx-auto max-w-2xl px-4 py-12 sm:px-6">
        <div className="mb-6 flex items-center gap-3">
          <span className="text-xs font-semibold uppercase tracking-widest text-emerald-500">${meta.contentClass}</span>
          <span className="text-xs text-muted-foreground">${meta.date ?? ''}</span>
        </div>
        <h1 className="mb-4 text-3xl font-bold leading-tight tracking-tight sm:text-4xl">${title}</h1>
        ${meta.subtitle ? `<p className="mb-8 text-lg text-muted-foreground leading-relaxed">${meta.subtitle}</p>` : ''}
        <div className="prose prose-neutral dark:prose-invert max-w-none">
          ${paras}
        </div>
        <div className="mt-10 text-center">
          <Link to="/join" className="inline-flex items-center gap-2 rounded-lg bg-emerald-600 px-6 py-3 text-sm font-semibold text-white hover:bg-emerald-500 transition-colors">
            Join the cooperative — $5/year
          </Link>
        </div>
      </article>
    </div>
  );
}
`;
}

function componentName(meta: ContentFileMeta): string {
  const slug = meta.slug ?? slugify(meta.title);
  return 'AutoPage_' + slug.replace(/-/g, '_');
}

export async function dispatchToPlatform(
  meta: ContentFileMeta,
  body: string,
  onProgress: (msg: string) => void,
): Promise<DispatchResult> {
  const platform = 'lianabanyan' as const;
  try {
    const slug = meta.slug ?? slugify(meta.title);
    const section = sectionPath(meta.contentClass);
    const pageName = componentName(meta);
    const pageFile = join(PAGES_DIR, `${pageName}.tsx`);

    onProgress('lianabanyan.com: writing page component…');
    writeFileSync(pageFile, buildReactPage(meta, body), 'utf8');

    // Patch public.tsx if route not already present
    const routesContent = readFileSync(PUBLIC_ROUTES, 'utf8');
    const routePath = `/${section}/${slug}`;
    if (!routesContent.includes(routePath)) {
      const importLine = `const ${pageName} = lazy(() => import("@/pages/${pageName}"));\n`;
      const routeLine = `    <Route path="${routePath}" element={<LazyPage><${pageName} /></LazyPage>} />\n`;
      const patched = routesContent
        .replace(
          '// BP082 -- Op-Ed: Thou Art the Man',
          `// Battery Dispatch auto-route: ${routePath}\n${routeLine}\n    // BP082 -- Op-Ed: Thou Art the Man`,
        )
        .replace(
          '// BP074 -- Founder story page\nconst FounderStory',
          `${importLine}// BP074 -- Founder story page\nconst FounderStory`,
        );
      writeFileSync(PUBLIC_ROUTES, patched, 'utf8');
      onProgress('lianabanyan.com: route registered');
    }

    onProgress('lianabanyan.com: building React platform…');
    await execAsync('npm run build', { cwd: PLATFORM, timeout: 300_000 });
    onProgress('lianabanyan.com: build complete');

    onProgress('lianabanyan.com: deploying to Firebase…');
    await execAsync('firebase deploy --only hosting:main -P default', { cwd: PLATFORM, timeout: 300_000 });
    onProgress('lianabanyan.com: deployed ✓');

    const url = `https://lianabanyan.com/${section}/${slug}/`;
    return { platform, status: 'success', url };
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    onProgress(`lianabanyan.com: ERROR — ${msg}`);
    return { platform, status: 'failed', error: msg };
  }
}
