-- =============================================================================
-- INNOVATION LOG — Session 11B Batch 4 — Steward System & Pizza Oven (#1624-#1630)
-- =============================================================================
-- Source: BISHOP_DROPZONE/THRESH_FOR_KNIGHT_SESSION_11B_BATCH4.md (Bishop thresh, March 14, 2026)
-- Count after: 1,630

INSERT INTO public.innovation_log (innovation_number, title, description, category, patent_bag, status)
VALUES
  (1624, 'Steward Role: Project Manager with Skin-in-the-Game via Pledged Marks', 'A Steward is a project/campaign manager who commits their own earned Marks (Pledged Marks) to the project they manage, creating aligned incentives. The Steward''s deferred compensation scales with their commitment ratio — the more they pledge, the more they earn back when the project succeeds. Distinct from BandWagon Influencers in that Stewards actively manage the project, not just back it. Deferred payment tracked by Marks, same legal structure as Bounties (wages for services rendered, not securities).', 'Cooperative Governance / Project Management', 'Bag 7', 'pending'),
  (1625, 'Pledged Marks: Personal Marks Escrowed to Specific Project', 'A third Mark subtype (after standard Marks and Backed Marks). Pledged Marks are a member''s own earned Marks that they voluntarily escrow to a specific project. They are compartmentalized per-project (not pooled), held until project completion, then released back to the member plus their proportional share of operational surplus. Distinct from Backed Marks (which come from the cooperative pool) in that Pledged Marks come from personal earned Marks and are project-specific pre-fund compartments.', 'Currency / Financial Infrastructure', 'Bag 7', 'pending'),
  (1626, 'The Pizza Oven: Marginal-Cost Batching Incentive for Multi-Campaign Stewards', 'Named after the principle that if you already heated a brick wood-fired oven that holds 30 pizzas for one pizza, you may as well cook more at the same time while it''s hot. Applied to Stewards: the operational overhead of managing one campaign through Kickstarter or similar platforms (legal, logistics, marketing, production) creates a hot oven. Managing additional campaigns simultaneously has dramatically lower marginal cost. Incentivizes Stewards to batch-manage multiple campaigns, increasing platform throughput.', 'Operational Efficiency / Incentive Design', 'Bag 8', 'pending'),
  (1627, 'Proportional Steward Compensation: Deferred Payment Scales with Commitment Ratio', 'A Steward''s deferred payment (in Marks) dynamically adjusts based on the ratio of their Pledged Marks to the total project funding needed. If a Steward pledges 50% of the required Marks, they receive proportionally larger deferred compensation. If they pledge 80%, the cooperative''s contribution drops to 20% and the Steward''s compensation increases accordingly. This creates a self-balancing funding mechanism: Stewards with more confidence in a project commit more, reducing cooperative risk while earning proportionally more.', 'Compensation / Incentive Design', 'Bag 7', 'pending'),
  (1628, 'Tri-Source Project Funding: Steward + BandWagon + LB Allocation', 'Projects are funded from three simultaneous sources that dynamically adjust: (1) Steward Pledged Marks — the project manager''s personal commitment, (2) BandWagon Backed Marks — Influencer/Taste Ranger allocations from the cooperative pool directed by members with demonstrated judgment, (3) LB Allocation Pool — the cooperative''s direct allocation. The ratios self-balance: as Steward and BandWagon commitments increase, LB''s required allocation decreases. Approximately 1/3 of other projects'' operational surplus flows into the allocation pool, creating a circular funding ecosystem.', 'Financial Infrastructure / Project Funding', 'Bag 7', 'pending'),
  (1629, 'Pledged Mark Release Mechanic: Escrow Release on Project Completion with Surplus Matching', 'When a project completes successfully, Pledged Marks are released back to the Steward (removing the project-specific hold). The Steward also receives their proportional share of production run surplus, matched to their commitment ratio. If a Steward pledged 50% and the production run generates surplus, they receive 50% of the distributable surplus as additional Marks. Failed projects result in Pledged Marks being absorbed into the cooperative pool (the "skin in the game" risk). This creates real consequence for Steward judgment.', 'Currency / Transaction Mechanics', 'Bag 7', 'pending'),
  (1630, 'Pledged Mark Voting: Commitment-Weighted Governance for Any Member', 'Generalization of the Steward''s Pledged Mark mechanic to any governance decision. Any member can pledge their own earned Marks to signal conviction on proposals, initiatives, or platform decisions — not just project funding. The pledge creates a temporary escrow that demonstrates commitment beyond a simple vote. Members who pledge correctly (the decision succeeds or the backed option wins) receive their Pledged Marks back plus reputation credit. This creates commitment-weighted governance where influence costs something real, preventing low-stakes trolling or casual manipulation while preserving one-member-one-vote for standard decisions.', 'Governance / Voting Mechanics', 'Bag 8', 'pending')
ON CONFLICT (innovation_number) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  patent_bag = EXCLUDED.patent_bag,
  status = EXCLUDED.status;
