-- =============================================================================
-- INNOVATION LOG — Session 11B Thresh — 14 LMD pipeline innovations #1600-#1613
-- =============================================================================
-- Source: BISHOP_DROPZONE/THRESH_FOR_KNIGHT_SESSION_11B.md (Bishop thresh from Founder Session 11)
-- Count after: 1,613

INSERT INTO public.innovation_log (innovation_number, title, description, category, patent_bag, status)
VALUES
  (1600, 'Recipe Popularity Leaderboard by Local Area', 'Rank dishes/recipes by number of fulfilled orders and unique recipients per geographic area (postal code, Node). Creates quality incentive: popularity = what people actually re-order. Dual purpose: member-facing leaderboard AND internal node-density/load-balancing data.', 'Let''s Make Dinner', 'Single Provisional', 'pending'),
  (1601, 'Recipe Edition Concept (Recipe × Cook Pair)', '"Edition" — named pairing of recipe with specific cook. "Maria''s Edition of Grandma''s Lasagna" vs "Tony''s Edition." Same recipe, different cook, separate reputation track. Per-iteration quality scoring without conflating recipe quality with cook quality.', 'Let''s Make Dinner', 'Single Provisional', 'pending'),
  (1602, 'Multi-Dimensional Recipe Review Scoring (Taste, Flavor, Spice, Mouthfeel)', 'Four-axis review system for meal quality: taste, flavor, spice, mouthfeel (each 1-5). Captures qualities that matter for food rather than generic star ratings. Reviewer reputation affected by participation — stamps build reviewer credibility.', 'Let''s Make Dinner', 'Single Provisional', 'pending'),
  (1603, 'Time-Bounded Review Incentive ("Become an Influencer")', 'Reward (e.g. 5 Marks) for submitting recipe review within X hours (e.g. 72) of meal delivery. Creates Influencer role: members who test each recipe and provide quality feedback. Configurable via dna_lock. Ties into Codebreaker-style guild progression.', 'Let''s Make Dinner / Reputation', 'Single Provisional', 'pending'),
  (1604, 'Cook-Declared Capacity-First Zone Partitioning', 'Service-area partitioning that starts from cook''s declared capacity and willingness ("I can make 30 but schedule 12 this week"). Zones defined by what cooks WANT to produce, then matched to demand. Capacity-first (worker preference) vs demand-first (platform) — patentable distinction.', 'Let''s Make Dinner / Range Optimization', 'Single Provisional', 'pending'),
  (1605, 'Primary/Secondary/Backup Cook Assignment for Recipe Continuity', 'Three-tier cook redundancy per recipe per area. Primary (60%) scheduled orders; Secondary (20%) vacation, illness, overflow; Backup + Staple Stand-in (20%) emergency. Multiple cooks per recipe for portion of returns. Recipe availability when primary unavailable.', 'Let''s Make Dinner', 'Single Provisional', 'pending'),
  (1606, 'Capacity Fulfiller Role', 'Cook role distinct from recipe originator — can "whip up a lasagna in 3 hours" as overflow coverage. Not primary recipe owner; skilled cook willing to step in for any recipe they are qualified to make. Separate from Staple Stand-ins (external partners e.g. pizza places).', 'Let''s Make Dinner', 'Single Provisional', 'pending'),
  (1607, 'Pre-Prepped Freeze-Dry Pipeline for LMD (60/40 Buffer Model)', 'Pipeline: Grocery Fulfillment → Delivery to Staging → Meal Prep → Freeze-Dry → Storage (60/40). For 6 preordered, make 10: deliver 6, store 4 freeze-dried. Stored = "just add water." Stored enter On-Demand Available at $10 (vs $5 preorder). FIFO freezer. Unclaimed in X days → charitable release. Safety margins include workers'' families.', 'Let''s Make Dinner / Supply Chain', 'Single Provisional', 'pending'),
  (1608, 'Storage Bounty (Chest Freezer Operator Role)', 'Bounty role: members operate chest freezers as LMD storage nodes. Platform prefunds freezer; operator pays electricity, maintains FIFO (e.g. 6 freezers). Payment: flat monthly + per-meal-stored variable. Distributed cold-storage network without centralized warehouse.', 'Let''s Make Dinner / Bounties', 'Single Provisional', 'pending'),
  (1609, 'On-Demand Premium from Buffer Inventory', 'The 4 stored portions (60/40 split) released to "Immediately Available" at $10 (double $5 preorder). Premium funds buffer. If not ordered within availability window (e.g. 14 days, dna_lock), automatic charitable release. Zero-waste: every portion sells at premium or fulfills charitable mission.', 'Let''s Make Dinner / Pricing', 'Single Provisional', 'pending'),
  (1610, 'Marks Reservation with Hold-and-Release (Hotel-Style)', 'Preorder schedules reserve Marks (held, not charged) like hotel holding card. Half applied at Let''s Get Groceries lead time; remainder converted at delivery/fulfillment. Cancel → release. If member lacks sufficient Marks at due date, charitable buffer covers gap.', 'Three-Currency System', 'Single Provisional', 'pending'),
  (1611, 'Charitable Buffer for Preorders (Capped, Time-Bounded Top-Up)', 'When member has preordered but lacks enough Marks/Credits for this week''s share, platform extends time-bound, capped top-up from charitable pool. Cap: max N meals/week OR max % of weekly need. Time-bound (e.g. 2 weeks) then review. No product difference — only who pays. Same dignity as Anonymous Volume.', 'Let''s Make Dinner / Charitable', 'Single Provisional', 'pending'),
  (1612, 'Dual-Use Order Data as Node-Density Intelligence', 'Same fulfilled-order data that drives recipe popularity leaderboard also maps node density across geography. Serves: (a) LMD range optimization, (b) load balancing across 16 initiatives, (c) anonymized aggregate data that can fund initiatives. One signal, multiple consumers.', 'Platform Data / Cross-Initiative', 'Single Provisional', 'pending'),
  (1613, 'Pipeline Bounty Diagram with Fillable Slots', 'Visual pipeline diagram (Mermaid or UI) showing each LMD supply-chain step as a "slot" members can claim as bounty. Slots: Grocery Fulfillment, Delivery to Staging, Meal Prep, Storage, Preorder Delivery, On-Demand Release. Each slot shows capacity, current fill, open bounties. Pipeline transparent and recruitable.', 'Let''s Make Dinner / Bounties', 'Single Provisional', 'pending')
ON CONFLICT (innovation_number) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  patent_bag = EXCLUDED.patent_bag,
  status = EXCLUDED.status;
