-- =============================================================================
-- INNOVATION LOG — Bishop Session 018D — 16 innovations #1785-#1800
-- Megadump 2: Duress Password, Card Passing, Heart of Peace, Turn-Key Plans,
-- Scheduling Surcharges, Wyze Cameras, Camera Review, Footage Storage,
-- Take Me To Work, Selfie Verification, Defense Klaus Elves, First-Back,
-- Node Distribution, Marketplace Layer, Data Sales, Political Proposals
-- =============================================================================
-- Source: BISHOP_DROPZONE/AA_SESSION_018D_MEGADUMP_2.md
-- Count after: 1,800

INSERT INTO public.innovation_log (innovation_number, title, description, category, patent_bag, status)
VALUES
  (1785, 'Duress Password / Sequence Security', 'Dual-password system: real password (standard or Sequence Security pathway ritual) and duress password that gives partial resources but silently alerts LB, flags transactions as compromised in immutable ledger evidentiary branch. Criminally evidentiary trail deters theft. Sequence Security: your login IS your behavior pattern — specific page-visit order IS the authentication.', 'Security / Anti-Theft', 'Bag 9', 'pending'),
  (1786, 'Medallion Card Passing Chain (Give-Forward Doubling)', 'After getting second card, give first to someone else. If recipient signs up, original holder marks DOUBLE. Gaming analysis: 50x gaming produces 50 meals eaten/given/sold/rotted — all self-correcting. Signup requires email + two passwords (real + duress). Name can be anything. Reputation and categorization apply.', 'Viral Growth / Social Impact', 'Bag 9', 'pending'),
  (1787, 'Heart of Peace Principle — Self-Correcting Anti-Gaming', 'From Arbinger Institute "The Anatomy of Peace": heart at peace sees people as people, not obstacles. Applied to LB: design systems that self-correct rather than prevent. Scarcity is valuable because scarce — when food is abundant, gaming food is as pointless as hoarding air. Constitutional-level principle alongside Cost+20%.', 'Platform Philosophy', 'Bag 9', 'pending'),
  (1788, 'Turn-Key Business Plans Page (Treasure Map Chest)', 'Platform page: chest of Treasure Maps, each a turn-key business plan for a Node type (Larder, Kitchen, Tool Swap, Running Jewels, Game Swap, Service Route). Includes cold start instructions, Multiplier slots, Cost+20% pricing, equipment list, regulatory notes. Integrates earmarked Credit escrow demand signals.', 'Business Infrastructure', 'Bag 9', 'pending'),
  (1789, 'Advance Scheduling Surcharge Tiers', 'Surcharges for last-minute requests instead of discounts for advance booking. Base price at 30+ days. Tier 1 surcharge under 30 days, Tier 2 under 7 days, Tier 3 under 24 hours, Tier 4 under 1 hour. Planning is cheaper. Applies to all scheduled services. "It behooves you to plan. Or hey, don not! LB makes more that way."', 'Pricing / Scheduling', 'Bag 9', 'pending'),
  (1790, 'Wyze Camera Keeper Monitoring System', 'Consumer Wyze cameras (~$20) recording 72-hour segments on food storage Nodes. Monitors pests, rodents, pets, people, fire. Camera feeds on Node Captain Bridge screens. Keeper cameras on Keeper Wyze account (physical plug-in + phone scan). Optional homeowner package for personal cameras paid through LB but on their own account. Two tiers: LB required vs personal optional.', 'Operations / Security / IoT', 'Bag 9', 'pending'),
  (1791, 'Camera Review Bounty (Fast-Forward Verification)', 'Two unaffiliated reviewers independently fast-forward 72-hour footage. Trained criteria: pests, unauthorized access, temperature, fire, equipment. Both sign off → Keeper and Prepper sign off → footage deleted. Easy money bounty: review 5 recordings in ~20 minutes. Flagged footage escalates to Captain then Steward.', 'Quality Assurance / Bounty', 'Bag 9', 'pending'),
  (1792, 'Secondary/Backup Team Footage Storage', 'Both Secondary AND Backup teams store footage copies on home devices. Two people per team = four total copies across four independent homes. All ledger transactions stamped. Teams do useful work (storing + availability for review) rather than just standing by. Distributed storage = no central server, no single point of failure.', 'Data Integrity / Evidence', 'Bag 9', 'pending'),
  (1793, 'Take Me To Work — Sponsored Labor Transport Bounty', 'Mission FOUR: pool of laborers with vetted Driver pickups and dropoffs. Scheduled rides to/from work. Selfie verification for safety. Defense Klaus Elves for physical safety response. Stamped jobs, pickups, dropoffs. Milk route model: more passengers = lower per-passenger cost. For people who cannot hold traditional jobs, LB flexibility provides alternatives.', 'Transportation / Employment', 'Bag 9', 'pending'),
  (1794, 'Selfie Verification Protocol (Driver + Passenger)', 'Both parties upload selfies before each ride. Driver: selfie to drive for us. Passenger: selfie before pickup. Both held by LB until other uploads, then driver pic shown to passenger before accepting ride. Not presented as mutual surveillance — standard verification. Immutable ledger records both with timestamps for evidence.', 'Safety / Identity Verification', 'Bag 9', 'pending'),
  (1795, 'Defense Klaus Elves — Door-Knock Safety Team', 'Physical response when Defense Klaus activated: 5 Elves at last known location asking for person, 5 more at registered residence. Metadata photo verification challenges for drivers (random: photo with chair from two angles in 1 min, shoe toe on chair). Hard to fake. Standing bounty for availability, activation pay when called. Volunteer firefighter model.', 'Safety / Physical Response', 'Bag 9', 'pending'),
  (1796, 'LB First-Back Guarantee (Johnny Appleseed Node Seeding)', 'LB backs the FIRST bounty of EVERY CATEGORY in any new area. Eliminates cold start risk for first Node Captain. Cost bounded: one backing per category per area. If Node succeeds, LB earns back through Cost+20%. If fails, LB gains market intelligence. Cue Card: Be the first in your area. LB guarantees the backing.', 'Cold Start / Growth', 'Bag 9', 'pending'),
  (1797, 'Node Distribution Formula — Hybrid Area Calculation', 'Defines ideal Node coverage. Hybrid model: demand triggers (25+ Local Sheet notifications or earmarked Credits), population caps (1 Node per 200 households per category), geography shapes (user-drawn areas from Local Sheet). First-Back Guarantee seeds below-threshold areas.', 'Operations / Geography', 'Bag 9', 'pending'),
  (1798, 'Local Sheet Marketplace Layer (Garage Sales, Closet Sales, Homemade)', 'OVERLAY on Local Sheet, not separate page. Garage sales, eBay-style closet sales, homemade goods. Filterable categories — toggle on/off. Shared delivery routes with LGG/LMD. Same XP reputation across all activities. One view, filterable layers.', 'Commerce / Discovery', 'Bag 9', 'pending'),
  (1799, 'Data Sales Member Benefit — Academic Revenue Sharing', 'LB sells anonymized aggregated platform data to academics and researchers. Revenue applied to initiative of EACH MEMBER choice. Surveillance capitalism inverted: transparent, member-directed, zero-demographics. Creates real-time poll of member priorities. FAQ Benefits section item.', 'Revenue / Member Benefits', 'Bag 9', 'pending'),
  (1800, 'Political Expedition Initiative Proposal System', 'New initiatives beyond Sweet Sixteen proposed and voted on through Political Expedition. Platform evolves by member demand. Pledged Mark Voting for commitment-weighted influence. The eggs and butter of concerns and issues — benefits.', 'Governance / Platform Evolution', 'Bag 9', 'pending')
ON CONFLICT (innovation_number) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  patent_bag = EXCLUDED.patent_bag,
  status = EXCLUDED.status;
