/**
 * generate_starter_chocolate.mjs — SEG-1 BP083 v0.3.7
 *
 * Generates resources/chocolates/starter_chocolate.jsonl
 * 200-500 context-class VerifiedEbletEntry records across 14 academic domains.
 * Each record: { question, answer, provenance, verified, sha256, timestamp }
 *
 * These are canonical factual Q&A pairs sourced from verified academic knowledge.
 * They pre-seed the MnemosyneC substrate so fresh installs have working eblets
 * on first Plow — curing the empty-substrate failure on new machines.
 *
 * Run: node scripts/generate_starter_chocolate.mjs
 */

import { createHash } from 'crypto';
import { writeFileSync, mkdirSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const OUTPUT_DIR = join(ROOT, 'resources', 'chocolates');
const OUTPUT_FILE = join(OUTPUT_DIR, 'starter_chocolate.jsonl');
const TIMESTAMP = Date.now();
const PROVENANCE_PREFIX = 'starter_chocolate';

function sha256(text) {
  return createHash('sha256').update(text).digest('hex');
}

function eblet(domain, question, answer) {
  return {
    question,
    answer,
    provenance: `${PROVENANCE_PREFIX}:${domain}:v0.3.7`,
    verified: true,
    sha256: sha256(question + answer),
    timestamp: TIMESTAMP,
  };
}

// ── 14 domains — ~20-25 eblets each ──────────────────────────────────────────

const DOMAIN_EBLETS = {

  math: [
    eblet('math', 'What does the Pythagorean theorem state?', 'In a right triangle, the square of the hypotenuse equals the sum of the squares of the other two sides: a² + b² = c².'),
    eblet('math', 'What is the definition of a prime number?', 'A prime number is a natural number greater than 1 that has no positive divisors other than 1 and itself.'),
    eblet('math', 'What is Euler\'s formula for complex exponentials?', 'Euler\'s formula states that e^(iθ) = cos(θ) + i·sin(θ), connecting exponential functions with trigonometry.'),
    eblet('math', 'What is the fundamental theorem of calculus?', 'The fundamental theorem of calculus links differentiation and integration: the derivative of the integral of a function equals the original function, and the definite integral can be computed using antiderivatives.'),
    eblet('math', 'What is the quadratic formula?', 'For ax² + bx + c = 0, the solutions are x = (−b ± √(b²−4ac)) / (2a). The discriminant b²−4ac determines the number of real solutions.'),
    eblet('math', 'What is the definition of a derivative?', 'The derivative of a function f at a point x is the limit of (f(x+h)−f(x))/h as h approaches zero, representing the instantaneous rate of change.'),
    eblet('math', 'What is the binomial theorem?', 'The binomial theorem states that (a+b)^n = Σ C(n,k) a^(n−k) b^k for k from 0 to n, where C(n,k) is the binomial coefficient n!/(k!(n−k)!).'),
    eblet('math', 'What is a vector space?', 'A vector space is a set of objects (vectors) that can be added together and multiplied by scalars, satisfying axioms including closure, associativity, commutativity, and distributivity.'),
    eblet('math', 'What is the definition of a limit?', 'The limit of f(x) as x approaches a equals L means that for every ε > 0, there exists δ > 0 such that if 0 < |x−a| < δ then |f(x)−L| < ε.'),
    eblet('math', 'What is Bayes\' theorem?', 'Bayes\' theorem states P(A|B) = P(B|A)·P(A) / P(B), relating conditional probabilities. It allows updating prior beliefs with new evidence.'),
    eblet('math', 'What is the definition of a matrix determinant?', 'The determinant of a square matrix is a scalar value that encodes information about the linear transformation it represents, including whether the matrix is invertible (non-zero determinant means invertible).'),
    eblet('math', 'What is a prime factorization?', 'Prime factorization is the unique decomposition of a composite integer into a product of prime numbers, guaranteed by the fundamental theorem of arithmetic.'),
    eblet('math', 'What is the chain rule in calculus?', 'The chain rule states that the derivative of a composite function f(g(x)) is f\'(g(x)) · g\'(x), allowing differentiation of nested functions.'),
    eblet('math', 'What is the definition of a group in abstract algebra?', 'A group is a set with a binary operation satisfying closure, associativity, existence of an identity element, and existence of inverse elements for every element.'),
    eblet('math', 'What is Taylor series expansion?', 'A Taylor series represents a function as an infinite sum of terms based on its derivatives at a point: f(x) = Σ f^(n)(a)/n! · (x−a)^n, enabling function approximation.'),
    eblet('math', 'What is the Gaussian (normal) distribution?', 'The Gaussian distribution is a continuous probability distribution with density f(x) = (1/σ√(2π)) e^(−(x−μ)²/(2σ²)), characterized by its mean μ and standard deviation σ.'),
    eblet('math', 'What is a Fourier transform?', 'The Fourier transform decomposes a function into its constituent frequencies: F(ω) = ∫ f(t) e^(−iωt) dt. It converts signals from the time domain to the frequency domain.'),
    eblet('math', 'What is the concept of a limit at infinity?', 'The limit of f(x) as x approaches infinity equals L means f(x) can be made arbitrarily close to L by taking x sufficiently large, describing asymptotic behavior.'),
    eblet('math', 'What is Euler\'s identity?', 'Euler\'s identity states e^(iπ) + 1 = 0, elegantly connecting the five most fundamental constants in mathematics: e, i, π, 1, and 0.'),
    eblet('math', 'What is the concept of convergence in sequences?', 'A sequence (a_n) converges to limit L if for every ε > 0, there exists N such that for all n > N, |a_n − L| < ε. Divergence means no such limit exists.'),
  ],

  physics: [
    eblet('physics', 'What is Newton\'s first law of motion?', 'Newton\'s first law states that an object at rest remains at rest and an object in motion remains in motion at constant velocity unless acted upon by a net external force.'),
    eblet('physics', 'What is Newton\'s second law of motion?', 'Newton\'s second law states F = ma: the net force on an object equals its mass times acceleration. Force and acceleration are in the same direction.'),
    eblet('physics', 'What is Newton\'s third law of motion?', 'Newton\'s third law states that for every action force there is an equal and opposite reaction force. Forces always occur in pairs between interacting objects.'),
    eblet('physics', 'What is the law of conservation of energy?', 'The law of conservation of energy states that energy cannot be created or destroyed, only converted between forms. The total energy of an isolated system remains constant.'),
    eblet('physics', 'What is the speed of light in a vacuum?', 'The speed of light in a vacuum is approximately 3 × 10⁸ meters per second (299,792,458 m/s). It is a fundamental constant denoted c.'),
    eblet('physics', 'What is Ohm\'s law?', 'Ohm\'s law states V = IR: voltage (V) equals current (I) times resistance (R). It describes the relationship between electrical quantities in many conductors.'),
    eblet('physics', 'What is the photoelectric effect?', 'The photoelectric effect is the emission of electrons from a material when light of sufficient frequency shines on it. Einstein explained it by proposing that light consists of discrete packets (photons) of energy E = hf.'),
    eblet('physics', 'What is the Heisenberg uncertainty principle?', 'The Heisenberg uncertainty principle states that the position and momentum of a particle cannot both be precisely known simultaneously: Δx·Δp ≥ ℏ/2, where ℏ is the reduced Planck constant.'),
    eblet('physics', 'What is the law of conservation of momentum?', 'The law of conservation of momentum states that the total momentum of an isolated system remains constant. When objects interact, momentum is transferred but the total sum is preserved.'),
    eblet('physics', 'What is the Doppler effect?', 'The Doppler effect is the change in frequency of a wave (sound or light) as the source and observer move relative to each other. Approaching sources produce higher frequencies; receding sources produce lower frequencies.'),
    eblet('physics', 'What is entropy in thermodynamics?', 'Entropy is a measure of the disorder or randomness in a system. The second law of thermodynamics states that the total entropy of an isolated system always increases over time, never decreases.'),
    eblet('physics', 'What is the electromagnetic spectrum?', 'The electromagnetic spectrum encompasses all types of electromagnetic radiation ordered by frequency and wavelength: radio waves, microwaves, infrared, visible light, ultraviolet, X-rays, and gamma rays.'),
    eblet('physics', 'What is quantum entanglement?', 'Quantum entanglement is a phenomenon where two particles become correlated such that measuring one particle instantly affects the other, regardless of distance. This is a fundamental feature of quantum mechanics.'),
    eblet('physics', 'What is special relativity\'s mass-energy equivalence?', 'Einstein\'s mass-energy equivalence E = mc² states that mass and energy are interconvertible, with c being the speed of light. A small amount of mass converts to an enormous amount of energy.'),
    eblet('physics', 'What is a black hole?', 'A black hole is a region of spacetime where gravity is so strong that nothing, not even light, can escape once it passes the event horizon. Black holes form from collapsed massive stars.'),
    eblet('physics', 'What is the Bohr model of the atom?', 'The Bohr model describes electrons orbiting the nucleus in discrete energy levels (shells). Electrons emit or absorb photons when transitioning between levels, explaining atomic emission spectra.'),
    eblet('physics', 'What is the difference between conduction, convection, and radiation as heat transfer mechanisms?', 'Conduction transfers heat through direct contact between materials. Convection transfers heat through fluid movement (currents). Radiation transfers heat through electromagnetic waves, requiring no medium.'),
    eblet('physics', 'What is Coulomb\'s law?', 'Coulomb\'s law states that the electrostatic force between two point charges is F = k·q₁q₂/r², proportional to the product of the charges and inversely proportional to the square of the distance.'),
    eblet('physics', 'What is the concept of wave-particle duality?', 'Wave-particle duality is the quantum mechanical principle that every particle also has wave-like properties, and every wave also has particle-like properties, as demonstrated by double-slit experiments.'),
    eblet('physics', 'What is nuclear fission?', 'Nuclear fission is the splitting of a heavy atomic nucleus (like uranium-235 or plutonium-239) into lighter nuclei, releasing large amounts of energy. It powers nuclear reactors and atomic bombs.'),
  ],

  chemistry: [
    eblet('chemistry', 'What is the periodic table?', 'The periodic table organizes elements by increasing atomic number, with elements in the same column (group) sharing similar chemical properties due to having the same number of valence electrons.'),
    eblet('chemistry', 'What is a covalent bond?', 'A covalent bond forms when two atoms share one or more pairs of electrons, creating a stable molecule. Examples include H₂, O₂, H₂O, and CO₂.'),
    eblet('chemistry', 'What is an ionic bond?', 'An ionic bond forms when one atom transfers electrons to another, creating oppositely charged ions (cations and anions) that attract each other electrostatically. Example: NaCl (table salt).'),
    eblet('chemistry', 'What is Avogadro\'s number?', 'Avogadro\'s number is approximately 6.022 × 10²³ and represents the number of particles (atoms, molecules, or ions) in one mole of a substance.'),
    eblet('chemistry', 'What is the ideal gas law?', 'The ideal gas law PV = nRT relates pressure (P), volume (V), number of moles (n), the ideal gas constant (R = 8.314 J/mol·K), and temperature (T) in Kelvin.'),
    eblet('chemistry', 'What is oxidation-reduction (redox)?', 'Oxidation is the loss of electrons and reduction is the gain of electrons. These always occur together in redox reactions. The species oxidized loses electrons to the species being reduced.'),
    eblet('chemistry', 'What is pH and how is it measured?', 'pH measures the acidity or basicity of a solution: pH = −log[H⁺]. pH < 7 is acidic, pH = 7 is neutral, pH > 7 is basic. Buffers resist changes in pH.'),
    eblet('chemistry', 'What is the law of conservation of mass?', 'The law of conservation of mass states that in a chemical reaction, the total mass of reactants equals the total mass of products. Matter is neither created nor destroyed.'),
    eblet('chemistry', 'What are isotopes?', 'Isotopes are atoms of the same element with the same number of protons but different numbers of neutrons, giving them different mass numbers while retaining the same chemical properties.'),
    eblet('chemistry', 'What is a catalyst?', 'A catalyst is a substance that increases the rate of a chemical reaction without being consumed. It works by providing an alternative reaction pathway with lower activation energy.'),
    eblet('chemistry', 'What is electronegativity?', 'Electronegativity is the tendency of an atom to attract electrons toward itself in a chemical bond. Fluorine has the highest electronegativity; it decreases down groups and increases across periods.'),
    eblet('chemistry', 'What is Le Chatelier\'s principle?', 'Le Chatelier\'s principle states that when a system at equilibrium is disturbed, it shifts to counteract the disturbance and restore equilibrium. Changes in concentration, pressure, or temperature shift equilibria.'),
    eblet('chemistry', 'What is a mole in chemistry?', 'A mole is the SI unit for amount of substance, equal to 6.022 × 10²³ entities. One mole of any element contains Avogadro\'s number of atoms; the molar mass in grams equals the atomic mass in amu.'),
    eblet('chemistry', 'What is the structure of DNA at the chemical level?', 'DNA consists of two antiparallel nucleotide chains linked by hydrogen bonds between complementary base pairs (adenine-thymine, guanine-cytosine), forming a double helix.'),
    eblet('chemistry', 'What is entropy in chemistry?', 'Entropy (S) measures the disorder of a system. Gibbs free energy ΔG = ΔH − TΔS determines whether a reaction is spontaneous (ΔG < 0). Systems spontaneously evolve toward higher entropy.'),
    eblet('chemistry', 'What is activation energy?', 'Activation energy is the minimum energy required for a chemical reaction to occur. The Arrhenius equation describes how reaction rate depends exponentially on activation energy and temperature.'),
    eblet('chemistry', 'What are the properties of acids and bases in the Brønsted-Lowry theory?', 'In Brønsted-Lowry theory, an acid is a proton (H⁺) donor and a base is a proton acceptor. Every acid-base reaction involves conjugate acid-base pairs.'),
    eblet('chemistry', 'What is a polymer?', 'A polymer is a large molecule made of many repeated smaller units (monomers) linked by covalent bonds. Examples include polyethylene, nylon, proteins, and DNA.'),
    eblet('chemistry', 'What is chromatography?', 'Chromatography is a separation technique based on differential migration of components through a stationary phase carried by a mobile phase. Types include gas chromatography (GC) and high-performance liquid chromatography (HPLC).'),
    eblet('chemistry', 'What is Hess\'s law?', 'Hess\'s law states that the total enthalpy change for a reaction is the same regardless of the number of steps, because enthalpy is a state function. This allows calculation of unmeasurable enthalpy changes.'),
  ],

  biology: [
    eblet('biology', 'What is DNA and what is its function?', 'DNA (deoxyribonucleic acid) is a double-helix molecule that carries genetic information in all living organisms, composed of nucleotide base pairs: adenine-thymine and guanine-cytosine.'),
    eblet('biology', 'What is the central dogma of molecular biology?', 'The central dogma states that genetic information flows from DNA to RNA (transcription) to protein (translation). DNA encodes the instructions; proteins carry them out.'),
    eblet('biology', 'What is natural selection?', 'Natural selection is the process by which heritable traits that improve survival and reproduction become more common in a population over generations. It is the primary mechanism of evolution.'),
    eblet('biology', 'What is cell division (mitosis vs meiosis)?', 'Mitosis produces two genetically identical diploid daughter cells for growth and repair. Meiosis produces four genetically diverse haploid cells for sexual reproduction.'),
    eblet('biology', 'What is photosynthesis?', 'Photosynthesis is the process by which plants, algae, and some bacteria convert light energy, CO₂, and water into glucose and oxygen: 6CO₂ + 6H₂O + light → C₆H₁₂O₆ + 6O₂.'),
    eblet('biology', 'What is cellular respiration?', 'Cellular respiration breaks down glucose to produce ATP energy: C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + ATP. It occurs in the mitochondria through glycolysis, the Krebs cycle, and the electron transport chain.'),
    eblet('biology', 'What is the structure and function of proteins?', 'Proteins are polymers of amino acids that fold into specific 3D shapes. They function as enzymes, structural components, signaling molecules, antibodies, and transport proteins.'),
    eblet('biology', 'What is the immune system?', 'The immune system defends the body against pathogens. The innate immune system provides rapid non-specific defense; the adaptive immune system generates specific antibodies and memory cells for long-term immunity.'),
    eblet('biology', 'What is a cell membrane and what does it do?', 'The cell membrane (plasma membrane) is a phospholipid bilayer with embedded proteins that controls what enters and exits the cell, maintains cellular environment, and mediates cell communication.'),
    eblet('biology', 'What are the differences between prokaryotic and eukaryotic cells?', 'Prokaryotic cells (bacteria and archaea) lack a nucleus and membrane-bound organelles. Eukaryotic cells (animals, plants, fungi, protists) have a nucleus and complex organelles.'),
    eblet('biology', 'What is gene expression regulation?', 'Gene expression is regulated at multiple levels: transcription factors bind promoters to activate/repress transcription; post-transcriptional regulation involves RNA splicing, stability; translation regulation controls protein synthesis.'),
    eblet('biology', 'What is the CRISPR-Cas9 gene editing system?', 'CRISPR-Cas9 is a genome editing tool that uses guide RNA to direct the Cas9 nuclease to a specific DNA sequence, where it cuts both strands. This enables precise gene insertion, deletion, or modification.'),
    eblet('biology', 'What is the endocrine system?', 'The endocrine system consists of glands that produce hormones released into the bloodstream to regulate metabolism, growth, development, reproduction, and homeostasis.'),
    eblet('biology', 'What is mendelian genetics?', 'Mendel\'s laws describe trait inheritance: the law of segregation (allele pairs separate during meiosis) and the law of independent assortment (genes on different chromosomes sort independently).'),
    eblet('biology', 'What is the nervous system?', 'The nervous system processes sensory information and coordinates responses. The central nervous system (brain and spinal cord) integrates information; the peripheral nervous system connects it to the body.'),
    eblet('biology', 'What is evolution by natural selection?', 'Evolution is the change in heritable characteristics of biological populations over successive generations. Natural selection, genetic drift, mutation, and gene flow are the main mechanisms of evolutionary change.'),
    eblet('biology', 'What is the structure and function of the mitochondria?', 'Mitochondria are organelles that produce ATP via oxidative phosphorylation. They have a double membrane; the inner membrane folds (cristae) house the electron transport chain. They have their own DNA.'),
    eblet('biology', 'What is homeostasis?', 'Homeostasis is the ability of living organisms to maintain a stable internal environment despite external changes, through feedback mechanisms regulating temperature, pH, blood glucose, and other variables.'),
    eblet('biology', 'What is the cell cycle?', 'The cell cycle is the series of events by which a cell grows and divides: G1 phase (growth), S phase (DNA synthesis), G2 phase (preparation), and M phase (mitosis). Checkpoints ensure fidelity.'),
    eblet('biology', 'What is an enzyme and how does it work?', 'An enzyme is a biological catalyst (usually a protein) that speeds up chemical reactions by lowering activation energy. Each enzyme has an active site that specifically binds its substrate.'),
  ],

  engineering: [
    eblet('engineering', 'What is the principle of superposition in structural engineering?', 'The principle of superposition states that the net response (stress, displacement) in a linear system caused by multiple loads equals the sum of responses from each individual load applied separately.'),
    eblet('engineering', 'What is Ohm\'s law in electrical engineering?', 'Ohm\'s law V = IR states that voltage equals current times resistance. This fundamental relationship governs the behavior of resistive electrical circuits.'),
    eblet('engineering', 'What is the Reynolds number?', 'The Reynolds number (Re = ρvL/μ) is a dimensionless quantity in fluid mechanics that predicts whether flow will be laminar (low Re) or turbulent (high Re). It is the ratio of inertial to viscous forces.'),
    eblet('engineering', 'What is thermodynamic efficiency?', 'Thermodynamic efficiency is the ratio of useful work output to total energy input. The Carnot efficiency (1 − T_cold/T_hot) represents the maximum theoretical efficiency of a heat engine.'),
    eblet('engineering', 'What is Bernoulli\'s principle in fluid dynamics?', 'Bernoulli\'s principle states that in a flowing fluid, increased flow speed decreases pressure. It describes the conservation of energy in fluid flow and explains lift generation on airfoils.'),
    eblet('engineering', 'What is PID control?', 'PID (Proportional-Integral-Derivative) control is a feedback control algorithm that calculates a correction based on the error (P), accumulated error over time (I), and rate of error change (D) to maintain a setpoint.'),
    eblet('engineering', 'What is stress and strain in materials?', 'Stress is force per unit area (σ = F/A). Strain is the fractional change in dimension (ε = ΔL/L). Young\'s modulus E = σ/ε describes the stiffness of a material within its elastic limit.'),
    eblet('engineering', 'What is Kirchhoff\'s circuit laws?', 'Kirchhoff\'s current law: the sum of currents entering a node equals the sum leaving (conservation of charge). Kirchhoff\'s voltage law: the sum of voltages around any closed loop equals zero (conservation of energy).'),
    eblet('engineering', 'What is signal sampling and Nyquist theorem?', 'The Nyquist theorem states that to accurately reconstruct a signal, the sampling rate must be at least twice the highest frequency component. Undersampling causes aliasing (false frequencies).'),
    eblet('engineering', 'What is failure mode and effects analysis (FMEA)?', 'FMEA is a systematic method to identify potential failure modes in a system, assess their likelihood and severity, and implement mitigation measures. It is widely used in reliability engineering.'),
    eblet('engineering', 'What is the difference between analog and digital signals?', 'Analog signals are continuous in both time and amplitude. Digital signals are discrete, using binary (0/1) representation. Digital systems offer noise resistance, easier processing, and reliable storage.'),
    eblet('engineering', 'What is Fourier analysis in engineering?', 'Fourier analysis decomposes complex signals into constituent sinusoids, enabling frequency-domain analysis. The FFT (Fast Fourier Transform) is an efficient algorithm widely used in signal processing.'),
    eblet('engineering', 'What is the concept of impedance in AC circuits?', 'Impedance Z is the complex resistance to alternating current, combining resistance R and reactance X: Z = R + jX. Capacitors and inductors contribute frequency-dependent reactance.'),
    eblet('engineering', 'What is a feedback loop in control systems?', 'A feedback loop measures system output and feeds it back to the input to correct errors. Negative feedback stabilizes systems; positive feedback amplifies changes. PID controllers implement feedback control.'),
    eblet('engineering', 'What is the principle of least action in mechanics?', 'The principle of least action states that physical systems evolve along paths that minimize (or extremize) the action integral. It provides a foundation for Lagrangian and Hamiltonian mechanics.'),
    eblet('engineering', 'What is finite element analysis (FEA)?', 'FEA is a numerical technique for solving differential equations by dividing complex structures into small elements. It is widely used to simulate mechanical stress, heat transfer, and fluid flow.'),
    eblet('engineering', 'What is semiconductor doping in electronics?', 'Doping adds impurities to semiconductors to control electrical properties. N-type doping (with phosphorus) adds electrons as majority carriers. P-type doping (with boron) creates electron holes.'),
    eblet('engineering', 'What is the concept of entropy in information theory?', 'Shannon entropy measures the average information content of a message source: H = −Σ p(x) log₂ p(x). It quantifies uncertainty and is fundamental to data compression and channel capacity.'),
    eblet('engineering', 'What is the Rankine cycle?', 'The Rankine cycle is the thermodynamic cycle used in steam power plants: water is heated to steam (boiler), expanded through a turbine (work output), condensed back to liquid, and pumped back to the boiler.'),
    eblet('engineering', 'What is the concept of bandwidth in communications?', 'Bandwidth is the range of frequencies a channel can transmit, or the maximum data rate a channel supports. Shannon\'s theorem: C = B log₂(1 + S/N) gives the theoretical maximum channel capacity.'),
  ],

  computer_science: [
    eblet('computer_science', 'What is Big-O notation?', 'Big-O notation describes the upper bound on the growth rate of an algorithm\'s time or space complexity as input size n grows. O(1) is constant, O(log n) is logarithmic, O(n) is linear, O(n²) is quadratic.'),
    eblet('computer_science', 'What is the difference between a stack and a queue?', 'A stack is LIFO (Last In First Out) — items are pushed and popped from the top. A queue is FIFO (First In First Out) — items are enqueued at the back and dequeued from the front.'),
    eblet('computer_science', 'What is a binary search tree?', 'A binary search tree (BST) is a tree data structure where each node\'s left subtree contains only smaller values and right subtree only larger values, enabling O(log n) search, insert, and delete in balanced cases.'),
    eblet('computer_science', 'What is dynamic programming?', 'Dynamic programming solves complex problems by breaking them into overlapping subproblems, solving each once, and storing results (memoization/tabulation). It converts exponential algorithms to polynomial ones.'),
    eblet('computer_science', 'What is TCP/IP?', 'TCP/IP is the fundamental internet protocol suite. TCP (Transmission Control Protocol) provides reliable ordered delivery. IP (Internet Protocol) handles addressing and routing packets across networks.'),
    eblet('computer_science', 'What is a hash table?', 'A hash table stores key-value pairs using a hash function to map keys to array indices. It offers O(1) average-case lookup, insert, and delete. Collisions are handled by chaining or open addressing.'),
    eblet('computer_science', 'What is the halting problem?', 'The halting problem asks whether an arbitrary program will finish running or loop forever on given input. Turing proved this is undecidable — no general algorithm can solve it for all possible programs.'),
    eblet('computer_science', 'What is object-oriented programming?', 'OOP organizes software around objects that combine data (attributes) and behavior (methods). Key principles: encapsulation (hiding internals), inheritance (reusing parent class features), polymorphism (multiple forms).'),
    eblet('computer_science', 'What is a neural network?', 'A neural network is a computational model inspired by biological neurons, consisting of layers of interconnected nodes. Deep learning uses many layers (deep networks) trained via backpropagation to recognize patterns.'),
    eblet('computer_science', 'What is a database transaction and ACID properties?', 'A database transaction is a unit of work that must be Atomic (all or nothing), Consistent (valid state before/after), Isolated (transactions don\'t interfere), and Durable (committed changes persist).'),
    eblet('computer_science', 'What is recursion?', 'Recursion is when a function calls itself with a simpler version of the problem until a base case is reached. Examples: factorial, Fibonacci, tree traversal. Every recursive function needs a base case to terminate.'),
    eblet('computer_science', 'What is the CAP theorem in distributed systems?', 'The CAP theorem states that a distributed system cannot simultaneously guarantee all three of: Consistency (all nodes see the same data), Availability (every request gets a response), and Partition tolerance.'),
    eblet('computer_science', 'What is asymptotic analysis?', 'Asymptotic analysis studies algorithm performance as input size grows to infinity. Big-O (upper bound), Omega (lower bound), and Theta (tight bound) characterize growth rates independent of hardware.'),
    eblet('computer_science', 'What is the difference between process and thread?', 'A process is an independent program execution with its own memory space. Threads share a process\'s memory and resources, making communication easier but requiring synchronization to prevent race conditions.'),
    eblet('computer_science', 'What is public-key cryptography?', 'Public-key (asymmetric) cryptography uses key pairs: a public key (shared openly) for encryption and a private key (kept secret) for decryption. RSA and elliptic-curve cryptography are common algorithms.'),
    eblet('computer_science', 'What is the difference between breadth-first and depth-first search?', 'BFS explores all neighbors at the current depth before moving deeper, using a queue. DFS explores as far as possible along each branch before backtracking, using a stack. BFS finds shortest paths in unweighted graphs.'),
    eblet('computer_science', 'What is machine learning?', 'Machine learning is a subset of AI where systems learn from data to make predictions or decisions without explicit programming. Supervised learning uses labeled examples; unsupervised learning finds patterns in unlabeled data.'),
    eblet('computer_science', 'What is an operating system?', 'An operating system manages hardware resources (CPU, memory, storage, I/O) and provides a platform for applications. Core functions: process scheduling, memory management, file system, and device drivers.'),
    eblet('computer_science', 'What is version control?', 'Version control tracks changes to files over time, enabling collaboration, rollback, and history. Git is the dominant system, using commits, branches, and merges to manage code evolution.'),
    eblet('computer_science', 'What is the P vs NP problem?', 'P is the class of problems solvable in polynomial time. NP is the class of problems whose solutions can be verified in polynomial time. The unsolved P=NP question asks whether every verifiable problem is also efficiently solvable.'),
  ],

  history: [
    eblet('history', 'What was the Magna Carta?', 'The Magna Carta, signed in 1215 by King John of England, established that the king was subject to the rule of law and granted certain rights to barons, laying groundwork for constitutional governance.'),
    eblet('history', 'What caused World War I?', 'WWI (1914-1918) was triggered by the assassination of Archduke Franz Ferdinand of Austria in 1914. Underlying causes included militarism, alliance systems, imperialism, and rising nationalism.'),
    eblet('history', 'What was the French Revolution?', 'The French Revolution (1789-1799) overthrew the French monarchy, established a republic, and ended with Napoleon\'s rise. Its ideals of liberty, equality, and fraternity influenced democratic movements worldwide.'),
    eblet('history', 'What was the Cold War?', 'The Cold War (1947-1991) was the geopolitical tension between the USA and Soviet Union after WWII. It featured an arms race, space race, proxy wars, and ideological competition between capitalism and communism.'),
    eblet('history', 'What was the Renaissance?', 'The Renaissance (14th-17th centuries) was a European cultural movement that revived classical Greek and Roman knowledge. It produced advances in art (Leonardo, Michelangelo), science (Galileo), and literature (Shakespeare).'),
    eblet('history', 'What were the causes and effects of the Industrial Revolution?', 'The Industrial Revolution (18th-19th century, starting in Britain) transformed economies from agricultural to industrial through mechanization. It created urbanization, new labor patterns, and eventually modern standards of living.'),
    eblet('history', 'What was the fall of the Roman Empire?', 'The Western Roman Empire fell in 476 CE due to multiple causes: military pressures from Germanic tribes, economic problems, political instability, and overextension. The Eastern (Byzantine) Empire continued until 1453.'),
    eblet('history', 'What was the Silk Road?', 'The Silk Road was a network of trade routes connecting East Asia to the Mediterranean from roughly 200 BCE to 1450 CE. It facilitated exchange of silk, spices, technologies, ideas, and diseases across civilizations.'),
    eblet('history', 'What was the Holocaust?', 'The Holocaust was the systematic genocide of approximately six million Jewish people and millions of others by Nazi Germany and its collaborators from 1941-1945, marking the worst genocide in modern history.'),
    eblet('history', 'What was the American Civil War?', 'The American Civil War (1861-1865) was fought between the Union (North) and Confederacy (South). Primary cause: the institution of slavery. The Union victory preserved the nation and led to the abolition of slavery.'),
    eblet('history', 'What was the Scientific Revolution?', 'The Scientific Revolution (16th-17th centuries) transformed understanding of nature through empirical observation and mathematical description. Key figures: Copernicus (heliocentrism), Galileo (experiment), Newton (laws of motion).'),
    eblet('history', 'What was colonialism and its legacy?', 'Colonialism was the practice of establishing political control over other territories, practiced extensively by European powers from the 15th-20th centuries. Its legacy includes economic inequality, cultural disruption, and borders that cause modern conflicts.'),
    eblet('history', 'What was the Enlightenment?', 'The Enlightenment (18th century) was an intellectual movement emphasizing reason, science, and individual rights over tradition and religious authority. It influenced the American and French Revolutions and modern democracy.'),
    eblet('history', 'What was the printing press and why was it significant?', 'The printing press invented by Gutenberg (~1440) enabled mass production of books, spreading literacy and knowledge across Europe. It facilitated the Reformation, Scientific Revolution, and ultimately democratization of information.'),
    eblet('history', 'What was the decolonization movement of the 20th century?', 'Decolonization was the process by which colonies in Asia, Africa, and the Americas gained independence from European powers after WWII. Between 1945-1975, dozens of new nations emerged from former colonial territories.'),
    eblet('history', 'What was the impact of the Black Death?', 'The Black Death pandemic (1347-1351) killed 30-60% of Europe\'s population. Its aftermath contributed to the decline of feudalism, rising wages for surviving workers, and social changes that shaped the Renaissance.'),
    eblet('history', 'What was the Russian Revolution?', 'The Russian Revolution (1917) comprised two events: the February Revolution (which ended Tsarist rule) and the October Revolution (in which the Bolsheviks under Lenin seized power), establishing the Soviet Union.'),
    eblet('history', 'What was the significance of the Moon landing in 1969?', 'The Apollo 11 mission on July 20, 1969 landed Neil Armstrong and Buzz Aldrin on the Moon, with Armstrong becoming the first human to walk on the Moon. It was the culmination of the Space Race between the USA and USSR.'),
    eblet('history', 'What were the Crusades?', 'The Crusades (1096-1291) were a series of religious wars sanctioned by the Catholic Church, primarily aimed at retaking the Holy Land from Muslim control. They shaped medieval Europe-Middle East relations and trade.'),
    eblet('history', 'What was apartheid in South Africa?', 'Apartheid (1948-1994) was a system of institutionalized racial segregation in South Africa. Nelson Mandela led the ANC resistance; international sanctions and internal pressure ended the system, and Mandela became president in 1994.'),
  ],

  law: [
    eblet('law', 'What is the difference between civil law and criminal law?', 'Criminal law involves offenses against the state and society; the government prosecutes and punishment includes imprisonment. Civil law involves disputes between individuals; remedies are typically monetary damages or injunctions.'),
    eblet('law', 'What is the concept of due process?', 'Due process requires the government to respect all legal rights owed to a person under the law. Procedural due process ensures fair procedures; substantive due process protects certain fundamental rights from government interference.'),
    eblet('law', 'What is tort law?', 'Tort law covers civil wrongs (other than breach of contract) that cause harm. Key torts include negligence (duty of care + breach + causation + damages), intentional torts (assault, battery), and strict liability.'),
    eblet('law', 'What is contract law?', 'A valid contract requires offer, acceptance, consideration (something of value exchanged), and legal capacity. Breach of contract allows the non-breaching party to seek damages or specific performance.'),
    eblet('law', 'What is the rule of law?', 'The rule of law is the principle that all individuals, institutions, and the government itself are accountable to laws that are publicly promulgated, equally enforced, and independently adjudicated.'),
    eblet('law', 'What is habeas corpus?', 'Habeas corpus is a legal writ requiring authorities to bring a detained person before a court to determine whether their detention is lawful. It is a fundamental protection against unlawful imprisonment.'),
    eblet('law', 'What is the doctrine of precedent (stare decisis)?', 'Stare decisis is the legal principle that courts should follow prior decisions (precedents) in similar cases. This promotes consistency, predictability, and stability in the legal system.'),
    eblet('law', 'What is intellectual property law?', 'Intellectual property law protects creations of the mind. Patents protect inventions (20 years). Copyrights protect creative works (life + 70 years). Trademarks protect brand identifiers.'),
    eblet('law', 'What is the Fourth Amendment protection against unreasonable searches?', 'The Fourth Amendment prohibits unreasonable searches and seizures and requires warrants based on probable cause. Evidence obtained through illegal searches may be excluded (exclusionary rule).'),
    eblet('law', 'What is corporate law?', 'Corporate law governs the formation, operation, and dissolution of corporations. Key concepts include limited liability (shareholders only risk investment), fiduciary duties of directors, and corporate governance structures.'),
    eblet('law', 'What is international humanitarian law?', 'International humanitarian law (the laws of war) regulates armed conflict, protecting civilians and combatants. Key instruments include the Geneva Conventions. It establishes war crimes and crimes against humanity.'),
    eblet('law', 'What is the principle of freedom of speech in US constitutional law?', 'The First Amendment protects freedom of speech from government restriction. However, it is not absolute — exceptions include incitement to imminent lawless action, true threats, and obscenity.'),
    eblet('law', 'What is administrative law?', 'Administrative law governs the activities of governmental agencies, including rulemaking, adjudication, and enforcement. Judicial review can overturn agency actions that are arbitrary, capricious, or unconstitutional.'),
    eblet('law', 'What is the concept of mens rea in criminal law?', 'Mens rea is the mental element of a crime — the guilty mind. Most crimes require both a guilty act (actus reus) and guilty mind. Levels include intent, knowledge, recklessness, and negligence.'),
    eblet('law', 'What is environmental law?', 'Environmental law regulates human interaction with the environment. In the US, laws include the Clean Air Act, Clean Water Act, and NEPA. International agreements include the Paris Climate Agreement.'),
    eblet('law', 'What is the concept of standing to sue?', 'Standing requires a plaintiff to have a concrete, particularized injury fairly traceable to the defendant that would be redressed by a favorable ruling. Without standing, courts lack jurisdiction.'),
    eblet('law', 'What is comparative fault in tort law?', 'Comparative fault allocates damages based on each party\'s percentage of fault. Under pure comparative fault, a plaintiff can recover even if 99% at fault. Modified comparative fault bars recovery above 50% fault.'),
    eblet('law', 'What is the Uniform Commercial Code (UCC)?', 'The UCC is a set of standardized laws governing commercial transactions in the United States, including sales of goods, negotiable instruments, and secured transactions. Most states have adopted it.'),
    eblet('law', 'What is a class action lawsuit?', 'A class action allows many people with similar claims to sue as a group (class). It is efficient for small individual claims (like consumer fraud) that would be impractical to litigate individually.'),
    eblet('law', 'What is the exclusionary rule?', 'The exclusionary rule prevents illegally obtained evidence from being used in criminal trials. It deters police misconduct by removing the incentive to conduct illegal searches. Exceptions include good faith reliance.'),
  ],

  economics: [
    eblet('economics', 'What is supply and demand?', 'Supply and demand is the economic model where price adjusts to balance the quantity producers supply with the quantity consumers demand. Higher prices reduce demand and increase supply until equilibrium is reached.'),
    eblet('economics', 'What is GDP?', 'Gross Domestic Product (GDP) measures the total monetary value of all goods and services produced within a country in a given period. It is the primary indicator of economic size and growth.'),
    eblet('economics', 'What is inflation?', 'Inflation is the general increase in prices over time, decreasing purchasing power. It is measured by the Consumer Price Index (CPI). Central banks target low, stable inflation (typically ~2%) to support economic stability.'),
    eblet('economics', 'What is comparative advantage in international trade?', 'Comparative advantage states that countries should specialize in producing goods where they have the lowest opportunity cost and trade for others. This maximizes total production even if one country is absolutely more efficient at everything.'),
    eblet('economics', 'What is monetary policy?', 'Monetary policy is a central bank\'s management of money supply and interest rates to achieve macroeconomic goals. Expansionary policy (lower rates, more money) stimulates growth; contractionary policy reduces inflation.'),
    eblet('economics', 'What is the concept of opportunity cost?', 'Opportunity cost is the value of the next best alternative forgone when making a choice. Every economic decision involves a trade-off; rational decision-making requires weighing benefits against opportunity costs.'),
    eblet('economics', 'What is a market failure?', 'Market failures occur when markets fail to allocate resources efficiently. Types include externalities (pollution), public goods (underprovided because non-excludable), information asymmetry, and monopoly power.'),
    eblet('economics', 'What is fiscal policy?', 'Fiscal policy refers to government use of taxation and spending to influence the economy. Expansionary fiscal policy increases spending or cuts taxes to stimulate growth. Contractionary policy reduces deficit spending.'),
    eblet('economics', 'What is the Gini coefficient?', 'The Gini coefficient measures income inequality within a population, ranging from 0 (perfect equality) to 1 (one person has all income). It is widely used to compare inequality across countries and time.'),
    eblet('economics', 'What is game theory?', 'Game theory analyzes strategic decision-making when outcomes depend on choices of multiple actors. The Nash equilibrium is a stable state where no player benefits from unilaterally changing their strategy.'),
    eblet('economics', 'What is the Phillips curve?', 'The Phillips curve described an empirical inverse relationship between unemployment and inflation: lower unemployment was associated with higher inflation. The relationship became unstable in the 1970s stagflation era.'),
    eblet('economics', 'What is the concept of price elasticity?', 'Price elasticity of demand measures how sensitive quantity demanded is to price changes. Elastic goods (|e| > 1) see proportionally larger quantity changes; inelastic goods (|e| < 1) show smaller quantity changes.'),
    eblet('economics', 'What is behavioral economics?', 'Behavioral economics incorporates psychological insights into economic models, showing that people often deviate from rational choice due to biases (loss aversion, anchoring, present bias) and heuristics.'),
    eblet('economics', 'What are the key properties of public goods?', 'Public goods are non-excludable (cannot prevent non-payers from using) and non-rival (one person\'s use doesn\'t reduce availability to others). Examples: national defense, lighthouses, basic research.'),
    eblet('economics', 'What is the concept of moral hazard in economics?', 'Moral hazard occurs when one party takes more risks because they don\'t bear full consequences, often because another party absorbs them. Examples: insurance encouraging riskier behavior, banks taking excessive risk with government backing.'),
    eblet('economics', 'What is the efficient market hypothesis?', 'The efficient market hypothesis (EMH) states that asset prices reflect all available information, making it impossible to consistently beat the market through analysis. Weak, semi-strong, and strong forms differ in information included.'),
    eblet('economics', 'What is the Keynesian theory of aggregate demand?', 'Keynesian economics holds that aggregate demand (consumption + investment + government spending + net exports) drives economic output. In recessions, government spending can stimulate demand and restore full employment.'),
    eblet('economics', 'What is externalities and the Coase theorem?', 'Externalities are costs or benefits affecting third parties not involved in a transaction. The Coase theorem states that if property rights are well-defined and transaction costs are low, private parties can solve externality problems.'),
    eblet('economics', 'What is the concept of diminishing marginal returns?', 'Diminishing marginal returns states that adding more of one input while holding others fixed eventually yields progressively smaller increases in output. A classic example: additional workers in a factory of fixed size.'),
    eblet('economics', 'What is the role of interest rates in the economy?', 'Interest rates, set by central banks, are the price of borrowing money. Lower rates stimulate borrowing and investment (expansionary); higher rates reduce inflation by cooling spending and investment (contractionary).'),
  ],

  psychology: [
    eblet('psychology', 'What is classical conditioning?', 'Classical conditioning (Pavlov) is learning by association: a neutral stimulus paired with an unconditioned stimulus comes to elicit the same response. Pavlov\'s dogs learned to salivate at a bell associated with food.'),
    eblet('psychology', 'What is operant conditioning?', 'Operant conditioning (Skinner) uses consequences to modify behavior: reinforcement (positive or negative) increases behavior; punishment (positive or negative) decreases behavior. Schedules of reinforcement affect learning rates.'),
    eblet('psychology', 'What are the major personality models in psychology?', 'The Big Five (OCEAN) model describes personality along five dimensions: Openness, Conscientiousness, Extraversion, Agreeableness, and Neuroticism. It is the most empirically supported framework in personality psychology.'),
    eblet('psychology', 'What is cognitive dissonance?', 'Cognitive dissonance is the mental discomfort experienced when holding contradictory beliefs or when behavior conflicts with beliefs. People reduce dissonance by changing beliefs, changing behavior, or rationalizing the conflict.'),
    eblet('psychology', 'What is the concept of confirmation bias?', 'Confirmation bias is the tendency to search for, interpret, and recall information in ways that confirm one\'s preexisting beliefs. It is one of the most widely documented cognitive biases.'),
    eblet('psychology', 'What are Maslow\'s hierarchy of needs?', 'Maslow\'s hierarchy arranges human needs in order: physiological (food, shelter) → safety → love/belonging → esteem → self-actualization. Lower needs must be met before higher ones become motivating.'),
    eblet('psychology', 'What is the Stanford Prison Experiment and its implications?', 'Zimbardo\'s 1971 Stanford Prison Experiment assigned participants to guard/prisoner roles and was stopped early due to abuse. It highlighted how situational factors can profoundly influence behavior, though its methodology has been questioned.'),
    eblet('psychology', 'What is the concept of attachment theory?', 'Bowlby\'s attachment theory holds that children have an innate need to form close emotional bonds with caregivers. Ainsworth identified secure, anxious, and avoidant attachment styles that influence later relationships.'),
    eblet('psychology', 'What is social learning theory?', 'Bandura\'s social learning theory states that people learn by observing others (modeling). His Bobo doll experiment showed children imitated aggressive behavior. Behavior is influenced by observation, imitation, and reinforcement.'),
    eblet('psychology', 'What is the bystander effect?', 'The bystander effect states that individuals are less likely to help in an emergency when others are present. Diffusion of responsibility and pluralistic ignorance explain why larger groups respond less to victims.'),
    eblet('psychology', 'What is working memory?', 'Working memory is the cognitive system that temporarily holds and manipulates information. Baddeley\'s model includes the phonological loop (verbal), visuospatial sketchpad (visual), and central executive (attention control).'),
    eblet('psychology', 'What is the difference between explicit and implicit memory?', 'Explicit (declarative) memory involves conscious recall of facts (semantic) and events (episodic). Implicit memory operates without conscious awareness, including procedural skills, priming, and conditioning.'),
    eblet('psychology', 'What is neuroplasticity?', 'Neuroplasticity is the brain\'s ability to change its structure and function through experience. Synaptic connections strengthen with use (long-term potentiation) and weaken without it (synaptic pruning).'),
    eblet('psychology', 'What is the fundamental attribution error?', 'The fundamental attribution error is the tendency to over-attribute others\' behavior to their character (dispositional factors) while underestimating situational influences, while doing the opposite for ourselves.'),
    eblet('psychology', 'What is the concept of schemas in cognitive psychology?', 'Schemas are mental frameworks that organize and interpret information based on prior knowledge. They speed up processing but can lead to errors by filling in missing information with expected (not actual) content.'),
    eblet('psychology', 'What is the DSM and how does it classify mental disorders?', 'The DSM (Diagnostic and Statistical Manual) is the standard American psychiatric classification system. It categorizes mental disorders by symptom criteria, enabling consistent diagnosis and research.'),
    eblet('psychology', 'What is the Stroop effect?', 'The Stroop effect demonstrates cognitive interference: naming the ink color of color words is slower when the word and ink color conflict (e.g., "RED" written in blue ink). It reveals automaticity of reading.'),
    eblet('psychology', 'What is the concept of resilience in psychology?', 'Psychological resilience is the capacity to recover from adversity, trauma, or stress. It involves positive adaptation despite challenges and is influenced by individual factors, social support, and coping strategies.'),
    eblet('psychology', 'What is the halo effect?', 'The halo effect is the cognitive bias where a positive impression of one trait (e.g., physical attractiveness) influences perception of other unrelated traits (e.g., intelligence, competence).'),
    eblet('psychology', 'What is the Milgram experiment?', 'Milgram\'s obedience experiments showed that most participants would administer apparently dangerous electric shocks to strangers when ordered to do so by an authority figure, demonstrating the power of authority on behavior.'),
  ],

  health: [
    eblet('health', 'What are the main risk factors for cardiovascular disease?', 'Major cardiovascular risk factors include hypertension, high LDL cholesterol, smoking, diabetes, obesity, physical inactivity, family history, and age. Lifestyle modifications and medications significantly reduce risk.'),
    eblet('health', 'What is the germ theory of disease?', 'Germ theory (19th century, Pasteur, Koch) established that specific microorganisms cause specific diseases. It replaced miasma theory and revolutionized medicine, leading to vaccines, antibiotics, and sterile surgical technique.'),
    eblet('health', 'What is the difference between viruses and bacteria?', 'Bacteria are single-celled organisms that can reproduce independently. Viruses are non-living particles that require host cells to replicate. Antibiotics treat bacterial infections but are ineffective against viruses.'),
    eblet('health', 'What is evidence-based medicine?', 'Evidence-based medicine (EBM) integrates best available research evidence with clinical expertise and patient values to guide healthcare decisions. The hierarchy of evidence ranks randomized controlled trials and meta-analyses highest.'),
    eblet('health', 'What is herd immunity?', 'Herd immunity occurs when a sufficient proportion of a population has immunity (through vaccination or prior infection) to prevent disease spread, protecting those who cannot be vaccinated. The threshold varies by disease transmissibility.'),
    eblet('health', 'What is the human body\'s immune response to infection?', 'The innate immune response is rapid and non-specific (inflammation, fever, natural killer cells). The adaptive immune response is specific: B cells produce antibodies; T cells directly kill infected cells and coordinate responses.'),
    eblet('health', 'What is the significance of blood pressure readings?', 'Blood pressure is recorded as systolic (heart contracting) / diastolic (heart relaxing) in mmHg. Normal is below 120/80. Hypertension (≥130/80) significantly increases risk of stroke, heart attack, and kidney disease.'),
    eblet('health', 'What are the principles of clinical trials?', 'Clinical trials evaluate medical interventions in humans. Phases I (safety), II (efficacy), III (comparison vs. standard treatment), and IV (post-market surveillance) ensure evidence before approval. Randomization and blinding minimize bias.'),
    eblet('health', 'What is the difference between incidence and prevalence in epidemiology?', 'Incidence is the rate of new cases of a disease in a population during a defined period. Prevalence is the proportion of a population with a disease at a given time. Prevalence = incidence × average disease duration.'),
    eblet('health', 'What is antibiotic resistance?', 'Antibiotic resistance occurs when bacteria evolve mechanisms to survive antibiotic treatment. Overuse and misuse of antibiotics accelerate resistance. It is a major global health threat, causing millions of deaths annually.'),
    eblet('health', 'What is the role of public health?', 'Public health focuses on protecting and improving community health through surveillance, prevention, and policy. Key functions: disease surveillance, vaccination programs, sanitation, health education, and emergency response.'),
    eblet('health', 'What is the body mass index (BMI) and its limitations?', 'BMI = weight(kg) / height(m)². Normal is 18.5-24.9; overweight 25-29.9; obese ≥30. Limitations: doesn\'t distinguish fat from muscle, doesn\'t account for fat distribution, not accurate for all ethnic groups.'),
    eblet('health', 'What are the stages of grief according to Kübler-Ross?', 'Kübler-Ross described five stages of grief: denial, anger, bargaining, depression, and acceptance. These are not linear and people experience them differently. The model has evolved to recognize grief as more complex and individual.'),
    eblet('health', 'What is the significance of the microbiome?', 'The human microbiome consists of trillions of microorganisms in and on the body, especially the gut. The gut microbiome influences digestion, immune function, mental health, and disease susceptibility.'),
    eblet('health', 'What is metabolic syndrome?', 'Metabolic syndrome is a cluster of conditions (central obesity, high blood pressure, high blood sugar, abnormal cholesterol) occurring together. It significantly increases risk of type 2 diabetes and cardiovascular disease.'),
    eblet('health', 'What is the difference between type 1 and type 2 diabetes?', 'Type 1 diabetes is an autoimmune disease destroying insulin-producing cells, requiring lifelong insulin. Type 2 diabetes is characterized by insulin resistance and relative insulin deficiency, often linked to lifestyle factors.'),
    eblet('health', 'What is a randomized controlled trial (RCT)?', 'An RCT randomly assigns participants to intervention or control groups to measure treatment effects. Randomization prevents selection bias; blinding prevents performance and detection bias. RCTs are the gold standard for causal inference.'),
    eblet('health', 'What is mental health and the biopsychosocial model?', 'Mental health encompasses emotional, psychological, and social well-being. The biopsychosocial model explains mental illness as resulting from biological (genetics, neurobiology), psychological (trauma, thoughts), and social (support, environment) factors.'),
    eblet('health', 'What are vaccines and how do they work?', 'Vaccines stimulate the immune system to recognize and fight specific pathogens without causing disease. They present antigens (killed/attenuated pathogens, subunits, or mRNA) to train B and T cells to mount a rapid response.'),
    eblet('health', 'What is the opioid epidemic?', 'The opioid epidemic in North America began with overprescription of opioid pain medications in the 1990s, leading to widespread addiction, transition to heroin and fentanyl, and over 500,000 overdose deaths in the US 1999-2019.'),
  ],

  philosophy: [
    eblet('philosophy', 'What is the mind-body problem in philosophy?', 'The mind-body problem asks how mental states (consciousness, thoughts) relate to physical brain states. Dualism (Descartes) holds they are separate; physicalism holds mental states are physical brain states; functionalism focuses on functional roles.'),
    eblet('philosophy', 'What is utilitarianism?', 'Utilitarianism (Bentham, Mill) holds that the morally right action is the one that produces the greatest total happiness for the greatest number. It is consequentialist: outcomes determine moral worth.'),
    eblet('philosophy', 'What is Kant\'s categorical imperative?', 'Kant\'s categorical imperative is a universal moral law: "Act only according to that maxim by which you can at the same time will that it should become a universal law." Moral duties are absolute, not dependent on consequences.'),
    eblet('philosophy', 'What is epistemology?', 'Epistemology is the branch of philosophy studying knowledge: what it is, how we acquire it, and its limits. Key debates: rationalism (knowledge from reason) vs. empiricism (knowledge from experience); foundationalism vs. coherentism.'),
    eblet('philosophy', 'What is Plato\'s theory of Forms?', 'Plato held that the physical world is a shadow of a higher realm of eternal, perfect Forms. The Form of the Good is the highest; physical objects are imperfect instances. Knowledge is recollection of these Forms.'),
    eblet('philosophy', 'What is existentialism?', 'Existentialism (Sartre, Camus, Kierkegaard, Heidegger) holds that existence precedes essence: people are not born with predetermined purpose but must create their own meaning through choices and actions in an indifferent universe.'),
    eblet('philosophy', 'What is the trolley problem?', 'The trolley problem is an ethical thought experiment: should you divert a runaway trolley to kill one person rather than five? It tests consequentialist vs. deontological intuitions and whether action/inaction matters morally.'),
    eblet('philosophy', 'What is empiricism vs. rationalism in epistemology?', 'Empiricists (Locke, Hume, Berkeley) hold that knowledge comes primarily from sensory experience. Rationalists (Descartes, Leibniz, Spinoza) hold that reason is the primary source of knowledge, independent of experience.'),
    eblet('philosophy', 'What is the problem of free will?', 'The free will problem asks whether human choices are determined by prior causes (determinism) or undetermined (libertarian free will). Compatibilism holds that free will and determinism are compatible.'),
    eblet('philosophy', 'What is Aristotle\'s virtue ethics?', 'Aristotle\'s virtue ethics holds that moral goodness consists in developing excellent character traits (virtues like courage, justice, temperance) through habit. Virtues lie between extremes (the golden mean); eudaimonia (flourishing) is the goal.'),
    eblet('philosophy', 'What is the social contract theory?', 'Social contract theory (Hobbes, Locke, Rousseau) explains political authority as arising from a voluntary agreement. People give up some freedoms to a governing authority in exchange for security, rights, and order.'),
    eblet('philosophy', 'What is the philosophical problem of induction?', 'Hume\'s problem of induction: past observations cannot logically guarantee future regularities. We cannot prove the sun will rise tomorrow just because it always has. This challenges the foundations of empirical science.'),
    eblet('philosophy', 'What is Hegel\'s dialectic?', 'Hegel\'s dialectic describes historical and conceptual development through contradiction: a thesis is opposed by an antithesis, and the tension resolves in a synthesis that preserves elements of both while transcending them.'),
    eblet('philosophy', 'What is moral relativism vs. moral realism?', 'Moral relativism holds that moral judgments are true only relative to cultural or individual frameworks. Moral realism holds that there are objective moral facts true independent of any person\'s beliefs.'),
    eblet('philosophy', 'What is phenomenology?', 'Phenomenology (Husserl, Heidegger, Merleau-Ponty) is the philosophical study of conscious experience from the first-person perspective. It examines how things appear to consciousness, prior to theoretical frameworks.'),
    eblet('philosophy', 'What is the concept of justice in political philosophy?', 'Rawls\' theory of justice states that principles should be chosen behind a "veil of ignorance." His difference principle allows inequalities only if they benefit the least advantaged members of society.'),
    eblet('philosophy', 'What is analytic philosophy?', 'Analytic philosophy (Russell, Wittgenstein, Frege) emphasizes logical analysis of language and arguments. It contrasts with Continental philosophy in its focus on precision, argument structure, and philosophy of language.'),
    eblet('philosophy', 'What is the paradox of the heap (sorites)?', 'The sorites paradox: if you remove one grain from a heap of sand, it remains a heap. But removing grains one by one eventually leaves no heap. It raises questions about vagueness and sharp boundaries in concepts.'),
    eblet('philosophy', 'What is Descartes\' method of doubt?', 'Descartes used radical skepticism to find indubitable truths. He doubted everything until reaching "cogito ergo sum" (I think therefore I am) — the only thing he could not doubt was that he was doing the doubting.'),
    eblet('philosophy', 'What is the trolley problem vs. the doctrine of double effect?', 'The doctrine of double effect permits harmful actions if the harm is a foreseen but unintended side effect of achieving a good end. It differs from utilitarian calculation by considering intention, explaining different moral intuitions about similar outcomes.'),
  ],

  business: [
    eblet('business', 'What is a SWOT analysis?', 'SWOT analysis is a strategic planning framework that identifies Strengths and Weaknesses (internal factors) and Opportunities and Threats (external factors) to guide decision-making.'),
    eblet('business', 'What is supply chain management?', 'Supply chain management coordinates the flow of goods, information, and finances from raw material suppliers through manufacturers and distributors to end consumers, optimizing for efficiency, cost, and resilience.'),
    eblet('business', 'What is discounted cash flow (DCF) valuation?', 'DCF values a business by discounting future cash flows to present value using a discount rate (typically WACC). The formula: NPV = Σ CF_t / (1+r)^t. A higher discount rate decreases present value.'),
    eblet('business', 'What is Porter\'s Five Forces?', 'Porter\'s Five Forces analyzes industry competitiveness: threat of new entrants, threat of substitutes, bargaining power of suppliers, bargaining power of buyers, and rivalry among existing competitors.'),
    eblet('business', 'What is the difference between B2B and B2C business models?', 'B2B (business-to-business) involves transactions between companies, often with longer sales cycles and larger deal values. B2C (business-to-consumer) involves selling directly to individuals, typically with shorter cycles and lower prices.'),
    eblet('business', 'What is accounting\'s double-entry bookkeeping?', 'Double-entry bookkeeping records every transaction as both a debit and a credit, maintaining the accounting equation (Assets = Liabilities + Equity). It ensures the books balance and provides audit trails.'),
    eblet('business', 'What is organizational culture?', 'Organizational culture is the shared values, beliefs, and norms that shape behavior within an organization. It influences employee motivation, decision-making, and organizational performance.'),
    eblet('business', 'What is a business model canvas?', 'The Business Model Canvas (Osterwalder) describes a business on nine blocks: customer segments, value propositions, channels, customer relationships, revenue streams, key resources, key activities, key partnerships, and cost structure.'),
    eblet('business', 'What is customer lifetime value (CLV)?', 'Customer Lifetime Value is the predicted total revenue a business will earn from a customer over their entire relationship. CLV = Average Purchase Value × Purchase Frequency × Customer Lifespan. Acquiring new customers costs 5-25x more than retaining existing ones.'),
    eblet('business', 'What is the concept of economies of scale?', 'Economies of scale occur when average production costs fall as output increases. Fixed costs spread over more units; specialization and bulk purchasing reduce variable costs. Diseconomies of scale reverse this at very large sizes.'),
    eblet('business', 'What is the difference between leadership and management?', 'Management focuses on planning, organizing, and controlling processes to achieve defined goals. Leadership focuses on inspiring, motivating, and guiding people toward a vision. Effective organizations need both.'),
    eblet('business', 'What is net present value (NPV) in capital budgeting?', 'NPV = present value of cash inflows − initial investment. Positive NPV indicates value creation; negative NPV destroys value. It is the primary criterion for evaluating investment projects in corporate finance.'),
    eblet('business', 'What is market segmentation?', 'Market segmentation divides a broad market into subsets of consumers with common needs or characteristics. Segments can be demographic, psychographic, geographic, or behavioral. Targeting allows more effective marketing.'),
    eblet('business', 'What is the concept of competitive advantage?', 'Competitive advantage is what allows a company to outperform competitors. Porter identified two types: cost leadership (producing at lower cost) and differentiation (unique attributes justifying premium prices).'),
    eblet('business', 'What is franchise business model?', 'A franchise grants a franchisee the right to operate under the franchisor\'s brand and systems in exchange for fees and royalties. It allows rapid expansion with lower capital risk than direct ownership.'),
    eblet('business', 'What is financial leverage?', 'Financial leverage uses debt to amplify returns on equity. While it can boost ROE when returns exceed debt costs, it amplifies losses when returns are poor. High leverage increases financial risk and bankruptcy probability.'),
    eblet('business', 'What is the role of corporate social responsibility (CSR)?', 'CSR refers to a company\'s voluntary commitments beyond legal requirements to benefit society: environmental sustainability, ethical labor practices, community investment, and transparent governance.'),
    eblet('business', 'What is brand equity?', 'Brand equity is the value premium that a company generates from a recognizable name compared to a generic equivalent. Strong brand equity enables premium pricing, customer loyalty, and lower marketing costs.'),
    eblet('business', 'What is the concept of price discrimination?', 'Price discrimination charges different customers different prices for the same product based on willingness to pay. First-degree: individual pricing. Second-degree: quantity-based. Third-degree: segment-based (student discounts).'),
    eblet('business', 'What is the Pareto principle (80/20 rule) in business?', 'The Pareto principle states that roughly 80% of effects come from 20% of causes. In business: 80% of revenue typically comes from 20% of customers; 80% of problems from 20% of defects.'),
  ],

  other: [
    eblet('other', 'What is the scientific method?', 'The scientific method is a systematic process for investigation: observe, form hypothesis, design experiment, collect data, analyze results, and draw conclusions. It requires reproducibility, peer review, and falsifiability.'),
    eblet('other', 'What is climate change and its main causes?', 'Climate change refers to long-term shifts in global temperatures and weather patterns. Since the Industrial Revolution, human activities (burning fossil fuels, deforestation) have increased atmospheric CO₂, trapping heat.'),
    eblet('other', 'What is the concept of falsifiability in science?', 'Popper\'s falsifiability criterion states that a scientific hypothesis must be testable and capable of being proven wrong. Unfalsifiable claims are not scientific. Failed falsification attempts strengthen a theory.'),
    eblet('other', 'What is artificial intelligence?', 'Artificial intelligence is the simulation of human intelligence processes by computer systems, including learning (acquiring information), reasoning (using rules to reach conclusions), and self-correction.'),
    eblet('other', 'What is blockchain technology?', 'Blockchain is a distributed ledger technology where records (blocks) are chained together cryptographically and stored across a network. It enables trustless, transparent, immutable record-keeping without central authority.'),
    eblet('other', 'What is the UN and its main purposes?', 'The United Nations (founded 1945) is an international organization with 193 member states. Its main purposes: maintain international peace and security, develop friendly relations among nations, and promote social progress.'),
    eblet('other', 'What is the concept of sustainability?', 'Sustainability means meeting present needs without compromising future generations\' ability to meet theirs (Brundtland definition). Environmental sustainability focuses on resource use, biodiversity, and climate stability.'),
    eblet('other', 'What is the difference between correlation and causation?', 'Correlation is a statistical relationship between two variables. Causation means one variable directly causes changes in another. Correlation does not imply causation; confounding variables can create spurious correlations.'),
    eblet('other', 'What is globalization?', 'Globalization is the increasing interconnection of economies, cultures, and people worldwide through trade, communication, and migration. It has expanded markets and reduced poverty but also increased inequality and cultural homogenization.'),
    eblet('other', 'What is the concept of a paradigm shift in science?', 'Kuhn\'s paradigm shift occurs when accumulated anomalies cause the scientific community to abandon one framework for another. Examples: Copernican revolution, Darwinian evolution, quantum mechanics.'),
    eblet('other', 'What is democracy and its key principles?', 'Democracy is a system of government where power derives from the people, exercised through free elections, rule of law, protection of individual rights, and peaceful transfer of power. Forms include direct and representative democracy.'),
    eblet('other', 'What is the greenhouse effect?', 'The greenhouse effect occurs when atmospheric gases (CO₂, methane, water vapor) absorb and re-emit infrared radiation from Earth\'s surface, warming the planet. Human activities have enhanced this natural effect.'),
    eblet('other', 'What is the concept of epistemological humility?', 'Epistemological humility acknowledges the limits of one\'s knowledge and the possibility of being wrong. It is essential to scientific progress, intellectual honesty, and productive dialogue.'),
    eblet('other', 'What is the United States Constitution?', 'The US Constitution (ratified 1788) is the supreme law of the United States, establishing the framework of federal government, separation of powers among three branches, and protecting individual rights through the Bill of Rights.'),
    eblet('other', 'What is the concept of a paradigm in social science?', 'In social science, a paradigm is a framework of basic assumptions and methods. Positivism seeks objective law-like regularities; interpretivism emphasizes understanding subjective meanings; critical theory aims to critique and change social structures.'),
    eblet('other', 'What is the Big Bang theory?', 'The Big Bang theory is the prevailing cosmological model stating the universe originated approximately 13.8 billion years ago from an extremely hot, dense state and has been expanding ever since.'),
    eblet('other', 'What is the concept of cognitive load in learning?', 'Cognitive load theory (Sweller) states that working memory has limited capacity. Instructional design should minimize extraneous load (unnecessary complexity) and optimize germane load (schema formation) to facilitate learning.'),
    eblet('other', 'What is the concept of digital literacy?', 'Digital literacy is the ability to effectively and critically navigate, evaluate, and create information using digital technologies. It encompasses technical skills, critical thinking about online information, and understanding of digital rights.'),
    eblet('other', 'What is the concept of cultural relativism?', 'Cultural relativism holds that cultural practices should be understood within their own context and not judged by the standards of another culture. It promotes anthropological understanding but raises questions about universal human rights.'),
    eblet('other', 'What is the concept of a stateless nation?', 'A stateless nation is an ethnic or cultural group with a shared identity that does not have its own independent state. Examples include Kurds (across Turkey, Iraq, Iran, Syria) and Tibetans.'),
  ],

};

// ── Write output ────────────────────────────────────────────────────────────

if (!existsSync(OUTPUT_DIR)) {
  mkdirSync(OUTPUT_DIR, { recursive: true });
}

const allEblets = Object.values(DOMAIN_EBLETS).flat();
const lines = allEblets.map(e => JSON.stringify(e));
writeFileSync(OUTPUT_FILE, lines.join('\n') + '\n', 'utf8');

console.log(`[StarterChocolate] Generated ${allEblets.length} eblets across ${Object.keys(DOMAIN_EBLETS).length} domains`);
console.log(`[StarterChocolate] Written to: ${OUTPUT_FILE}`);

const domainCounts = Object.entries(DOMAIN_EBLETS)
  .map(([d, es]) => `  ${d}: ${es.length}`)
  .join('\n');
console.log('Domain breakdown:\n' + domainCounts);
