-- K506 Phase D: Extend test_frame_results with per-query substrate-savings telemetry.
-- Adds savings columns to existing table; no existing rows are touched.
-- All new columns are nullable so old inserts without savings data still work.

ALTER TABLE "public"."test_frame_results"
  ADD COLUMN IF NOT EXISTS "query_input_tokens"           integer,
  ADD COLUMN IF NOT EXISTS "query_output_tokens"          integer,
  ADD COLUMN IF NOT EXISTS "substrate_injection_tokens"   integer,
  ADD COLUMN IF NOT EXISTS "cold_baseline_estimated_tokens" integer,
  ADD COLUMN IF NOT EXISTS "member_friction_confirmations" integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "savings_estimated"            boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS "savings_logged_at"            timestamptz;

COMMENT ON COLUMN "public"."test_frame_results"."query_input_tokens" IS
  'K506: input tokens consumed by member AI session for this query';
COMMENT ON COLUMN "public"."test_frame_results"."query_output_tokens" IS
  'K506: output tokens generated by member AI for this query';
COMMENT ON COLUMN "public"."test_frame_results"."substrate_injection_tokens" IS
  'K506: tokens from Cathedral substrate injection into this query';
COMMENT ON COLUMN "public"."test_frame_results"."cold_baseline_estimated_tokens" IS
  'K506: counterfactual token estimate for cold-run (without substrate), using R13 multiplier';
COMMENT ON COLUMN "public"."test_frame_results"."member_friction_confirmations" IS
  'K506: count of yes/that/do-it confirmations observed (auto-detected from query timing or member-supplied)';
COMMENT ON COLUMN "public"."test_frame_results"."savings_estimated" IS
  'K506: true when token counts are estimated from query size/timing, false when measured by AI vendor API';
COMMENT ON COLUMN "public"."test_frame_results"."savings_logged_at" IS
  'K506: timestamp when savings were computed and logged';

-- ── Savings aggregate view (member-visible + community dashboard) ─────────────
CREATE OR REPLACE VIEW "public"."test_frame_savings_aggregate" AS
SELECT
  COUNT(*)                                              AS total_runs,
  COUNT(*) FILTER (WHERE query_input_tokens IS NOT NULL) AS runs_with_savings_data,
  ROUND(AVG(lift_pp), 1)                               AS mean_lift_pp,
  SUM(query_input_tokens)                              AS total_input_tokens,
  SUM(query_output_tokens)                             AS total_output_tokens,
  SUM(substrate_injection_tokens)                      AS total_substrate_tokens,
  ROUND(
    (SUM(query_input_tokens + query_output_tokens)::numeric
     / NULLIF(SUM(cold_baseline_estimated_tokens), 0)) * 100, 1
  )                                                    AS pct_of_cold_baseline,
  ROUND(AVG(member_friction_confirmations), 2)         AS avg_friction_confirmations,
  COUNT(*) FILTER (WHERE savings_estimated = false)    AS measured_runs,
  COUNT(*) FILTER (WHERE savings_estimated = true)     AS estimated_runs,
  MAX(savings_logged_at)                               AS last_savings_logged_at,
  MAX(created_at)                                      AS last_submission_at
FROM "public"."test_frame_results";

COMMENT ON VIEW "public"."test_frame_savings_aggregate" IS
  'K506 aggregate savings stats for the community-empirical dashboard at librarian.the2ndsecond.com/community-empirical';

-- ── Right-to-deletion: existing policy covers these new columns via DELETE ────
-- (member_delete_own policy already deletes the whole row including new columns)
