-- Innovation Log — Session 7D (March 8, 2026)
-- Areopagus Doctrine Engine + Feature Tips + Legal Compliance

INSERT INTO innovation_log (innovation_number, title, description, category, session_tag) VALUES
(1516, 'Feature Tip Discovery System', 'Google Admin-style first-time popover tips with localStorage persistence, GOT IT / DON''T SHOW TIPS controls, and centralized tip ID registry. Non-blocking, contextual, dismissible, educational.', 'UX/Discovery', 'Session 7D'),
(1517, 'Areopagus Doctrine Engine', 'Doctrine-based knowledge system organized by BELIEF at divergence points, not denomination. Three Columns (Believed/Taught/Practiced), 12 doctrine domains, 7 scopes, evidence basis categorization with 12 types, scholar/non-scholar distinction, depth levels (overview to scholarly), and comprehensive data model with 10 new database tables.', 'Architecture/Religion', 'Session 7D'),
(1518, 'Doctrine Explorer UI', 'Interactive three-panel UI: doctrine tree browser, three-column position cards with linked dictionary terms, depth selector (Overview/Standard/Deep/Scholarly), breadcrumb navigation, search, and evidence basis visualization.', 'UX/Religion', 'Session 7D'),
(1519, 'Areopagus Dictionary Panel', 'Definitive dictionary slide-out panel showing all definitions per term across traditions. Shows WHY traditions disagree — different definitions of the same word. Includes lexicon entries (BDAG, Strong''s, Thayer''s), scripture occurrence comparison across translations, etymology, and counter-arguments for each definition.', 'UX/Education', 'Session 7D'),
(1520, 'Empty Column 3 → CTA Bridge', 'When a doctrinal position''s Practiced column is empty, it transforms into a Call To Action connecting to the 16 Initiatives. Charitable domain mapping: feed_hungry → Let''s Make Dinner / Let''s Get Groceries, shelter_homeless → VSL, heal_sick → MSA, educate → Schoolhouse, etc.', 'Architecture/Civic', 'Session 7D'),
(1521, 'TikTok Compliance: ToS + Privacy Policy', 'Public-facing Terms of Service and Privacy Policy pages with TikTok Login Kit scope documentation (user.info.profile), PKCE flow explanation, homepage footer links. Resolves TikTok Developer Portal rejection for scopes mismatch, missing ToS, and missing PP.', 'Legal/Compliance', 'Session 7D'),
(1522, 'Jurassic Park Principle / Switzerland Flow', 'Areopagus ethos architecture: charitable action flows OUT to 16 Initiatives, religious debate stays IN the arena. "Say what you Do, Do what you Say" contract principle applied to faith. Platform communicates ethos through structure, not lectures.', 'Architecture/Ethics', 'Session 7D')
ON CONFLICT (innovation_number) DO NOTHING;
