-- =============================================================================
-- INNOVATION LOG — Bishop Session 018B — 17 innovations #1767-#1783
-- Megadump: Charity Medallion, Earmarked Credits, Keepers, Mission ONE,
-- Running Jewels, Tool Swap, Shade-Tree, Reciprocal Maintenance,
-- Video Game Swap, Local Sheet, Barter Exchange, Mission Sequence,
-- Maintenance Scheduling, Service Exchange, Patent Attorney Bounty
-- =============================================================================
-- Source: BISHOP_DROPZONE/AA_SESSION_018B_MEGADUMP.md
--         BISHOP_DROPZONE/AA_SESSION_018B_MEGADUMP_AMENDMENT_1.md
-- Count after: 1,783

INSERT INTO public.innovation_log (innovation_number, title, description, category, patent_bag, status)
VALUES
  (1767, 'Charity Medallion QR Card (Digital→Physical Morph)', 'Starts as digital Cue Card, morphs to physical white card — the LB Card for charity recipients. QR code on face links to dynamic interface showing scheduled meal drop-off times/locations per locale and user. Integrated with Family Table scheduling, same cookbooks and recipes as LMD/LGG — no separate charity food stigma. Weatherproof (laminated/plastic). Each locale defines delivery routes for homeless drop-offs on existing LMD routes.', 'Payment / Social Impact', 'Bag 9', 'pending'),
  (1768, 'Earmarked Credits — Granular Donor-Directed Giving', 'Members earmark Credits to specific causes, initiatives, geographic areas, guilds, families, or individuals — as granular as the giver chooses. NO food restrictions (potato chips are fine). Matching uses behavioral/participatory signals only (guild, area, project history) — zero demographics. Unlock tiers: business development earmarking available after two successful projects. Unfulfilled earmarks held in escrow until matching Node activates (demand signal for cold start).', 'Payment / Philanthropy', 'Bag 9', 'pending'),
  (1769, 'Keeper Key Hierarchy (Prepper/Non-Prepper Access Tiers)', 'Non-Prepper Keepers provide space, power, monitoring — NO keys to freezers. Prepper Keepers (LMD providers) get keys to their prep freezers/rooms because they need access to cook. Brand new freezers ONLY — always an LB freezer — for food safety baseline, warranty, standardization, energy efficiency, and branding.', 'Operations / Security', 'Bag 9', 'pending'),
  (1770, 'Mission ONE: EVERYONE Eats Tonight Banner System', 'Large event banner covering top of platform on special occasions. Text: "Mission ONE: EVERYONE Eats Tonight" with subtitle "For it rains on the Just and the Unjust" (Matthew 5:45). Entire banner image is a clickable link to LMD + Cold Start onboarding. Les Mis Bishop Myriel archetype — LB as the Bishop for the next Valjean. Default state for new visitors.', 'UX / Identity', 'Bag 9', 'pending'),
  (1771, 'Crew Call Bounty Board on LMD Page', 'Multiplier Slots displayed on LMD page as Crew Call bounties: Driver, Keeper, Prep Helper. Sequence: first food then make money. Every person who comes for food also sees earning opportunities. Conversion from consumer to provider is one scroll. Same Crew Call pattern as Modular Manufacturing.', 'UX / Recruitment', 'Bag 9', 'pending'),
  (1772, 'Running Jewels — Cooperative Vehicle Acquisition + Repair', 'Existing Founder business. Buy used cars at auction (volume pricing), fix with local mechanics (Shade-Tree or shop), sell at Cost+20% with VSL financing. Prioritize minivans and SUVs. Rally Group operation. Mission THREE infrastructure — most people need A-to-B transportation, does not have to be fancy, just has to be.', 'Transportation / Social Impact', 'Bag 9', 'pending'),
  (1773, 'Neighborhood Garage / Tool Swap (Tool Library Node)', 'Garage hosts tools rented through LB at Cost+20%. Another way to be Node Captain — Tool Library Node. Modeled after MIL clothing redistribution operation: flexible rules, trust-based enforcement, zero bureaucracy. Reputation system via XP — damage a tool, reputation reflects it. Tool condition photos at checkout/return.', 'Sharing Economy / Nodes', 'Bag 9', 'pending'),
  (1774, 'Shade-Tree Mechanic — Marks-Backed Reputation Service', 'Service providers must back jobs with Marks (which takes Joules) through LB. STAMP verification from customer closes quality loop. Universal template for ALL service roles: plumbers, electricians, lawn care, computer repair, tutors. Back your claim with Marks, deliver, get STAMPed, earn XP.', 'Service / Reputation', 'Bag 9', 'pending'),
  (1775, 'Reciprocal Maintenance Subscription Model', 'Monthly subscription for GUARANTEED service coverage IF customer follows provider recommendations. Inverts incentive structure: provider profits from health not sickness. Volume pricing: more subscribers = lower per-subscriber cost. Conditional element prevents abuse. Based on Founder IT-for-car-maintenance arrangement. Applies to any service type.', 'Service / Economic Model', 'Bag 9', 'pending'),
  (1776, 'Video Game Swap — Scheduled Rotation Library', 'Weekly pickup/dropoff schedule through LB. Call dibs on available games, keep 1 week (5 Credits), 50-credit refundable deposit, 2-week overage grace before deposit invoked, then owed Marks payback rate applies. Extends to books, DVDs, board games. Rides existing delivery routes.', 'Sharing Economy / Entertainment', 'Bag 9', 'pending'),
  (1777, 'The Local Sheet — Living Availability Document', 'Living document at Public Square listing everything available in user-defined geographic area: active Nodes, available meals, tool inventories, open bounties, vehicles, game titles. Custom geo via map drawing (not limited to zip/city boundaries). Subscribe for notifications. Demand signal intelligence for cold start. Digital neighborhood newspaper.', 'Information / Discovery', 'Bag 9', 'pending'),
  (1778, 'Reciprocal Service Exchange — Formalized Barter + LB Settlement', 'Two+ parties exchange services directly with LB as record-keeper and settlement layer. Uneven exchanges settled in Credits/Marks at Cost+20%. Both parties STAMP verify. Makes barter scalable — LB handles accounting humans are bad at. Multi-party exchanges supported.', 'Economic Model / Barter', 'Bag 9', 'pending'),
  (1779, 'Allies Page — Non-Partner Public Acknowledgment', 'Platform page acknowledging businesses that help people in crisis without formal partnership: Walmart (overnight parking), Jims (24-hour wifi + coffee). Not sponsors, not partners — just businesses that helped when they did not have to.', 'Content / Community', 'Bag 9', 'pending'),
  (1780, 'Mission Sequence Framework (ONE→TWO→THREE)', 'Sequential mission banners: Mission ONE = EVERYONE Eats Tonight (LMD/LGG/Cold Start). Mission TWO = A Place to Stay (shelter/Rally). Mission THREE = A Way to Get There (Running Jewels/transportation). Each unlocks when platform can deliver. Goal: eliminate homelessness through sequential concrete deliverables.', 'Strategy / Identity', 'Bag 9', 'pending'),
  (1781, 'Maintenance Visit Scheduling — Volume-Priced Service Rounds', 'Service providers make scheduled rounds: home visits weekly or monthly. More subscribers in area = lower price for ALL (milk route model). Provider routes optimized by geography. Same scheduling infrastructure as LMD delivery, Video Game Swap, and Tool Swap. 73% lower per-customer cost at 8 houses vs 1.', 'Service / Scheduling', 'Bag 9', 'pending'),
  (1782, 'MIL Clothing Redistribution Model — Trust-Based Sharing Template', 'Template from Founder MIL: receive donations, process (wash/categorize by age/gender/size), display in homemade shed/store. Rules enforced only when someone takes advantage (2 items/person, 5/family — flexible when genuine need). Simple, human, effective. Generalizable to Tool Swap, Game Swap, any sharing Node.', 'Sharing Economy / Template', 'Bag 9', 'pending'),
  (1783, 'Patent Attorney Bounty', 'Post bounties for patent attorneys through LB bounty system instead of cold-hiring at $400-600/hr. Scope: review 8 provisionals (1751 innovations), file continuations/non-provisionals, prior art search for Crown Jewels. Compensation at Cost+20% or deferred (Marks + Joules). Accepting creates formal professional engagement with standard attorney-client privilege.', 'Legal / Bounty', 'Bag 9', 'pending')
ON CONFLICT (innovation_number) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  patent_bag = EXCLUDED.patent_bag,
  status = EXCLUDED.status;
