"use strict";
// tdata-e.cjs -- Machine translations Group E (languages 109-134)
// to haw dv om ti rn sg lu kg gn tet tpi ilo tt zgh hil min bug cv br ve pam dz nr gd kab
module.exports = {
  "to": {
    speakFriend: {
      title: "Lea ki e kāinga, pea hū.",
      description: "Liana Banyan 'oku langa ke tatala ki he lea kotoa pē. Ko e lea tatala 'oku 'iai ha totongi 'e taha ki he fakatonulea.",
      languages: "ngaahi lea",
      openBounties: "ngaahi totongi tatala",
      marksAwarded: "Marks tuku atu (ngaahi token kau ki ai)",
      provisional: "Feave'aki:",
      provisionalNotice: "Ko e lisi lea mo e ngaahi 'aata Marks 'oku feave'aki. Ko e Marks ko e ngaahi token kau ki ai, 'ikai ko e saea.",
      bountyOpen: "Totongi tatala",
      claimed: "Kole'i",
      complete: "Kamata",
      translationBountyTitle: "Totongi Fakatonulea",
      bountyDescription: "Fakatonulea 'a Liana Banyan ki he {{language}}. Ma'u {{marks}} Marks.",
      scopeWelcome: "Ngaahi Folofola Malo e Lelei / Māmani Laumālie",
      scopeCueCards: "Seti Kaati Huufi",
      scopeNavigation: "Ngaahi fakatonu fononga mo e ngaahi pōpoaki hala",
      scopeWildfire: "Wildfire Beacon Run: Kumi ngāue",
      claimBounty: "Kole e Totongi Fakatonulea ni",
      baseLanguage: "Lea 'etangata -- 'ikai fiema'u ha totongi.",
      claimedBy: "@{{handle}} 'oku kole -- 'oku 'oku hoko.",
      marksProvisional: "{{marks}} Marks (feave'aki)",
      speakFounderTitle: "Leá 'a e Tu'i Ngāue: Ko e Ha 'a e Ngaahi Lea ni",
      speakFounderDesc: "'Oku 'iai ha'ane 'uhinga 'a e huafa 'o e lea kotoa pē 'i he ngāue ni. 'Uhinga 26 huafa mahu'inga.",
      howBountiesWork: "Ko e Ha 'a e Ngaahi Totongi Fakatonulea",
      step1Title: "Kole e Totongi",
      step1Body: "Tatali e Totongi Fakatonulea mei Help Wanted.",
      step2Title: "Fakatonulea mo Tuku Atu",
      step2Body: "Fakatonulea e ngaahi laine kotoa pē. Tuku atu 'ia Bounty Poster.",
      step3Title: "Ma'u Marks",
      step3Body: "Hili hono tali, ke ma'u Marks pea tānaki ki he IP Ledger.",
      hide: "fakafufū",
      why: "ko e ha?",
    },
    languageSwitcher: {
      changeLanguage: "Liliu lea",
      selectLanguage: "Fili lea",
      quickEnglish: "Pilitānia",
      tip: "Fa'ahi ngaahi lea kehekehe ki he Matapā 'o Durin ke hu ki he ngaahi a'usia makehe!",
    },
  },
  "haw": {
    speakFriend: {
      title: "ʻōlelo i ka hoaaloha, a komo.",
      description: "Ua kūkulu ʻia ʻo Liana Banyan e wehe ana no kēlā me kēia ʻōlelo. He uku hoʻolilo kekahi no kēlā me kēia ʻōlelo.",
      languages: "ʻōlelo",
      openBounties: "uku wehe",
      marksAwarded: "Ua hāʻawi ʻia nā Marks (nā hōʻailona kākoʻo)",
      provisional: "Panee:",
      provisionalNotice: "He panee ka papa inoa ʻōlelo a me nā huina Marks. He hōʻailona kākoʻo nā Marks, ʻaʻole palena.",
      bountyOpen: "Uku wehe",
      claimed: "Ua koi ʻia",
      complete: "Hoʻopau",
      translationBountyTitle: "Uku Unuhi",
      bountyDescription: "E unuhi iā Liana Banyan i ka ʻōlelo {{language}}. E loaʻa {{marks}} Marks.",
      scopeWelcome: "Nā pale Aloha / Honua Uhane",
      scopeCueCards: "Pūʻolo Kāleka Paipai",
      scopeNavigation: "Nā hōʻailona alakaʻi a me nā leka hewa",
      scopeWildfire: "Wildfire Beacon Run: ʻImi i kahi hana",
      claimBounty: "E koi i kēia Uku Unuhi",
      baseLanguage: "ʻŌlelo kumu -- ʻaʻohe uku e pono ai.",
      claimedBy: "Ua koi ʻia e @{{handle}} -- e hele ana.",
      marksProvisional: "{{marks}} Marks (panee)",
      speakFounderTitle: "Leo o ka Mea Hoʻokumu: No ke Aha nā Hua Palapala",
      speakFounderDesc: "He kumu ko ia hua palapala o kēia kahua. Ke kumu o nā inoa 26 koʻikoʻi.",
      howBountiesWork: "Pehea e hana ai nā Uku Unuhi",
      step1Title: "E koi i ka Uku",
      step1Body: "E wehe i ka Uku Unuhi mai Help Wanted.",
      step2Title: "E unuhi a e hāʻawi",
      step2Body: "E unuhi i nā kaula like ʻole. E hāʻawi ma Bounty Poster.",
      step3Title: "E loaʻa nā Marks",
      step3Body: "Ma hope o ke kāpono, loaʻa nā Marks a e hoʻopaʻa ʻia i ka IP Ledger.",
      hide: "pee",
      why: "no ke aha?",
    },
    languageSwitcher: {
      changeLanguage: "E hoʻololi i ka ʻōlelo",
      selectLanguage: "E koho i ka ʻōlelo",
      quickEnglish: "Pelekānia",
      tip: "E hoʻohana i nā hua huna ʻōlelo ʻokoʻa ma ka Puka o Durin e wehe ai i nā moʻolelo kūʻiʻo!",
    },
  },
  "dv": {
    speakFriend: {
      title: "ތިމާގެ ދޮސްތި ހިފަހައްޓާ، ވަދޭ.",
      description: "Liana Banyan ހުރިހާ ބަހެއްގެ ދޮރު ހުޅުވިފައިވޭ. ކޮންމެ ދޭތީ ތަރިޖަމަ ހިނގައިދޭ.",
      languages: "ބަސްތައް",
      openBounties: "ހުޅުވިފައިވާ ބަދަލު",
      marksAwarded: "Marks ދީފިން (ބައިވެރިވުން ޓޯކަން)",
      provisional: "ވަގުތީ:",
      provisionalNotice: "ބަސްތަކުގެ ލިސްޓް، Marks ރޭޓް ވަގުތީ. Marks ބައިވެރިވުން ޓޯކަން، ހިއްސާ ނޫން.",
      bountyOpen: "ބަދަލު ހުޅުވިފައި",
      claimed: "ދައުވާ ކޮށްފި",
      complete: "ފުރިހަމަ",
      translationBountyTitle: "ތަރިޖަމަ ބަދަލު",
      bountyDescription: "Liana Banyan {{language}} ތަރިޖަމަ ކުރޭ. {{marks}} Marks ލިބިދޭ.",
      scopeWelcome: "ވަދޭ / ރޫހުގެ ދުނިޔެ",
      scopeCueCards: "ބޮޑު ހިލޭ ހިންދި",
      scopeNavigation: "ނެވިގޭޝަން ލޭބަލް، ގޯސް ޚަބަރު",
      scopeWildfire: "Wildfire Beacon Run: ވަޒީފާ ހޯދޭ",
      claimBounty: "ތަރިޖަމަ ބަދަލު ހޯދޭ",
      baseLanguage: "ބޮޑު ބަސް -- ބަދަލު ނުކިޔޭ.",
      claimedBy: "@{{handle}} ދައުވާ ކޮށްފި -- ކުރިޔަށް.",
      marksProvisional: "{{marks}} Marks (ވަގުތީ)",
      speakFounderTitle: "ބަނިކިޔަ ލިބިފިތިލަ: ކީއްވެ ބަސްތަކެ",
      speakFounderDesc: "ދިމާ ކޮންމެ ބަހެއް ދިވެހި. 26 ނަން ތިލަ.",
      howBountiesWork: "ތަރިޖަމަ ބަދަލު ކުރިޔަށ",
      step1Title: "ބަދަލު ދައުވާ",
      step1Body: "Help Wanted ތިލަ ތަރިޖަމަ ހުޅުވޭ.",
      step2Title: "ތަރިޖަމަ ފޮނިތެޔ",
      step2Body: "ތަރިޖަމަ ހުރިހާ ސިލްސިލާ. Bounty Poster ފޮނިތެ.",
      step3Title: "Marks ލިބިދޭ",
      step3Body: "ލިބިދޭ Marks ، IP Ledger ލިޔިފިތި.",
      hide: "ފޮރުވޭ",
      why: "ކީއްވެ?",
    },
    languageSwitcher: {
      changeLanguage: "ބަސް ބަދަލު ކުރޭ",
      selectLanguage: "ބަސް ހޮވޭ",
      quickEnglish: "އިނގިރޭސި",
      tip: "Durin ދޮރުން ތަފާތު ބަސް ލެވި ބޭހެ!",
    },
  },
  "om": {
    speakFriend: {
      title: "Jaalas jedhi, gali.",
      description: "Liana Banyan afaan hundaaf banaatii ijaarame. Afaan tokko tokkoon badhaasa hiikkaa qaba.",
      languages: "afaanota",
      openBounties: "badhaasa banaa",
      marksAwarded: "Marks kenname (mallattoo hirmaannaa)",
      provisional: "Yeroo duraaf:",
      provisionalNotice: "Tarree afaanota fi gatiin Marks yeroo duraafi. Marks mallattoo hirmaannaa, akka hirmaannaa qabeenyaa miti.",
      bountyOpen: "Badhaasni banaa",
      claimed: "Gaafatame",
      complete: "Xumurame",
      translationBountyTitle: "Badhaasa Hiikuu",
      bountyDescription: "Liana Banyan gara {{language}} hiiki. {{marks}} Marks argadhu.",
      scopeWelcome: "Baga Nagaan Dhuftan / Addunyaa Ayyaannaa",
      scopeCueCards: "Seetii Kaardii Qajeelfamaa",
      scopeNavigation: "Mallattoolee qajeelfamaa fi ergaa dogoggoraa",
      scopeWildfire: "Wildfire Beacon Run: Hojii Argadhu",
      claimBounty: "Badhaasa Hiikuu Kana Gaafadhu",
      baseLanguage: "Afaan madda -- badhaasni hin barbaachisu.",
      claimedBy: "@{{handle}} gaafate -- itti fufaa.",
      marksProvisional: "{{marks}} Marks (yeroo duraaf)",
      speakFounderTitle: "Sagalee Hundeessaa: Maaliif Jechoota Kunneen",
      speakFounderDesc: "Jechoonni karri tokko tokkoon sababaa qabanitti moggaafame. Madda maqaa 26 cimoo.",
      howBountiesWork: "Badhaasni Hiikuu Akkamitti Hojjeta",
      step1Title: "Badhaasa Gaafadhu",
      step1Body: "Badhaasa Hiikuu Help Wanted irraa bana.",
      step2Title: "Hiiki Ergi",
      step2Body: "Hunda strings barbaachisan hiiki. Bounty Poster dhan ergi.",
      step3Title: "Marks Argadhu",
      step3Body: "Erga fudhatamee booda, Marks argatta IP Ledger galmeeffama.",
      hide: "dhoksi",
      why: "maaliif?",
    },
    languageSwitcher: {
      changeLanguage: "Afaan jijjiiri",
      selectLanguage: "Afaan fili",
      quickEnglish: "Ingliffaa",
      tip: "Fuula Durin irra jechoolee afaan gara garaa fayyadami muuxannoo addaa banachuuf!",
    },
  },
  "ti": {
    speakFriend: {
      title: "ሓዊ ኢልካ ኣቱ።",
      description: "Liana Banyan ንኹሉ ቋንቋ ክፉት ተሃኒጽዋ። ነፍሲ ወከፍ ቋንቋ ሓደ ሽልማት ትርጉም ኣለዎ።",
      languages: "ቋንቋታት",
      openBounties: "ክፉት ሽልማታት",
      marksAwarded: "Marks ተዋሂቡ (ምስታፍ ቶኬናት)",
      provisional: "ግዚያዊ:",
      provisionalNotice: "ዝርዝር ቋንቋ ክምኡ Marks ዋጋ ግዚያዊ እዮም። Marks ምስታፍ ቶኬናት ኢዮም፡ ዋርሳ ኣይኮነን።",
      bountyOpen: "ሽልማት ክፉት",
      claimed: "ተሓቲቱ",
      complete: "ተዛዚሙ",
      translationBountyTitle: "ሽልማት ትርጉም",
      bountyDescription: "Liana Banyan ናብ {{language}} ትርጉም ምለሶ። {{marks}} Marks ርኸብ።",
      scopeWelcome: "ብርሃን / ዓለም መናፍስቲ",
      scopeCueCards: "ዋና ካርድ ቡዙሕ",
      scopeNavigation: "ሳጺናት ምምራሕን ዓንቀፎ",
      scopeWildfire: "Wildfire Beacon Run: ስራሕ ርኸብ",
      claimBounty: "ሽልማት ትርጉም ሕተቶ",
      baseLanguage: "ቋንቋ መሰረት -- ሽልማት ኣየድሊ።",
      claimedBy: "@{{handle}} ሓቲቱ -- ቀጺሉ።",
      marksProvisional: "{{marks}} Marks (ግዚያዊ)",
      speakFounderTitle: "ድምጺ መስረቲ: ዝናምሲ ቃላት",
      speakFounderDesc: "ኣብ ፕላትፎርም ነፍሲ ወከፍ ቃል ንሓደ ምኽንያት ተዓዝዚቡ። 26 ሽማ ምንጪ።",
      howBountiesWork: "ሽልማቶ ትርጉም ከምዚ ምዃን",
      step1Title: "ሽልማት ሕተቶ",
      step1Body: "ሽልማት ትርጉም ካብ Help Wanted ክፈቶ።",
      step2Title: "ተርጉምዶ ልኣኾ",
      step2Body: "ዘድሊ ሕብረቁምፊ ተርጉምዶ Bounty Poster ካብ ልኣኾ።",
      step3Title: "Marks ርኸብ",
      step3Body: "ምስ ተቐበሉ Marks ርኸብ IP Ledger ምዝጋብ።",
      hide: "ደብቅ",
      why: "ስለምንታይ?",
    },
    languageSwitcher: {
      changeLanguage: "ቋንቋ ቀይር",
      selectLanguage: "ቋንቋ ምረጽ",
      quickEnglish: "እንግሊዝኛ",
      tip: "Durin ሰጊናት ቋንቋ ናይ ዝተፈላለዩ ሊዋ ዓምዩ!",
    },
  },
  "rn": {
    speakFriend: {
      title: "Vuga incuti, usome.",
      description: "Liana Banyan yaranguwe kugira ngo ivugure ku rurimi rwose. Ururimi rwose rufunguye rufite umusanzu umwe wo guhindura.",
      languages: "indimi",
      openBounties: "amafaranga y'umusanzu afunguye",
      marksAwarded: "Marks yarahawe (ibimenyetso vy'ugutera imbere)",
      provisional: "Muri make:",
      provisionalNotice: "Urutonde rw'indimi n'ingano z'Marks ni rw'igihe gito. Marks ibimenyetso vy'ugutera imbere, si imigabane.",
      bountyOpen: "Umusanzu ufunguye",
      claimed: "Basavye",
      complete: "Birangiye",
      translationBountyTitle: "Umusanzu wo Guhindura",
      bountyDescription: "Hindura Liana Banyan mu {{language}}. Unguka {{marks}} Marks.",
      scopeWelcome: "Ikaze / Isi y'Imizuka",
      scopeCueCards: "Urutonde rw'Amakarata y'Amabwiriza",
      scopeNavigation: "Amashira y'inzira n'ubutumwa bw'amakosa",
      scopeWildfire: "Wildfire Beacon Run: Shaka Akazi",
      claimBounty: "Saba Umusanzu uyu wo Guhindura",
      baseLanguage: "Ururimi rw'ibanze -- nta musanzu ukenewe.",
      claimedBy: "@{{handle}} yarasavye -- biragenda.",
      marksProvisional: "{{marks}} Marks (muri make)",
      speakFounderTitle: "Ijwi ry'Umutwazi: Impamvu y'Ayo Majambo",
      speakFounderDesc: "Ijambo ryose muri sisitemu iyi ryatowe n'impamvu. Inkomoko y'amazina 26 y'ingenzi.",
      howBountiesWork: "Amafaranga y'Umusanzu Agenda Gute",
      step1Title: "Saba Umusanzu",
      step1Body: "Fungura Umusanzu wo Guhindura ku kibaho Help Wanted.",
      step2Title: "Hindura Wohereze",
      step2Body: "Hindura ivyari bikenwa vyose. Ohereza ukoresheje Bounty Poster.",
      step3Title: "Unguka Marks",
      step3Body: "Nyuma yo kwemeranwa, uzahabwa Marks kandi uzandikwe muri IP Ledger.",
      hide: "hisha",
      why: "impamvu?",
    },
    languageSwitcher: {
      changeLanguage: "Hindura ururimi",
      selectLanguage: "Hitamo ururimi",
      quickEnglish: "Icongereza",
      tip: "Koresha ibifaranga vy'indimi zitandukanye ku muryango wa Durin kugira ngo ukingure uburambe budasanzwe!",
    },
  },
  "sg": {
    speakFriend: {
      title: "Linga sô-kôlî, kûê lo.",
      description: "Liana Banyan balë-ngango yâ bïla sêse. Ngbangâ yângâ mû sêse ayeke nzû ti nzûna.",
      languages: "sêse",
      openBounties: "nzûna lângö",
      marksAwarded: "Marks adukundë (takwë ti fa nzö)",
      provisional: "Sîgî:",
      provisionalNotice: "Lïngö ti sêse na azo na Marks sîgî. Marks takwë ti fa nzö, ngangö ê nzûna.",
      bountyOpen: "Nzûna lângö",
      claimed: "Aläkö",
      complete: "Pekë",
      translationBountyTitle: "Nzûna ti Mbï-tëne",
      bountyDescription: "Mbï-tëne Liana Banyan ti {{language}}. Sö {{marks}} Marks.",
      scopeWelcome: "Yeke lo / Mbïla Ndë",
      scopeCueCards: "Kûta ya Kayë ti Ndô",
      scopeNavigation: "Alakö ti ngû na kîrî ti pekë",
      scopeWildfire: "Wildfire Beacon Run: Sö Kûa",
      claimBounty: "Läkö Nzûna oyo ti Mbï-tëne",
      baseLanguage: "Sêse ti leke -- nzûna âwa.",
      claimedBy: "@{{handle}} aläkö -- sô-mbï.",
      marksProvisional: "{{marks}} Marks (sîgî)",
      speakFounderTitle: "Kôlî ti Mbo-tere: Pekë Sô Môdî",
      speakFounderDesc: "Sô-kôlî nzö tûndûa yê na ndô. Sô 26 na ndö mbo.",
      howBountiesWork: "Nzûna ti Mbï-tëne Sô Yeke",
      step1Title: "Läkö Nzûna",
      step1Body: "Lângö Nzûna ti Mbï-tëne sô Help Wanted.",
      step2Title: "Mbï-tëne Kûê",
      step2Body: "Mbï-tëne sô-kôlî yângo. Kûê ti Bounty Poster.",
      step3Title: "Sö Marks",
      step3Body: "Bïla nzö, sö Marks na IP Ledger.",
      hide: "fakara",
      why: "pekë?",
    },
    languageSwitcher: {
      changeLanguage: "Sö sêse",
      selectLanguage: "Bîla sêse",
      quickEnglish: "Zïngo",
      tip: "Sëse ni fata sô Durin nzö takwë!",
    },
  },
  "lu": {
    speakFriend: {
      title: "Badia mukwasha, nena.",
      description: "Liana Banyan yazengwa kuza yafunguka mu zilimi zonse. Lulimi lonse lufunguka lunawo muswapo umwi wa kusoselela.",
      languages: "zilimi",
      openBounties: "miswapo ifungulwa",
      marksAwarded: "Marks yapelwa (fitambwa fya kukabila)",
      provisional: "Nkabalenshi:",
      provisionalNotice: "Ulupungu wa zilimi na miimo ya Marks ni ya nkabalenshi. Marks fitambwa fya kukabila, ne fyabufi.",
      bountyOpen: "Muswapo ufungulwa",
      claimed: "Yasabwa",
      complete: "Yalyakana",
      translationBountyTitle: "Muswapo wa Kusoselela",
      bountyDescription: "Soselela Liana Banyan mu {{language}}. Poka {{marks}} Marks.",
      scopeWelcome: "Imitemuko Mutende / Isonde lya Imipepo",
      scopeCueCards: "Intulo ya Amakaadi ya Fingulo",
      scopeNavigation: "Inshibilo ya njila na makosa",
      scopeWildfire: "Wildfire Beacon Run: Poka Umwanya",
      claimBounty: "Saba Uyu Muswapo wa Kusoselela",
      baseLanguage: "Lulimi lwa kubalilapo -- tamuswapwa.",
      claimedBy: "@{{handle}} yasabwa -- ya-pita.",
      marksProvisional: "{{marks}} Marks (nkabalenshi)",
      speakFounderTitle: "Inshimi ya Mwine: Ifi Fyena Ifyebo",
      speakFounderDesc: "Ubupyali bonse bwa platform yi bafilwe ishina pa mulandu. Ipapatilo lya malambo 26.",
      howBountiesWork: "Miswapo ya Kusoselela Ikabila Shani",
      step1Title: "Saba Muswapo",
      step1Body: "Fungula Muswapo wa Kusoselela ku Help Wanted.",
      step2Title: "Soselela Tuma",
      step2Body: "Soselela imipalamino yonse. Tuma ku Bounty Poster.",
      step3Title: "Poka Marks",
      step3Body: "Peshya yakibilwa, mupoka Marks na ukuwandika ku IP Ledger.",
      hide: "fisa",
      why: "ifi?",
    },
    languageSwitcher: {
      changeLanguage: "Sinda lulumi",
      selectLanguage: "Sala lulumi",
      quickEnglish: "Icingelezi",
      tip: "Umishindo ya zilimi ishindwa ku Mwango wa Durin poka ifyafisomwa fya lwakwa!",
    },
  },
  "kg": {
    speakFriend: {
      title: "Luvutu bantu, yiza.",
      description: "Liana Banyan etangwa bue ewusaka bantu yonso. Luninga yonso ezolangwa elunga mosi ya luzolo.",
      languages: "mininga",
      openBounties: "malunga mazolangwa",
      marksAwarded: "Marks epesami (bikangudi bya kosangana)",
      provisional: "Ntangu ndambu:",
      provisionalNotice: "Lulendo ya mininga na Marks ntangu ndambu. Marks bikangudi bya kosangana.",
      bountyOpen: "Lunga ezolangwa",
      claimed: "Ebombami",
      complete: "Ekosama",
      translationBountyTitle: "Lunga ya Kulongulula",
      bountyDescription: "Longulula Liana Banyan na {{language}}. Zwa {{marks}} Marks.",
      scopeWelcome: "Mbote / Nseke ya Bikokolo",
      scopeCueCards: "Biteke bya Lukeno",
      scopeNavigation: "Biloko bya nzila na bitoke bya misala",
      scopeWildfire: "Wildfire Beacon Run: Yiba Misala",
      claimBounty: "Bamba Lunga oyo ya Kulongulula",
      baseLanguage: "Luninga yanda -- lunga ke ikele.",
      claimedBy: "@{{handle}} ebombami -- etambula.",
      marksProvisional: "{{marks}} Marks (ntangu ndambu)",
      speakFounderTitle: "Ntiti ya Mfumu: Ndambu Baandike",
      speakFounderDesc: "Binkundi yonso platform yina matambu kia nzina. Mikanda 26 ya mbazi.",
      howBountiesWork: "Malunga ya Kulongulula Kosala",
      step1Title: "Bamba Lunga",
      step1Body: "Zola Lunga ya Kulongulula eka Help Wanted.",
      step2Title: "Longulula Tinda",
      step2Body: "Longulula iyo yonso. Tinda Bounty Poster.",
      step3Title: "Zwa Marks",
      step3Body: "Mpo yatambulwa, uzwa Marks ya IP Ledger.",
      hide: "kumbisa",
      why: "bua nini?",
    },
    languageSwitcher: {
      changeLanguage: "Mona luninga",
      selectLanguage: "Sala luninga",
      quickEnglish: "Ngelesa",
      tip: "Ntoto ya luninga Durin kamba muntu!",
    },
  },
  "gn": {
    speakFriend: {
      title: "Emombe'u amigo, ha eike.",
      description: "Liana Banyan omopu'ã haguã ojehecha oĩ ñe'ẽ rehe. Ñe'ẽ peteĩ peteĩ ojehecha oĩ pe'a ojupe rembiporu.",
      languages: "ñe'ẽ",
      openBounties: "pe'a ojehecha oĩ",
      marksAwarded: "Marks ojeguereko (token ñemyatyrõ)",
      provisional: "Umi peteĩ aravo:",
      provisionalNotice: "Lista ñe'ẽ Marks rëi umi peteĩ aravo. Marks token ñemyatyrõ, ndaha'éi acción.",
      bountyOpen: "Pe'a ojehecha",
      claimed: "Ojeporu",
      complete: "Oĩporãkuéra",
      translationBountyTitle: "Pe'a Ñembohasa",
      bountyDescription: "Eñembohasa Liana Banyan {{language}}. Egueru {{marks}} Marks.",
      scopeWelcome: "Terekome / Yvy Añã",
      scopeCueCards: "Karîi Ñeha'ã",
      scopeNavigation: "Tembirehe ñande jepoha ha mba'e'akatúpe",
      scopeWildfire: "Wildfire Beacon Run: Eikuaasa Tembiapo",
      claimBounty: "Ejeporu Pe'a Ñembohasa Kõi",
      baseLanguage: "Ñe'ẽ ñemoha -- pe'a ndaipóri.",
      claimedBy: "@{{handle}} ojeporu -- oĩporã.",
      marksProvisional: "{{marks}} Marks (umi peteĩ aravo)",
      speakFounderTitle: "Ñe'ẽ Ñemoha: Mba'érepa Ko Mba'e",
      speakFounderDesc: "Mba'ety ko plataforma-pe oĩ rire ñemombeu. 26 réra ambuépe.",
      howBountiesWork: "Mba'éicha Pe'a Ñembohasa Oiko",
      step1Title: "Ejeporu Pe'a",
      step1Body: "Eja Pe'a Ñembohasa Help Wanted-gui.",
      step2Title: "Eñembohasa Embou",
      step2Body: "Eñembohasa mba'e oĩ porãite. Embou Bounty Poster rupive.",
      step3Title: "Egueru Marks",
      step3Body: "Oñembohasa rire eike Marks IP Ledger-pe.",
      hide: "embyky",
      why: "mba'érepa?",
    },
    languageSwitcher: {
      changeLanguage: "Embosako ñe'ẽ",
      selectLanguage: "Eiporavo ñe'ẽ",
      quickEnglish: "Ingléso ñe'ẽ",
      tip: "Eiporu ñe'ẽ mbyky heta Durin tape-pe!",
    },
  },
  "tet": {
    speakFriend: {
      title: "Ko dehan amigo, no tama.",
      description: "Liana Banyan maka halo ba lingua hotu-hotu bele tama. Lingua ida-idak iha rekompensu tradusaun ida.",
      languages: "lingua",
      openBounties: "rekompensu aberta",
      marksAwarded: "Marks fó ona (token partisipasaun)",
      provisional: "Provisóriu:",
      provisionalNotice: "Lista lingua no taxa Marks provisóriu. Marks token partisipasaun, la'ós asaun.",
      bountyOpen: "Rekompensu aberta",
      claimed: "Reklamadu",
      complete: "Kompletu",
      translationBountyTitle: "Rekompensu Tradusaun",
      bountyDescription: "Tradus Liana Banyan ba {{language}}. Hetan {{marks}} Marks.",
      scopeWelcome: "Bem-vindo / Mundu Espíritu",
      scopeCueCards: "Konjuntu Kartu Instrusaun",
      scopeNavigation: "Etiketa navigasaun no mensajen erru",
      scopeWildfire: "Wildfire Beacon Run: Hetan Servisu",
      claimBounty: "Reklamar Rekompensu Tradusaun Ida ne'e",
      baseLanguage: "Lingua baze -- la presiza rekompensu.",
      claimedBy: "@{{handle}} reklamar -- kontinua.",
      marksProvisional: "{{marks}} Marks (provisóriu)",
      speakFounderTitle: "Lian Fundadór: Tanba sa Liafuan sira ne'e",
      speakFounderDesc: "Termu ida-idak iha plataforma ne'e iha razaun naran. Origem 26 naran importante.",
      howBountiesWork: "Oinsá Rekompensu Tradusaun Servisu",
      step1Title: "Reklamar Rekompensu",
      step1Body: "Abre Rekompensu Tradusaun hosi Help Wanted.",
      step2Title: "Tradus no Submete",
      step2Body: "Tradus liña hotu-hotu presiza. Submete liu Bounty Poster.",
      step3Title: "Hetan Marks",
      step3Body: "Depois akseita, simu Marks no rejista iha IP Ledger.",
      hide: "taka",
      why: "tanba sa?",
    },
    languageSwitcher: {
      changeLanguage: "Muda lingua",
      selectLanguage: "Hili lingua",
      quickEnglish: "Inglés",
      tip: "Uza senha lingua diferente iha Porta Durin atu loke esperiénsia úniku!",
    },
  },
  "tpi": {
    speakFriend: {
      title: "Tok pren, na kam insait.",
      description: "Liana Banyan i bin wokim olsem olgeta tok ples inap lukim. Wanwan tok ples i gat wanpela prais bilong tanim tok.",
      languages: "tok ples",
      openBounties: "prais i op",
      marksAwarded: "Marks i givim (token bilong painim)",
      provisional: "Nau tasol:",
      provisionalNotice: "Lis tok ples na rei bilong Marks em nau tasol. Marks em token bilong painim, no share.",
      bountyOpen: "Prais i op",
      claimed: "I askim pinis",
      complete: "I pinis",
      translationBountyTitle: "Prais Bilong Tanim Tok",
      bountyDescription: "Tanim Liana Banyan long {{language}}. Kisim {{marks}} Marks.",
      scopeWelcome: "Kam Gut / Graun Bilong Spirit",
      scopeCueCards: "Sik Kasen Bilong Helpim",
      scopeNavigation: "Mak bilong wokabaut na tok bilong bagarap",
      scopeWildfire: "Wildfire Beacon Run: Painim Wok",
      claimBounty: "Askim Dispela Prais Tanim Tok",
      baseLanguage: "Namba wan tok ples -- prais i no nidim.",
      claimedBy: "@{{handle}} i askim -- i go yet.",
      marksProvisional: "{{marks}} Marks (nau tasol)",
      speakFounderTitle: "Tok Bilong Namba Wan Man: Bilong Wanem Dispela Tok",
      speakFounderDesc: "Wanwan tok long dispela ples i gat nem bilong wanem. 26 nem i olsem.",
      howBountiesWork: "Olsem Wanem Prais Tanim Tok i Wok",
      step1Title: "Askim Prais",
      step1Body: "Opim Prais Tanim Tok long Help Wanted.",
      step2Title: "Tanim Tok na Salim",
      step2Body: "Tanim olgeta lain i nidim. Salim long Bounty Poster.",
      step3Title: "Kisim Marks",
      step3Body: "Bihain long orait, kisim Marks na IP Ledger i raitim.",
      hide: "hait",
      why: "bilong wanem?",
    },
    languageSwitcher: {
      changeLanguage: "Senis tok ples",
      selectLanguage: "Makim tok ples",
      quickEnglish: "Tok Inglis",
      tip: "Yusim tok hait bilong narapela tok ples long dua Durin bilong opim samting nupela!",
    },
  },
  "ilo": {
    speakFriend: {
      title: "Ibaga ti kakaduam, ken sumrek.",
      description: "Liana Banyan napatakder tapno naabriranna iti tunggal pagsasao. Tunggal pagsasao ket addaan iti maysa nga padaya ti patarus.",
      languages: "pagsasao",
      openBounties: "naabriran a padaya",
      marksAwarded: "Natted dagiti Marks (dagiti token ti panangiturong)",
      provisional: "Temporal:",
      provisionalNotice: "Ti listaan ti pagsasao ken dagiti rate ti Marks temporal. Dagiti Marks dagiti token ti panangiturong, saan nga stock.",
      bountyOpen: "Naabriran ti padaya",
      claimed: "Naalpas",
      complete: "Natungpal",
      translationBountyTitle: "Padaya ti Patarus",
      bountyDescription: "Ikkat ti Liana Banyan idiay {{language}}. Mangala iti {{marks}} Marks.",
      scopeWelcome: "Daytoy / Lubong dagiti Espiritu",
      scopeCueCards: "Grupo dagiti Kard ti Tagubilin",
      scopeNavigation: "Dagiti marka ti pagsasao ken dagiti mensahe ti biddut",
      scopeWildfire: "Wildfire Beacon Run: Agbirbirok ti Trabaho",
      claimBounty: "Alpasan Daytoy nga Padaya ti Patarus",
      baseLanguage: "Nakabasaran a pagsasao -- awan padaya nga masapul.",
      claimedBy: "@{{handle}} ti nagalpa -- agpadapadayon.",
      marksProvisional: "{{marks}} Marks (temporal)",
      speakFounderTitle: "Timek ti Mangaramid: Apay Dagitoy a Sasao",
      speakFounderDesc: "Tunggal termino iti daytoy a plataporma nasanganaan iti rason. Nagsaritan dagiti 26 a naganyo.",
      howBountiesWork: "Kasano Mangagmamula dagiti Padaya ti Patarus",
      step1Title: "Alpasan ti Padaya",
      step1Body: "Abriran ti Padaya ti Patarus manipud Help Wanted.",
      step2Title: "Pataruse ken Ibalhoy",
      step2Body: "Pataruse amin a napateg a linya. Ibalhoy babaen ti Bounty Poster.",
      step3Title: "Mangala iti Marks",
      step3Body: "Kalpasan ti aprobaran, makala iti Marks ken nairehistro iti IP Ledger.",
      hide: "itago",
      why: "apay?",
    },
    languageSwitcher: {
      changeLanguage: "Bagayan ti pagsasao",
      selectLanguage: "Piliem ti pagsasao",
      quickEnglish: "Ingles",
      tip: "Usaren dagiti password ti nadumaduma a pagsasao iti Ridaw ni Durin tapno mailukat dagiti naidumduma nga aramid!",
    },
  },
  "tt": {
    speakFriend: {
      title: "Дус ди, кер.",
      description: "Liana Banyan һәр тел өчен ачык итеп төзелгән. Ачык теллернең берсе тәрҗемә бүләгенә ия.",
      languages: "телләр",
      openBounties: "ачык бүләкләр",
      marksAwarded: "Marks бирелде (катнашу токеннары)",
      provisional: "Вакытлыча:",
      provisionalNotice: "Телләр исемлеге һәм Marks ставкалары вакытлыча. Marks катнашу токеннары, акция түгел.",
      bountyOpen: "Бүләк ачык",
      claimed: "Таләп ителде",
      complete: "Тамамланды",
      translationBountyTitle: "Тәрҗемә Бүләге",
      bountyDescription: "Liana Banyan-ны {{language}} теленә тәрҗемә итегез. {{marks}} Marks казаныгыз.",
      scopeWelcome: "Хуш килдегез / Рухлар Дөньясы экраннары",
      scopeCueCards: "Төп Киңәш картасы тупланмасы",
      scopeNavigation: "Навигация билгеләре һәм хата хәбәрләре",
      scopeWildfire: "Wildfire Beacon Run: Эш тап",
      claimBounty: "Бу Тәрҗемә Бүләгенә таләп кил",
      baseLanguage: "Нигез теле -- бүләк кирәк түгел.",
      claimedBy: "@{{handle}} таләп итте -- дәвам итә.",
      marksProvisional: "{{marks}} Marks (вакытлыча)",
      speakFounderTitle: "Нигезче Тавышы: Нигә Бу Сүзләр",
      speakFounderDesc: "Бу платформадагы һәр термин бер сәбәп белән аталган. 26 мөһим исемнең чыгышы.",
      howBountiesWork: "Тәрҗемә Бүләкләре Ничек Эшли",
      step1Title: "Бүләккә таләп кил",
      step1Body: "Help Wanted такталасыннан Тәрҗемә Бүләгенә ача торгыз.",
      step2Title: "Тәрҗемә ит һәм Сул тот",
      step2Body: "Барлык кирәкле юлларны тәрҗемә итегез. Bounty Poster аша тот.",
      step3Title: "Marks казан",
      step3Body: "Кабул ителгәннән соң Marks алдыгыз. IP Ledger-да язылдыгыз.",
      hide: "яшерергә",
      why: "нигә?",
    },
    languageSwitcher: {
      changeLanguage: "Телне алмаштыр",
      selectLanguage: "Тел сайлагыз",
      quickEnglish: "Инглиз",
      tip: "Дурин Ишегендә төрле тел паролларын куллан үзенчәлекле тәҗрибәләр ачу өчен!",
    },
  },
  "zgh": {
    speakFriend: {
      title: "ⵉⵏⵉ ⴰⵎⴷⴷⴰⴽⴽⴻⵍ, ⵉⵍⵍⴻⵖ.",
      description: "Liana Banyan ⵜⴻⴱⵏⴰ ⴰⴽⴽⴻⵏ ⴰⴷ ⵜⴻⴱⴷⵓ ⵉ ⵉⵍⵙⴰⵡⴻⵏ ⴽⵓⵍⵍⵓ. ⴽⵓⵍⵍⵓ ⴰⵍⵙⴰⵡ ⴷⴰⵔⵙ ⵜⴰⵍⵖⴰ ⵢⵉⵡⴻⵜ ⵏ ⵜⴻⵖⵔⵉ.",
      languages: "ⵜⵉⵍⵙⴰⵡⵉⵏ",
      openBounties: "ⵉⵏⴰⴷⴷⴻⵎ ⵉⴱⴷⴰⵏ",
      marksAwarded: "Marks ⵉⵜⵜⵡⴰⴽⵛⵎ (ⵜⵉⴽⴻⵏⴰⵜ ⵏ ⵓⵎⵢⴰⴳⴻⵔ)",
      provisional: "ⵉⵎⵉⵔⵏ:",
      provisionalNotice: "ⵜⴰⵍⵖⴰ ⵏ ⵜⵉⵍⵙⴰⵡⵉⵏ ⴷ ⵉⵥⴻⴹⵕⴰⵏ ⵏ Marks ⵉⵎⵉⵔⵏ. Marks ⵜⵉⴽⴻⵏⴰⵜ ⵏ ⵓⵎⵢⴰⴳⴻⵔ, ⵓⵔ ⴷ ⴰⵖⵔⴻⵎ.",
      bountyOpen: "ⴰⵏⴰⴷⴷⴻⵎ ⵉⴱⴷⴰ",
      claimed: "ⵉⵜⵜⵡⴰⴼⵔⴰ",
      complete: "ⵉⴽⵎⴻⵍ",
      translationBountyTitle: "ⴰⵏⴰⴷⴷⴻⵎ ⵏ ⵜⴻⵖⵔⵉ",
      bountyDescription: "Liana Banyan ⵜⴻⵖⵔⵉ ⵙ {{language}}. ⵉⵙⵓ {{marks}} Marks.",
      scopeWelcome: "ⴰⵏⵙⵓⴼ / ⴰⴷⴻⵏⵢⴰ ⵏ ⵉⵔⵓⵀⴰⵏ",
      scopeCueCards: "ⵜⴰⵙⴳⴰ ⵏ ⵜⴽⴰⵔⴹⴰ ⵏ ⵉⵙⵓⵔⴰ",
      scopeNavigation: "ⵉⵔⴰⴽⵉⵙⴻⵏ ⵏ ⵓⵙⴻⵎⵔⴻⵙ ⴷ ⵜⵎⴻⵔⵙⴰⵍ",
      scopeWildfire: "Wildfire Beacon Run: ⴼⴻⵔ ⴰⵣⴻⵔⴼⴰⵏ",
      claimBounty: "ⴼⴰⵔ ⵓⵏⴰⴷⴷⴻⵎ ⴰⴷ ⵏ ⵜⴻⵖⵔⵉ",
      baseLanguage: "ⴰⵍⵙⴰⵡ ⴰⴷⴷⴰⴷ -- ⵓⵔ ⵉⵍⴰ ⴰⵏⴰⴷⴷⴻⵎ.",
      claimedBy: "@{{handle}} ⵉⴼⴰⵔ -- ⵉⵎⵎⴻⵙⵍⴰⵢ.",
      marksProvisional: "{{marks}} Marks (ⵉⵎⵉⵔⵏ)",
      speakFounderTitle: "ⵜⴰⵔⵎⵉⵜ ⵏ ⵓⵏⴻⴳⴳⴰⵔⵓ: ⵎⵏⵉⴷ ⵉⵙⴻⵎⵔⴰⵙⴻⵏ",
      speakFounderDesc: "ⴽⵓⵍⵍⵓ ⴰⵎⴰⵍⵙⴰⵡ ⴷⴰⵔⵙ ⵜⵓⵇⵇⴰ. 26 ⵉⵙⵎⴰⵡⴻⵏ ⵉⵎⵇⵔⴰⵏⴻⵏ.",
      howBountiesWork: "ⵎⴰⵎⴻⴽ ⵉⵙⴻⵇⵇⴰⵔ ⵓⵏⴰⴷⴷⴻⵎ ⵏ ⵜⴻⵖⵔⵉ",
      step1Title: "ⴼⴰⵔ ⵓⵏⴰⴷⴷⴻⵎ",
      step1Body: "ⵇⴻⴹ ⵓⵏⴰⴷⴷⴻⵎ ⵏ ⵜⴻⵖⵔⵉ ⴷ Help Wanted.",
      step2Title: "ⵜⴻⵖⵔⵉ ⴷ ⵉⵙⵓ",
      step2Body: "ⵜⴻⵖⵔⵉ ⴽⵓⵍⵍⵓ ⵜⵉⵏⴻⵙⵇⴰⵎⵜ ⵉⵔⵓⵙⴻⵏ. ⵉⵙⵓ ⴷ Bounty Poster.",
      step3Title: "ⵉⵙⵓ Marks",
      step3Body: "ⵢⴻⵎⵎⴻⵜ ⴰⴷ ⵉⵙⵓ Marks ⵜⵜⵡⴰⵎⵓⴽⴽⴻⵙ ⴷⴻⴳ IP Ledger.",
      hide: "ⵣⵣⵍ",
      why: "ⵎⴰⵎⴻⴽ?",
    },
    languageSwitcher: {
      changeLanguage: "ⵙⵏⴻⴼⵍⴻⵍ ⴰⵍⵙⴰⵡ",
      selectLanguage: "ⵙⵜⵉ ⴰⵍⵙⴰⵡ",
      quickEnglish: "ⵜⴰⵏⴳⵍⵉⵣⵜ",
      tip: "ⵇⴻⴷⴷⴻⵎ ⵙ ⵜⵢⵓⵔⴹⴰⵏ ⵏ ⵜⵉⵍⵙⴰⵡⵉⵏ ⵢⴰⴹⵏⵉⵏ ⴷ ⵜⵉⴼⵉⵙⵏⵉⵜ ⵏ Durin!",
    },
  },
  "hil": {
    speakFriend: {
      title: "Hamuon hi abyan, kag sulod.",
      description: "Ang Liana Banyan ginhimo para maabri sa bisan ano nga pinulongan. Ang tagsa ka bukas nga pinulongan may isa ka premyo sa paghubad.",
      languages: "mga pinulongan",
      openBounties: "bukas nga premyo",
      marksAwarded: "Marks gin-hatag (mga token sang pakig-ambit)",
      provisional: "Temporaryo:",
      provisionalNotice: "Ang listahan sang mga pinulongan kag mga rate sang Marks temporaryo. Ang Marks mga token sang pakig-ambit, indi equity.",
      bountyOpen: "Bukas ang premyo",
      claimed: "Gin-angkon na",
      complete: "Natapos",
      translationBountyTitle: "Premyo sang Paghubad",
      bountyDescription: "Hubaron ang Liana Banyan sa {{language}}. Makuha ang {{marks}} Marks.",
      scopeWelcome: "Mga screen sang Maayong Pag-abot / Ghost World",
      scopeCueCards: "Core nga hanay sang Cue Card",
      scopeNavigation: "Mga label sang navigasyon kag mensahe sang sala",
      scopeWildfire: "Wildfire Beacon Run: Pangita sang Trabaho",
      claimBounty: "Angkona ini nga Premyo sang Paghubad",
      baseLanguage: "Sukaranan nga pinulongan -- wala premyo nga kinahanglan.",
      claimedBy: "Gin-angkon ni @{{handle}} -- nagapadayon.",
      marksProvisional: "{{marks}} Marks (temporaryo)",
      speakFounderTitle: "Tingog sang Nagtukod: Ngaa ini nga mga Pulong",
      speakFounderDesc: "Ang tagsa ka termino ginganlan tungod sa isa ka rason. Ang ginikanan sang 26 pinaka-importante nga mga ngalan.",
      howBountiesWork: "Paano Nagaobra ang mga Premyo sang Paghubad",
      step1Title: "Angkona ang Premyo",
      step1Body: "Ablihan ang Premyo sang Paghubad halin sa Help Wanted.",
      step2Title: "Hubad kag Isumite",
      step2Body: "Hubaron ang tanan nga kinahanglan nga mga string. Isumite pinaagi sa Bounty Poster.",
      step3Title: "Makuha ang Marks",
      step3Body: "Sa pagdawat, makatanggap ka sang Marks kag ma-rekord sa IP Ledger.",
      hide: "itago",
      why: "ngaa?",
    },
    languageSwitcher: {
      changeLanguage: "Usba ang pinulongan",
      selectLanguage: "Pilion ang pinulongan",
      quickEnglish: "Iningles",
      tip: "Gamiton ang lain-laing mga password sang pinulongan sa Pintuan ni Durin para ma-unlock ang natatanging kasinatian!",
    },
  },
  "min": {
    speakFriend: {
      title: "Kato sahabat, masuak.",
      description: "Liana Banyan dibuek untuak tarbuka untuak satiok bahaso. Satiok bahaso nan tarbuka punyo satu hadiah terjemahan.",
      languages: "bahaso",
      openBounties: "hadiah tarbuka",
      marksAwarded: "Marks dibuerian (token partisipasi)",
      provisional: "Samarantaro:",
      provisionalNotice: "Daftar bahaso jo tarip Marks samarantaro. Marks token partisipasi, indak ekuitas.",
      bountyOpen: "Hadiah tarbuka",
      claimed: "Diklaim",
      complete: "Salasai",
      translationBountyTitle: "Hadiah Terjemahan",
      bountyDescription: "Terjemahkan Liana Banyan ka {{language}}. Dapek {{marks}} Marks.",
      scopeWelcome: "Layar Salamaik Datang / Dunio Hantu",
      scopeCueCards: "Set Kartu Isyarat Inti",
      scopeNavigation: "Label navigasi jo pesan kasalahan",
      scopeWildfire: "Wildfire Beacon Run: Cari Karajo",
      claimBounty: "Klaim Hadiah Terjemahan Ko",
      baseLanguage: "Bahaso dasar -- indak paralu hadiah.",
      claimedBy: "@{{handle}} ngaklaim -- sadang bajalan.",
      marksProvisional: "{{marks}} Marks (samarantaro)",
      speakFounderTitle: "Suaro Pandiri: Manga Kato Ko",
      speakFounderDesc: "Satiok istilah di platform ko punyo alasan namanya. Asal 26 namo terpenting.",
      howBountiesWork: "Camano Hadiah Terjemahan Bakarajo",
      step1Title: "Klaim Hadiah",
      step1Body: "Buak Hadiah Terjemahan dari papan Help Wanted.",
      step2Title: "Terjemah jo Kirim",
      step2Body: "Terjemahkan samua string nan diparaluan. Kirim melalui Bounty Poster.",
      step3Title: "Dapek Marks",
      step3Body: "Sasudah diterima, anda dapek Marks jo tacatat di IP Ledger.",
      hide: "sambunyikan",
      why: "manga?",
    },
    languageSwitcher: {
      changeLanguage: "Ganti bahaso",
      selectLanguage: "Pilih bahaso",
      quickEnglish: "Bahaso Inggih",
      tip: "Gunakan kata sandi bahaso beda-beda di Pintu Durin untuak mambuka pengalaman unik!",
    },
  },
  "bug": {
    speakFriend: {
      title: "Passé bija-é, narekko.",
      description: "Liana Banyan nabangun mangekka terbuka ri sininna basa. Sininna basa nasibawang satu hadiah pallebbangeng.",
      languages: "basa",
      openBounties: "hadiah nateruka",
      marksAwarded: "Marks nawere (token partisipasi)",
      provisional: "Makkatenni:",
      provisionalNotice: "Laddere basa enreng tarif Marks makkatenni. Marks token partisipasi, de ekuitas.",
      bountyOpen: "Hadiah nateruka",
      claimed: "Napatungka",
      complete: "Naputtama",
      translationBountyTitle: "Hadiah Pallebbangeng",
      bountyDescription: "Pallebbang Liana Banyan ri {{language}}. Waré {{marks}} Marks.",
      scopeWelcome: "Layar Tabe / Lino Bunting",
      scopeCueCards: "Set Kartu Pandeng",
      scopeNavigation: "Label navigasi enreng pesan sala",
      scopeWildfire: "Wildfire Beacon Run: Pappole Nawa",
      claimBounty: "Patungka Hadiah Pallebbangeng Kiyai",
      baseLanguage: "Basa asalenna -- de perlu hadiah.",
      claimedBy: "@{{handle}} napatungka -- napolei.",
      marksProvisional: "{{marks}} Marks (makkatenni)",
      speakFounderTitle: "Lontara Passé: Aga Elo Makkeda Ko",
      speakFounderDesc: "Sininna istilah nasibawangi alasan ri lalenna narangi. 26 aseng natinggi.",
      howBountiesWork: "Pole Hadiah Pallebbangeng Maneng",
      step1Title: "Patungka Hadiah",
      step1Body: "Teruka Hadiah Pallebbangeng ri Help Wanted.",
      step2Title: "Pallebbang Kirim",
      step2Body: "Pallebbang sininna string. Kirim ri Bounty Poster.",
      step3Title: "Waré Marks",
      step3Body: "Sanggenna naterima, namawa Marks enreng natulis ri IP Ledger.",
      hide: "saléng",
      why: "aga?",
    },
    languageSwitcher: {
      changeLanguage: "Pèkke basa",
      selectLanguage: "Pilih basa",
      quickEnglish: "Basa Inggeris",
      tip: "Pakéi kata sandi basa laing ri Pakkita Durin!",
    },
  },
  "cv": {
    speakFriend: {
      title: "Юрату тесе, кӗр.",
      description: "Liana Banyan кашни чӗлхе валли уçă тунă. Кашни уçă чӗлхен куçару сыйлăхĕ пур.",
      languages: "чӗлхесем",
      openBounties: "уçă сыйлăхсем",
      marksAwarded: "Marks пачĕç (хутшăну токенĕсем)",
      provisional: "Вăхăтлăха:",
      provisionalNotice: "Чӗлхе çыравĕпе Marks тарифĕсем вăхăтлăха. Marks хутшăну токенĕсем, акцисем мар.",
      bountyOpen: "Сыйлăх уçă",
      claimed: "Тупсă илнĕ",
      complete: "Пĕтернĕ",
      translationBountyTitle: "Куçару сыйлăхĕ",
      bountyDescription: "Liana Banyan-a {{language}} чӗлхине куçар. {{marks}} Marks туп.",
      scopeWelcome: "Аннесем / Ĕмĕт тĕнчи",
      scopeCueCards: "Тĕп картă наборĕ",
      scopeNavigation: "Навигаци палăкĕсемпе йăнăш çырăвĕсем",
      scopeWildfire: "Wildfire Beacon Run: Ĕç тупса ил",
      claimBounty: "Ку куçару сыйлăхне тупса ил",
      baseLanguage: "Тĕп чӗлхе -- сыйлăх кирлĕ мар.",
      claimedBy: "@{{handle}} тупсă илнĕ -- тăсать.",
      marksProvisional: "{{marks}} Marks (вăхăтлăха)",
      speakFounderTitle: "Йышăну ман сасă: Мĕн тĕлĕшпе ку сăмахсем",
      speakFounderDesc: "Ку платформăра кашни çыrav сăмах тĕлĕшпе ятланнă. 26 пĕлтерĕшлĕ ят тымарĕ.",
      howBountiesWork: "Куçару сыйлăхĕсем мĕнле ĕçлеç",
      step1Title: "Сыйлăх ил",
      step1Body: "Help Wanted-тан куçару сыйлăхне уç.",
      step2Title: "Куçарпа Яр",
      step2Body: "Кирлĕ строксен кашниĕсем куçар. Bounty Poster урлă яр.",
      step3Title: "Marks туп",
      step3Body: "Хваллăна хыççăн Marks тупатăн, IP Ledger-та палăртатăн.",
      hide: "пытар",
      why: "мĕн тĕлĕшпе?",
    },
    languageSwitcher: {
      changeLanguage: "Чӗлхене улăштар",
      selectLanguage: "Чӗлхе суйла",
      quickEnglish: "Акăлчан",
      tip: "Дуринăн çурçĕрне тĕрлĕ чӗлхе пытарулăхĕпе кĕрсе уникăл тата тупса ил!",
    },
  },
  "br": {
    speakFriend: {
      title: "Lavar mignon ha mont e-barzh.",
      description: "Liana Banyan zo savet a-benn bezañ digor evit pep yezh. Pep yezh digor en deus ur priz troidigezhel.",
      languages: "yezhoù",
      openBounties: "prizioù digor",
      marksAwarded: "Marks roet (tokenn kemer-perzh)",
      provisional: "Da vare:",
      provisionalNotice: "Roll ar yezhoù hag ar prisioù Marks a zo da vare. Marks a zo tokenn kemer-perzh, ket aksionoù.",
      bountyOpen: "Priz digor",
      claimed: "Goulennet",
      complete: "Graet",
      translationBountyTitle: "Priz Troidigezhel",
      bountyDescription: "Treiñ Liana Banyan e {{language}}. Kraouiñ {{marks}} Marks.",
      scopeWelcome: "Skrinioù Degemer / Bed an Anaon",
      scopeCueCards: "Strollad kartenn skoazell diazez",
      scopeNavigation: "Tikedennoù levataet ha kemennadurioù fazi",
      scopeWildfire: "Wildfire Beacon Run: Kavout labour",
      claimBounty: "Goulenn ar Priz Troidigezhel-mañ",
      baseLanguage: "Yezh diazez -- n'eus priz ebet azgouledet.",
      claimedBy: "@{{handle}} en deus goulennet -- oc'h kenderc'hel.",
      marksProvisional: "{{marks}} Marks (da vare)",
      speakFounderTitle: "Mouezh ar Groueur: Perak ar Gerioù-mañ",
      speakFounderDesc: "Pep termen war ar bladform-mañ a zo anvet gant un abeg. Tarzh 26 anv pouezusañ.",
      howBountiesWork: "Penaos ez a Prizioù Troidigezhel",
      step1Title: "Goulenn ar Priz",
      step1Body: "Digeriñ ur Priz Troidigezhel deus ar vord Help Wanted.",
      step2Title: "Treiñ ha Kas",
      step2Body: "Treiñ an holl linestoù azgouledet. Kas dre Bounty Poster.",
      step3Title: "Kraouiñ Marks",
      step3Body: "Goude bezañ asantet, resevit Marks ha reolennet e IP Ledger.",
      hide: "kuzhat",
      why: "perak?",
    },
    languageSwitcher: {
      changeLanguage: "Cheñch yezh",
      selectLanguage: "Dibab yezh",
      quickEnglish: "Saozneg",
      tip: "Implijit ger-tremen yezhoù disheñvel e Dor Durin evit digorañ emglevioù unan ha nep!",
    },
  },
  "ve": {
    speakFriend: {
      title: "Amba muhasho, ndo dzhena.",
      description: "Liana Banyan yo vhewa u bva i vhulelwa kha luambo luṅwe na luṅwe. Luambo luṅwe na luṅwe vhu na mupfumedzano muthihi wa u shandulula.",
      languages: "luambo",
      openBounties: "mipfumedzano i vhulaho",
      marksAwarded: "Marks dzhiwa (zwishandiso zwa u dzhena)",
      provisional: "Tshifhinga:",
      provisionalNotice: "Tshedu ya luambo na mitengo ya Marks ndi ya tshifhinga. Marks zwishandiso zwa u dzhena, si manweledza.",
      bountyOpen: "Mupfumedzano wo vuliwa",
      claimed: "Zwa humbulwa",
      complete: "Zwa fhedzwa",
      translationBountyTitle: "Mupfumedzano wa U Shandulula",
      bountyDescription: "Shandulula Liana Banyan kha {{language}}. Dzhia {{marks}} Marks.",
      scopeWelcome: "Dzanga zwavhudi / Shango ya Miphefumulo",
      scopeCueCards: "Tshiseto tsha Kaḓi ya Fungo",
      scopeNavigation: "Zwidodombedzwa zwa nḓila na mafhungo a phoso",
      scopeWildfire: "Wildfire Beacon Run: Wana mushumo",
      claimBounty: "Humbula Mupfumedzano uyu wa U Shandulula",
      baseLanguage: "Luambo lwa tshiofhisi -- a si na mupfumedzano.",
      claimedBy: "@{{handle}} a humbula -- tsho khou ita.",
      marksProvisional: "{{marks}} Marks (tshifhinga)",
      speakFounderTitle: "Ipfi la Muṱanganedzi: Ndi Ngani Maipfi Aṱo",
      speakFounderDesc: "Ipfi riṅwe na riṅwe kha platform iyi riṇavha zina nga ndivho. Ḓisendeko ḽa madzina 26 a botshelo.",
      howBountiesWork: "Mipfumedzano ya U Shandulula I Shuma Hani",
      step1Title: "Humbula Mupfumedzano",
      step1Body: "Vhula Mupfumedzano wa U Shandulula kha Help Wanted.",
      step2Title: "Shandulula Ruma",
      step2Body: "Shandulula maḓagasi oṱhe. Ruma nga Bounty Poster.",
      step3Title: "Dzhia Marks",
      step3Body: "Nga murahu ha u amukela, u dzhia Marks u ṅwalwa kha IP Ledger.",
      hide: "fihla",
      why: "ndi ngani?",
    },
    languageSwitcher: {
      changeLanguage: "Shandukisa luambo",
      selectLanguage: "Nanga luambo",
      quickEnglish: "Luambo lwa English",
      tip: "Shandukisa mufinyu wa luambo lwa nnḓa kha Muḓo wa Durin u vhula zwiimo zwa tshenzhelo!",
    },
  },
  "pam": {
    speakFriend: {
      title: "Iyabika i kaluguran, at lumubus.",
      description: "Ing Liana Banyan ginagawa para magbukas para king balang amanu. Balang bukas a amanu atin yang metung a gantimpala ning salin.",
      languages: "amanu",
      openBounties: "bukas a gantimpala",
      marksAwarded: "Marks a binie (mga token ning pakiamping)",
      provisional: "Pansamantala:",
      provisionalNotice: "Ing listang amanu at mga rate ning Marks pansamantala. Ang Marks mga token ning pakiamping, e equity.",
      bountyOpen: "Bukas ing gantimpala",
      claimed: "Mig-angkon na",
      complete: "Tapos na",
      translationBountyTitle: "Gantimpala ning Salin",
      bountyDescription: "Isalin ing Liana Banyan king {{language}}. Kumita ning {{marks}} Marks.",
      scopeWelcome: "Mga screen ning Mabusing Piyabia / Ghost World",
      scopeCueCards: "Core a set ning Cue Card",
      scopeNavigation: "Mga label ning navigasyon at mensahe ning sala",
      scopeWildfire: "Wildfire Beacon Run: Mikimawa Trabaho",
      claimBounty: "I-angkon iti Gantimpala ning Salin",
      baseLanguage: "Abak a amanu -- e mengailangan gantimpala.",
      claimedBy: "Mig-angkon ni @{{handle}} -- kasalungsayan.",
      marksProvisional: "{{marks}} Marks (pansamantala)",
      speakFounderTitle: "Tinig ning Tagpamagal: Bakit Ini Deng Adwa",
      speakFounderDesc: "Balang termino iti sinabyan ya ngeni ya rason. Ugatan deng 26 mas mahalaga a ngaran.",
      howBountiesWork: "Paanu Magobra Deng Gantimpala ning Salin",
      step1Title: "I-angkon ing Gantimpala",
      step1Body: "Bukasan ing Gantimpala ning Salin ibat Help Wanted.",
      step2Title: "Isalin at Isubmit",
      step2Body: "Isalin deng lang-langauang string. Isubmit king Bounty Poster.",
      step3Title: "Kumita ng Marks",
      step3Body: "Pagka tanggap, makatanggap kang Marks at mairekord sa IP Ledger.",
      hide: "itago",
      why: "bakit?",
    },
    languageSwitcher: {
      changeLanguage: "Magbago amanu",
      selectLanguage: "Pilian amanu",
      quickEnglish: "Ingles",
      tip: "Gamitin deng iba-ibang password amanu king Pintuan ni Durin para ma-unlock deng natatanging karanasan!",
    },
  },
  "dz": {
    speakFriend: {
      title: "གྲོགས་པོ་ཟེར་ནས་ཕྱིར་ཚུར་འོང་།",
      description: "Liana Banyan ཀྱི་ཚད་ལ་སྐད་ཡིག་ཀུན་ལུ་ཁ་ཕྱེ་མི་གཞི་བཙུགས་ཡི། སྐད་ཡིག་རེ་རེར་ཞིབ་སྒྱུར་གྱི་བྱིན་སྐྱེར་ཅིག་ཡོད།",
      languages: "སྐད་ཡིག",
      openBounties: "ཁ་ཕྱེ་ཡོད་པའི་བྱིན་སྐྱེར",
      marksAwarded: "Marks སྤྲོད་ཡི་ (སྡོམ་ལེན་ཤོག་འཐེན)",
      provisional: "ཅུང་ཟད་ར་འགྱུར:",
      provisionalNotice: "སྐད་ཡིག་ཐོ་རང་ Marks ཉིན་འགག་ར་འགྱུར་ཨིནམ། Marks སྡོམ་ལེན་ཤོག་འཐེན་ཨིན།",
      bountyOpen: "བྱིན་སྐྱེར་ཁ་ཕྱེ་ཡི",
      claimed: "ཞུ་ཡི",
      complete: "གྲུབ་ཡི",
      translationBountyTitle: "ཞིབ་སྒྱུར་བྱིན་སྐྱེར",
      bountyDescription: "Liana Banyan {{language}} ལུ་ཞིབ་སྒྱུར་འབད། {{marks}} Marks འཐོབ།",
      scopeWelcome: "གཤེགས་པར་དགའ་བྱིན།",
      scopeCueCards: "ལམ་སྟོན་ཤོག་འཐེན་ཚོགས་",
      scopeNavigation: "འཁྱམས་ལམ་རྟགས་ཆུང་ཐིག་གི་ཕྲིན་",
      scopeWildfire: "Wildfire Beacon Run: ལས་ཀ་འཚོལ",
      claimBounty: "ཞིབ་སྒྱུར་བྱིན་སྐྱེར་འདི་ཞུ",
      baseLanguage: "གཞི་རྟེན་སྐད་ཡིག་ -- བྱིན་སྐྱེར་མི་དགོས།",
      claimedBy: "@{{handle}} ཞུ་ཡི་ -- མུ་མཐུད་",
      marksProvisional: "{{marks}} Marks (ར་འགྱུར)",
      speakFounderTitle: "གཞི་བཙུགས་མི་གི་སྐད་ -- ཅིའི་ཕྱིར་མིང་འདི",
      speakFounderDesc: "Liana Banyan ཀྱི་ཕྲིན་ཡིག་ཡོངས་ལ་ར་འགྱུར་མི་ཨིནམ། 26 གལ་ཆེ་མིང་།",
      howBountiesWork: "ཞིབ་སྒྱུར་བྱིན་སྐྱེར་སྒྲུབ་ཚུལ",
      step1Title: "བྱིན་སྐྱེར་ཞུ",
      step1Body: "Help Wanted ལས་ཞིབ་སྒྱུར་བྱིན་སྐྱེར་ཐིག་",
      step2Title: "ཞིབ་སྒྱུར་འབད་ཞིབ་སྤྲོད",
      step2Body: "ཚད་ལྡན་ཡིག་ཐིག་ཡོངས་ཞིབ་སྒྱུར། Bounty Poster ལས་སྤྲོད།",
      step3Title: "Marks འཐོབ",
      step3Body: "འགྲིམས་ཡི་རྗེས་ Marks འཐོབ། IP Ledger ལུ་བཀོད།",
      hide: "སྦས",
      why: "ཅིའི་ཕྱིར?",
    },
    languageSwitcher: {
      changeLanguage: "སྐད་ཡིག་བཅོས",
      selectLanguage: "སྐད་ཡིག་གདམ",
      quickEnglish: "ཨིང་སྐད",
      tip: "Durin གི་སྒོ་ལས་ཐ་མི་དད་སྐད་ཡིག་གི་གསང་ཨང་བེད་སྤྱོད་འབད།",
    },
  },
  "nr": {
    speakFriend: {
      title: "Khuluma umngani, ume ungene.",
      description: "I-Liana Banyan yakhiwe ukuvula kulimi lonke. Ulimi ngalunye olukhululekileyo lunebhizi elilodwa lokuhumusha.",
      languages: "iilwimi",
      openBounties: "amabhizi avuliweyo",
      marksAwarded: "Marks anikwe (amatokeni okuthatha inxaxheba)",
      provisional: "Okwethutyana:",
      provisionalNotice: "Uhlu lwezilwimi namazinga e-Marks okwethutyana. Marks amatokeni okuthatha inxaxheba, hayi izabelo.",
      bountyOpen: "Ibhizi livuliwe",
      claimed: "Kukhanyelwe",
      complete: "Kuphelele",
      translationBountyTitle: "Ibhizi lokuHumusha",
      bountyDescription: "Humusha i-Liana Banyan kwi-{{language}}. Fumana {{marks}} Marks.",
      scopeWelcome: "Ama-screen Wamukelekile / Ihlabathi Leemimoya",
      scopeCueCards: "Isampula se-Cue Card Esiyinhloko",
      scopeNavigation: "Izilebula zokukhomba kunye nemilayezo yamaphoswa",
      scopeWildfire: "Wildfire Beacon Run: Fumana Umsebenzi",
      claimBounty: "Khanyela le-Bhizi lokuHumusha",
      baseLanguage: "Ulwimi lwesisekelo -- akudingeki bhizi.",
      claimedBy: "@{{handle}} wakhanyela -- uyaqhubeka.",
      marksProvisional: "{{marks}} Marks (okwethutyana)",
      speakFounderTitle: "Ilizwi loMseki: Kutheni la Magama",
      speakFounderDesc: "Igama ngalinye kule platform lanikezwa ibizo ngezizathu. Imvelaphi yamagama angama-26 abalulekile.",
      howBountiesWork: "Amabhizi OkuHumusha Asebenza Njani",
      step1Title: "Khanyela Ibhizi",
      step1Body: "Vula i-Bhizi lokuHumusha kwi-Help Wanted.",
      step2Title: "Humusha bese Uthumela",
      step2Body: "Humusha zonke izichazelo ezidzingekayo. Thumela nge-Bounty Poster.",
      step3Title: "Fumana Marks",
      step3Body: "Uma samukela, uthola Marks futhi urekhodi ku-IP Ledger.",
      hide: "fihla",
      why: "kutheni?",
    },
    languageSwitcher: {
      changeLanguage: "Tshintsha ulwimi",
      selectLanguage: "Khetha ulwimi",
      quickEnglish: "IsiNgisi",
      tip: "Sebenzisa amagama aphasiwedhi ezilwimi ezahlukeneyo eMnyango kaDurin ukuvula amava amahlanu!",
    },
  },
  "gd": {
    speakFriend: {
      title: "Abair caraid, agus thig a-steach.",
      description: "Chaidh Liana Banyan a thogail gus a bhith fosgailte dha gach cànan. Tha duais eadar-theangachaidh aig gach cànan fosgailte.",
      languages: "cànanan",
      openBounties: "duaisean fosgailte",
      marksAwarded: "Marks air an toirt (comharran com-pàirt)",
      provisional: "Sealach:",
      provisionalNotice: "Tha liosta nan cànanan agus rèitean Marks sealach. Is comharran com-pàirt Marks, chan e earrannan.",
      bountyOpen: "Duais fosgailte",
      claimed: "Air iarraidh",
      complete: "Coileanta",
      translationBountyTitle: "Duais Eadar-theangachaidh",
      bountyDescription: "Eadar-theangaich Liana Banyan gu {{language}}. Coisinn {{marks}} Marks.",
      scopeWelcome: "Sgrìn Fàilte / Saoghal nan Spiorad",
      scopeCueCards: "Stòras Cairt Stiùiridh",
      scopeNavigation: "Leubailean seòladh agus teachdaireachdan mearachd",
      scopeWildfire: "Wildfire Beacon Run: Lorg obair",
      claimBounty: "Iarr an Duais Eadar-theangachaidh seo",
      baseLanguage: "Cànain bunaiteach -- chan eil feum air duais.",
      claimedBy: "Chaidh an duais iarraidh le @{{handle}} -- a' dol air adhart.",
      marksProvisional: "{{marks}} Marks (sealach)",
      speakFounderTitle: "Guth an Stèidheadair: Carson na Faclan sin",
      speakFounderDesc: "Tha gach teirm air an àrd-ùrlar seo ainmichte le adhbhar. Tùs nan 26 ainmean as cudromaiche.",
      howBountiesWork: "Mar a Dh'obraicheas Duaisean Eadar-theangachaidh",
      step1Title: "Iarr an Duais",
      step1Body: "Fosgail Duais Eadar-theangachaidh bhon bhòrd Help Wanted.",
      step2Title: "Eadar-theangaich agus Cuir a-steach",
      step2Body: "Eadar-theangaich gach sreang riatanach. Cuir a-steach tro Bounty Poster.",
      step3Title: "Coisinn Marks",
      step3Body: "Às dèidh gabhail ris, gheibh thu Marks agus thèid do chlàradh ann an IP Ledger.",
      hide: "falaich",
      why: "carson?",
    },
    languageSwitcher: {
      changeLanguage: "Atharraich cànan",
      selectLanguage: "Tagh cànan",
      quickEnglish: "Beurla",
      tip: "Cleachd faclan-faire cànanan eadar-dhealaichte aig Doras Durin gus eòlasan sònraichte a thoirt air adhart!",
    },
  },
  "kab": {
    speakFriend: {
      title: "Ini ameddakel, qqim-d.",
      description: "Liana Banyan tebna akken ad tili tamurt i yiwen wemdan kullu. Kullu tutlayt tezmer ad tawi uferdis n tisuγin.",
      languages: "tutlayin",
      openBounties: "uferdisen ifṭiṭen",
      marksAwarded: "Marks ttunefken (tiktutin n usekcem)",
      provisional: "Akka drus:",
      provisionalNotice: "Tabdart n tutlayin d lqima n Marks akka drus. Marks tiktutin n usekcem, mačči yimawlan.",
      bountyOpen: "Uferdis yettwali",
      claimed: "Yettusraga",
      complete: "Yekfa",
      translationBountyTitle: "Uferdis n Tisuγin",
      bountyDescription: "Siγel Liana Banyan γer {{language}}. Awi {{marks}} Marks.",
      scopeWelcome: "Anewway / Akal n Iruhanen",
      scopeCueCards: "Tasddart n Tkarin n Tilitit",
      scopeNavigation: "Taddart n uzriz d yizen n tεulliwin",
      scopeWildfire: "Wildfire Beacon Run: Nadi amahil",
      claimBounty: "Sraga Uferdis-a n Tisuγin",
      baseLanguage: "Tutlayt n izazen -- uferdis ur yettudarkel.",
      claimedBy: "@{{handle}} yesraga -- iruhu.",
      marksProvisional: "{{marks}} Marks (akka drus)",
      speakFounderTitle: "Asγar n Amserwes: Mel d Tiγri n Tigawt-a",
      speakFounderDesc: "Kull awal deg unekcum-agi yesεa imawlan. Anẓad n 26 n yismawen n tallit.",
      howBountiesWork: "Amek Uferdisen n Tisuγin Tteddu",
      step1Title: "Sraga Uferdis",
      step1Body: "Badu Uferdis n Tisuγin seg Help Wanted.",
      step2Title: "Siγel Unekcum",
      step2Body: "Siγel widen yettusentem. Uned Bounty Poster.",
      step3Title: "Awi Marks",
      step3Body: "Awali yekcem Marks ttwanafken IP Ledger.",
      hide: "fer",
      why: "acimi?",
    },
    languageSwitcher: {
      changeLanguage: "Snifel tutlayt",
      selectLanguage: "Fren tutlayt",
      quickEnglish: "Tanglizt",
      tip: "Seqdec tawrakin n tutlayin niḍen deg Tabburt n Durin akken ad tebdiḍ isallen ara ttwasṭen!",
    },
  },
};
