"use strict";
// tdata-c.cjs -- Machine translations Group C (languages 55-81)
// ln ny lo sq fi da no bg sk sl et lv lt ka hy ca mk be af xh st tn wo ak ee ky tg
module.exports = {
  "ln": {
    speakFriend: {
      title: "Loba moninga, mpe kota.",
      description: "Liana Banyan ezali miso ya bato nyonso. Monoko nyonso ezali na matomba moko ya kobalola.",
      languages: "minoko",
      openBounties: "matomba ya peli",
      marksAwarded: "Marks epesami (tokens ya kozanga)",
      provisional: "Sima na:",
      provisionalNotice: "Liste ya minoko mpe misure ya Marks ezali ya sima na. Marks ezali tokens ya kozanga, te aksi.",
      bountyOpen: "Matomba ya peli",
      claimed: "Babongi",
      complete: "Ekosi",
      translationBountyTitle: "Matomba ya Kobalola",
      bountyDescription: "Balola Liana Banyan na {{language}}. Zwa {{marks}} Marks.",
      scopeWelcome: "Mikanda ya Boyei bino / Mokili ya Mizimu",
      scopeCueCards: "Ensemble ya Makabu ya Toli",
      scopeNavigation: "Malembo ya nzela mpe mitindo ya mabuta",
      scopeWildfire: "Wildfire Beacon Run: Zwa Mosala",
      claimBounty: "Bonga Matomba oyo ya Kobalola",
      baseLanguage: "Monoko ya ebandeli -- matomba esengami te.",
      claimedBy: "@{{handle}} abongi -- ekosala.",
      marksProvisional: "{{marks}} Marks (sima na)",
      speakFounderTitle: "Liloba ya Motandisi: Mpo na Nini Maloba Oyo",
      speakFounderDesc: "Liloba nyonso na eteni oyo ezwi nkombo na ntina. Ebandeli ya nkombo 26 ya ntina.",
      howBountiesWork: "Matomba ya Kobalola Esalaka Ndenge Nini",
      step1Title: "Bonga Matomba",
      step1Body: "Fungola Matomba ya Kobalola na Help Wanted.",
      step2Title: "Balola mpe Tinda",
      step2Body: "Balola misinga nyonso. Tinda na Bounty Poster.",
      step3Title: "Zwa Marks",
      step3Body: "Sima na kobondelema, ozwi Marks mpe ozalisi na IP Ledger.",
      hide: "planque",
      why: "mpo na nini?",
    },
    languageSwitcher: {
      changeLanguage: "Suka monoko",
      selectLanguage: "Pona monoko",
      quickEnglish: "Lingala ya Angele",
      tip: "Zala na mots de passe ya minoko ndenge na ndenge na Porte ya Durin!",
    },
  },
  "ny": {
    speakFriend: {
      title: "Nena bwenzi, ndipo ulowe.",
      description: "Liana Banyan yamezengedwa kuti isungunuke pa chilankhulo chilichonse. Chilankhulo chilichonse chili ndi mphoto imodzi ya kumasulira.",
      languages: "zilankhulo",
      openBounties: "mphoto zotsegulika",
      marksAwarded: "Marks zapatsidwa (ma token a kutenga nawo gawo)",
      provisional: "Kwa nthawi ino:",
      provisionalNotice: "Mndandanda wa zilankhulo ndi mitengo ya Marks ndi ya kwa nthawi ino. Marks ndi ma token a kutenga nawo gawo, osati udziwe.",
      bountyOpen: "Mphoto yatsegulidwa",
      claimed: "Yafunsidwa",
      complete: "Yakwanira",
      translationBountyTitle: "Mphoto ya Kumasulira",
      bountyDescription: "Masulira Liana Banyan mu {{language}}. Peza {{marks}} Marks.",
      scopeWelcome: "Zosakira Moni / Dziko la Mizimu",
      scopeCueCards: "Gulu la Kadi za Malangizo Oyamba",
      scopeNavigation: "Zizindikiro za njira ndi mauthenga olakwika",
      scopeWildfire: "Wildfire Beacon Run: Peza Ntchito",
      claimBounty: "Funsani Mphoto iyi ya Kumasulira",
      baseLanguage: "Chilankhulo chachikulu -- palibe mphoto yofunika.",
      claimedBy: "@{{handle}} wafunsa -- ikupitilira.",
      marksProvisional: "{{marks}} Marks (kwa nthawi ino)",
      speakFounderTitle: "Mawu a Woyambitsa: Chifukwa Cha Mawu Awa",
      speakFounderDesc: "Mawu aliyense pa platform iyi atumikiridwa ndi chifukwa. Chiyambi cha mayina 26 ofunika kwambiri.",
      howBountiesWork: "Mphoto za Kumasulira Zimayendera Bwanji",
      step1Title: "Funsani Mphoto",
      step1Body: "Tsegurani Mphoto ya Kumasulira kuchokera pa Help Wanted.",
      step2Title: "Masulira ndi Tumiza",
      step2Body: "Masulira misintho yonse yofunika. Tumizani kudzera mu Bounty Poster.",
      step3Title: "Peza Marks",
      step3Body: "Atangowona, mudzalandira Marks ndipo mudzalembedwa mu IP Ledger.",
      hide: "bisa",
      why: "chifukwa chiyani?",
    },
    languageSwitcher: {
      changeLanguage: "Sinthani chilankhulo",
      selectLanguage: "Sankhani chilankhulo",
      quickEnglish: "Chingerezi",
      tip: "Gwiritsani ntchito mawu achinsinsi a zilankhulo zosiyanasiyana pa Chitseko cha Durin kuti mutsegule zinthu zapadera!",
    },
  },
  "lo": {
    speakFriend: {
      title: "ເວົ້າເຈົ້າຫມູ່, ແລ້ວເຂົ້າມາ.",
      description: "Liana Banyan ສ້າງຂຶ້ນເພື່ອເປີດໃຫ້ທຸກພາສາ. ແຕ່ລະພາສາທີ່ເປີດມີລາງວັນການແປໜຶ່ງ.",
      languages: "ພາສາ",
      openBounties: "ລາງວັນທີ່ເປີດ",
      marksAwarded: "Marks ໄດ້ຮັບ (ໂທເຄັນການມີສ່ວນຮ່ວມ)",
      provisional: "ຊົ່ວຄາວ:",
      provisionalNotice: "ລາຍຊື່ພາສາ ແລະ ອັດຕາ Marks ເປັນຊົ່ວຄາວ. Marks ເປັນໂທເຄັນການມີສ່ວນຮ່ວມ, ບໍ່ແມ່ນຫຸ້ນ.",
      bountyOpen: "ລາງວັນເປີດ",
      claimed: "ຮຽກຮ້ອງແລ້ວ",
      complete: "ສຳເລັດ",
      translationBountyTitle: "ລາງວັນການແປ",
      bountyDescription: "ແປ Liana Banyan ເປັນ {{language}}. ຮັບ {{marks}} Marks.",
      scopeWelcome: "ໜ້າຕ້ອນຮັບ / ໂລກວິນຍານ",
      scopeCueCards: "ຊຸດບັດຄຳແນະນຳຫຼັກ",
      scopeNavigation: "ປ້າຍນຳທາງ ແລະ ຂໍ້ຄວາມຜິດພາດ",
      scopeWildfire: "Wildfire Beacon Run: ຫາວຽກ",
      claimBounty: "ຮຽກຮ້ອງລາງວັນການແປນີ້",
      baseLanguage: "ພາສາພື້ນຖານ -- ບໍ່ຕ້ອງການລາງວັນ.",
      claimedBy: "@{{handle}} ຮຽກຮ້ອງ -- ກຳລັງດຳເນີນ.",
      marksProvisional: "{{marks}} Marks (ຊົ່ວຄາວ)",
      speakFounderTitle: "ສຽງຜູ້ກໍ່ຕັ້ງ: ເປັນຫຍັງຄຳເຫຼົ່ານີ້",
      speakFounderDesc: "ທຸກຄຳໃນເວທີນີ້ຖືກຕັ້ງຊື່ດ້ວຍເຫດຜົນ. ຕົ້ນກຳເນີດຂອງ 26 ຊື່ສຳຄັນທີ່ສຸດ.",
      howBountiesWork: "ລາງວັນການແປເຮັດວຽກແນວໃດ",
      step1Title: "ຮຽກຮ້ອງລາງວັນ",
      step1Body: "ເປີດລາງວັນການແປຈາກກະດານ Help Wanted.",
      step2Title: "ແປ ແລະ ສົ່ງ",
      step2Body: "ແປສະຕຣິງທີ່ຕ້ອງການທັງໝົດ. ສົ່ງຜ່ານ Bounty Poster.",
      step3Title: "ຮັບ Marks",
      step3Body: "ເມື່ອຮັບຮອງ, ທ່ານໄດ້ Marks ແລະ ຖືກບັນທຶກໃນ IP Ledger.",
      hide: "ເຊົ້າ",
      why: "ເປັນຫຍັງ?",
    },
    languageSwitcher: {
      changeLanguage: "ປ່ຽນພາສາ",
      selectLanguage: "ເລືອກພາສາ",
      quickEnglish: "ພາສາອັງກິດ",
      tip: "ໃຊ້ລະຫັດຜ່ານພາສາຕ່າງໆທີ່ປະຕູ Durin ເພື່ອປົດລ໊ອກປະສົບການທີ່ພິເສດ!",
    },
  },
  "sq": {
    speakFriend: {
      title: "Thuaj mik dhe hyr.",
      description: "Liana Banyan eshte ndertuar per te qene e hapur per cdo gjuhe. Cdo gjuhe e hapur ka nje shenperblim perkthimi.",
      languages: "gjuhe",
      openBounties: "shenperblime te hapura",
      marksAwarded: "Marks u dha (shenja pjesemarrjeje)",
      provisional: "Perkohesisht:",
      provisionalNotice: "Lista e gjuheve dhe normat e Marks jane perkohesisht. Marks jane shenja pjesemarrjeje, jo aksione.",
      bountyOpen: "Shenperblimi i hapur",
      claimed: "U kerkua",
      complete: "Perfunduar",
      translationBountyTitle: "Shenperblim Perkthimi",
      bountyDescription: "Perktheni Liana Banyan ne {{language}}. Fitoni {{marks}} Marks.",
      scopeWelcome: "Ekranet e Mireseardhjes / Bota e Fantazmave",
      scopeCueCards: "Seti Baze i Kartave te Sugjerimeve",
      scopeNavigation: "Etiketa navigimi dhe mesazhe gabimesh",
      scopeWildfire: "Wildfire Beacon Run: Gjeni Pune",
      claimBounty: "Kerkoni kete Shenperblim Perkthimi",
      baseLanguage: "Gjuha baze -- nuk nevojitet shenperblim.",
      claimedBy: "@{{handle}} kerkoi -- ne proces.",
      marksProvisional: "{{marks}} Marks (perkohesisht)",
      speakFounderTitle: "Zeri i Themeluesit: Pse Keto Fjale",
      speakFounderDesc: "Cdo term ne kete platforme eshte emertuar me arsye. Origjina e 26 emrave me te rendesishem.",
      howBountiesWork: "Si Funksionojne Shenperblime Perkthimi",
      step1Title: "Kerkoni Shenperblimin",
      step1Body: "Hapni nje Shenperblim Perkthimi nga Help Wanted.",
      step2Title: "Perktheni dhe Dergoni",
      step2Body: "Perktheni te gjitha vargjet e nevojshme. Dergoni nepermjet Bounty Poster.",
      step3Title: "Fitoni Marks",
      step3Body: "Pas pranimit, merrni Marks dhe regjistroheni ne IP Ledger.",
      hide: "fshih",
      why: "pse?",
    },
    languageSwitcher: {
      changeLanguage: "Ndrro gjuhen",
      selectLanguage: "Zgjidhni gjuhen",
      quickEnglish: "Anglisht",
      tip: "Perdorni fjalekalime te gjuheve te ndryshme ne Dyert e Durinit per te shkyequr pervoja unike!",
    },
  },
  "fi": {
    speakFriend: {
      title: "Sano ystava ja astu sisaan.",
      description: "Liana Banyan on rakennettu avoimeksi jokaiselle kielelle. Jokaisella avoimella kielella on yksi kaannospalkinto.",
      languages: "kielet",
      openBounties: "avoimet palkinnot",
      marksAwarded: "Marks myonnetty (osallistumistokenit)",
      provisional: "Valiaikaisesti:",
      provisionalNotice: "Kielilista ja Marks-hinnat ovat valiaikaisesti. Marks ovat osallistumistokeneita, ei osakkeita.",
      bountyOpen: "Palkinto avoinna",
      claimed: "Vaadittu",
      complete: "Valmis",
      translationBountyTitle: "Kaannospalkinto",
      bountyDescription: "Kaanna Liana Banyan kielelle {{language}}. Ansaitse {{marks}} Marks hyvaksymisen jalkeen.",
      scopeWelcome: "Tervetuloa / Haamumaailma naytot",
      scopeCueCards: "Perus Vinkki-korttisetti",
      scopeNavigation: "Navigointimerkinnot ja virheilmoitukset",
      scopeWildfire: "Wildfire Beacon Run: Loyda tyo",
      claimBounty: "Vaadi tata Kaannosmerkintaa",
      baseLanguage: "Peruskieli -- ei palkintoa tarvita.",
      claimedBy: "@{{handle}} vaati -- kaynnissa.",
      marksProvisional: "{{marks}} Marks (valiaikaisesti)",
      speakFounderTitle: "Perustajan aani: Miksi Nama Sanat",
      speakFounderDesc: "Jokainen termi talla alustalla on nimetty syyta varten. 26 tarkeimman nimen alkupera.",
      howBountiesWork: "Kuinka Kaannospalkinnot Toimivat",
      step1Title: "Vaadi Palkinto",
      step1Body: "Avaa Kaannospalkinto Help Wanted -taulusta.",
      step2Title: "Kaanna ja Laheta",
      step2Body: "Kaanna kaikki tarvittavat merkkijonot. Laheta Bounty Poster -prosessin kautta.",
      step3Title: "Ansaitse Marks",
      step3Body: "Hyvaksymisen jalkeen saat Marks ja kirjataan IP Ledger -rekisteriin.",
      hide: "piilota",
      why: "miksi?",
    },
    languageSwitcher: {
      changeLanguage: "Vaihda kielta",
      selectLanguage: "Valitse kieli",
      quickEnglish: "Englanti",
      tip: "Kayta eri kielten salasanoja Durinin portilla avataksesi ainutlaatuisia kokemuksia!",
    },
  },
  "da": {
    speakFriend: {
      title: "Sig ven, og gaa ind.",
      description: "Liana Banyan er bygget til at vaere aaben for hvert sprog. Hvert aabent sprog har een oversaettelsespraemie.",
      languages: "sprog",
      openBounties: "aabne praemier",
      marksAwarded: "Marks tildelt (deltagelsestokens)",
      provisional: "Midlertidigt:",
      provisionalNotice: "Sprogsliste og Marks-satser er midlertidige. Marks er deltagelsestokens, ikke aktier.",
      bountyOpen: "Praemie aaben",
      claimed: "Kraevet",
      complete: "Fuldfoert",
      translationBountyTitle: "Oversaettelsespraemie",
      bountyDescription: "Overs. Liana Banyan til {{language}}. Optjen {{marks}} Marks ved godkendelse.",
      scopeWelcome: "Velkomst / Spoegelsesverden skaerme",
      scopeCueCards: "Grundlaeggende Cue-kortsaet",
      scopeNavigation: "Navigationsmaerker og fejlmeddelelser",
      scopeWildfire: "Wildfire Beacon Run: Find arbejde",
      claimBounty: "Kraev denne Oversaettelsespraemie",
      baseLanguage: "Grundsprog -- ingen praemie noedvendig.",
      claimedBy: "@{{handle}} kraevede -- igangvaerende.",
      marksProvisional: "{{marks}} Marks (midlertidigt)",
      speakFounderTitle: "Grundlaeggerens stemme: Hvorfor disse ord",
      speakFounderDesc: "Hvert udtryk pa denne platform er navngivet med en grund. Oprindlesen af de 26 vigtigste navne.",
      howBountiesWork: "Saadan fungerer Oversaettelsespraemier",
      step1Title: "Kraev Praemien",
      step1Body: "Aaben en Oversaettelsespraemie fra Help Wanted-opslaget.",
      step2Title: "Overs. og indsend",
      step2Body: "Overs. alle noedvendige strenge. Indsend via Bounty Poster.",
      step3Title: "Optjen Marks",
      step3Body: "Efter godkendelse faar du Marks og registreres i IP Ledger.",
      hide: "skjul",
      why: "hvorfor?",
    },
    languageSwitcher: {
      changeLanguage: "Skift sprog",
      selectLanguage: "Vaelg sprog",
      quickEnglish: "Engelsk",
      tip: "Brug adgangskoder paa forskellige sprog ved Durins Dor for at laase op for unikke oplevelser!",
    },
  },
  "no": {
    speakFriend: {
      title: "Si venn, og gaa inn.",
      description: "Liana Banyan er bygget for aa vaere aapen for hvert spraak. Hvert aapent spraak har en oversettelsespremie.",
      languages: "spraak",
      openBounties: "aapne premier",
      marksAwarded: "Marks tildelt (deltakelsestokens)",
      provisional: "Midlertidig:",
      provisionalNotice: "Spraaksliste og Marks-satser er midlertidige. Marks er deltakelsestokens, ikke aksjer.",
      bountyOpen: "Premier aapen",
      claimed: "Krevd",
      complete: "Fullfort",
      translationBountyTitle: "Oversettelsespremie",
      bountyDescription: "Oversett Liana Banyan til {{language}}. Tjen {{marks}} Marks ved godkjenning.",
      scopeWelcome: "Velkomst / Spøkelsesverden skjermer",
      scopeCueCards: "Grunnleggende Cue-kortsett",
      scopeNavigation: "Navigasjonsmerker og feilmeldinger",
      scopeWildfire: "Wildfire Beacon Run: Finn jobb",
      claimBounty: "Krev denne Oversettelsespremien",
      baseLanguage: "Grunnspraak -- ingen premier noedvendig.",
      claimedBy: "@{{handle}} krevde -- paagaar.",
      marksProvisional: "{{marks}} Marks (midlertidig)",
      speakFounderTitle: "Grunnleggerens stemme: Hvorfor disse ordene",
      speakFounderDesc: "Hvert uttrykk paa denne plattformen er navngitt med en grunn. Opprinnelsen til de 26 viktigste navnene.",
      howBountiesWork: "Slik fungerer Oversettelsespremier",
      step1Title: "Krev Premien",
      step1Body: "Aapne en Oversettelsespremie fra Help Wanted-tavlen.",
      step2Title: "Oversett og send inn",
      step2Body: "Oversett alle noedvendige strenger. Send inn via Bounty Poster.",
      step3Title: "Tjen Marks",
      step3Body: "Etter godkjenning faar du Marks og registreres i IP Ledger.",
      hide: "skjul",
      why: "hvorfor?",
    },
    languageSwitcher: {
      changeLanguage: "Bytt spraak",
      selectLanguage: "Velg spraak",
      quickEnglish: "Engelsk",
      tip: "Bruk passord paa ulike spraak ved Durins Dor for aa laase opp unike opplevelser!",
    },
  },
  "bg": {
    speakFriend: {
      title: "Кажи приятел и влез.",
      description: "Liana Banyan е изградена да бъде отворена за всеки език. Всеки отворен език има една награда за превод.",
      languages: "езици",
      openBounties: "отворени награди",
      marksAwarded: "Marks присъдени (токени за участие)",
      provisional: "Временно:",
      provisionalNotice: "Списъкът с езици и ставките Marks са временни. Marks са токени за участие, не акции.",
      bountyOpen: "Наградата е отворена",
      claimed: "Поискано",
      complete: "Завършено",
      translationBountyTitle: "Награда за Превод",
      bountyDescription: "Преведете Liana Banyan на {{language}}. Спечелете {{marks}} Marks.",
      scopeWelcome: "Екрани Добре дошли / Свят на духовете",
      scopeCueCards: "Основен набор от карти с подсказки",
      scopeNavigation: "Навигационни етикети и съобщения за грешки",
      scopeWildfire: "Wildfire Beacon Run: Намери работа",
      claimBounty: "Поискайте тази Награда за Превод",
      baseLanguage: "Основен език -- не е нужна награда.",
      claimedBy: "Наградата е поискана от @{{handle}} -- в ход.",
      marksProvisional: "{{marks}} Marks (временно)",
      speakFounderTitle: "Гласът на Основателя: Защо Тези Думи",
      speakFounderDesc: "Всеки термин на тази платформа е наименован с причина. Произходът на 26-те най-важни имена.",
      howBountiesWork: "Как Работят Наградите за Превод",
      step1Title: "Поискайте Наградата",
      step1Body: "Отворете Награда за Превод от таблото Help Wanted.",
      step2Title: "Преведете и Изпратете",
      step2Body: "Преведете всички необходими низове. Изпратете чрез Bounty Poster.",
      step3Title: "Спечелете Marks",
      step3Body: "След приемане получавате Marks и сте записани в IP Ledger.",
      hide: "скрий",
      why: "защо?",
    },
    languageSwitcher: {
      changeLanguage: "Смени езика",
      selectLanguage: "Избери език",
      quickEnglish: "Английски",
      tip: "Използвайте пароли на различни езици на Вратата на Дурин за уникални преживявания!",
    },
  },
  "sk": {
    speakFriend: {
      title: "Poved priatel a vstup.",
      description: "Liana Banyan je postavena otvorene pre kazdy jazyk. Kazdy otvoreny jazyk ma jednu prekladatelsku odmenu.",
      languages: "jazyky",
      openBounties: "otvorene odmeny",
      marksAwarded: "Marks udelene (tokeny ucasti)",
      provisional: "Docasne:",
      provisionalNotice: "Zoznam jazykov a sadzby Marks su docasne. Marks su tokeny ucasti, nie akcie.",
      bountyOpen: "Odmena otvorena",
      claimed: "Narokovana",
      complete: "Dokoncene",
      translationBountyTitle: "Prekladatelska Odmena",
      bountyDescription: "Prelozit Liana Banyan do {{language}}. Ziskat {{marks}} Marks po akceptacii.",
      scopeWelcome: "Obrazovky Vitajte / Svet Duchov",
      scopeCueCards: "Zakladna sada Karet Napovedy",
      scopeNavigation: "Navigacne stitky a chybove spravy",
      scopeWildfire: "Wildfire Beacon Run: Najdi pracu",
      claimBounty: "Narokovat tuto Prekladatelsku Odmenu",
      baseLanguage: "Zakladny jazyk -- odmena nie je potrebna.",
      claimedBy: "Odmena narokovana @{{handle}} -- prebieha.",
      marksProvisional: "{{marks}} Marks (docasne)",
      speakFounderTitle: "Hlas Zakladatela: Preco Tieto Slova",
      speakFounderDesc: "Kazdy pojem na tejto platforme je pomenuvany z dovodu. Povod 26 najdolezitejsich mien.",
      howBountiesWork: "Ako Funguju Prekladatelske Odmeny",
      step1Title: "Narokovat Odmenu",
      step1Body: "Otvorit Prekladatelsku Odmenu z nastenky Help Wanted.",
      step2Title: "Prelozit a Odoslat",
      step2Body: "Prelozit vsetky potrebne retazce. Odoslat prostrednictvom Bounty Poster.",
      step3Title: "Ziskat Marks",
      step3Body: "Po akceptacii dostanete Marks a ste zaznamenani v IP Ledger.",
      hide: "skryt",
      why: "preco?",
    },
    languageSwitcher: {
      changeLanguage: "Zmenit jazyk",
      selectLanguage: "Vybrat jazyk",
      quickEnglish: "Anglictina",
      tip: "Pouzite rozne jazykove hesla u Durinovych dveri na odomknutie jedinecnych zazitkov!",
    },
  },
  "sl": {
    speakFriend: {
      title: "Reci prijatelj in vstopi.",
      description: "Liana Banyan je zgrajena, da bo odprta za vsak jezik. Vsak odprt jezik ima eno nagrado za prevod.",
      languages: "jeziki",
      openBounties: "odprte nagrade",
      marksAwarded: "Marks dodeljeni (zdruzki za udelezbo)",
      provisional: "Zacasno:",
      provisionalNotice: "Seznam jezikov in stopnje Marks so zacasni. Marks so zdruzki za udelezbo, ne delnice.",
      bountyOpen: "Nagrada odprta",
      claimed: "Zahtevano",
      complete: "Dokoncano",
      translationBountyTitle: "Nagrada za Prevod",
      bountyDescription: "Prevedite Liana Banyan v {{language}}. Zasluzite {{marks}} Marks.",
      scopeWelcome: "Zasloni Dobrodosli / Svet Duhov",
      scopeCueCards: "Osnovna sestava Karte namigov",
      scopeNavigation: "Navigacijske oznake in sporocila o napakah",
      scopeWildfire: "Wildfire Beacon Run: Najdi Sluzbeno Mesto",
      claimBounty: "Zahtevajte to Nagrado za Prevod",
      baseLanguage: "Osnoven jezik -- nagrada ni potrebna.",
      claimedBy: "Nagrado zahteval @{{handle}} -- v teku.",
      marksProvisional: "{{marks}} Marks (zacasno)",
      speakFounderTitle: "Glas Ustanovitelja: Zakaj Te Besede",
      speakFounderDesc: "Vsak izraz na tej platformi je poimenovan z razlogom. Izvor 26 najpomembnejsih imen.",
      howBountiesWork: "Kako Delujejo Nagrade za Prevod",
      step1Title: "Zahtevajte Nagrado",
      step1Body: "Odprite Nagrado za Prevod z oglasne plosce Help Wanted.",
      step2Title: "Prevedite in Posljite",
      step2Body: "Prevedite vse potrebne nize. Posljite prek Bounty Poster.",
      step3Title: "Zasluzite Marks",
      step3Body: "Po sprejemu prejmete Marks in ste evidentirani v IP Ledger.",
      hide: "skrij",
      why: "zakaj?",
    },
    languageSwitcher: {
      changeLanguage: "Sprememba jezika",
      selectLanguage: "Izberite jezik",
      quickEnglish: "Anglescina",
      tip: "Uporabite gesla razlicnih jezikov pri Durinovih Vratih za edinstvene izkusnje!",
    },
  },
  "et": {
    speakFriend: {
      title: "Utle song ja mine sisse.",
      description: "Liana Banyan on ehitatud igale keelele avatud olemiseks. Igal avatud keelel on uks toelgitsemise auhinnd.",
      languages: "keeled",
      openBounties: "avatud auhinnad",
      marksAwarded: "Marks antud (osaluszetoonid)",
      provisional: "Ajutiselt:",
      provisionalNotice: "Keelte nimekiri ja Marks-maarad on ajutised. Marks on osaluszetoonid, mitte aktsiad.",
      bountyOpen: "Auhind avatud",
      claimed: "Noudutud",
      complete: "Loetud",
      translationBountyTitle: "Tolkimisauhind",
      bountyDescription: "Tolkige Liana Banyan keeles {{language}}. Teenige {{marks}} Marks kinnitamisel.",
      scopeWelcome: "Tere tulemast / Vaimude Maailm ekraanid",
      scopeCueCards: "Pohiline vihjekaartkomplekt",
      scopeNavigation: "Navigatsiooni silte ja veateated",
      scopeWildfire: "Wildfire Beacon Run: Leia too",
      claimBounty: "Noudke seda Tolkimisauhinda",
      baseLanguage: "Pohikeel -- auhind pole vajalik.",
      claimedBy: "@{{handle}} noudis -- kestab.",
      marksProvisional: "{{marks}} Marks (ajutiselt)",
      speakFounderTitle: "Asutaja haal: Miks Need Sonad",
      speakFounderDesc: "Iga termin sellel platvormil on nimetatud pohjendusel. 26 tahtsaima nime pariolu.",
      howBountiesWork: "Kuidas Tolkimisauhinnad Tootavad",
      step1Title: "Noudke Auhinda",
      step1Body: "Avage Tolkimisauhind Help Wanted tahvlilt.",
      step2Title: "Tolkige ja Saatke",
      step2Body: "Tolkige koik vajalikud stringid. Saatke Bounty Poster kaudu.",
      step3Title: "Teenige Marks",
      step3Body: "Kinnitamise jargselt saate Marks ja kantakse IP Ledgerisse.",
      hide: "peida",
      why: "miks?",
    },
    languageSwitcher: {
      changeLanguage: "Muuda keelt",
      selectLanguage: "Vali keel",
      quickEnglish: "Inglise",
      tip: "Kasutage erinevate keelte paroole Durini Ukse juures ainulaadsete kogemuste avamiseks!",
    },
  },
  "lv": {
    speakFriend: {
      title: "Saki draugs un ieej.",
      description: "Liana Banyan ir uzbuves ta, lai buts atklata katrai valodai. Katrai atklatajai valodai ir viena tulkosanas balva.",
      languages: "valodas",
      openBounties: "atverts balvas",
      marksAwarded: "Marks pieskirti (dalibas zimes)",
      provisional: "Pagaidu:",
      provisionalNotice: "Valodu saraksts un Marks liktnes ir pagaidu. Marks ir dalibas zimes, ne akcijas.",
      bountyOpen: "Balva atverta",
      claimed: "Pieprasita",
      complete: "Pabeigts",
      translationBountyTitle: "Tulkosanas Balva",
      bountyDescription: "Tulkojiet Liana Banyan {{language}} valoda. Nopelniet {{marks}} Marks.",
      scopeWelcome: "Laipni lugts / Spooku Pasaule ekrani",
      scopeCueCards: "Pamata Padomu Karti komplekts",
      scopeNavigation: "Navigacijas etiketju un kludu zinojumi",
      scopeWildfire: "Wildfire Beacon Run: Atrod darbu",
      claimBounty: "Pieprasit so Tulkosanas Balvu",
      baseLanguage: "Pamata valoda -- balva nav nepieciesama.",
      claimedBy: "@{{handle}} pieprasija -- turpinas.",
      marksProvisional: "{{marks}} Marks (pagaidu)",
      speakFounderTitle: "Dibildinatajs Balss: Kapec Sie Vardi",
      speakFounderDesc: "Katrs termins saja platforma ir nosaukts ar iemeslu. 26 svarigako nosaukumu izcelsme.",
      howBountiesWork: "Ka Darbojas Tulkosanas Balvas",
      step1Title: "Pieprasit Balvu",
      step1Body: "Atverit Tulkosanas Balvu no Help Wanted.",
      step2Title: "Tulkot un Nosutit",
      step2Body: "Tulkojiet visas nepieciesamas virknes. Nosutiet caur Bounty Poster.",
      step3Title: "Nopelnit Marks",
      step3Body: "Pec apstiprinasanas sanemat Marks un tiekat reginstreti IP Ledger.",
      hide: "paslept",
      why: "kapec?",
    },
    languageSwitcher: {
      changeLanguage: "Maint valodu",
      selectLanguage: "Izvelaties valodu",
      quickEnglish: "Anglu",
      tip: "Izmantojiet dazadu valodu paroles Durins Durvim, lai atblokets unikalas pieredzes!",
    },
  },
  "lt": {
    speakFriend: {
      title: "Pasakyk draugas ir eik vidun.",
      description: "Liana Banyan sukurta buti atvirais kiekvienai kalbai. Kiekviena atvira kalba turi viena vertimo premija.",
      languages: "kalbos",
      openBounties: "atviros premijos",
      marksAwarded: "Marks priskirti (dalyvavimo zetonai)",
      provisional: "Laikinai:",
      provisionalNotice: "Kalbu sarasas ir Marks normos laikinos. Marks yra dalyvavimo zetonai, ne akcijos.",
      bountyOpen: "Premija atidaryta",
      claimed: "Pareikalauta",
      complete: "Baigta",
      translationBountyTitle: "Vertimo Premija",
      bountyDescription: "Isverskite Liana Banyan i {{language}}. Uzdirbkite {{marks}} Marks.",
      scopeWelcome: "Sveikiname / Vaiduokliu Pasaulio ekranai",
      scopeCueCards: "Pagrindinis Pataarimu Korteliu rinkinys",
      scopeNavigation: "Navigacijos etiketiu ir klaidu pranesimai",
      scopeWildfire: "Wildfire Beacon Run: Rask darba",
      claimBounty: "Pareikalaukite sios Vertimo Premijos",
      baseLanguage: "Pagrindine kalba -- premija nereikalinga.",
      claimedBy: "@{{handle}} pareikalavo -- vyksta.",
      marksProvisional: "{{marks}} Marks (laikinai)",
      speakFounderTitle: "Istegejos balsas: Kodel Sie Zodziai",
      speakFounderDesc: "Kiekvienas terminas sioje platformoje pavadintas priezastimi. 26 svarbiausiu pavadinimu kilme.",
      howBountiesWork: "Kaip Veikia Vertimo Premijos",
      step1Title: "Pareikalaukite Premijos",
      step1Body: "Atidarykite Vertimo Premija is Help Wanted lentes.",
      step2Title: "Isverskite ir Issiuskite",
      step2Body: "Isverskite visas reikalingas eilutes. Siuskite per Bounty Poster.",
      step3Title: "Uzdirbkite Marks",
      step3Body: "Priemimo metu gausite Marks ir bute registruojami IP Ledger.",
      hide: "slept",
      why: "kodel?",
    },
    languageSwitcher: {
      changeLanguage: "Keisti kalba",
      selectLanguage: "Pasirinkite kalba",
      quickEnglish: "Anglu",
      tip: "Naudokite skirtingu kalbu slaptazodzius prie Durino Vartu, kad atrakintumete unikalias patirtis!",
    },
  },
  "ka": {
    speakFriend: {
      title: "თქვი მეგობარი და შედი.",
      description: "Liana Banyan აგებულია ყველა ენისთვის ღია. ყოველ ღია ენას ერთი თარგმანის ჯილდო აქვს.",
      languages: "ენები",
      openBounties: "ღია ჯილდოები",
      marksAwarded: "Marks მიენიჭა (მონაწილეობის ჟეტონები)",
      provisional: "დროებით:",
      provisionalNotice: "ენების სია და Marks-ის განაკვეთები დროებითია. Marks არის მონაწილეობის ჟეტონები, არა აქციები.",
      bountyOpen: "ჯილდო ღია",
      claimed: "მოთხოვნილია",
      complete: "დასრულებულია",
      translationBountyTitle: "თარგმანის ჯილდო",
      bountyDescription: "თარგმნეთ Liana Banyan {{language}} ენაზე. გამოიმუშავეთ {{marks}} Marks.",
      scopeWelcome: "კეთილი მობრძანდეთ / მოჩვენებების სამყარო",
      scopeCueCards: "ძირითადი სასწავლო ბარათების კომპლექტი",
      scopeNavigation: "ნავიგაციის ეტიკეტები და შეცდომის შეტყობინებები",
      scopeWildfire: "Wildfire Beacon Run: სამსახური გაიდე",
      claimBounty: "მოითხოვეთ ეს თარგმანის ჯილდო",
      baseLanguage: "ძირითადი ენა -- ჯილდო არ სჭირდება.",
      claimedBy: "@{{handle}} მოითხოვა -- მიმდინარეობს.",
      marksProvisional: "{{marks}} Marks (დროებით)",
      speakFounderTitle: "დამფუძნებლის ხმა: ეს სიტყვები რატომ",
      speakFounderDesc: "ამ პლატფორმაზე ყოველ სიტყვას მიზეზი აქვს. 26 მნიშვნელოვანი სახელის წარმოშობა.",
      howBountiesWork: "როგორ მუშაობს თარგმანის ჯილდოები",
      step1Title: "ჯილდო მოითხოვეთ",
      step1Body: "Help Wanted-დან თარგმანის ჯილდო გახსენით.",
      step2Title: "თარგმნეთ და გამოაგზავნეთ",
      step2Body: "ყველა საჭირო სტრინგი თარგმნეთ. Bounty Poster-ის მეშვეობით გამოაგზავნეთ.",
      step3Title: "Marks გამოიმუშავეთ",
      step3Body: "მიღების შემდეგ Marks მიიღებთ. IP Ledger-ში დარეგისტრირდებით.",
      hide: "დამალვა",
      why: "რატომ?",
    },
    languageSwitcher: {
      changeLanguage: "ენის შეცვლა",
      selectLanguage: "ენის არჩევა",
      quickEnglish: "ინგლისური",
      tip: "Durin's Door-ზე სხვადასხვა ენის პაროლები გამოიყენეთ განსაკუთრებული გამოცდილებისთვის!",
    },
  },
  "hy": {
    speakFriend: {
      title: "Ases bnger, ev mti.",
      description: "Liana Banyan-y karrucvel e bac linel bolor lezvneri hamar. Amorustyun lezu unes mi targmanutyun mtakatrutun.",
      languages: "lezuner",
      openBounties: "bac mtakatrutunner",
      marksAwarded: "Marks shetvel en (mijnord zhetoner)",
      provisional: "Zhamamanak:",
      provisionalNotice: "Lezvneri cankik ev Marks-i drusherevnern en zhamanakavor. Marks mijnord zhetoner en, ayl stock chi.",
      bountyOpen: "Mtakatrutun bac e",
      claimed: "Pahanjvec",
      complete: "Avartvel e",
      translationBountyTitle: "Targmanutyun Mtakatrutun",
      bountyDescription: "Targmanecek Liana Banyan-y {{language}} lezvov. Kcerkek {{marks}} Marks.",
      scopeWelcome: "Barivkeluts / Hoogor Ashkharh",
      scopeCueCards: "Hushagreri Holovashkhar",
      scopeNavigation: "Navigatsiayi petakner ev skhalneri petakner",
      scopeWildfire: "Wildfire Beacon Run: Gortsoghutyun Gorvatsir",
      claimBounty: "Pahanjveck Ays Targmanutyun Mtakatrutun",
      baseLanguage: "Hishayin lezun -- mtakatrutun petk chi.",
      claimedBy: "@{{handle}} pahanjev -- yndzoghum e.",
      marksProvisional: "{{marks}} Marks (zhamanakavor)",
      speakFounderTitle: "Hisnateli Dzaynen: Inchu Ayd Bajrery",
      speakFounderDesc: "Ayd harkum amenayin bajrern kochvum en parachow: 26 garjanakayin anunner.",
      howBountiesWork: "Inch Kaerpov en Katarum Targmanutyun Mtakatrutunnery",
      step1Title: "Pahanjveck Mtakatrutun",
      step1Body: "Batsek Targmanutyun Mtakatrutun Help Wanted-ic.",
      step2Title: "Targmaneck ev Usarkel",
      step2Body: "Targmaneck bolor anrakhet taxtakaghery. Usarkel Bounty Poster-ov.",
      step3Title: "Shchek Marks",
      step3Body: "Chkayummane heto kcerkek Marks ev katagrveck IP Ledger-um.",
      hide: "takcnl",
      why: "inch u?",
    },
    languageSwitcher: {
      changeLanguage: "Fhokhel lezun",
      selectLanguage: "Entel lezun",
      quickEnglish: "Angleren",
      tip: "Ogtagortsvek tarber lezuneri gorjanisherove Durin-i Derkin mot!",
    },
  },
  "ca": {
    speakFriend: {
      title: "Digues amic i entra.",
      description: "Liana Banyan esta construida per ser oberta a cada idioma. Cada idioma obert te una recompensa de traduccio.",
      languages: "idiomes",
      openBounties: "recompenses obertes",
      marksAwarded: "Marks atorgats (tokens de participacio)",
      provisional: "Provisionalment:",
      provisionalNotice: "La llista d'idiomes i els tipus de Marks son provisionals. Els Marks son tokens de participacio, no accions.",
      bountyOpen: "Recompensa oberta",
      claimed: "Reclamada",
      complete: "Completat",
      translationBountyTitle: "Recompensa de Traduccio",
      bountyDescription: "Traduiu Liana Banyan a {{language}}. Guanyeu {{marks}} Marks en ser acceptada.",
      scopeWelcome: "Pantalles de Benvinguda / Mon Fantasmal",
      scopeCueCards: "Conjunt base de targetes de suggeriments",
      scopeNavigation: "Etiquetes de navegacio i missatges d'error",
      scopeWildfire: "Wildfire Beacon Run: Troba feina",
      claimBounty: "Reclameu aquesta Recompensa de Traduccio",
      baseLanguage: "Idioma base -- no cal recompensa.",
      claimedBy: "Recompensa reclamada per @{{handle}} -- en curs.",
      marksProvisional: "{{marks}} Marks (provisionalment)",
      speakFounderTitle: "La Veu del Fundador: Per que Aquestes Paraules",
      speakFounderDesc: "Cada terme d'aquesta plataforma ha estat nomenat per un motiu. Origen dels 26 noms mes importants.",
      howBountiesWork: "Com Funcionen les Recompenses de Traduccio",
      step1Title: "Reclameu la Recompensa",
      step1Body: "Obriu una Recompensa de Traduccio del tauler Help Wanted.",
      step2Title: "Traduiu i Envieu",
      step2Body: "Traduiu totes les cadenes necessaries. Envieu-les a traves del flux Bounty Poster.",
      step3Title: "Guanyeu Marks",
      step3Body: "Despres de l'acceptacio, rebreu Marks i s'us registrara a IP Ledger.",
      hide: "amaga",
      why: "per que?",
    },
    languageSwitcher: {
      changeLanguage: "Canvia l'idioma",
      selectLanguage: "Selecciona l'idioma",
      quickEnglish: "Angles",
      tip: "Feu servir contrasenyes en idiomes diferents a la Porta de Durin per desbloquejar experiencies uniques!",
    },
  },
  "mk": {
    speakFriend: {
      title: "Kazi prijatel i vlezi.",
      description: "Liana Banyan e izgradena da bide otvorena za sekoj jazik. Sekoj otvoreni jazik ima edna nagrada za prevod.",
      languages: "jazici",
      openBounties: "otvoreni nagradi",
      marksAwarded: "Marks dodeleni (tokeni za ucestvo)",
      provisional: "Privremeno:",
      provisionalNotice: "Listata na jazici i stopkite Marks se privremeni. Marks se tokeni za ucestvo, ne akcii.",
      bountyOpen: "Nagradata otvorena",
      claimed: "Pobarano",
      complete: "Zavrseno",
      translationBountyTitle: "Nagrada za Prevod",
      bountyDescription: "Prevedete Liana Banyan na {{language}}. Zarabotete {{marks}} Marks.",
      scopeWelcome: "Ekrani Dobrodojdovte / Svetot na Duhovi",
      scopeCueCards: "Osnoven set na Karticki so soveti",
      scopeNavigation: "Navigaciski oznaki i poraki za greski",
      scopeWildfire: "Wildfire Beacon Run: Najdi Rabota",
      claimBounty: "Pobarajte ja ovaa Nagrada za Prevod",
      baseLanguage: "Osnoven jazik -- nagradata ne e potrebna.",
      claimedBy: "Nagradata pobara @{{handle}} -- vo tek.",
      marksProvisional: "{{marks}} Marks (privremeno)",
      speakFounderTitle: "Glasot na Osnivacot: Zosto Ovie Zborovi",
      speakFounderDesc: "Sekoj termin na ovaa platforma e naречен so pricina. Potekloto na 26-te najvazni iminji.",
      howBountiesWork: "Kako Rabotат Nagradite za Prevod",
      step1Title: "Pobarajte Nagradata",
      step1Body: "Otvorete Nagrada za Prevod od plocata Help Wanted.",
      step2Title: "Prevedete i Pratete",
      step2Body: "Prevedete gi site potrebni nizi. Pratete preku Bounty Poster.",
      step3Title: "Zarabotete Marks",
      step3Body: "Po prifakanjeto dobivate Marks i ste evidentirani vo IP Ledger.",
      hide: "skri",
      why: "zosto?",
    },
    languageSwitcher: {
      changeLanguage: "Promeni jazik",
      selectLanguage: "Izberi jazik",
      quickEnglish: "Anglisko",
      tip: "Koristete lozinki na razlicni jazici na Poratata na Durin za edinstveni iskustva!",
    },
  },
  "be": {
    speakFriend: {
      title: "Скажы сябар і ўвайдзі.",
      description: "Liana Banyan пабудавана адкрытай для кожнай мовы. Кожная адкрытая мова мае адну ўзнагароду за пераклад.",
      languages: "мовы",
      openBounties: "адкрытыя ўзнагароды",
      marksAwarded: "Marks прысвоены (токены ўдзелу)",
      provisional: "Часова:",
      provisionalNotice: "Спіс моў і стаўкі Marks з'яўляюцца часовымі. Marks з'яўляюцца токенамі ўдзелу, не акцыямі.",
      bountyOpen: "Узнагарода адкрытая",
      claimed: "Запатрабавана",
      complete: "Завершана",
      translationBountyTitle: "Узнагарода за Пераклад",
      bountyDescription: "Перакладзіце Liana Banyan на {{language}}. Атрымайце {{marks}} Marks.",
      scopeWelcome: "Экраны Сардэчна запрашаем / Свет прывідаў",
      scopeCueCards: "Асноўны набор картак падказак",
      scopeNavigation: "Навігацыйныя пазнакі і паведамленні пра памылкі",
      scopeWildfire: "Wildfire Beacon Run: Знайдзі працу",
      claimBounty: "Запатрабаваць гэтую ўзнагароду за пераклад",
      baseLanguage: "Базавая мова -- узнагарода не патрэбная.",
      claimedBy: "Узнагарода запатрабавана @{{handle}} -- у працэсе.",
      marksProvisional: "{{marks}} Marks (часова)",
      speakFounderTitle: "Голас заснавальніка: чаму гэтыя словы",
      speakFounderDesc: "Кожны тэрмін на гэтай платформе названы не выпадкова. Паходжанне 26 найважнейшых назваў.",
      howBountiesWork: "Як працуюць узнагароды за пераклад",
      step1Title: "Запатрабаваць узнагароду",
      step1Body: "Адкрыйце ўзнагароду за пераклад з дошкі Help Wanted.",
      step2Title: "Перакласці і падаць",
      step2Body: "Перакладзіце ўсе неабходныя радкі. Падайце праз Bounty Poster.",
      step3Title: "Зарабіць Marks",
      step3Body: "Пасля прыняцця атрымаеце Marks і будзеце ўнесены ў IP Ledger.",
      hide: "схаваць",
      why: "чаму?",
    },
    languageSwitcher: {
      changeLanguage: "Змяніць мову",
      selectLanguage: "Выбраць мову",
      quickEnglish: "Англійская",
      tip: "Выкарыстоўвайце паролі розных моў у Дзверах Дурына для унікальных уражанняў!",
    },
  },
  "af": {
    speakFriend: {
      title: "Se vriend en gaan in.",
      description: "Liana Banyan is gebou om oop te wees vir elke taal. Elke oop taal het een vertaalpremie.",
      languages: "tale",
      openBounties: "oop premies",
      marksAwarded: "Marks toegeken (deelname-tekens)",
      provisional: "Voorlopig:",
      provisionalNotice: "Die taallys en Marks-koerse is voorlopig. Marks is deelname-tekens, nie aandele nie.",
      bountyOpen: "Premie oop",
      claimed: "Geeis",
      complete: "Voltooi",
      translationBountyTitle: "Vertaalpremie",
      bountyDescription: "Vertaal Liana Banyan na {{language}}. Verdien {{marks}} Marks.",
      scopeWelcome: "Welkom / Spookwereld skerms",
      scopeCueCards: "Basis Wenk-kaart stel",
      scopeNavigation: "Navigasie-etikette en foutberichte",
      scopeWildfire: "Wildfire Beacon Run: Kry werk",
      claimBounty: "Eis hierdie Vertaalpremie",
      baseLanguage: "Baastaal -- geen premie nodig nie.",
      claimedBy: "@{{handle}} het geeis -- aan die gang.",
      marksProvisional: "{{marks}} Marks (voorlopig)",
      speakFounderTitle: "Die Stigter se Stem: Hoekom Hierdie Woorde",
      speakFounderDesc: "Elke term op hierdie platform is om 'n rede vernoem. Die oorsprong van die 26 belangrikste name.",
      howBountiesWork: "Hoe Vertaalpremies Werk",
      step1Title: "Eis die Premie",
      step1Body: "Maak 'n Vertaalpremie oop van die Help Wanted-bord.",
      step2Title: "Vertaal en Stuur",
      step2Body: "Vertaal al die nodige strings. Stuur via die Bounty Poster-stroom.",
      step3Title: "Verdien Marks",
      step3Body: "Na aanvaarding ontvang jy Marks en word by IP Ledger aangeteken.",
      hide: "verberg",
      why: "hoekom?",
    },
    languageSwitcher: {
      changeLanguage: "Verander taal",
      selectLanguage: "Kies taal",
      quickEnglish: "Engels",
      tip: "Gebruik wagwoorde in verskillende tale by Durin se Deur om unieke ervaringe te ontsluit!",
    },
  },
  "xh": {
    speakFriend: {
      title: "Thetha umhlobo, ube ungene.",
      description: "I-Liana Banyan yakhiwe ukuba ivuleke kulo naliphi na ulwimi. Ulwimi ngalunye oluvuliweyo lunomvuzo omnye woguqulelo.",
      languages: "iilwimi",
      openBounties: "imivuzo evuliweyo",
      marksAwarded: "Marks anikwe (amatokeni okuthatha inxaxheba)",
      provisional: "Okwexesha elifutshane:",
      provisionalNotice: "Uluhlu lwezilwimi nezinga le-Marks lixeshekile. I-Marks yitokeni yokuthatha inxaxheba, hayi izabelo.",
      bountyOpen: "Umvuzo uvuliwe",
      claimed: "Kucelwe",
      complete: "Kuphelele",
      translationBountyTitle: "Umvuzo Woguqulelo",
      bountyDescription: "Guqulela i-Liana Banyan kwi-{{language}}. Fumana {{marks}} Marks.",
      scopeWelcome: "Iibakali Wamkelekile / Ihlabathi Lamimoya",
      scopeCueCards: "Iseti se-Cue Card Esiyinxalenye",
      scopeNavigation: "Amanqaku okhokelo kunye nemiyalezo yamaphoswa",
      scopeWildfire: "Wildfire Beacon Run: Fumana Umsebenzi",
      claimBounty: "Cela lo Mvuzo Woguqulelo",
      baseLanguage: "Ulwimi lwesiseko -- akudingeki mvuzo.",
      claimedBy: "@{{handle}} wacela -- iqhuba.",
      marksProvisional: "{{marks}} Marks (okwexesha elifutshane)",
      speakFounderTitle: "Ilizwi loMseki: Kutheni la Magama",
      speakFounderDesc: "Igama ngalinye kule platform ilinikezwe igama ngezizathu. Imvelaphi yamagama angama-26 abalulekileyo.",
      howBountiesWork: "Imivuzo Yoguqulelo Isebenza Njani",
      step1Title: "Cela Umvuzo",
      step1Body: "Vula Umvuzo Woguqulelo kwi-Help Wanted.",
      step2Title: "Guqulela uze Uthumele",
      step2Body: "Guqulela izicatshulwa zonke ezidinwayo. Thumela nge-Bounty Poster.",
      step3Title: "Fumana Marks",
      step3Body: "Emva kokamkelwa, ufumana Marks kwaye ubhalwa kwi-IP Ledger.",
      hide: "fihla",
      why: "kutheni?",
    },
    languageSwitcher: {
      changeLanguage: "Tshintsha ulwimi",
      selectLanguage: "Khetha ulwimi",
      quickEnglish: "IsiNgesi",
      tip: "Sebenzisa amagama aphasiwedhi ezilwimi ezahlukeneyo eMnyango kaDurin ukuvula amava amahlanu!",
    },
  },
  "st": {
    speakFriend: {
      title: "Bua motsoalle, ebe o kene.",
      description: "Liana Banyan e hahilwe ho bula dipuo tsohle. Puo e ngoe le e ngoe e na le moputso o mong wa phetolelo.",
      languages: "dipuo",
      openBounties: "meputso e buleha",
      marksAwarded: "Marks e fuwe (litokene tsa ho nka karolo)",
      provisional: "Ka nakoana:",
      provisionalNotice: "Lethathamo la dipuo le litheko tsa Marks ke tsa nakoana. Marks ke litokene tsa ho nka karolo, esio seabo.",
      bountyOpen: "Moputso o buleha",
      claimed: "Ho kopilwe",
      complete: "Ho phethilwe",
      translationBountyTitle: "Moputso wa Phetolelo",
      bountyDescription: "Fetola Liana Banyan ho {{language}}. Fumana {{marks}} Marks.",
      scopeWelcome: "Karete tsa Amohetsoa / Lefatshe la Meea",
      scopeCueCards: "Sete e kaholimo ya Karete tsa Maikutlo",
      scopeNavigation: "Dihlahlobo tsa tsela le melaetsa ya mathata",
      scopeWildfire: "Wildfire Beacon Run: Fumana Mosebetsi",
      claimBounty: "Kopa Moputso ona wa Phetolelo",
      baseLanguage: "Puo ya motheo -- ha ho moputso o hlokahileng.",
      claimedBy: "@{{handle}} o kopile -- e tsoela pele.",
      marksProvisional: "{{marks}} Marks (ka nakoana)",
      speakFounderTitle: "Lentsoe la Mosehli: Ke Hobaneng le Mantsoe Ana",
      speakFounderDesc: "Lentsoe lohle mona le bitswa ka lebaka. Motheo wa mabitso a 26 a bohlokwa.",
      howBountiesWork: "Meputso ya Phetolelo e Sebetsa Jwang",
      step1Title: "Kopa Moputso",
      step1Body: "Bula Moputso wa Phetolelo ho tswa Help Wanted.",
      step2Title: "Fetola le Romela",
      step2Body: "Fetola listring tsohle tse hlokahileng. Romela ka Bounty Poster.",
      step3Title: "Fumana Marks",
      step3Body: "Ka mora ho amohelwa, o fumana Marks le ho kwadiswa ho IP Ledger.",
      hide: "pata",
      why: "hobaneng?",
    },
    languageSwitcher: {
      changeLanguage: "Fetola puo",
      selectLanguage: "Khetha puo",
      quickEnglish: "Senyesemane",
      tip: "Sebedisa diphasewete tsa dipuo tse fapaneng ho Lefako la Durin ho bula maitemogelo a ikhethang!",
    },
  },
  "tn": {
    speakFriend: {
      title: "Bua mohumagadi, o tsene.",
      description: "Liana Banyan e agile go bula go puo nngwe le nngwe. Puo nngwe le nngwe e na le moputso o mongwe wa phetolelo.",
      languages: "dipuo",
      openBounties: "meputso e bulegile",
      marksAwarded: "Marks e neelwa (ditokene tsa go tshwara karolo)",
      provisional: "Ka selekanyo:",
      provisionalNotice: "Lenaane la dipuo le ditekelo tsa Marks ke tsa selekanyo. Marks ke ditokene tsa karolo, eseng dikaelo.",
      bountyOpen: "Moputso o bulegile",
      claimed: "Go kgopilwe",
      complete: "Go phethilwe",
      translationBountyTitle: "Moputso wa Phetolelo",
      bountyDescription: "Fetola Liana Banyan go {{language}}. Bona {{marks}} Marks.",
      scopeWelcome: "Dikarata tsa Amogela / Lefatshe la Mewa",
      scopeCueCards: "Sete ya Karata ya Maele",
      scopeNavigation: "Ditlhomeso tsa tsela le melaetsa ya mathata",
      scopeWildfire: "Wildfire Beacon Run: Bona Tiro",
      claimBounty: "Kopa Moputso ono wa Phetolelo",
      baseLanguage: "Puo ya motheo -- ga go moputso o o hlokegang.",
      claimedBy: "@{{handle}} o kgopile -- e tswela pele.",
      marksProvisional: "{{marks}} Marks (selekanyo)",
      speakFounderTitle: "Lentswe la Mothei: Ke Goreng Mafoko Ano",
      speakFounderDesc: "Lentsu lefe lefe mono le bitsiwa ka lebaka. Motheo wa maina 26 a botlhokwa.",
      howBountiesWork: "Meputso ya Phetolelo e Dira Jang",
      step1Title: "Kopa Moputso",
      step1Body: "Bula Moputso wa Phetolelo go tswa Help Wanted.",
      step2Title: "Fetola le Romela",
      step2Body: "Fetola distring tsotlhe tse di hlokegang. Romela ka Bounty Poster.",
      step3Title: "Bona Marks",
      step3Body: "Morago ga go amogela, o bona Marks e kwadisiwa mo IP Ledger.",
      hide: "fitlha",
      why: "goreng?",
    },
    languageSwitcher: {
      changeLanguage: "Fetola puo",
      selectLanguage: "Kgethola puo",
      quickEnglish: "Sekgoa",
      tip: "Dirisa diphasewete tsa dipuo tse di farologaneng kwa Kgoro ya Durin go bula maitemogelo a a ikgethileng!",
    },
  },
  "wo": {
    speakFriend: {
      title: "Wax xarit, bu dem dëkk.",
      description: "Liana Banyan dañu ko feri ngir mënees woon ci këlëfum kaw. Këlëfu bu nekk am nanu jëf bu yëgël ci tayre.",
      languages: "kañ",
      openBounties: "jëfandikoo yi juddu",
      marksAwarded: "Marks joxe (tokeniyu dëkku)",
      provisional: "Bu dëkku xam-xam:",
      provisionalNotice: "Listu kañ yi ak dewe Marks di soxor xam-xam. Marks di tokeniyu dëkku, mënees nekk xëmu.",
      bountyOpen: "Jëfandikoo jude",
      claimed: "Dindal",
      complete: "Jeex",
      translationBountyTitle: "Jëfandikoo ci Tayre",
      bountyDescription: "Tayre Liana Banyan ci {{language}}. Seet {{marks}} Marks.",
      scopeWelcome: "Yëgëlgëm / Àddina Jinne",
      scopeCueCards: "Sëtti Kaaru Xam-xam",
      scopeNavigation: "Siy ci yoonu ak kiiray njot-buukam",
      scopeWildfire: "Wildfire Beacon Run: Seet liggéey",
      claimBounty: "Jëfe Jëfandikoo bi ci Tayre bi",
      baseLanguage: "Kañ bu mboole -- amul jëfandikoo.",
      claimedBy: "@{{handle}} jëfe -- mu giggal.",
      marksProvisional: "{{marks}} Marks (xam-xam bu dëkku)",
      speakFounderTitle: "Xobalu Dekkanteeku: Lu tax Bataaxal yi",
      speakFounderDesc: "Kaw yëp ci réew bi dem nekk ci xam-xam yi. Mbuur mburu 26 bi siy.",
      howBountiesWork: "Lu tax Jëfandikoo ci Tayre Dox",
      step1Title: "Jëfe Jëfandikoo",
      step1Body: "Yëkkati Jëfandikoo ci Tayre ci Help Wanted.",
      step2Title: "Tayre Ci Yonn",
      step2Body: "Tayre kaw string yi. Yonn ci Bounty Poster.",
      step3Title: "Seet Marks",
      step3Body: "Bi dem nanu, nga xam Marks ak di ñëw ci IP Ledger.",
      hide: "planke",
      why: "lu tax?",
    },
    languageSwitcher: {
      changeLanguage: "Soppi kañ",
      selectLanguage: "Tann kañ",
      quickEnglish: "Angale",
      tip: "Jëfe bataaxal kañ ci yooyu Dëkk Durin ngir yëgël xam xam bu am solo!",
    },
  },
  "ak": {
    speakFriend: {
      title: "Ka se adamfo, na wo ko mu.",
      description: "Wode Liana Banyan ama kasa biara betumi ato mu. Kasa biara wɔ bommɔne baako a wɔka nkyerɛ mu.",
      languages: "kasa",
      openBounties: "bommɔne a wɔkado",
      marksAwarded: "Wode Marks maa (token a wɔba ho)",
      provisional: "Dapem:",
      provisionalNotice: "Kasa nhyehyɛe ne Marks bɛhyɛ no yɛ dapem. Marks yɛ token a wɔba ho, na ɛnyɛ sekyɛn.",
      bountyOpen: "Bommɔne wɔ adi",
      claimed: "Yɛagye",
      complete: "Yɛawie",
      translationBountyTitle: "Bommɔne Nkyerɛkyerɛmu",
      bountyDescription: "Kyerɛ Liana Banyan mu wɔ {{language}}. Nya {{marks}} Marks.",
      scopeWelcome: "Nnae a yɛkye / Asase Honhom",
      scopeCueCards: "Kard nhyehyɛe a ɛfa ho nsɛm",
      scopeNavigation: "Kwan nhyehyɛe ne nkyerɛmu nsɛm",
      scopeWildfire: "Wildfire Beacon Run: Nya Adwuma",
      claimBounty: "Gye Bommɔne yi wɔ Nkyerɛkyerɛmu mu",
      baseLanguage: "Kasa titiriw -- bommɔne nhia.",
      claimedBy: "@{{handle}} agye -- rekɔ so.",
      marksProvisional: "{{marks}} Marks (dapem)",
      speakFounderTitle: "Ohene no Nne: Adɛn na Nsɛm yi",
      speakFounderDesc: "Nsɛm biara wɔ platform yi mu wɔ nea ɛmaa ne din. Fiase 26 din a ɛho hia.",
      howBountiesWork: "Nkyerɛkyerɛmu Bommɔne bɛyɛ dɛn",
      step1Title: "Gye Bommɔne no",
      step1Body: "Bue Bommɔne Nkyerɛkyerɛmu wɔ Help Wanted.",
      step2Title: "Kyerɛ Ne Fi",
      step2Body: "Kyerɛ strings a ɛhia nyinaa. Fi wɔ Bounty Poster mu.",
      step3Title: "Nya Marks",
      step3Body: "Wɔagye no akyi, wunya Marks na wɔde wo kɔ IP Ledger mu.",
      hide: "kaha",
      why: "adɛn?",
    },
    languageSwitcher: {
      changeLanguage: "Sesa kasa",
      selectLanguage: "Yi kasa",
      quickEnglish: "Borɔfoɔ Kasa",
      tip: "Fa kasa foforo pasowedi wɔ Durin Pon ho na wo benya adeɛ a ɛpɛ so!",
    },
  },
  "ee": {
    speakFriend: {
      title: "Gblɔ ɖoviɖo, eye wɔ dzo.",
      description: "Liana Banyan wɔɖe ɖe amedede be woagae ɖe gbegbɔgblɔ siwo katã. Gbegbɔgblɔ siã le akɔuntɔgbe ɖeka ɖe gblɔdzidzi.",
      languages: "gbegbɔgblɔ",
      openBounties: "akɔuntɔgbewo si woɖe",
      marksAwarded: "Marks ná (le kadzɛdzɛ tokens)",
      provisional: "Sigenyi:",
      provisionalNotice: "Gbegbɔgblɔwoe dzesi kple Marks didi le sigenyi. Marks nye kadzɛdzɛ tokens, manya didia.",
      bountyOpen: "Akɔuntɔgbe ɖe",
      claimed: "Woñlɔe",
      complete: "Woɖoa",
      translationBountyTitle: "Akɔuntɔgbe Gblɔdzidzi",
      bountyDescription: "Gblɔ Liana Banyan ɖe {{language}} me. Ɖu {{marks}} Marks.",
      scopeWelcome: "Deɖeɖe / Tɔxelu Tsiefe",
      scopeCueCards: "Akpa Kple Fɔmefɔme Kards",
      scopeNavigation: "Kpɔkpɔ-dɔ nutinuwo kple nuvevenyawo",
      scopeWildfire: "Wildfire Beacon Run: Kpɔ dɔ",
      claimBounty: "Ñlɔ Akɔuntɔgbe sia ɖe Gblɔdzidzi",
      baseLanguage: "Gbegbɔgblɔ tititi -- akɔuntɔgbe mehiã o.",
      claimedBy: "@{{handle}} ñlɔe -- ede agbenɔnɔ.",
      marksProvisional: "{{marks}} Marks (sigenyi)",
      speakFounderTitle: "Dɔwɔlawo Gbe: Edze Nusi Ŋkeke Sia Ƒe",
      speakFounderDesc: "Nusiwo katã le platform sia me wɔɖe ŋkeke ɖe gbegbɔgblɔ. 26 ŋkeke siwo wɔle ŋutɔŋutɔ.",
      howBountiesWork: "Akɔuntɔgbe Gblɔdzidzi le Nusi Dɔ",
      step1Title: "Ñlɔ Akɔuntɔgbe no",
      step1Body: "Zi Akɔuntɔgbe Gblɔdzidzi le Help Wanted.",
      step2Title: "Gblɔ kple Bliɛa",
      step2Body: "Gblɔ strings siwo hiã katã. Bliɛa abe Bounty Poster.",
      step3Title: "Ɖu Marks",
      step3Body: "Kpe le wogaɖeɖe emegbe, ede Marks kple IP Ledger ñlɔ.",
      hide: "gbo",
      why: "edze nusi?",
    },
    languageSwitcher: {
      changeLanguage: "Tia gbegbɔgblɔ",
      selectLanguage: "Yi gbegbɔgblɔ",
      quickEnglish: "Yevugbe",
      tip: "Zã gbegbɔgblɔ siwo ɣe ɣem passwords le Durin ƒe Ŋkɔ dzi ɖe kplɔ nyuitɔ!",
    },
  },
  "ky": {
    speakFriend: {
      title: "Дос де, кире бер.",
      description: "Liana Banyan ар бир тил үчүн ачык курулган. Ар бир ачык тилде бир которуу сыйлыгы бар.",
      languages: "тилдер",
      openBounties: "ачык сыйлыктар",
      marksAwarded: "Marks берилди (катышуу токендери)",
      provisional: "Убактылуу:",
      provisionalNotice: "Тилдердин тизмеси жана Marks ставкалары убактылуу. Marks катышуу токендери, акция эмес.",
      bountyOpen: "Сыйлык ачык",
      claimed: "Талап кылынды",
      complete: "Аяктады",
      translationBountyTitle: "Которуу Сыйлыгы",
      bountyDescription: "Liana Banyan-ды {{language}} тилине которуңуз. {{marks}} Marks табыңыз.",
      scopeWelcome: "Кош келиңиздер / Рухтар Дүйнөсү экрандары",
      scopeCueCards: "Негизги Кеңеш карталары жыйындысы",
      scopeNavigation: "Навигация белгилери жана ката билдирүүлөр",
      scopeWildfire: "Wildfire Beacon Run: Иш тапкыла",
      claimBounty: "Бул которуу сыйлыгын талап кылыңыз",
      baseLanguage: "Негизги тил -- сыйлык кажет эмес.",
      claimedBy: "@{{handle}} талап кылды -- жүрүп жатат.",
      marksProvisional: "{{marks}} Marks (убактылуу)",
      speakFounderTitle: "Негиздөөчүнүн добушу: Эмне үчүн бул сөздөр",
      speakFounderDesc: "Бул платформадагы ар бир термин бир себеп менен аталган. 26 маанилүү атамалардын келип чыгышы.",
      howBountiesWork: "Которуу сыйлыктары кандай иштейт",
      step1Title: "Сыйлыкты талап кылыңыз",
      step1Body: "Help Wanted такталасынан которуу сыйлыгын ачыңыз.",
      step2Title: "Которуп жөнөтүңүз",
      step2Body: "Бардык керектүү саптарды которуңуз. Bounty Poster аркылуу жөнөтүңүз.",
      step3Title: "Marks табыңыз",
      step3Body: "Кабыл алынгандан кийин Marks аласыз. IP Ledger-ге катталасыз.",
      hide: "жашыруу",
      why: "эмне үчүн?",
    },
    languageSwitcher: {
      changeLanguage: "Тилди өзгөртүү",
      selectLanguage: "Тил тандаңыз",
      quickEnglish: "Англис",
      tip: "Уникалдуу тажрыйбалар үчүн Дурин Дарбазасында ар кандай тил сырсөздөрүн колдонуңуз!",
    },
  },
  "tg": {
    speakFriend: {
      title: "Дӯст гӯ ва дохил шав.",
      description: "Liana Banyan барои ҳар як забон кушода сохта шудааст. Ҳар забони кушода як мукофоти тарҷума дорад.",
      languages: "забонҳо",
      openBounties: "мукофоти кушода",
      marksAwarded: "Marks дода шуд (нишонаҳои иштирок)",
      provisional: "Муваққатан:",
      provisionalNotice: "Рӯйхати забонҳо ва меъёрҳои Marks муваққатӣ мебошанд. Marks нишонаҳои иштирок мебошанд, на саҳмияҳо.",
      bountyOpen: "Мукофот кушода аст",
      claimed: "Талаб карда шуд",
      complete: "Тамом",
      translationBountyTitle: "Мукофоти Тарҷума",
      bountyDescription: "Liana Banyan-ро ба забони {{language}} тарҷума кунед. {{marks}} Marks ба даст оред.",
      scopeWelcome: "Экранҳои Хуш омадед / Дунёи Арвоҳ",
      scopeCueCards: "Маҷмӯи Корти Маслиҳати Асосӣ",
      scopeNavigation: "Тамғаҳои навигатсия ва паёмҳои хато",
      scopeWildfire: "Wildfire Beacon Run: Корро ёбед",
      claimBounty: "Ин мукофоти тарҷумаро талаб кунед",
      baseLanguage: "Забони асосӣ -- мукофот лозим нест.",
      claimedBy: "@{{handle}} талаб кард -- дар ҷараён.",
      marksProvisional: "{{marks}} Marks (муваққатан)",
      speakFounderTitle: "Овози Асосгузор: Чаро Ин Калимаҳо",
      speakFounderDesc: "Ҳар истилоҳ дар ин платформа бо сабаб номгузорӣ шудааст. Пайдоиши 26 номи муҳимтарин.",
      howBountiesWork: "Мукофотҳои Тарҷума Чӣ Тавр Кор Мекунанд",
      step1Title: "Мукофотро талаб кунед",
      step1Body: "Мукофоти тарҷумаро аз тахтаи Help Wanted кушоед.",
      step2Title: "Тарҷума кунед ва Фиристед",
      step2Body: "Ҳамаи риштаҳои заруриро тарҷума кунед. Тавассути Bounty Poster фиристед.",
      step3Title: "Marks ба даст оред",
      step3Body: "Пас аз қабул, Marks мегиред ва дар IP Ledger сабт мешавед.",
      hide: "пинҳон кунед",
      why: "чаро?",
    },
    languageSwitcher: {
      changeLanguage: "Забонро иваз кунед",
      selectLanguage: "Забонро интихоб кунед",
      quickEnglish: "Англисӣ",
      tip: "Барои таҷрибаҳои беназир дар Дари Дурин рамзҳои забонҳои гуногунро истифода баред!",
    },
  },
};
