"use strict";
// tdata-b.cjs -- Machine translations Group B (languages 28-54)
// ff uk so az tl km ceb mg si sd ku kk sn mn bo su bho mai ro zu cs el hu hr sr bs rw
module.exports = {
  "ff": {
    speakFriend: {
      title: "Wiy tappude, inna.",
      description: "Liana Banyan nawnii so hannde yooltee e kala demngal. Kala demngal woni gootol murdin ngurndan.",
      languages: "demde",
      openBounties: "murdi dinde yubbinoooje",
      marksAwarded: "Marks nabaama (kontooji goongaaji)",
      provisional: "Bodal:",
      provisionalNotice: "Libol demde e njeeyru Marks ko bodal. Marks ko kontooji goongaaji, alaa nafa.",
      bountyOpen: "Murdi din yubbii",
      claimed: "Beydaama",
      complete: "Timminii",
      translationBountyTitle: "Murdi Din Ngurndan",
      bountyDescription: "Ngurndanu Liana Banyan e {{language}}. Heb {{marks}} Marks.",
      scopeWelcome: "Jangirde Naamaare / Aduna Ruuhu",
      scopeCueCards: "Kade Tiitoonde Toownde",
      scopeNavigation: "Niooode laawol e bataake moortiingo",
      scopeWildfire: "Wildfire Beacon Run: Yiynu liggaade",
      claimBounty: "Heb Murdi Din Ngurndan ngo",
      baseLanguage: "Demngal dadol -- alaa murdi din.",
      claimedBy: "@{{handle}} hebii -- ina dabba.",
      marksProvisional: "{{marks}} Marks (bodal)",
      speakFounderTitle: "Kulol Goddo Gawtori: Hol to tii wolde ndee",
      speakFounderDesc: "Kala tiitoonde e nder dee sifa ko nder mbaadi. Asaluuji 26 innde.",
      howBountiesWork: "No Murdi Din Ngurndan Nguurdi",
      step1Title: "Heb Murdi Din",
      step1Body: "Uddit Murdi Din Ngurndan e Help Wanted.",
      step2Title: "Ngurndanu e Naat",
      step2Body: "Ngurndanu kala damirde. Naat e Bounty Poster.",
      step3Title: "Heb Marks",
      step3Body: "Caggal nalngo, heban Marks e a winndirtoo IP Ledger.",
      hide: "soofu",
      why: "no?",
    },
    languageSwitcher: {
      changeLanguage: "Sokku demngal",
      selectLanguage: "Sub demngal",
      quickEnglish: "Engele",
      tip: "Huutooro binndi demde godde e Damal Durin ngam udditde miijo!",
    },
  },
  "uk": {
    speakFriend: {
      title: "Скажи «друг» -- і увійди.",
      description: "Liana Banyan побудована відкритою для кожної мови. Кожна мова має одну перекладацьку нагороду.",
      languages: "мови",
      openBounties: "відкриті нагороди",
      marksAwarded: "Marks нараховано (токени участі)",
      provisional: "Тимчасово:",
      provisionalNotice: "Список мов і ставки Marks є тимчасовими. Marks є токенами участі, не акціями.",
      bountyOpen: "Нагорода відкрита",
      claimed: "Заявлено",
      complete: "Завершено",
      translationBountyTitle: "Нагорода за Переклад",
      bountyDescription: "Перекладіть Liana Banyan на {{language}}. Отримайте {{marks}} Marks.",
      scopeWelcome: "Екрани Ласкаво просимо / Світ привидів",
      scopeCueCards: "Основний набір карток підказок",
      scopeNavigation: "Навігаційні мітки та повідомлення про помилки",
      scopeWildfire: "Wildfire Beacon Run: Знайди роботу",
      claimBounty: "Заявити цю нагороду за переклад",
      baseLanguage: "Базова мова -- нагорода не потрібна.",
      claimedBy: "Нагороду заявив @{{handle}} -- у процесі.",
      marksProvisional: "{{marks}} Marks (тимчасово)",
      speakFounderTitle: "Голос засновника: чому ці слова",
      speakFounderDesc: "Кожен термін на цій платформі названо не випадково. Походження 26 найважливіших назв.",
      howBountiesWork: "Як працюють нагороди за переклад",
      step1Title: "Заявити нагороду",
      step1Body: "Відкрийте нагороду за переклад з дошки Help Wanted.",
      step2Title: "Перекласти та подати",
      step2Body: "Перекладіть усі необхідні рядки. Подайте через Bounty Poster.",
      step3Title: "Заробити Marks",
      step3Body: "Після прийняття ви отримаєте Marks і будете внесені до IP Ledger.",
      hide: "приховати",
      why: "чому?",
    },
    languageSwitcher: {
      changeLanguage: "Змінити мову",
      selectLanguage: "Вибрати мову",
      quickEnglish: "Англійська",
      tip: "Використовуйте паролі різних мов у Дверях Дуріна, щоб відкривати унікальні враження!",
    },
  },
  "so": {
    speakFriend: {
      title: "Dheh saaxiib, oo gal.",
      description: "Liana Banyan waxaa loogu dhisay inuu furan yahay dhammaan luqadaha. Luqad kasta oo furan waxay leedahay hal abaal-marin tarjumad.",
      languages: "luqadaha",
      openBounties: "abaal-marino furan",
      marksAwarded: "Marks la siiyey (calaamadaha ka qaybgalka)",
      provisional: "Ku meel-gaar ah:",
      provisionalNotice: "Liiska luqadaha iyo heerarka Marks waa ku meel-gaar ah. Marks waa calaamadaha ka qaybgalka, maaha hantida.",
      bountyOpen: "Abaal-marin furan",
      claimed: "La sheegay",
      complete: "Dhameystiran",
      translationBountyTitle: "Abaal-marin Tarjumad",
      bountyDescription: "Ku turjum Liana Banyan {{language}}. Hel {{marks}} Marks marka la aqbalo.",
      scopeWelcome: "Shaashad Soo Dhawayn / Adduunka Ruuxa",
      scopeCueCards: "Kooxda Kaarka Tilmaan Asasiga",
      scopeNavigation: "Astaamaha saadaasha iyo farriimaha khaladaadka",
      scopeWildfire: "Wildfire Beacon Run: Hel Shaqo",
      claimBounty: "Sheeg Abaal-marinta Tarjumadda Kani",
      baseLanguage: "Luqadda asaasiga -- abaal-marin looma baahna.",
      claimedBy: "@{{handle}} ayaa sheegay -- socda.",
      marksProvisional: "{{marks}} Marks (ku meel-gaar)",
      speakFounderTitle: "Codka Aasaasaha: Sababta Ereyadan",
      speakFounderDesc: "Ereyad kasta oo ku jira barnaamijkan waxaa loo magacaabay sabab. Asalka 26 magac ee ugu muhiimsan.",
      howBountiesWork: "Sida Abaal-marinnada Tarjumadda u Shaqeeyaan",
      step1Title: "Sheeg Abaal-marinta",
      step1Body: "Fur Abaal-marin Tarjumad ee Help Wanted.",
      step2Title: "Turjum oo Soo Gudbi",
      step2Body: "Ku turjum xarfaha oo dhan ee loo baahan yahay. Soo gudbi iyada oo Bounty Poster.",
      step3Title: "Hel Marks",
      step3Body: "Marka la aqbalo, waad helaysaa Marks waxaana lagu diiwaangeliyaa IP Ledger.",
      hide: "qari",
      why: "maxaa?",
    },
    languageSwitcher: {
      changeLanguage: "Beddel luqadda",
      selectLanguage: "Xulo luqadda",
      quickEnglish: "Ingiriisi",
      tip: "Isticmaal eraybixiyaha luqadaha kala duwan ee Albaabka Durin si aad u furto khibradaha gaar ah!",
    },
  },
  "az": {
    speakFriend: {
      title: "Dost de, daxil ol.",
      description: "Liana Banyan her dil ucun aciq qurulmusdur. Her aciq dil ucun bir tercume mukafati var.",
      languages: "diller",
      openBounties: "aciq mukafatlar",
      marksAwarded: "Marks verildi (istirak tokenlerj)",
      provisional: "Muvegqeti:",
      provisionalNotice: "Dillerin siyahisi ve Marks dereceleri muvegqetidir. Marks istirak tokenleri, kapital deyil.",
      bountyOpen: "Mukafat aciqdir",
      claimed: "Teleb edilib",
      complete: "Tamamlandi",
      translationBountyTitle: "Tercume Mukafati",
      bountyDescription: "Liana Banyan-i {{language}} diline tercume edin. {{marks}} Marks qazanin.",
      scopeWelcome: "Xos gelmissiniz / Xeyal Dunyasi ekranlari",
      scopeCueCards: "Esasi Ipucu Kartlari desti",
      scopeNavigation: "Naviqasiya etiketleri ve xeta mesajlari",
      scopeWildfire: "Wildfire Beacon Run: Is tap",
      claimBounty: "Bu Tercume Mukafatini teleb edin",
      baseLanguage: "Esas dil -- mukafat teleb olunmur.",
      claimedBy: "Mukafat @{{handle}} terefjinden teleb edilib -- davam edir.",
      marksProvisional: "{{marks}} Marks (muvegqeti)",
      speakFounderTitle: "Qurucunun Sesi: Niye Bu Sozler",
      speakFounderDesc: "Bu platformdaki her termin bir sebeple adlandirilb. 26 muhum adin mensejj.",
      howBountiesWork: "Tercume Mukafatlari Nece Isleyir",
      step1Title: "Mukafati teleb edin",
      step1Body: "Help Wanted lovhesinden Tercume Mukafati acin.",
      step2Title: "Tercume edin ve gonderin",
      step2Body: "Butun teleb olunan satirlari tercume edin. Bounty Poster vasitesile gonderin.",
      step3Title: "Marks qazanin",
      step3Body: "Qebul edildikden sonra Marks alirsiniz. IP Ledger-e qeyd olunursunuz.",
      hide: "gizlet",
      why: "niye?",
    },
    languageSwitcher: {
      changeLanguage: "Dil deyisdir",
      selectLanguage: "Dil secin",
      quickEnglish: "Ingilis",
      tip: "Unikal tecrubelər ucun Durin Qapisinda muxtəlif dil sifrelerindən istifade edin!",
    },
  },
  "tl": {
    speakFriend: {
      title: "Sabihing kaibigan, at pumasok.",
      description: "Ang Liana Banyan ay ginawa para buksan sa bawat wika. Bawat bukas na wika ay may isang gantimpala ng pagsasalin.",
      languages: "wika",
      openBounties: "bukas na gantimpala",
      marksAwarded: "Marks na ibinigay (mga token ng pakikilahok)",
      provisional: "Pansamantala:",
      provisionalNotice: "Ang listahan ng wika at mga rate ng Marks ay pansamantala. Ang Marks ay mga token ng pakikilahok, hindi equity.",
      bountyOpen: "Bukas ang gantimpala",
      claimed: "Na-claim na",
      complete: "Kumpleto",
      translationBountyTitle: "Gantimpala ng Pagsasalin",
      bountyDescription: "Isalin ang Liana Banyan sa {{language}}. Kumita ng {{marks}} Marks kapag tinanggap.",
      scopeWelcome: "Mga screen ng Maligayang Pagdating / Ghost World",
      scopeCueCards: "Core na hanay ng Cue Card",
      scopeNavigation: "Mga label ng navigation at mensahe ng error",
      scopeWildfire: "Wildfire Beacon Run: Maghanap ng Trabaho",
      claimBounty: "I-claim ang Gantimpalang Ito ng Pagsasalin",
      baseLanguage: "Batayang wika -- hindi kailangan ng gantimpala.",
      claimedBy: "Na-claim ng @{{handle}} -- kasalukuyan.",
      marksProvisional: "{{marks}} Marks (pansamantala)",
      speakFounderTitle: "Tinig ng Tagapagtatag: Bakit Ang Mga Salitang Ito",
      speakFounderDesc: "Bawat termino sa platform na ito ay pinangalanan nang may dahilan. Pinagmulan ng 26 pinakamahalgang pangalan.",
      howBountiesWork: "Paano Gumagana ang Mga Gantimpala ng Pagsasalin",
      step1Title: "I-claim ang Gantimpala",
      step1Body: "Buksan ang Gantimpala ng Pagsasalin mula sa Help Wanted.",
      step2Title: "Isalin at Isumite",
      step2Body: "Isalin ang lahat ng kinakailangang mga string. Isumite sa pamamagitan ng Bounty Poster.",
      step3Title: "Kumita ng Marks",
      step3Body: "Pagkatapos tanggapin, makakatanggap ka ng Marks at maitala sa IP Ledger.",
      hide: "itago",
      why: "bakit?",
    },
    languageSwitcher: {
      changeLanguage: "Baguhin ang wika",
      selectLanguage: "Piliin ang wika",
      quickEnglish: "Ingles",
      tip: "Gumamit ng iba't ibang password ng wika sa Pintuan ni Durin para ma-unlock ang natatanging karanasan!",
    },
  },
  "km": {
    speakFriend: {
      title: "និយាយថា មិត្ត ហើយចូល។",
      description: "Liana Banyan ត្រូវបានបង្កើតឡើងដើម្បីបើកចំហសម្រាប់រាល់ភាសា។ ភាសានីមួយៗមានរង្វាន់បកប្រែមួយ។",
      languages: "ភាសា",
      openBounties: "រង្វាន់ដែលបើក",
      marksAwarded: "Marks ត្រូវបានប្រគល់ (ថូខឹនចូលរួម)",
      provisional: "បណ្តោះអាសន្ន:",
      provisionalNotice: "បញ្ជីភាសា និងអត្រា Marks គឺបណ្តោះអាសន្ន។ Marks គឺជាថូខឹនចូលរួម មិនមែនភាគហ៊ុនទេ។",
      bountyOpen: "រង្វាន់បើក",
      claimed: "ត្រូវបានទាមទារ",
      complete: "បានបញ្ចប់",
      translationBountyTitle: "រង្វាន់ការបកប្រែ",
      bountyDescription: "បកប្រែ Liana Banyan ទៅ {{language}}។ ទទួល {{marks}} Marks។",
      scopeWelcome: "អេក្រង់ស្វាគមន៍ / ពិភពវិញ្ញាណ",
      scopeCueCards: "សំណុំកាតណែនាំស្នូល",
      scopeNavigation: "លេបផ្លូវ និងសារកំហុស",
      scopeWildfire: "Wildfire Beacon Run: រកការងារ",
      claimBounty: "ទាមទាររង្វាន់ការបកប្រែនេះ",
      baseLanguage: "ភាសាមូលដ្ឋាន -- មិនត្រូវការរង្វាន់ទេ។",
      claimedBy: "@{{handle}} ទាមទារ -- កំពុងដំណើរការ។",
      marksProvisional: "{{marks}} Marks (បណ្តោះអាសន្ន)",
      speakFounderTitle: "សំឡេងស្ថាបនិក: ហេតុអ្វីបានជាពាក្យទាំងនេះ",
      speakFounderDesc: "គ្រប់ពាក្យនៅលើវេទិកានេះសុទ្ធតែត្រូវបានដាក់ឈ្មោះដោយមានហេតុផល។ ប្រភពនៃឈ្មោះ 26 ដ៏សំខាន់ជាងគេ។",
      howBountiesWork: "រង្វាន់ការបកប្រែដំណើរការដូចម្ដេច",
      step1Title: "ទាមទាររង្វាន់",
      step1Body: "បើករង្វាន់ការបកប្រែពីក្ដារ Help Wanted។",
      step2Title: "បកប្រែ ហើយដាក់ស្នើ",
      step2Body: "បកប្រែ string ទាំងអស់ដែលត្រូវការ។ ដាក់ស្នើតាម Bounty Poster។",
      step3Title: "ទទួល Marks",
      step3Body: "បន្ទាប់ពីទទួលយក អ្នកទទួល Marks ហើយត្រូវបានកត់ត្រានៅ IP Ledger។",
      hide: "លាក់",
      why: "ហេតុអ្វី?",
    },
    languageSwitcher: {
      changeLanguage: "ប្តូរភាសា",
      selectLanguage: "ជ្រើសភាសា",
      quickEnglish: "ភាសាអង់គ្លេស",
      tip: "ប្រើពាក្យសម្ងាត់ភាសាផ្សេងៗនៅទ្វារ Durin ដើម្បីដោះសោបទពិសោធន៍តែមួយគត់!",
    },
  },
  "ceb": {
    speakFriend: {
      title: "Ingnon ang higala, ug sulod.",
      description: "Ang Liana Banyan gitukod aron aberto sa matag pinulongan. Ang matag pinulongan adunay usa ka ganti sa paghubad.",
      languages: "mga pinulongan",
      openBounties: "bukas nga ganti",
      marksAwarded: "Marks gihatag (mga token sa pagapil)",
      provisional: "Pansamantala:",
      provisionalNotice: "Ang lista sa pinulongan ug mga rate sa Marks temporaryo. Ang Marks mao ang mga token sa pagapil, dili equity.",
      bountyOpen: "Bukas ang ganti",
      claimed: "Gi-claim na",
      complete: "Nahuman",
      translationBountyTitle: "Ganti sa Paghubad",
      bountyDescription: "Hubara ang Liana Banyan ngadto sa {{language}}. Makita ang {{marks}} Marks.",
      scopeWelcome: "Mga screen sa Maayong Pagabot / Ghost World",
      scopeCueCards: "Core nga hanay sa Cue Card",
      scopeNavigation: "Mga label sa navigasyon ug mensahe sa kasaypanan",
      scopeWildfire: "Wildfire Beacon Run: Pangita og Trabaho",
      claimBounty: "I-claim kini nga Ganti sa Paghubad",
      baseLanguage: "Sukaranan nga pinulongan -- wala'y ganti nga gikinahanglan.",
      claimedBy: "Gi-claim ni @{{handle}} -- nagpadayon.",
      marksProvisional: "{{marks}} Marks (pansamantala)",
      speakFounderTitle: "Tingog sa Nagpatindog: Nganong Kining mga Pulong",
      speakFounderDesc: "Ang matag termino gihinganlan tungod sa usa ka rason. Ang gigikanan sa 26 labing hinungdanon nga mga ngalan.",
      howBountiesWork: "Unsaon Pagtrabaho sa mga Ganti sa Paghubad",
      step1Title: "I-claim ang Ganti",
      step1Body: "Ablihi ang Ganti sa Paghubad gikan sa Help Wanted.",
      step2Title: "Hubara ug Isumite",
      step2Body: "Hubara ang tanan nga gikinahanglang mga string. Isumite pinaagi sa Bounty Poster.",
      step3Title: "Makita ang Marks",
      step3Body: "Human sa pag-dawat, makadawat ka og Marks ug ma-rekord sa IP Ledger.",
      hide: "itago",
      why: "nganong?",
    },
    languageSwitcher: {
      changeLanguage: "Usba ang pinulongan",
      selectLanguage: "Pilia ang pinulongan",
      quickEnglish: "Iningles",
      tip: "Gamita ang lain-laing mga password sa pinulongan sa Pultahan ni Durin aron ma-unlock ang talagsaon nga kasinatian!",
    },
  },
  "mg": {
    speakFriend: {
      title: "Lazao hoe namana ianao, dia midira.",
      description: "Liana Banyan dia nataon-dehibe ho misokatra amin'ny fiteny rehetra. Fiteny tsirairay manana valisoa fandikana iray.",
      languages: "fiteny",
      openBounties: "valisoa misokatra",
      marksAwarded: "Marks nomena (famantarana fandraisan'anjara)",
      provisional: "Vonjimaika:",
      provisionalNotice: "Ny lisitry ny fiteny sy ny vidim-bidy Marks vonjimaika. Marks famantarana fandraisan'anjara, tsy hanankirai-tsoaka.",
      bountyOpen: "Valisoa misokatra",
      claimed: "Nilefy",
      complete: "Vita",
      translationBountyTitle: "Valisoa Fandikana",
      bountyDescription: "Adikao ny Liana Banyan ho amin'ny {{language}}. Mahazo {{marks}} Marks rehefa noraisina.",
      scopeWelcome: "Screenin'ny Fiarahabana / Tontolo Fanahy",
      scopeCueCards: "Andiana Karatra Tsentsiny Fototra",
      scopeNavigation: "Marika tantana sy hafatra diso",
      scopeWildfire: "Wildfire Beacon Run: Mitady Asa",
      claimBounty: "Ilefyo ity Valisoa Fandikana ity",
      baseLanguage: "Fiteny fototra -- tsy misy valisoa ilaina.",
      claimedBy: "@{{handle}} nilefy -- amidy.",
      marksProvisional: "{{marks}} Marks (vonjimaika)",
      speakFounderTitle: "Feon'ny Mpamorona: Nahoana ireo teny ireo",
      speakFounderDesc: "Ny teny tsirairay amin'ity sehatra ity nomena anarana noho ny antony. Loharanon'ny anarana 26 manan-danja indrindra.",
      howBountiesWork: "Ahoana ny Fandaharana ny Valisoa Fandikana",
      step1Title: "Ilefyo ny Valisoa",
      step1Body: "Sokafy ny Valisoa Fandikana avy amin'ny Help Wanted.",
      step2Title: "Adikao ary Alefa",
      step2Body: "Adikao ny rindram-peo rehetra ilaina. Alefa amin'ny Bounty Poster.",
      step3Title: "Mahazo Marks",
      step3Body: "Rehefa noraisina, mahazo Marks ianao sary voasoratra ao amin'ny IP Ledger.",
      hide: "afeno",
      why: "nahoana?",
    },
    languageSwitcher: {
      changeLanguage: "Ovay ny fiteny",
      selectLanguage: "Safidio ny fiteny",
      quickEnglish: "Anglisy",
      tip: "Ampiasao teny fidirana fiteny samy hafa amin'ny Varavaran'i Durin mba hamokatra traikefa tokana!",
    },
  },
  "si": {
    speakFriend: {
      title: "යාළුවා කිව්ව, ඇතුල් වෙල්ලා.",
      description: "Liana Banyan සෑම භාෂාවකටම විවෘතව ගොඩනඟා ඇත. සෑම භාෂාවකටම පරිවර්තන ත්‍යාගයක් ඇත.",
      languages: "භාෂා",
      openBounties: "විවෘත ත්‍යාග",
      marksAwarded: "Marks ලබාදී ඇත (සහභාගිත්ව ටෝකන)",
      provisional: "තාවකාලික:",
      provisionalNotice: "භාෂා ලැයිස්තුව සහ Marks අනුපාත තාවකාලිකයි. Marks සහභාගිත්ව ටෝකන, කොටස් නොවේ.",
      bountyOpen: "ත්‍යාගය විවෘතයි",
      claimed: "ඉල්ලා ඇත",
      complete: "සම්පූර්ණ",
      translationBountyTitle: "පරිවර්තන ත්‍යාගය",
      bountyDescription: "Liana Banyan {{language}} වෙත පරිවර්තනය කරන්න. {{marks}} Marks උපයන්න.",
      scopeWelcome: "ආයුබෝවන් / අවතාර ලෝකය තිරය",
      scopeCueCards: "මූල සෙල්ලු කාඩ් කට්ටලය",
      scopeNavigation: "සංචලන ලේබල සහ දෝෂ පණිවිඩ",
      scopeWildfire: "Wildfire Beacon Run: රැකියා ලබාගන්න",
      claimBounty: "මෙම පරිවර්තන ත්‍යාගය ඉල්ලා ගන්න",
      baseLanguage: "මූල භාෂාව -- ත්‍යාගයක් අවශ්‍ය නොවේ.",
      claimedBy: "@{{handle}} විසින් ඉල්ලා ඇත -- ක්‍රියාවලිය.",
      marksProvisional: "{{marks}} Marks (තාවකාලික)",
      speakFounderTitle: "ආරම්භකයාගේ හඬ: මෙම වචන ඇයි",
      speakFounderDesc: "මෙම වේදිකාවේ සෑම පදයක්ම හේතුවක් සඳහා නම් කර ඇත. 26 වැදගත් නම්වල මූලය.",
      howBountiesWork: "පරිවර්තන ත්‍යාග ක්‍රියා කරන ආකාරය",
      step1Title: "ත්‍යාගය ඉල්ලා ගන්න",
      step1Body: "Help Wanted ෆලකයෙන් පරිවර්තන ත්‍යාගය විවෘත කරන්න.",
      step2Title: "පරිවර්තනය කර ඉදිරිපත් කරන්න",
      step2Body: "අවශ්‍ය සියලු strings පරිවර්තනය කරන්න. Bounty Poster හරහා ඉදිරිපත් කරන්න.",
      step3Title: "Marks උපයන්න",
      step3Body: "පිළිගැනීමෙන් පසු Marks ලැබේ. IP Ledger හි සටහන් කෙරේ.",
      hide: "සඟවන්න",
      why: "ඇයි?",
    },
    languageSwitcher: {
      changeLanguage: "භාෂාව වෙනස් කරන්න",
      selectLanguage: "භාෂාව තෝරන්න",
      quickEnglish: "ඉංග්‍රීසි",
      tip: "Durin's Door හි විවිධ භාෂා මුරපද භාවිත කරා අපූරු අත්දැකීම් විවෘත කරන්න!",
    },
  },
  "sd": {
    speakFriend: {
      title: "دوست چئو ۽ اندر اچو.",
      description: "لیانا بانیان هر ٻولي لاءِ کُلي بنيادي تي ٺاهي وئي آهي. هر ٻولي لاءِ هڪ ترجمو انعام آهي.",
      languages: "ٻوليون",
      openBounties: "کُلا انعام",
      marksAwarded: "Marks ڏنل آهن (شرڪت ٽوڪن)",
      provisional: "عارضي:",
      provisionalNotice: "ٻولين جي فهرست ۽ Marks جا ريٽ عارضي آهن. Marks شرڪت ٽوڪن آهن، حصص نه.",
      bountyOpen: "انعام کُلو آهي",
      claimed: "دعويٰ ڪئي وئي",
      complete: "مڪمل",
      translationBountyTitle: "ترجمي جو انعام",
      bountyDescription: "لیانا بانیان کي {{language}} ۾ ترجمو ڪريو. {{marks}} Marks حاصل ڪريو.",
      scopeWelcome: "ڀلي آيا / روح دنيا اسڪرين",
      scopeCueCards: "مُک اشارن ڪارڊ سيٽ",
      scopeNavigation: "نيويگيشن ليبلز ۽ غلطي پيغام",
      scopeWildfire: "Wildfire Beacon Run: ڪم ڳوليو",
      claimBounty: "هن ترجمي جي انعام جي دعويٰ ڪريو",
      baseLanguage: "بنيادي ٻولي -- ڪنهن انعام جي ضرورت نه.",
      claimedBy: "@{{handle}} پاران دعويٰ ڪئي -- جاري آهي.",
      marksProvisional: "{{marks}} Marks (عارضي)",
      speakFounderTitle: "بانيءَ جي آواز: اهي لفظ ڇو",
      speakFounderDesc: "هن پليٽ فارم تي هر اصطلاح هڪ سبب سان نامزد آهي. 26 اهم نالن جو اصل.",
      howBountiesWork: "ترجمي جا انعام ڪيئن ڪم ڪن ٿا",
      step1Title: "انعام جي دعويٰ ڪريو",
      step1Body: "Help Wanted بورڊ مان ترجمي جو انعام کوليو.",
      step2Title: "ترجمو ڪريو ۽ جمع ڪريو",
      step2Body: "ضروري سڀ اسٽرنگز ترجمو ڪريو. Bounty Poster ذريعي جمع ڪريو.",
      step3Title: "Marks حاصل ڪريو",
      step3Body: "قبوليت کان پوءِ Marks ملندا. IP Ledger ۾ درج ٿيندا.",
      hide: "لڪايو",
      why: "ڇو؟",
    },
    languageSwitcher: {
      changeLanguage: "ٻولي تبديل ڪريو",
      selectLanguage: "ٻولي چونڊيو",
      quickEnglish: "انگريزي",
      tip: "Durin's Door تي مختلف ٻولين جا پاسورڊ استعمال ڪريو!",
    },
  },
  "ku": {
    speakFriend: {
      title: "Beje dost, u bikeve.",
      description: "Liana Banyan ji bo her zimani vekirî hatiye cekirin. Her zimane vekirî xelatiyek wergerandinê heye.",
      languages: "ziman",
      openBounties: "xelatên vekirî",
      marksAwarded: "Marks hate dan (nisaneyên besdarbûnê)",
      provisional: "Demkî:",
      provisionalNotice: "Listeyên zimanan û rejeyên Marks demkî ne. Marks nisaneyên besdarbûnê ne, ne sermaye.",
      bountyOpen: "Xelat vekirî",
      claimed: "Tê daxwazkirinê",
      complete: "Temam",
      translationBountyTitle: "Xelata Wergerandinê",
      bountyDescription: "Liana Banyan bo {{language}} wergêrîne. {{marks}} Marks qezenç bike.",
      scopeWelcome: "Ekranên Xêrhatî / Cîhana Giyan",
      scopeCueCards: "Komika Kartên Rêberiyê",
      scopeNavigation: "Nîsaneyên navîgeriyê û peyamên cewtiyê",
      scopeWildfire: "Wildfire Beacon Run: Kar Bibîne",
      claimBounty: "Vê Xelata Wergerandinê Daxwaz Bike",
      baseLanguage: "Zimane bingehîn -- ne hewce xelat.",
      claimedBy: "@{{handle}} daxwaz kir -- di rê de.",
      marksProvisional: "{{marks}} Marks (demkî)",
      speakFounderTitle: "Denge Damezrîner: Cima Van Peyvan",
      speakFounderDesc: "Her têgeh di vê platformê de ji bo sedema xwe hatiye navkirin. Destpêka 26 navên herî girîng.",
      howBountiesWork: "Cawa Xelatên Wergerandinê Dixebitin",
      step1Title: "Xelat Daxwaz Bike",
      step1Body: "Xelata Wergerandinê ji Help Wanted veke.",
      step2Title: "Wergêrîne û Bisîne",
      step2Body: "Hemû rêzikên pêwist wergêrîne. Bi Bounty Poster bisîne.",
      step3Title: "Marks Qezenç Bike",
      step3Body: "Piştî pejirandinê, Marks distî û di IP Ledger de tê tomarkirin.",
      hide: "vesêre",
      why: "cima?",
    },
    languageSwitcher: {
      changeLanguage: "Zimanan biguheze",
      selectLanguage: "Ziman hilbijêre",
      quickEnglish: "Îngilîzî",
      tip: "Ji bo ezmûnên yekta li Deriyê Durin sîfreyên zimanan cûda bi kar bîne!",
    },
  },
  "kk": {
    speakFriend: {
      title: "Дос де, кір.",
      description: "Liana Banyan кез келген тіл үшін ашық болып жасалған. Әрбір ашық тілде бір аударма сыйлығы бар.",
      languages: "тілдер",
      openBounties: "ашық сыйлықтар",
      marksAwarded: "Marks берілді (қатысу токендері)",
      provisional: "Уақытша:",
      provisionalNotice: "Тілдер тізімі мен Marks мөлшерлемелері уақытша. Marks қатысу токендері, капитал емес.",
      bountyOpen: "Сыйлық ашық",
      claimed: "Талап етілді",
      complete: "Аяқталды",
      translationBountyTitle: "Аударма Сыйлығы",
      bountyDescription: "Liana Banyan-ды {{language}} тіліне аударыңыз. {{marks}} Marks табыңыз.",
      scopeWelcome: "Қош келдіңіз / Аруақтар Әлемі экрандары",
      scopeCueCards: "Негізгі кеңес карталары жиынтығы",
      scopeNavigation: "Навигация белгілері мен қате хабарлары",
      scopeWildfire: "Wildfire Beacon Run: Жұмыс тауып",
      claimBounty: "Осы аударма сыйлығын талап ету",
      baseLanguage: "Негізгі тіл -- сыйлық қажет емес.",
      claimedBy: "@{{handle}} талап етті -- жүріп жатыр.",
      marksProvisional: "{{marks}} Marks (уақытша)",
      speakFounderTitle: "Негізшінің дауысы: неліктен осы сөздер",
      speakFounderDesc: "Бұл платформадағы әрбір термин бір себеппен аталған. 26 маңызды атаудың шығу тегі.",
      howBountiesWork: "Аударма сыйлықтары қалай жұмыс істейді",
      step1Title: "Сыйлықты талап ету",
      step1Body: "Help Wanted тақтасынан аударма сыйлығын ашыңыз.",
      step2Title: "Аудару және жіберу",
      step2Body: "Барлық қажетті жолдарды аударыңыз. Bounty Poster арқылы жіберіңіз.",
      step3Title: "Marks табу",
      step3Body: "Қабылданғаннан кейін Marks аласыз. IP Ledger-ге тіркеледіңіз.",
      hide: "жасыру",
      why: "неге?",
    },
    languageSwitcher: {
      changeLanguage: "Тілді өзгерту",
      selectLanguage: "Тіл таңдаңыз",
      quickEnglish: "Ағылшын",
      tip: "Бірегей тәжірибелер үшін Дурин Есігінде әртүрлі тіл құпия сөздерін пайдаланыңыз!",
    },
  },
  "sn": {
    speakFriend: {
      title: "Ti shamwari, upinde.",
      description: "Liana Banyan yakavakwa kuti ivhurike kumitauro yose. Mutauro wose une mubayiro wekushandura.",
      languages: "mitauro",
      openBounties: "mibayiro yakavhurika",
      marksAwarded: "Marks yakapihwa (matokeni ekutora chikamu)",
      provisional: "Zvekutanga:",
      provisionalNotice: "Rondedzero yemitauro uye mibayiro ya Marks inogona kushanduka. Marks matokeni ekutora chikamu, kwete hisa.",
      bountyOpen: "Mubayiro wakavhurika",
      claimed: "Wakatambirwa",
      complete: "Yapera",
      translationBountyTitle: "Mubayiro weShanduro",
      bountyDescription: "Shandura Liana Banyan ku{{language}}. Wana Marks {{marks}}.",
      scopeWelcome: "Machinjikwa ekuMukirirei / Nyika yeZvinhu",
      scopeCueCards: "Seti yeKadhi reChikuva",
      scopeNavigation: "Zviratidzo zvekufamba uye meseji dzepamishonga",
      scopeWildfire: "Wildfire Beacon Run: Tsvaga Basa",
      claimBounty: "Tora Mubayiro uyu weShanduro",
      baseLanguage: "Mutauro wepasi -- hapana mubayiro unodikanwa.",
      claimedBy: "@{{handle}} akatora -- iri kufamba.",
      marksProvisional: "{{marks}} Marks (zvekutanga)",
      speakFounderTitle: "Inzwi reMuvambi: Nei Mashoko Aya",
      speakFounderDesc: "Shoko rega rega pane chirongwa ichi rakapihwa zita nemhaka. Mavambo emazita 26 akakosha.",
      howBountiesWork: "Mibayiro yeShanduro inoshanda sei",
      step1Title: "Tora Mubayiro",
      step1Body: "Vhura Mubayiro weShanduro kubva Help Wanted.",
      step2Title: "Shandura uye Tumira",
      step2Body: "Shandura mitsetse yose inodikanwa. Tumira neBounty Poster.",
      step3Title: "Wana Marks",
      step3Body: "Mushure mekugamuchirwa, unowana Marks uye unorekodwa pa IP Ledger.",
      hide: "vanza",
      why: "nei?",
    },
    languageSwitcher: {
      changeLanguage: "Shandura mutauro",
      selectLanguage: "Sarudza mutauro",
      quickEnglish: "Chirungu",
      tip: "Shandisa mapasiwedhi emitauro akasiyana paDoor yaDurin kuwana makamuri akakosha!",
    },
  },
  "mn": {
    speakFriend: {
      title: "Найз гэж хэлж ор.",
      description: "Liana Banyan нь аль ч хэлэнд нээлттэй байхаар баригдсан. Нэг бүр хэлэнд орчуулгын нэг урамшуулал байдаг.",
      languages: "хэлүүд",
      openBounties: "нээлттэй урамшуулал",
      marksAwarded: "Marks олгосон (оролцооны токен)",
      provisional: "Түр:",
      provisionalNotice: "Хэлний жагсаалт болон Marks-ийн хүү түр зуурынх. Marks оролцооны токен, хувьцаа биш.",
      bountyOpen: "Урамшуулал нээлттэй",
      claimed: "Нэхэмжилсэн",
      complete: "Дуусгасан",
      translationBountyTitle: "Орчуулгын Урамшуулал",
      bountyDescription: "Liana Banyan-ыг {{language}} хэлрүү орчуулна уу. {{marks}} Marks олох.",
      scopeWelcome: "Тавтай морил / Сүнсний Ертөнцийн дэлгэц",
      scopeCueCards: "Үндсэн Зөвлөмжийн Картуудын иж бүрдэл",
      scopeNavigation: "Навигацийн шошго ба алдааны мессеж",
      scopeWildfire: "Wildfire Beacon Run: Ажил ол",
      claimBounty: "Энэ Орчуулгын Урамшуулалыг нэхэмжилнэ үү",
      baseLanguage: "Үндсэн хэл -- урамшуулал хэрэгтэй биш.",
      claimedBy: "@{{handle}} нэхэмжилсэн -- явагдаж байна.",
      marksProvisional: "{{marks}} Marks (түр)",
      speakFounderTitle: "Үүсгэн байгуулагчийн дуу хоолой: Яагаад эдгээр үг",
      speakFounderDesc: "Энэ платформын тоо томшгүй нэр томьёо нь учиртай нэрлэгдсэн. 26 чухал нэрийн гарал.",
      howBountiesWork: "Орчуулгын Урамшуулал Хэрхэн Ажилладаг Вэ",
      step1Title: "Урамшуулал нэхэмжилнэ үү",
      step1Body: "Help Wanted самбараас Орчуулгын Урамшуулал нээнэ үү.",
      step2Title: "Орчуулж илгээнэ үү",
      step2Body: "Бүх шаардлагатай мөрийг орчуул. Bounty Poster-ийн урсгалаар илгээнэ үү.",
      step3Title: "Marks олно уу",
      step3Body: "Хүлээн авсны дараа Marks авна. IP Ledger-т бүртгэгдэнэ.",
      hide: "нуух",
      why: "яагаад?",
    },
    languageSwitcher: {
      changeLanguage: "Хэлийг солих",
      selectLanguage: "Хэл сонгоно уу",
      quickEnglish: "Англи",
      tip: "Онцгой туршлагуудыг нээхийн тулд Дурины хаалган дээр өөр өөр хэлний нууц үг ашиглаарай!",
    },
  },
  "bo": {
    speakFriend: {
      title: "གྲོགས་པོ་ཟེར་ནས་ཁ་ཡར་བཤད།",
      description: "ལིཡཱ་ན་བན་ཡཱན་ཞེས་པ་དེ་སྐད་ཡིག་ཐམས་ཅད་ལ་ཕྱེ་ནས་བཟོས་ཡོད། སྐད་ཡིག་རེར་ལོ་ཙཱ་བའི་གྲངས་ཤིག་ཡོད།",
      languages: "སྐད་ཡིག",
      openBounties: "ཕྱེ་བའི་གྲངས།",
      marksAwarded: "Marks ཕུལ་སོང་ (མཉམ་ཞུགས་ཀྱི་ཊོ་ཀེན)",
      provisional: "སྐབས་བཀོལ།",
      provisionalNotice: "སྐད་ཡིག་གི་རེའུ་མིག་དང་ Marks ཀྱི་ཚད་སྐབས་བཀོལ་ཡིན། Marks མཉམ་ཞུགས་ཀྱི་ཊོ་ཀེན་ཡིན།",
      bountyOpen: "གྲངས་ཕྱེ་ཡོད།",
      claimed: "གཏོང་ཞུ་བྱས།",
      complete: "ཚར་སོང།",
      translationBountyTitle: "ལོ་ཙཱའི་གྲངས།",
      bountyDescription: "ལིཡཱ་ན་བན་ཡཱན་ {{language}} ལ་ལོ་ཙཱ་བྱོས། {{marks}} Marks ཐོབ།",
      scopeWelcome: "གཤེགས་པ་ལེགས་སོ།",
      scopeCueCards: "གཞི་གནད་ཀྱི་ལག་རྟགས་ཚོགས་གྲས།",
      scopeNavigation: "འཛུལ་ལམ་ཀྱི་མཚན་གཞི་དང་ནོར་ཆ།",
      scopeWildfire: "Wildfire Beacon Run: ལས་ཀ་ལྟོས།",
      claimBounty: "ལོ་ཙཱའི་གྲངས་འདི་གཏོང་ཞུ།",
      baseLanguage: "གཞི་གནད་སྐད་ཡིག་ -- གྲངས་མི་དགོས།",
      claimedBy: "@{{handle}} གིས་གཏོང་ཞུ་བྱས་ -- བྱ་བ་བྱེད་བཞིན།",
      marksProvisional: "{{marks}} Marks (སྐབས་བཀོལ)",
      speakFounderTitle: "གཞི་བཙུགས་མཁན་གྱི་སྒྲ་ -- ཅིའི་ཕྱིར་ཚིག་འདི་རྣམས།",
      speakFounderDesc: "མིང་གི་རྒྱུ་མཚན་དང་ལྷན་བཀོད་ཡོད། གལ་ཆེའི་མིང་ ༢༦ ཀྱི་འབྱུང་ཁུངས།",
      howBountiesWork: "ལོ་ཙཱའི་གྲངས་ཇི་ལྟར་འཁྱེར།",
      step1Title: "གྲངས་གཏོང་ཞུ།",
      step1Body: "Help Wanted ལས་ལོ་ཙཱའི་གྲངས་ཕྱེ།",
      step2Title: "ལོ་ཙཱ་བྱས་ནས་ཕུལ།",
      step2Body: "ཡིག་ཆ་ཐམས་ཅད་ལོ་ཙཱ་བྱས་ Bounty Poster བརྒྱུད་ཕུལ།",
      step3Title: "Marks ཐོབ།",
      step3Body: "བལྟས་ནས་ Marks ཐོབ། IP Ledger ལ་བཀོད།",
      hide: "སྦས།",
      why: "ཅིའི་ཕྱིར།",
    },
    languageSwitcher: {
      changeLanguage: "སྐད་ཡིག་བཅོས།",
      selectLanguage: "སྐད་ཡིག་གདམ་།",
      quickEnglish: "དབྱིན་ཡིག",
      tip: "Durin གྱི་སྒོ་ལ་སྐད་ཡིག་མི་འདྲ་བའི་གསང་ཚིག་སྤྱོད།",
    },
  },
  "su": {
    speakFriend: {
      title: "Sebutkeun babaturan, tuluy asup.",
      description: "Liana Banyan diwangun pikeun muka pikeun unggal basa. Unggal basa anu muka miboga hiji hadiah tarjamahan.",
      languages: "basa",
      openBounties: "hadiah muka",
      marksAwarded: "Marks dianugrahkeun (token partisipasi)",
      provisional: "Samentawis:",
      provisionalNotice: "Daptar basa sareng tarif Marks samentawis. Marks token partisipasi, sanes ekuitas.",
      bountyOpen: "Hadiah muka",
      claimed: "Diklaim",
      complete: "Rengse",
      translationBountyTitle: "Hadiah Tarjamahan",
      bountyDescription: "Tarjamahkeun Liana Banyan kana {{language}}. Meunangkeun {{marks}} Marks.",
      scopeWelcome: "Layar Wilujeng Sumping / Dunya Jurig",
      scopeCueCards: "Set Kartu Isyarat Inti",
      scopeNavigation: "Label navigasi sareng pesen kasalahan",
      scopeWildfire: "Wildfire Beacon Run: Neangan Pagawean",
      claimBounty: "Klaim Hadiah Tarjamahan Ieu",
      baseLanguage: "Basa dasar -- teu butuh hadiah.",
      claimedBy: "@{{handle}} ngaklaim -- keur lumangsung.",
      marksProvisional: "{{marks}} Marks (samentawis)",
      speakFounderTitle: "Sora Pangdiri: Naha Kecap-kecap Ieu",
      speakFounderDesc: "Unggal istilah aya alesan ngaran na. Asal 26 ngaran anu paling penting.",
      howBountiesWork: "Kumaha Hadiah Tarjamahan Damel",
      step1Title: "Klaim Hadiah",
      step1Body: "Buka Hadiah Tarjamahan tina papan Help Wanted.",
      step2Title: "Tarjamah sareng Kirim",
      step2Body: "Tarjamahkeun sadaya string anu dibutuhkeun. Kirim via Bounty Poster.",
      step3Title: "Meunang Marks",
      step3Body: "Saatos ditampi, anjeun meunang Marks sareng dicatet di IP Ledger.",
      hide: "sumputkeun",
      why: "naha?",
    },
    languageSwitcher: {
      changeLanguage: "Ganti basa",
      selectLanguage: "Pilih basa",
      quickEnglish: "Inggris",
      tip: "Gunakeun kecap konci basa beda di Panto Durin pikeun muka pangalaman unik!",
    },
  },
  "bho": {
    speakFriend: {
      title: "दोस्त कहो अउर अंदर जाव।",
      description: "Liana Banyan हर भाषा खातिर खुला बनावल बा। हर भाषा खातिर एगो अनुवाद इनाम बा।",
      languages: "भाषा",
      openBounties: "खुला इनाम",
      marksAwarded: "Marks दिहल गइल (भागीदारी टोकन)",
      provisional: "अस्थाई:",
      provisionalNotice: "भाषा के लिस्ट आ Marks दर अस्थाई बा। Marks भागीदारी टोकन बा, शेयर ना।",
      bountyOpen: "इनाम खुला बा",
      claimed: "दावा कइल गइल",
      complete: "पूरा",
      translationBountyTitle: "अनुवाद इनाम",
      bountyDescription: "Liana Banyan के {{language}} में अनुवाद करीं। {{marks}} Marks कमाईं।",
      scopeWelcome: "स्वागत / भूत दुनिया स्क्रीन",
      scopeCueCards: "मुख्य क्यू कार्ड सेट",
      scopeNavigation: "नेविगेशन लेबल आ गलती संदेश",
      scopeWildfire: "Wildfire Beacon Run: नौकरी पाईं",
      claimBounty: "इ अनुवाद इनाम दावा करीं",
      baseLanguage: "मूल भाषा -- कउनो इनाम के जरूरत नइखे।",
      claimedBy: "@{{handle}} द्वारा दावा -- चालू बा।",
      marksProvisional: "{{marks}} Marks (अस्थाई)",
      speakFounderTitle: "संस्थापक के आवाज: ई शब्द काहे",
      speakFounderDesc: "इ प्लेटफार्म पर हर शब्द के नाम कारण से रखल बा। 26 महत्वपूर्ण नाम के मूल।",
      howBountiesWork: "अनुवाद इनाम कइसे काम करेला",
      step1Title: "इनाम दावा करीं",
      step1Body: "Help Wanted बोर्ड से अनुवाद इनाम खोलीं।",
      step2Title: "अनुवाद करीं आ जमा करीं",
      step2Body: "सब जरूरी स्ट्रिंग के अनुवाद करीं। Bounty Poster से जमा करीं।",
      step3Title: "Marks कमाईं",
      step3Body: "स्वीकार होला पर Marks मिली। IP Ledger में दर्ज होयीं।",
      hide: "लुकाईं",
      why: "काहे?",
    },
    languageSwitcher: {
      changeLanguage: "भाषा बदलीं",
      selectLanguage: "भाषा चुनीं",
      quickEnglish: "अंग्रेजी",
      tip: "Durin's Door पर अलग-अलग भाषा के पासवर्ड इस्तेमाल करीं!",
    },
  },
  "mai": {
    speakFriend: {
      title: "दोस्त कहू आ भीतर आबू।",
      description: "Liana Banyan हर भाषा लेल खुला बनाओल गेल छैक। हर भाषा लेल एकटा अनुवाद पुरस्कार छैक।",
      languages: "भाषा",
      openBounties: "खुला पुरस्कार",
      marksAwarded: "Marks देल गेल (सहभागिता टोकन)",
      provisional: "अस्थायी:",
      provisionalNotice: "भाषाक सूची आ Marks दर अस्थायी अछि। Marks सहभागिता टोकन अछि, शेयर नहि।",
      bountyOpen: "पुरस्कार खुला",
      claimed: "दावा कएल गेल",
      complete: "पूर्ण",
      translationBountyTitle: "अनुवाद पुरस्कार",
      bountyDescription: "Liana Banyan केँ {{language}} मे अनुवाद करू। {{marks}} Marks कमाउ।",
      scopeWelcome: "स्वागत / भूत दुनिया स्क्रीन",
      scopeCueCards: "मूल क्यू कार्ड सेट",
      scopeNavigation: "नेविगेशन लेबल आ त्रुटि संदेश",
      scopeWildfire: "Wildfire Beacon Run: काज पाबू",
      claimBounty: "इ अनुवाद पुरस्कार दावा करू",
      baseLanguage: "मूल भाषा -- पुरस्कारक आवश्यकता नहि।",
      claimedBy: "@{{handle}} द्वारा दावा -- जारी अछि।",
      marksProvisional: "{{marks}} Marks (अस्थायी)",
      speakFounderTitle: "संस्थापकक आवाज: एहि शब्दक कारण",
      speakFounderDesc: "एहि प्लेटफर्म पर हर शब्द कारणसँ नाम रखल गेल अछि। 26 महत्वपूर्ण नामक मूल।",
      howBountiesWork: "अनुवाद पुरस्कार कोना काज करैत अछि",
      step1Title: "पुरस्कार दावा करू",
      step1Body: "Help Wanted बोर्डसँ अनुवाद पुरस्कार खोलू।",
      step2Title: "अनुवाद करू आ जमा करू",
      step2Body: "सभ आवश्यक स्ट्रिंग अनुवाद करू। Bounty Poster द्वारा जमा करू।",
      step3Title: "Marks कमाउ",
      step3Body: "स्वीकृति पर Marks भेटत। IP Ledger मे दर्ज भेल।",
      hide: "लुकाउ",
      why: "किएक?",
    },
    languageSwitcher: {
      changeLanguage: "भाषा बदलू",
      selectLanguage: "भाषा चुनू",
      quickEnglish: "अंग्रेजी",
      tip: "Durin's Door पर भिन्न भाषाक पासवर्ड उपयोग करू!",
    },
  },
  "ro": {
    speakFriend: {
      title: "Spune prieten si intra.",
      description: "Liana Banyan este construita sa fie deschisa fiecarei limbi. Fiecare limba are o recompensa de traducere.",
      languages: "limbi",
      openBounties: "recompense deschise",
      marksAwarded: "Marks acordate (token-uri de participare)",
      provisional: "Provizoriu:",
      provisionalNotice: "Lista limbilor si ratele Marks sunt provizorii. Marks sunt token-uri de participare, nu actiuni.",
      bountyOpen: "Recompensa deschisa",
      claimed: "Revendicata",
      complete: "Complet",
      translationBountyTitle: "Recompensa de Traducere",
      bountyDescription: "Traduceti Liana Banyan in {{language}}. Castigati {{marks}} Marks la acceptare.",
      scopeWelcome: "Ecrane de Bun venit / Lumea Fantomelor",
      scopeCueCards: "Set de Carduri de Sfaturi de Baza",
      scopeNavigation: "Etichete de navigare si mesaje de eroare",
      scopeWildfire: "Wildfire Beacon Run: Gaseste un Job",
      claimBounty: "Revendicati aceasta Recompensa de Traducere",
      baseLanguage: "Limba de baza -- nu este nevoie de recompensa.",
      claimedBy: "Recompensa revendicata de @{{handle}} -- in curs.",
      marksProvisional: "{{marks}} Marks (provizoriu)",
      speakFounderTitle: "Vocea Fondatorului: De ce Aceste Cuvinte",
      speakFounderDesc: "Fiecare termen din aceasta platforma este denumit cu un motiv. Originea celor 26 de nume importante.",
      howBountiesWork: "Cum Functioneaza Recompensele de Traducere",
      step1Title: "Revendica Recompensa",
      step1Body: "Deschide o Recompensa de Traducere din panoul Help Wanted.",
      step2Title: "Traduci si Trimite",
      step2Body: "Traduceti toate sirurile necesare. Trimiteti prin fluxul Bounty Poster.",
      step3Title: "Castiga Marks",
      step3Body: "Dupa acceptare primesti Marks si esti inregistrat in IP Ledger.",
      hide: "ascunde",
      why: "de ce?",
    },
    languageSwitcher: {
      changeLanguage: "Schimba limba",
      selectLanguage: "Selecteaza limba",
      quickEnglish: "Engleza",
      tip: "Foloseste parole in limbi diferite la Usa lui Durin pentru a debloca experiente unice!",
    },
  },
  "zu": {
    speakFriend: {
      title: "Sithi umngane, ungenele.",
      description: "I-Liana Banyan yakhiwe ukuvuliwa kulimi lonke. Ulimi ngalunye oluvuliwe lunobhizi bokuhumusha.",
      languages: "izilimi",
      openBounties: "amabhizi avuliwe",
      marksAwarded: "Marks anikwe (amatoken okubambela)",
      provisional: "Okwesikhashana:",
      provisionalNotice: "Uhlu lwezilimi namazinga e-Marks okwesikhashana. Marks amatoken okubambela, hhayi amahlandla.",
      bountyOpen: "Ibhizi livuliwe",
      claimed: "Kukhanyelwe",
      complete: "Kuphelele",
      translationBountyTitle: "Ibhizi lokuHumusha",
      bountyDescription: "Humusha i-Liana Banyan ngolimi lwe-{{language}}. Thola {{marks}} Marks.",
      scopeWelcome: "Ama-screen Wamukelekile / Izwe Lamadlozi",
      scopeCueCards: "Isampula se-Cue Card Esiyinhloko",
      scopeNavigation: "Izilebula zokukhomba kanye nemilayezo yamaphutha",
      scopeWildfire: "Wildfire Beacon Run: Thola Umsebenzi",
      claimBounty: "Khanyela le-Bhizi lokuHumusha",
      baseLanguage: "Ulimi lwesisekelo -- akudingeki bhizi.",
      claimedBy: "@{{handle}} wakhanyela -- uyaqhubeka.",
      marksProvisional: "{{marks}} Marks (okwesikhashana)",
      speakFounderTitle: "Izwi LoMsunguli: Kungani Lamagama",
      speakFounderDesc: "Igama ngalinye kuleli nkundla lanikwa ibizo ngezizathu. Imvelaphi yamagama ayi-26 abalulekile.",
      howBountiesWork: "Amabhizi OkuHumusha Asebenza Kanjani",
      step1Title: "Khanyela Ibhizi",
      step1Body: "Vula i-Bhizi lokuHumusha kwi-Help Wanted.",
      step2Title: "Humusha bese Uthumela",
      step2Body: "Humusha zonke izichazelo ezidzingekayo. Thumela nge-Bounty Poster.",
      step3Title: "Thola Marks",
      step3Body: "Uma samukela, uthola Marks futhi urekhodi ku-IP Ledger.",
      hide: "fihla",
      why: "kungani?",
    },
    languageSwitcher: {
      changeLanguage: "Shintsha ulimi",
      selectLanguage: "Khetha ulimi",
      quickEnglish: "IsiNgisi",
      tip: "Sebenzisa amagama aphethe ezilimi ezihlukene eMnyango kaDurin ukuvula izinto ezikhethekile!",
    },
  },
  "cs": {
    speakFriend: {
      title: "Rekni pritel a vstup.",
      description: "Liana Banyan je vystavena otevrene pro kazdy jazyk. Kazdy otevreny jazyk ma jednu prekladatelskou odmenu.",
      languages: "jazyky",
      openBounties: "otevrene odmeny",
      marksAwarded: "Marks udeleny (tokeny ucasti)",
      provisional: "Prozatimni:",
      provisionalNotice: "Seznam jazyku a sazby Marks jsou prozatimni. Marks jsou tokeny ucasti, nikoli akcie.",
      bountyOpen: "Odmena otevrena",
      claimed: "Narokovana",
      complete: "Dokonceno",
      translationBountyTitle: "Prekladatelska Odmena",
      bountyDescription: "Prelozit Liana Banyan do {{language}}. Ziskat {{marks}} Marks po prijeti.",
      scopeWelcome: "Obrazovky Vitejte / Svet Duchu",
      scopeCueCards: "Sada Zakladnich Karet Napovedy",
      scopeNavigation: "Navigacni stitky a chybove zpravy",
      scopeWildfire: "Wildfire Beacon Run: Najdi praci",
      claimBounty: "Narokovat tuto Prekladatelskou Odmenu",
      baseLanguage: "Zakladni jazyk -- odmena neni potreba.",
      claimedBy: "Odmena narokovana @{{handle}} -- probiha.",
      marksProvisional: "{{marks}} Marks (prozatimni)",
      speakFounderTitle: "Hlas Zakladatele: Proc Tato Slova",
      speakFounderDesc: "Kazdy pojem na teto platforme je pojmenovan z duvodu. Puvod 26 nejdulezitejsich jmen.",
      howBountiesWork: "Jak Funguji Prekladatelske Odmeny",
      step1Title: "Narokovat Odmenu",
      step1Body: "Otevrit Prekladatelskou Odmenu z nastenne Help Wanted.",
      step2Title: "Prelozit a Odeslat",
      step2Body: "Prelozit vsechny potrebne retezce. Odeslat prostrednictvim Bounty Poster.",
      step3Title: "Ziskat Marks",
      step3Body: "Po prijeti dostanete Marks a jste zaznamenani v IP Ledger.",
      hide: "skryt",
      why: "proc?",
    },
    languageSwitcher: {
      changeLanguage: "Zmenit jazyk",
      selectLanguage: "Vybrat jazyk",
      quickEnglish: "Anglictina",
      tip: "Pouzijte ruzna jazykova hesla u Durinovych dveri pro odemceni jedinecnych zazitku!",
    },
  },
  "el": {
    speakFriend: {
      title: "Πες φίλος και μπες.",
      description: "Η Liana Banyan έχει κατασκευαστεί για να είναι ανοιχτή σε κάθε γλώσσα. Κάθε ανοιχτή γλώσσα έχει ένα βραβείο μετάφρασης.",
      languages: "γλώσσες",
      openBounties: "ανοιχτά βραβεία",
      marksAwarded: "Marks απονεμήθηκαν (μάρκες συμμετοχής)",
      provisional: "Προσωρινά:",
      provisionalNotice: "Η λίστα γλωσσών και οι τιμές Marks είναι προσωρινές. Τα Marks είναι μάρκες συμμετοχής, όχι μετοχές.",
      bountyOpen: "Βραβείο ανοιχτό",
      claimed: "Διεκδικήθηκε",
      complete: "Ολοκληρώθηκε",
      translationBountyTitle: "Βραβείο Μετάφρασης",
      bountyDescription: "Μεταφράστε το Liana Banyan σε {{language}}. Κερδίστε {{marks}} Marks μετά την αποδοχή.",
      scopeWelcome: "Οθόνες Καλωσορίσματος / Κόσμος Φαντασμάτων",
      scopeCueCards: "Βασικό Σετ Καρτών Υπόδειξης",
      scopeNavigation: "Ετικέτες πλοήγησης και μηνύματα σφάλματος",
      scopeWildfire: "Wildfire Beacon Run: Βρες Δουλειά",
      claimBounty: "Διεκδίκηση αυτού του Βραβείου Μετάφρασης",
      baseLanguage: "Βασική γλώσσα -- δεν χρειάζεται βραβείο.",
      claimedBy: "Το βραβείο διεκδικήθηκε από @{{handle}} -- σε εξέλιξη.",
      marksProvisional: "{{marks}} Marks (προσωρινά)",
      speakFounderTitle: "Φωνή Ιδρυτή: Γιατί Αυτές οι Λέξεις",
      speakFounderDesc: "Κάθε όρος σε αυτήν την πλατφόρμα ονομάζεται για κάποιο λόγο. Προέλευση των 26 πιο σημαντικών ονομάτων.",
      howBountiesWork: "Πώς Λειτουργούν τα Βραβεία Μετάφρασης",
      step1Title: "Διεκδίκηση Βραβείου",
      step1Body: "Ανοίξτε ένα Βραβείο Μετάφρασης από τον πίνακα Help Wanted.",
      step2Title: "Μεταφράστε και Υποβάλετε",
      step2Body: "Μεταφράστε όλες τις απαραίτητες συμβολοσειρές. Υποβάλετε μέσω Bounty Poster.",
      step3Title: "Κερδίστε Marks",
      step3Body: "Μετά την αποδοχή, λαμβάνετε Marks και καταχωρείστε στο IP Ledger.",
      hide: "απόκρυψη",
      why: "γιατί;",
    },
    languageSwitcher: {
      changeLanguage: "Αλλαγή γλώσσας",
      selectLanguage: "Επιλογή γλώσσας",
      quickEnglish: "Αγγλικά",
      tip: "Χρησιμοποιήστε κωδικούς γλώσσας στην Πύλη του Δουρίν για να ξεκλειδώσετε μοναδικές εμπειρίες!",
    },
  },
  "hu": {
    speakFriend: {
      title: "Mondj barat, es lepj be.",
      description: "A Liana Banyan nyitottnak van megepitve minden nyelv szamara. Minden nyitott nyelvhez van egy forditasi jutalom.",
      languages: "nyelvek",
      openBounties: "nyitott jutalmak",
      marksAwarded: "Marks juttatva (reszveteli tokenek)",
      provisional: "Ideiglenes:",
      provisionalNotice: "A nyelvek listaja es a Marks-aranyok ideiglenesek. A Marks reszveteli tokenek, nem reszveny.",
      bountyOpen: "Jutalom nyitott",
      claimed: "Igénybe véve",
      complete: "Befejezve",
      translationBountyTitle: "Forditasi Jutalom",
      bountyDescription: "Forditsa le a Liana Banyan-t {{language}} nyelvre. Keresson {{marks}} Marks-ot elfogadaskor.",
      scopeWelcome: "Udvozlo / Szellemvilag kepernyo",
      scopeCueCards: "Alap jelzokartya-keszlet",
      scopeNavigation: "Navigacios feliratok es hibaüzenetek",
      scopeWildfire: "Wildfire Beacon Run: Talalj Munkat",
      claimBounty: "Igenyelje ezt a Forditasi Jutalmat",
      baseLanguage: "Alap nyelv -- nincs szukseg jutalomra.",
      claimedBy: "A jutalmat @{{handle}} igenyelge -- folyamatban.",
      marksProvisional: "{{marks}} Marks (ideiglenes)",
      speakFounderTitle: "Alapito Hangja: Miert Ezek a Szavak",
      speakFounderDesc: "A platform minden kifejezese egy okkal van elnevezve. A 26 legfontosabb nev eredete.",
      howBountiesWork: "Hogyan Mukodnek a Forditasi Jutalmak",
      step1Title: "Igenyelje a Jutalmat",
      step1Body: "Nyisson egy Forditasi Jutalmat a Help Wanted tablan.",
      step2Title: "Forditson es Nyujtson be",
      step2Body: "Forditson le minden szukseges karakterlancot. Nyujtson be a Bounty Poster folyamaton.",
      step3Title: "Marks Keresese",
      step3Body: "Elfogadas utan Marks-ot kap es rogzitve van az IP Ledger-ben.",
      hide: "elrejt",
      why: "miert?",
    },
    languageSwitcher: {
      changeLanguage: "Nyelv modositasa",
      selectLanguage: "Valasszon nyelvet",
      quickEnglish: "Angol",
      tip: "Kulonbozo nyelvi jelszavakat hasznaljon Durin Kapujanal egyedi elmenyek eleresehez!",
    },
  },
  "hr": {
    speakFriend: {
      title: "Reci prijatelj i udi.",
      description: "Liana Banyan izgradujena je da bude otvorena za svaki jezik. Svaki otvoreni jezik ima jednu nagradu za prijevod.",
      languages: "jezici",
      openBounties: "otvorene nagrade",
      marksAwarded: "Marks dodijeljeni (zetoni sudjelovanja)",
      provisional: "Privremeno:",
      provisionalNotice: "Popis jezika i stope Marks su privremeni. Marks su zetoni sudjelovanja, ne dionice.",
      bountyOpen: "Nagrada otvorena",
      claimed: "Zatrazeno",
      complete: "Dovrseno",
      translationBountyTitle: "Nagrada za Prijevod",
      bountyDescription: "Prevedite Liana Banyan na {{language}}. Zaradite {{marks}} Marks.",
      scopeWelcome: "Zasloni Dobrodoslice / Svijet Duhova",
      scopeCueCards: "Osnovni skup kartica s uputama",
      scopeNavigation: "Navigacijske oznake i poruke o pogresci",
      scopeWildfire: "Wildfire Beacon Run: Nadi Posao",
      claimBounty: "Zatrazite ovu Nagradu za Prijevod",
      baseLanguage: "Temeljni jezik -- ne treba nagrada.",
      claimedBy: "Nagradu zatrazio @{{handle}} -- u tijeku.",
      marksProvisional: "{{marks}} Marks (privremeno)",
      speakFounderTitle: "Glas Osnivaca: Zasto Ove Rijeci",
      speakFounderDesc: "Svaki pojam na ovoj platformi imenovan je s razlogom. Podrijetlo 26 najvaznijih naziva.",
      howBountiesWork: "Kako Rade Nagrade za Prijevod",
      step1Title: "Zatrazite Nagradu",
      step1Body: "Otvorite Nagradu za Prijevod s ploce Help Wanted.",
      step2Title: "Prevedite i Posaljite",
      step2Body: "Prevedite sve potrebne nizove. Posaljite putem Bounty Poster.",
      step3Title: "Zaradite Marks",
      step3Body: "Nakon prihvacanja dobivate Marks i evidentirani ste u IP Ledger.",
      hide: "sakrij",
      why: "zasto?",
    },
    languageSwitcher: {
      changeLanguage: "Promijeni jezik",
      selectLanguage: "Odaberi jezik",
      quickEnglish: "Engleski",
      tip: "Koristite lozinke razlicitih jezika na Durinovim Vratima za jedinstvena iskustva!",
    },
  },
  "sr": {
    speakFriend: {
      title: "Реци пријатељ и уђи.",
      description: "Liana Banyan је изграђена да буде отворена за сваки језик. Сваки отворени језик има једну награду за превод.",
      languages: "језици",
      openBounties: "отворене награде",
      marksAwarded: "Marks додељени (жетони учешћа)",
      provisional: "Привремено:",
      provisionalNotice: "Списак језика и стопе Marks су привремени. Marks су жетони учешћа, не акције.",
      bountyOpen: "Награда отворена",
      claimed: "Затражено",
      complete: "Завршено",
      translationBountyTitle: "Награда за Превод",
      bountyDescription: "Преведите Liana Banyan на {{language}}. Зарадите {{marks}} Marks.",
      scopeWelcome: "Екрани Добродошлице / Свет Духова",
      scopeCueCards: "Основни скуп картица са упутствима",
      scopeNavigation: "Навигациони ознаке и поруке о грешкама",
      scopeWildfire: "Wildfire Beacon Run: Нађи Посао",
      claimBounty: "Затражите ову Награду за Превод",
      baseLanguage: "Основни језик -- не треба награда.",
      claimedBy: "Награду затражио @{{handle}} -- у току.",
      marksProvisional: "{{marks}} Marks (привремено)",
      speakFounderTitle: "Глас Оснивача: Зашто Ове Речи",
      speakFounderDesc: "Сваки термин на овој платформи именован је са разлогом. Порекло 26 најважнијих назива.",
      howBountiesWork: "Kako Rade Награде за Превод",
      step1Title: "Затражите Награду",
      step1Body: "Отворите Награду за Превод са табле Help Wanted.",
      step2Title: "Преведите и Пошаљите",
      step2Body: "Преведите све потребне низове. Пошаљите путем Bounty Poster.",
      step3Title: "Зарадите Marks",
      step3Body: "Након прихватања добијате Marks и евидентирани сте у IP Ledger.",
      hide: "сакриј",
      why: "зашто?",
    },
    languageSwitcher: {
      changeLanguage: "Промени језик",
      selectLanguage: "Одабери језик",
      quickEnglish: "Енглески",
      tip: "Користите лозинке различитих језика на Дуриновим Вратима за јединствена искуства!",
    },
  },
  "bs": {
    speakFriend: {
      title: "Reci prijatelju i udi.",
      description: "Liana Banyan je izgradujena da bude otvorena za svaki jezik. Svaki otvoreni jezik ima jednu nagradu za prijevod.",
      languages: "jezici",
      openBounties: "otvorene nagrade",
      marksAwarded: "Marks dodijeljeni (zetoni sudjelovanja)",
      provisional: "Privremeno:",
      provisionalNotice: "Popis jezika i stope Marks su privremene. Marks su zetoni sudjelovanja, ne dionice.",
      bountyOpen: "Nagrada otvorena",
      claimed: "Zatrazeno",
      complete: "Dovrseno",
      translationBountyTitle: "Nagrada za Prijevod",
      bountyDescription: "Prevedite Liana Banyan na {{language}}. Zaradite {{marks}} Marks.",
      scopeWelcome: "Ekrani Dobrodoslice / Svijet Duhova",
      scopeCueCards: "Osnovni skup kartica s uputama",
      scopeNavigation: "Navigacijske oznake i poruke o greskama",
      scopeWildfire: "Wildfire Beacon Run: Nadi Posao",
      claimBounty: "Zatrazite ovu Nagradu za Prijevod",
      baseLanguage: "Temeljni jezik -- ne treba nagrada.",
      claimedBy: "Nagradu zatrazio @{{handle}} -- u toku.",
      marksProvisional: "{{marks}} Marks (privremeno)",
      speakFounderTitle: "Glas Osnivaca: Zasto Ove Rijeci",
      speakFounderDesc: "Svaki pojam na ovoj platformi imenovan je s razlogom. Porijeklo 26 najvaznijih naziva.",
      howBountiesWork: "Kako Rade Nagrade za Prijevod",
      step1Title: "Zatrazite Nagradu",
      step1Body: "Otvorite Nagradu za Prijevod s table Help Wanted.",
      step2Title: "Prevedite i Posaljite",
      step2Body: "Prevedite sve potrebne nizove. Posaljite putem Bounty Poster.",
      step3Title: "Zaradite Marks",
      step3Body: "Nakon prihvacanja dobijate Marks i evidentirani ste u IP Ledger.",
      hide: "sakrij",
      why: "zasto?",
    },
    languageSwitcher: {
      changeLanguage: "Promijeni jezik",
      selectLanguage: "Odaberi jezik",
      quickEnglish: "Engleski",
      tip: "Koristite lozinke razlicitih jezika na Durinovim Vratima za jedinstvena iskustva!",
    },
  },
  "rw": {
    speakFriend: {
      title: "Vuga inshuti, winjire.",
      description: "Liana Banyan yubatswe kugira ngo ifunguke ku rurimi rwose. Ururimi rwose rufunguye rufite igihembo kimwe cy'ubusobanuro.",
      languages: "indimi",
      openBounties: "ibihembo bifunguye",
      marksAwarded: "Marks yahawe (ibimenyetso by'intagatifu)",
      provisional: "By'agateganyo:",
      provisionalNotice: "Urutonde rw'indimi n'ingano z'Marks ni by'agateganyo. Marks ni ibimenyetso by'intagatifu, si imigabane.",
      bountyOpen: "Igihembo gifunguye",
      claimed: "Cyabajijwe",
      complete: "Byarangiye",
      translationBountyTitle: "Igihembo cy'Ubusobanuro",
      bountyDescription: "Sobanura Liana Banyan mu {{language}}. Unguka {{marks}} Marks.",
      scopeWelcome: "Ibigaragaza Murakaza neza / Isi y'Amazimu",
      scopeCueCards: "Urutonde rw'Amakarita y'Amabwiriza Nshingiro",
      scopeNavigation: "Impano z'inzira n'ubutumwa bw'amakosa",
      scopeWildfire: "Wildfire Beacon Run: Shaka Akazi",
      claimBounty: "Saba Iki Gihembo cy'Ubusobanuro",
      baseLanguage: "Ururimi rw'ibanze -- nta gihembo gikenewe.",
      claimedBy: "@{{handle}} yasabye -- biragenda.",
      marksProvisional: "{{marks}} Marks (by'agateganyo)",
      speakFounderTitle: "Ijwi ry'Umushinga: Impamvu y'Aya Magambo",
      speakFounderDesc: "Ijambo ryose muri iyi sisitemu ryatowe n'impamvu. Inkomoko ya mazina 26 y'ingenzi.",
      howBountiesWork: "Ibihembo by'Ubusobanuro Bigenda Bite",
      step1Title: "Saba Igihembo",
      step1Body: "Fungura Igihembo cy'Ubusobanuro ku kibaho Help Wanted.",
      step2Title: "Sobanura Ukoheze",
      step2Body: "Sobanura imigabane yose ikenewe. Ohereza ukoresheje Bounty Poster.",
      step3Title: "Unguka Marks",
      step3Body: "Nyuma yo kwemererwa, uzahabwa Marks kandi uzandikwe muri IP Ledger.",
      hide: "hisha",
      why: "impamvu iki?",
    },
    languageSwitcher: {
      changeLanguage: "Hindura ururimi",
      selectLanguage: "Hitamo ururimi",
      quickEnglish: "Icyongereza",
      tip: "Koresha imihango y'indimi zitandukanye ku Muryango wa Durin kugira ngo ukingure uburambe budasanzwe!",
    },
  },
};
