"use strict";
// tdata-a.cjs -- Machine translations Group A (languages 1-27)
// bn ur id sw mr te tr yue ta vi fa ha th gu am kn pa jv or yo ml ms uz ig my ne ps
module.exports = {
  "bn": {
    speakFriend: {
      title: "বন্ধু বলো, এবং প্রবেশ করো।",
      description: "লিয়ানা বানিয়ান সকল ভাষার জন্য উন্মুক্ত। প্রতিটি ভাষার জন্য একটি অনুবাদ বাউন্টি রয়েছে। Marks অর্জন করুন।",
      languages: "ভাষা",
      openBounties: "খোলা বাউন্টি",
      marksAwarded: "Marks প্রদান (অংশগ্রহণ টোকেন)",
      provisional: "অস্থায়ী:",
      provisionalNotice: "ভাষার তালিকা ও Marks হার অস্থায়ী। Marks অংশগ্রহণ টোকেন -- ইকুইটি নয়, আর্থিক স্বার্থ নেই।",
      bountyOpen: "বাউন্টি খোলা",
      claimed: "দাবি করা হয়েছে",
      complete: "সম্পূর্ণ",
      translationBountyTitle: "অনুবাদ বাউন্টি",
      bountyDescription: "লিয়ানা বানিয়ান {{language}} ভাষায় অনুবাদ করুন। গৃহীত হলে {{marks}} Marks অর্জন করুন।",
      scopeWelcome: "স্বাগত / ভূত বিশ্বের স্ক্রিন",
      scopeCueCards: "মূল কিউ কার্ড সেট (অর্থনৈতিক আইন + শাসন)",
      scopeNavigation: "নেভিগেশন লেবেল ও ত্রুটি বার্তা",
      scopeWildfire: "ওয়াইল্ডফায়ার বিকন রান: চাকরি পান",
      claimBounty: "এই অনুবাদ বাউন্টি দাবি করুন",
      baseLanguage: "মূল ভাষা -- কোনো বাউন্টি নেই।",
      claimedBy: "@{{handle}} দ্বারা দাবি -- চলমান।",
      marksProvisional: "{{marks}} Marks (অস্থায়ী)",
      speakFounderTitle: "প্রতিষ্ঠাতার বক্তব্য: কেন এই শব্দগুলো",
      speakFounderDesc: "এই প্ল্যাটফর্মের প্রতিটি শব্দ একটি কারণে নামকরণ। ২৬টি নামের উৎস।",
      howBountiesWork: "বাউন্টি কীভাবে কাজ করে",
      step1Title: "বাউন্টি দাবি করুন",
      step1Body: "Help Wanted বোর্ড থেকে অনুবাদ বাউন্টি নিন।",
      step2Title: "অনুবাদ করুন ও জমা দিন",
      step2Body: "সমস্ত স্ট্রিং অনুবাদ করে Bounty Poster ফ্লোতে জমা দিন।",
      step3Title: "Marks অর্জন করুন",
      step3Body: "গৃহীত হলে Marks পাবেন। IP Ledger-এ নথিভুক্ত হবেন।",
      hide: "লুকান",
      why: "কেন?",
    },
    languageSwitcher: {
      changeLanguage: "ভাষা পরিবর্তন করুন",
      selectLanguage: "ভাষা নির্বাচন করুন",
      quickEnglish: "ইংরেজি",
      tip: "Durin's Door-এ ভিন্ন ভাষার পাসওয়ার্ড ব্যবহার করুন অনন্য অভিজ্ঞতা আনলক করতে!",
    },
  },
  "ur": {
    speakFriend: {
      title: "دوست کہو، اور داخل ہو۔",
      description: "لیانا بانیان ہر زبان کے لیے کھلی ہے۔ ہر زبان کا ترجمہ انعام موجود ہے۔",
      languages: "زبانیں",
      openBounties: "کھلے انعام",
      marksAwarded: "Marks دیے گئے (شرکت ٹوکن)",
      provisional: "عارضی:",
      provisionalNotice: "زبانوں کی فہرست اور Marks کی شرحیں عارضی ہیں۔ Marks شرکت ٹوکن ہیں، حصص نہیں۔",
      bountyOpen: "انعام کھلا ہے",
      claimed: "دعوی کیا گیا",
      complete: "مکمل",
      translationBountyTitle: "ترجمہ انعام",
      bountyDescription: "لیانا بانیان {{language}} میں ترجمہ کریں۔ قبولیت پر {{marks}} Marks کمائیں۔",
      scopeWelcome: "خوش آمدید / بھوت دنیا کی اسکرینیں",
      scopeCueCards: "مرکزی کیو کارڈ سیٹ (اقتصادی قوانین + گورننس)",
      scopeNavigation: "نیویگیشن لیبل اور ایرر پیغامات",
      scopeWildfire: "وائلڈ فائر بیکن رن: نوکری حاصل کریں",
      claimBounty: "یہ ترجمہ انعام دعوی کریں",
      baseLanguage: "بنیادی زبان -- کوئی انعام ضروری نہیں۔",
      claimedBy: "@{{handle}} نے دعوی کیا -- جاری ہے۔",
      marksProvisional: "{{marks}} Marks (عارضی)",
      speakFounderTitle: "بانی کی آواز: یہ الفاظ کیوں",
      speakFounderDesc: "اس پلیٹ فارم کا ہر لفظ ایک وجہ سے نامزد ہے۔ ۲۶ اہم ناموں کی اصل۔",
      howBountiesWork: "انعام کیسے کام کرتے ہیں",
      step1Title: "انعام دعوی کریں",
      step1Body: "Help Wanted بورڈ سے ترجمہ انعام کھولیں۔",
      step2Title: "ترجمہ کریں اور جمع کریں",
      step2Body: "تمام ضروری تار کا ترجمہ کریں اور Bounty Poster فلو سے جمع کریں۔",
      step3Title: "Marks کمائیں",
      step3Body: "قبولیت پر Marks ملیں گے۔ IP Ledger میں درج ہوں گے۔",
      hide: "چھپائیں",
      why: "کیوں؟",
    },
    languageSwitcher: {
      changeLanguage: "زبان تبدیل کریں",
      selectLanguage: "زبان منتخب کریں",
      quickEnglish: "انگریزی",
      tip: "Durin's Door پر مختلف زبانوں کے پاس ورڈ استعمال کریں!",
    },
  },
  "id": {
    speakFriend: {
      title: "Ucapkan teman, dan masuklah.",
      description: "Liana Banyan terbuka untuk semua bahasa. Setiap bahasa memiliki satu hadiah terjemahan.",
      languages: "bahasa",
      openBounties: "hadiah terbuka",
      marksAwarded: "Marks diberikan (token partisipasi)",
      provisional: "Sementara:",
      provisionalNotice: "Daftar bahasa dan tarif Marks bersifat sementara. Marks adalah token partisipasi, bukan ekuitas.",
      bountyOpen: "Hadiah terbuka",
      claimed: "Diklaim",
      complete: "Selesai",
      translationBountyTitle: "Hadiah Terjemahan",
      bountyDescription: "Terjemahkan Liana Banyan ke {{language}}. Dapatkan {{marks}} Marks setelah diterima.",
      scopeWelcome: "Layar Selamat Datang / Dunia Hantu",
      scopeCueCards: "Set Kartu Isyarat Inti (Hukum Ekonomi + Tata Kelola)",
      scopeNavigation: "Label navigasi dan pesan kesalahan",
      scopeWildfire: "Wildfire Beacon Run: Cari Kerja (tur masuk)",
      claimBounty: "Klaim Hadiah Terjemahan Ini",
      baseLanguage: "Bahasa dasar -- tidak perlu hadiah.",
      claimedBy: "Hadiah diklaim oleh @{{handle}} -- sedang berlangsung.",
      marksProvisional: "{{marks}} Marks (sementara)",
      speakFounderTitle: "Suara Pendiri: Mengapa Kata-Kata Ini",
      speakFounderDesc: "Setiap istilah di platform ini dinamai dengan alasan. Asal usul 26 nama terpenting.",
      howBountiesWork: "Cara Kerja Hadiah Terjemahan",
      step1Title: "Klaim Hadiahnya",
      step1Body: "Buka Hadiah Terjemahan dari papan Help Wanted.",
      step2Title: "Terjemahkan dan Kirim",
      step2Body: "Terjemahkan semua string yang diperlukan dan kirim melalui alur Bounty Poster.",
      step3Title: "Dapatkan Marks",
      step3Body: "Setelah diterima, Anda mendapat Marks dan tercatat di IP Ledger.",
      hide: "sembunyikan",
      why: "mengapa?",
    },
    languageSwitcher: {
      changeLanguage: "Ganti bahasa",
      selectLanguage: "Pilih bahasa",
      quickEnglish: "Inggris",
      tip: "Gunakan kata sandi berbahasa berbeda di Durin's Door untuk membuka pengalaman unik!",
    },
  },
  "sw": {
    speakFriend: {
      title: "Sema rafiki, na uingie.",
      description: "Liana Banyan imejengwa kufungua kwa kila lugha. Kila lugha ina tuzo moja ya tafsiri.",
      languages: "lugha",
      openBounties: "tuzo wazi",
      marksAwarded: "Marks iliyotolewa (tokeni za ushiriki)",
      provisional: "Ya muda:",
      provisionalNotice: "Orodha ya lugha na viwango vya Marks ni ya muda. Marks ni tokeni za ushiriki, si hisa.",
      bountyOpen: "Tuzo wazi",
      claimed: "Imedaiwa",
      complete: "Imekamilika",
      translationBountyTitle: "Tuzo ya Tafsiri",
      bountyDescription: "Tafsiri Liana Banyan kwa {{language}}. Pata {{marks}} Marks baada ya kukubaliwa.",
      scopeWelcome: "Skrini za Karibu / Dunia ya Pepo",
      scopeCueCards: "Seti kuu ya Kadi za Vidokezo (Sheria za Uchumi + Utawala)",
      scopeNavigation: "Lebo za urambazaji na ujumbe wa makosa",
      scopeWildfire: "Wildfire Beacon Run: Pata Kazi (ziara ya kuingia)",
      claimBounty: "Dai Tuzo Hii ya Tafsiri",
      baseLanguage: "Lugha ya msingi -- hakuna tuzo inayohitajika.",
      claimedBy: "Tuzo imedaiwa na @{{handle}} -- inaendelea.",
      marksProvisional: "{{marks}} Marks (ya muda)",
      speakFounderTitle: "Sauti ya Mwanzilishi: Kwa Nini Maneno Haya",
      speakFounderDesc: "Kila neno katika mfumo huu limepewa jina kwa sababu. Asili ya majina 26 muhimu.",
      howBountiesWork: "Jinsi Tuzo za Tafsiri Zinavyofanya Kazi",
      step1Title: "Dai Tuzo",
      step1Body: "Fungua Tuzo ya Tafsiri kutoka kwenye ubao wa Help Wanted.",
      step2Title: "Tafsiri na Wasilisha",
      step2Body: "Tafsiri masharti yote yanayohitajika na uwasilishe kupitia mtiririko wa Bounty Poster.",
      step3Title: "Pata Marks",
      step3Body: "Baada ya kukubaliwa, unapata Marks na unarekodiwa katika IP Ledger.",
      hide: "ficha",
      why: "kwa nini?",
    },
    languageSwitcher: {
      changeLanguage: "Badilisha lugha",
      selectLanguage: "Chagua lugha",
      quickEnglish: "Kiingereza",
      tip: "Tumia nywila za lugha tofauti kwenye Mlango wa Durin kufungua uzoefu wa kipekee!",
    },
  },
  "mr": {
    speakFriend: {
      title: "मित्र म्हणा आणि आत या।",
      description: "लियाना बानयान प्रत्येक भाषेसाठी खुले आहे. प्रत्येक भाषेसाठी भाषांतर बाउंटी आहे.",
      languages: "भाषा",
      openBounties: "खुल्या बाउंटी",
      marksAwarded: "Marks दिले (सहभाग टोकन)",
      provisional: "तात्पुरते:",
      provisionalNotice: "भाषांची यादी व Marks दर तात्पुरते आहेत. Marks सहभाग टोकन, इक्विटी नाही.",
      bountyOpen: "बाउंटी खुली",
      claimed: "दावा केला",
      complete: "पूर्ण",
      translationBountyTitle: "भाषांतर बाउंटी",
      bountyDescription: "लियाना बानयान {{language}} मध्ये भाषांतरित करा. {{marks}} Marks मिळवा.",
      scopeWelcome: "स्वागत / भूत जग स्क्रीन",
      scopeCueCards: "मूळ क्यू कार्ड संच (आर्थिक कायदे + शासन)",
      scopeNavigation: "नेव्हिगेशन लेबल्स आणि त्रुटी संदेश",
      scopeWildfire: "वाइल्डफायर बीकन रन: नोकरी मिळवा",
      claimBounty: "ही भाषांतर बाउंटी दावा करा",
      baseLanguage: "मूळ भाषा -- कोणती बाउंटी नाही.",
      claimedBy: "बाउंटी @{{handle}} ने दावा केली -- चालू.",
      marksProvisional: "{{marks}} Marks (तात्पुरते)",
      speakFounderTitle: "संस्थापकाचे बोल: या शब्दांचे कारण",
      speakFounderDesc: "या प्लॅटफॉर्मवरील प्रत्येक शब्द कारणासाठी नामित. २६ नावांचे मूळ.",
      howBountiesWork: "बाउंटी कशा काम करतात",
      step1Title: "बाउंटी दावा करा",
      step1Body: "Help Wanted बोर्डवरून भाषांतर बाउंटी उघडा.",
      step2Title: "भाषांतर करा आणि सादर करा",
      step2Body: "सर्व आवश्यक स्ट्रिंग भाषांतरित करा. Bounty Poster फ्लोद्वारे सादर करा.",
      step3Title: "Marks मिळवा",
      step3Body: "स्वीकृतीनंतर Marks मिळतात. IP Ledger मध्ये नोंद होते.",
      hide: "लपवा",
      why: "का?",
    },
    languageSwitcher: {
      changeLanguage: "भाषा बदला",
      selectLanguage: "भाषा निवडा",
      quickEnglish: "इंग्रजी",
      tip: "Durin's Door वर वेगवेगळ्या भाषांचे पासवर्ड वापरा!",
    },
  },
  "te": {
    speakFriend: {
      title: "స్నేహితుడా అని చెప్పి లోపలికి రా.",
      description: "లియానా బన్యాన్ అన్ని భాషలకు తెరిచి ఉంది. ప్రతి భాషకు ఒక అనువాద బౌంటీ ఉంది.",
      languages: "భాషలు",
      openBounties: "తెరిచిన బౌంటీలు",
      marksAwarded: "Marks అందించారు (భాగస్వామ్య టోకెన్లు)",
      provisional: "తాత్కాలిక:",
      provisionalNotice: "భాషల జాబితా మరియు Marks రేట్లు తాత్కాలికంగా ఉన్నాయి. Marks భాగస్వామ్య టోకెన్లు, వాటాలు కావు.",
      bountyOpen: "బౌంటీ తెరిచి ఉంది",
      claimed: "క్లెయిమ్ చేశారు",
      complete: "పూర్తయింది",
      translationBountyTitle: "అనువాద బౌంటీ",
      bountyDescription: "లియానా బన్యాన్‌ను {{language}}లోకి అనువదించండి. {{marks}} Marks సంపాదించండి.",
      scopeWelcome: "స్వాగతం / ఘోస్ట్ వరల్డ్ స్క్రీన్లు",
      scopeCueCards: "ముఖ్య క్యూ కార్డ్ సెట్ (ఆర్థిక చట్టాలు + పాలన)",
      scopeNavigation: "నావిగేషన్ లేబుల్స్ మరియు లోపాల సందేశాలు",
      scopeWildfire: "వైల్డ్‌ఫైర్ బీకన్ రన్: ఉద్యోగం పొందండి",
      claimBounty: "ఈ అనువాద బౌంటీని క్లెయిమ్ చేయండి",
      baseLanguage: "ప్రాథమిక భాష -- బౌంటీ అవసరం లేదు.",
      claimedBy: "@{{handle}} క్లెయిమ్ చేశారు -- పురోగతిలో ఉంది.",
      marksProvisional: "{{marks}} Marks (తాత్కాలిక)",
      speakFounderTitle: "వ్యవస్థాపకుని స్వరం: ఈ పదాలు ఎందుకు",
      speakFounderDesc: "ఈ ప్లాట్‌ఫామ్‌లో ప్రతి పదానికి ఒక కారణం ఉంది. 26 ముఖ్యమైన పేర్ల మూలం.",
      howBountiesWork: "బౌంటీలు ఎలా పని చేస్తాయి",
      step1Title: "బౌంటీ క్లెయిమ్ చేయండి",
      step1Body: "Help Wanted బోర్డు నుండి అనువాద బౌంటీ తెరవండి.",
      step2Title: "అనువదించండి మరియు సమర్పించండి",
      step2Body: "అన్ని అవసరమైన స్ట్రింగ్‌లను అనువదించి Bounty Poster ద్వారా సమర్పించండి.",
      step3Title: "Marks సంపాదించండి",
      step3Body: "ఆమోదించిన తర్వాత Marks పొందుతారు. IP Ledger లో నమోదు అవుతారు.",
      hide: "దాచు",
      why: "ఎందుకు?",
    },
    languageSwitcher: {
      changeLanguage: "భాష మార్చండి",
      selectLanguage: "భాష ఎంచుకోండి",
      quickEnglish: "ఇంగ్లీష్",
      tip: "ప్రత్యేక అనుభవాలు పొందడానికి Durin's Door వద్ద వేర్వేరు భాష పాస్‌వర్డ్‌లు ఉపయోగించండి!",
    },
  },
  "tr": {
    speakFriend: {
      title: "Dost de ve gir.",
      description: "Liana Banyan her dile açık kurulmuştur. Her açık dil için bir çeviri ödülü var.",
      languages: "dil",
      openBounties: "açık ödüller",
      marksAwarded: "Marks verildi (katılım tokenleri)",
      provisional: "Geçici:",
      provisionalNotice: "Dil listesi ve Marks oranları geçici olarak işleniyor. Marks katılım tokenleri, hisse değil.",
      bountyOpen: "Ödül açık",
      claimed: "Talep edildi",
      complete: "Tamamlandı",
      translationBountyTitle: "Çeviri Ödülü",
      bountyDescription: "Liana Banyan'ı {{language}} diline çevirin. Kabul üzerine {{marks}} Marks kazanın.",
      scopeWelcome: "Hoş Geldiniz / Hayalet Dünya ekranları",
      scopeCueCards: "Temel İpucu Kartı seti (Ekonomik Yasalar + Yönetim)",
      scopeNavigation: "Navigasyon etiketleri ve hata mesajları",
      scopeWildfire: "Wildfire Beacon Run: İş Bul (giriş turu)",
      claimBounty: "Bu Çeviri Ödülünü Talep Et",
      baseLanguage: "Temel dil -- ödül gerekmiyor.",
      claimedBy: "Ödül @{{handle}} tarafından talep edildi -- devam ediyor.",
      marksProvisional: "{{marks}} Marks (geçici)",
      speakFounderTitle: "Kurucu'nun Sesi: Bu Kelimeler Neden",
      speakFounderDesc: "Bu platformdaki her terim bir nedenle adlandırılmıştır. 26 önemli ismin kökeni.",
      howBountiesWork: "Çeviri Ödülleri Nasıl Çalışır",
      step1Title: "Ödülü Talep Et",
      step1Body: "Help Wanted panosundan Çeviri Ödülünü açın.",
      step2Title: "Çevir ve Gönder",
      step2Body: "Tüm gereken dizeleri çevirin ve Bounty Poster akışıyla gönderin.",
      step3Title: "Marks Kazan",
      step3Body: "Kabul üzerine Marks alırsınız ve IP Ledger'a kaydedilirsiniz.",
      hide: "gizle",
      why: "neden?",
    },
    languageSwitcher: {
      changeLanguage: "Dil değiştir",
      selectLanguage: "Dil seç",
      quickEnglish: "İngilizce",
      tip: "Benzersiz deneyimler için Durin'in Kapısı'nda farklı dil şifreleri kullanın!",
    },
  },
  "yue": {
    speakFriend: {
      title: "講朋友，然後入嚟。",
      description: "Liana Banyan 對所有語言開放。每種語言有一個翻譯賞金。",
      languages: "語言",
      openBounties: "開放賞金",
      marksAwarded: "Marks 已發放（參與代幣）",
      provisional: "暫定:",
      provisionalNotice: "語言列表及 Marks 匯率暫定。Marks 係參與代幣，唔係股權。",
      bountyOpen: "賞金開放",
      claimed: "已認領",
      complete: "完成",
      translationBountyTitle: "翻譯賞金",
      bountyDescription: "將 Liana Banyan 翻譯成 {{language}}。獲接受後賺取 {{marks}} Marks。",
      scopeWelcome: "歡迎 / 鬼世界畫面",
      scopeCueCards: "核心提示卡套裝（經濟法則 + 管治）",
      scopeNavigation: "導航標籤及錯誤訊息",
      scopeWildfire: "Wildfire Beacon Run: 搵工（入門導覽）",
      claimBounty: "認領呢個翻譯賞金",
      baseLanguage: "基礎語言——唔需要賞金。",
      claimedBy: "賞金已由 @{{handle}} 認領——進行中。",
      marksProvisional: "{{marks}} Marks（暫定）",
      speakFounderTitle: "創辦人心聲：點解揀呢啲詞",
      speakFounderDesc: "平台每個術語都有原因。26 個最重要名稱嘅起源。",
      howBountiesWork: "翻譯賞金點樣運作",
      step1Title: "認領賞金",
      step1Body: "從 Help Wanted 板開啟翻譯賞金。",
      step2Title: "翻譯並提交",
      step2Body: "翻譯所有所需字串，透過 Bounty Poster 流程提交。",
      step3Title: "賺取 Marks",
      step3Body: "獲接受後，你收到 Marks，貢獻記錄於 IP Ledger。",
      hide: "隱藏",
      why: "點解？",
    },
    languageSwitcher: {
      changeLanguage: "更改語言",
      selectLanguage: "選擇語言",
      quickEnglish: "英文",
      tip: "喺 Durin 之門使用唔同語言密碼，解鎖獨特體驗！",
    },
  },
  "ta": {
    speakFriend: {
      title: "நண்பன் என்று சொல்லி உள்ளே வா.",
      description: "லியானா பன்யான் அனைத்து மொழிகளுக்கும் திறந்தது. ஒவ்வொரு மொழிக்கும் ஒரு மொழிபெயர்ப்பு பரிசு உள்ளது.",
      languages: "மொழிகள்",
      openBounties: "திறந்த பரிசுகள்",
      marksAwarded: "Marks வழங்கப்பட்டது (பங்கேற்பு டோக்கன்கள்)",
      provisional: "தற்காலிக:",
      provisionalNotice: "மொழிப் பட்டியல் மற்றும் Marks விகிதங்கள் தற்காலிகமானவை. Marks பங்கேற்பு டோக்கன்கள், பங்கு அல்ல.",
      bountyOpen: "பரிசு திறந்தது",
      claimed: "கோரப்பட்டது",
      complete: "முழுமை",
      translationBountyTitle: "மொழிபெயர்ப்பு பரிசு",
      bountyDescription: "லியானா பன்யானை {{language}} மொழிக்கு மொழிபெயர்க்கவும். {{marks}} Marks சம்பாதிக்கவும்.",
      scopeWelcome: "வரவேற்பு / பேய் உலக திரைகள்",
      scopeCueCards: "முக்கிய குறிப்பு அட்டை தொகுப்பு (பொருளாதார சட்டங்கள் + ஆட்சி)",
      scopeNavigation: "வழிசெலுத்தல் முத்திரைகள் மற்றும் பிழை செய்திகள்",
      scopeWildfire: "வைல்ட்ஃபயர் பீக்கன் ரன்: வேலை கிடைக்கும்",
      claimBounty: "இந்த மொழிபெயர்ப்பு பரிசைக் கோரவும்",
      baseLanguage: "அடிப்படை மொழி -- பரிசு தேவையில்லை.",
      claimedBy: "@{{handle}} கோரினார் -- நடக்கிறது.",
      marksProvisional: "{{marks}} Marks (தற்காலிக)",
      speakFounderTitle: "நிறுவனர் குரல்: இந்த வார்த்தைகள் ஏன்",
      speakFounderDesc: "இந்த தளத்தில் ஒவ்வொரு சொல்லும் ஒரு காரணத்தால் பெயரிடப்பட்டது. 26 முக்கிய பெயர்களின் தோற்றம்.",
      howBountiesWork: "மொழிபெயர்ப்பு பரிசுகள் எப்படி வேலை செய்கின்றன",
      step1Title: "பரிசைக் கோரவும்",
      step1Body: "Help Wanted பலகையிலிருந்து மொழிபெயர்ப்பு பரிசை திறக்கவும்.",
      step2Title: "மொழிபெயர்த்து சமர்ப்பிக்கவும்",
      step2Body: "தேவையான அனைத்து வரிகளையும் மொழிபெயர்க்கவும். Bounty Poster வழியாக சமர்ப்பிக்கவும்.",
      step3Title: "Marks சம்பாதிக்கவும்",
      step3Body: "ஏற்றுக்கொள்ளப்பட்டால் Marks கிடைக்கும். IP Ledger-ல் பதிவாகும்.",
      hide: "மறை",
      why: "ஏன்?",
    },
    languageSwitcher: {
      changeLanguage: "மொழி மாற்றவும்",
      selectLanguage: "மொழி தேர்ந்தெடுக்கவும்",
      quickEnglish: "ஆங்கிலம்",
      tip: "Durin's Door-ல் வேர்வேறு மொழி கடவுச்சொற்களை பயன்படுத்துங்கள்!",
    },
  },
  "vi": {
    speakFriend: {
      title: "Nói bạn, và bước vào.",
      description: "Liana Banyan được xây dựng để mở với mọi ngôn ngữ. Mỗi ngôn ngữ có một phần thưởng dịch thuật.",
      languages: "ngôn ngữ",
      openBounties: "phần thưởng mở",
      marksAwarded: "Marks được trao (token tham gia)",
      provisional: "Tạm thời:",
      provisionalNotice: "Danh sách ngôn ngữ và tỷ lệ Marks là tạm thời. Marks là token tham gia, không phải cổ phần.",
      bountyOpen: "Phần thưởng mở",
      claimed: "Đã nhận",
      complete: "Hoàn thành",
      translationBountyTitle: "Phần Thưởng Dịch Thuật",
      bountyDescription: "Dịch Liana Banyan sang {{language}}. Kiếm {{marks}} Marks khi được chấp nhận.",
      scopeWelcome: "Màn hình Chào mừng / Thế giới Ma",
      scopeCueCards: "Bộ Thẻ Gợi ý Cốt lõi (Luật Kinh tế + Quản trị)",
      scopeNavigation: "Nhãn điều hướng và thông báo lỗi",
      scopeWildfire: "Wildfire Beacon Run: Tìm Việc (tour nhập môn)",
      claimBounty: "Nhận Phần Thưởng Dịch Thuật Này",
      baseLanguage: "Ngôn ngữ cơ sở -- không cần phần thưởng.",
      claimedBy: "Phần thưởng đã được @{{handle}} nhận -- đang tiến hành.",
      marksProvisional: "{{marks}} Marks (tạm thời)",
      speakFounderTitle: "Tiếng Sáng Lập Viên: Tại Sao Những Từ Này",
      speakFounderDesc: "Mỗi thuật ngữ trên nền tảng này được đặt tên có lý do. Nguồn gốc 26 tên quan trọng nhất.",
      howBountiesWork: "Cách Thức Hoạt Động Của Phần Thưởng Dịch Thuật",
      step1Title: "Nhận Phần Thưởng",
      step1Body: "Mở Phần Thưởng Dịch Thuật từ bảng Help Wanted.",
      step2Title: "Dịch và Nộp",
      step2Body: "Dịch tất cả các chuỗi cần thiết. Nộp qua luồng Bounty Poster.",
      step3Title: "Kiếm Marks",
      step3Body: "Khi được chấp nhận, bạn nhận Marks và được ghi vào IP Ledger.",
      hide: "ẩn",
      why: "tại sao?",
    },
    languageSwitcher: {
      changeLanguage: "Đổi ngôn ngữ",
      selectLanguage: "Chọn ngôn ngữ",
      quickEnglish: "Tiếng Anh",
      tip: "Sử dụng mật khẩu ngôn ngữ khác nhau tại Cổng Durin để mở khóa trải nghiệm độc đáo!",
    },
  },
  "fa": {
    speakFriend: {
      title: "بگو دوست، و وارد شو.",
      description: "لیانا بنیان برای همه زبان‌ها ساخته شده است. هر زبان یک جایزه ترجمه دارد.",
      languages: "زبان‌ها",
      openBounties: "جوایز باز",
      marksAwarded: "Marks اعطا شد (توکن‌های مشارکت)",
      provisional: "موقت:",
      provisionalNotice: "فهرست زبان‌ها و نرخ‌های Marks موقتی است. Marks توکن‌های مشارکت هستند، نه سهام.",
      bountyOpen: "جایزه باز",
      claimed: "ادعا شده",
      complete: "کامل",
      translationBountyTitle: "جایزه ترجمه",
      bountyDescription: "لیانا بنیان را به {{language}} ترجمه کنید. {{marks}} Marks دریافت کنید.",
      scopeWelcome: "صفحات خوش‌آمدگویی / دنیای روح",
      scopeCueCards: "مجموعه کارت‌های راهنما (قوانین اقتصادی + حکمرانی)",
      scopeNavigation: "برچسب‌های ناوبری و پیام‌های خطا",
      scopeWildfire: "Wildfire Beacon Run: کار پیدا کن",
      claimBounty: "این جایزه ترجمه را ادعا کنید",
      baseLanguage: "زبان پایه -- نیازی به جایزه نیست.",
      claimedBy: "جایزه توسط @{{handle}} ادعا شده -- در جریان.",
      marksProvisional: "{{marks}} Marks (موقت)",
      speakFounderTitle: "صدای بنیان‌گذار: چرا این کلمات",
      speakFounderDesc: "هر اصطلاح در این پلتفرم دلیلی دارد. ریشه 26 نام مهم‌ترین.",
      howBountiesWork: "نحوه کار جوایز ترجمه",
      step1Title: "جایزه را ادعا کنید",
      step1Body: "یک جایزه ترجمه از تابلوی Help Wanted باز کنید.",
      step2Title: "ترجمه کنید و ارسال کنید",
      step2Body: "همه رشته‌های مورد نیاز را ترجمه کنید و از طریق جریان Bounty Poster ارسال کنید.",
      step3Title: "Marks کسب کنید",
      step3Body: "پس از پذیرش، Marks دریافت می‌کنید و در IP Ledger ثبت می‌شوید.",
      hide: "پنهان",
      why: "چرا؟",
    },
    languageSwitcher: {
      changeLanguage: "تغییر زبان",
      selectLanguage: "انتخاب زبان",
      quickEnglish: "انگلیسی",
      tip: "برای تجربه‌های منحصربه‌فرد از رمزهای عبور زبان مختلف در درب دورین استفاده کنید!",
    },
  },
  "ha": {
    speakFriend: {
      title: "Ce aboki, ka shiga.",
      description: "An gina Liana Banyan don bude wa kowane harshe. Kowane harshe yana da lada ta fassara.",
      languages: "harsuna",
      openBounties: "lada a bude",
      marksAwarded: "An ba da Marks (alamun shiga)",
      provisional: "Na wucin-gadi:",
      provisionalNotice: "Jerin harsunan da kimar Marks na wucin-gadi ne. Marks alamun shiga ne, ba hannun jari ba.",
      bountyOpen: "Lada a bude",
      claimed: "An yi ikrari",
      complete: "Cikakke",
      translationBountyTitle: "Ladan Fassara",
      bountyDescription: "Fassara Liana Banyan zuwa {{language}}. Samu Marks {{marks}} bayan karba.",
      scopeWelcome: "Allon Barka da zuwa / Duniyar Ruhu",
      scopeCueCards: "Babban saitin Katin Jagora (Dokokin Tattalin Arziki + Mulki)",
      scopeNavigation: "Lakabi na kewayawa da sakonnin kuskure",
      scopeWildfire: "Wildfire Beacon Run: Samu Aiki",
      claimBounty: "Yi ikrarin wannan Ladan Fassara",
      baseLanguage: "Asalin harshe -- babu lada da ake bukata.",
      claimedBy: "An yi ikrarin ladan ta @{{handle}} -- yana ci gaba.",
      marksProvisional: "Marks {{marks}} (na wucin-gadi)",
      speakFounderTitle: "Muryar Wanda Ya Kafa: Me Ya Sa Kalmomi Haka",
      speakFounderDesc: "Kowace kalma a wannan dandalin an sanya mata suna da dalili. Asalin sunayen 26 mafi mahimmanci.",
      howBountiesWork: "Yadda Ladajen Fassara Ke Aiki",
      step1Title: "Yi Ikrarin Lada",
      step1Body: "Bude Ladan Fassara daga allon Help Wanted.",
      step2Title: "Yi Fassara kuma Ka Tura",
      step2Body: "Fassara duk kirtani da ake bukata. Tura ta hanyar saiti na Bounty Poster.",
      step3Title: "Samu Marks",
      step3Body: "Bayan karba, kuna samun Marks kuma ana rikodin ku a IP Ledger.",
      hide: "boye",
      why: "me ya sa?",
    },
    languageSwitcher: {
      changeLanguage: "Canza harshe",
      selectLanguage: "Zabi harshe",
      quickEnglish: "Turanci",
      tip: "Yi amfani da kalmomin wucewar harshe daban-daban a Kofar Durin don bude kwarewa ta musamman!",
    },
  },
  "th": {
    speakFriend: {
      title: "พูดว่าเพื่อน แล้วเข้ามา",
      description: "Liana Banyan สร้างขึ้นเพื่อเปิดทุกภาษา ภาษาที่เปิดแต่ละภาษามีรางวัลการแปล",
      languages: "ภาษา",
      openBounties: "รางวัลที่เปิดอยู่",
      marksAwarded: "ได้รับ Marks (โทเค็นการมีส่วนร่วม)",
      provisional: "ชั่วคราว:",
      provisionalNotice: "รายการภาษาและอัตรา Marks เป็นการชั่วคราว Marks คือโทเค็นการมีส่วนร่วม ไม่ใช่หุ้น",
      bountyOpen: "รางวัลเปิดอยู่",
      claimed: "อ้างสิทธิ์แล้ว",
      complete: "สมบูรณ์",
      translationBountyTitle: "รางวัลการแปล",
      bountyDescription: "แปล Liana Banyan เป็น {{language}} รับ {{marks}} Marks เมื่อได้รับการยอมรับ",
      scopeWelcome: "หน้าจอยินดีต้อนรับ / โลกผี",
      scopeCueCards: "ชุดบัตรคำแนะนำหลัก (กฎเศรษฐศาสตร์ + การกำกับดูแล)",
      scopeNavigation: "ป้ายนำทางและข้อความข้อผิดพลาด",
      scopeWildfire: "Wildfire Beacon Run: หางาน (ทัวร์เข้า)",
      claimBounty: "อ้างสิทธิ์รางวัลการแปลนี้",
      baseLanguage: "ภาษาพื้นฐาน -- ไม่ต้องการรางวัล",
      claimedBy: "@{{handle}} อ้างสิทธิ์แล้ว -- กำลังดำเนินการ",
      marksProvisional: "{{marks}} Marks (ชั่วคราว)",
      speakFounderTitle: "เสียงผู้ก่อตั้ง: ทำไมถึงเลือกคำเหล่านี้",
      speakFounderDesc: "ทุกคำในแพลตฟอร์มนี้มีเหตุผลในการตั้งชื่อ ต้นกำเนิดของ 26 ชื่อสำคัญที่สุด",
      howBountiesWork: "วิธีการทำงานของรางวัลการแปล",
      step1Title: "อ้างสิทธิ์รางวัล",
      step1Body: "เปิดรางวัลการแปลจากกระดาน Help Wanted",
      step2Title: "แปลและส่ง",
      step2Body: "แปลสตริงที่ต้องการทั้งหมด ส่งผ่านขั้นตอน Bounty Poster",
      step3Title: "รับ Marks",
      step3Body: "เมื่อได้รับการยอมรับ คุณได้รับ Marks และบันทึกใน IP Ledger",
      hide: "ซ่อน",
      why: "ทำไม?",
    },
    languageSwitcher: {
      changeLanguage: "เปลี่ยนภาษา",
      selectLanguage: "เลือกภาษา",
      quickEnglish: "ภาษาอังกฤษ",
      tip: "ใช้รหัสผ่านภาษาต่างๆ ที่ประตู Durin เพื่อปลดล็อคประสบการณ์พิเศษ!",
    },
  },
  "gu": {
    speakFriend: {
      title: "મિત્ર કહો અને અંદર આવો.",
      description: "Liana Banyan દરેક ભાષા માટે ખુલ્લી છે. દરેક ભાષા માટે એક અનુવાદ ઇનામ છે.",
      languages: "ભાષાઓ",
      openBounties: "ખુલ્લા ઇનામ",
      marksAwarded: "Marks આપ્યા (ભાગીદારી ટોકન)",
      provisional: "અસ્થાઈ:",
      provisionalNotice: "ભાષાઓની સૂચિ અને Marks દર અસ્થાઈ છે. Marks ભાગીદારી ટોકન છે, ઇક્વિટી નહીં.",
      bountyOpen: "ઇનામ ખુલ્લું",
      claimed: "દાવો કર્યો",
      complete: "પૂર્ણ",
      translationBountyTitle: "અનુવાદ ઇનામ",
      bountyDescription: "Liana Banyan ને {{language}} માં અનુવાદ કરો. {{marks}} Marks કમાઓ.",
      scopeWelcome: "સ્વાગત / ભૂત વિશ્વ સ્ક્રીન",
      scopeCueCards: "મૂળ ક્યુ કાર્ડ સેટ (આર્થિક કાયદા + ગવર્નન્સ)",
      scopeNavigation: "નેવિગેશન લેબલ્સ અને ભૂલ સંદેશ",
      scopeWildfire: "Wildfire Beacon Run: નોકરી મળે",
      claimBounty: "આ અનુવાદ ઇનામ માટે દાવો કરો",
      baseLanguage: "આધાર ભાષા -- કોઈ ઇનામ ની જરૂર નથી.",
      claimedBy: "@{{handle}} દ્વારા દાવો -- ચાલુ છે.",
      marksProvisional: "{{marks}} Marks (અસ્થાઈ)",
      speakFounderTitle: "સ્થાપકની આવાઝ: આ શબ્દો કેમ",
      speakFounderDesc: "આ પ્લેટફોર્મ પર દરેક શબ્દ કોઈ કારણ સાથે નામ આપ્યો છે. 26 મહત્વના નામોની ઉત્પત્તિ.",
      howBountiesWork: "અનુવાદ ઇનામ કેવી રીતે કામ કરે છે",
      step1Title: "ઇનામ માટે દાવો",
      step1Body: "Help Wanted બોર્ડ પરથી અનુવાદ ઇનામ ખોલો.",
      step2Title: "અનુવાદ કરો અને સબમિટ કરો",
      step2Body: "બધી જરૂરી સ્ટ્રિંગ્સ અનુવાદ કરો. Bounty Poster ફ્લો દ્વારા સબમિટ કરો.",
      step3Title: "Marks કમાઓ",
      step3Body: "સ્વીકૃતિ પછી Marks મળે. IP Ledger માં નોંધ થઈ.",
      hide: "છુપાવો",
      why: "કેમ?",
    },
    languageSwitcher: {
      changeLanguage: "ભાષા બદલો",
      selectLanguage: "ભાષા પસંદ કરો",
      quickEnglish: "અંગ્રેજી",
      tip: "Durin's Door પર વિવિધ ભાષા પાસવર્ડ વાપરો!",
    },
  },
  "am": {
    speakFriend: {
      title: "ወዳጅ ብለህ ግባ።",
      description: "ሊያና ባንያን ለሁሉም ቋንቋዎች ክፍት ነው። ለእያንዳንዱ ቋንቋ አንድ ትርጉም ሽልማት አለ።",
      languages: "ቋንቋዎች",
      openBounties: "ክፍት ሽልማቶች",
      marksAwarded: "Marks ተሰጥቷል (የተሳትፎ ቶኬን)",
      provisional: "ጊዜያዊ:",
      provisionalNotice: "የቋንቋ ዝርዝር እና Marks ዋጋ ጊዜያዊ ናቸው። Marks የተሳትፎ ቶኬን ናቸው፣ ድርሻ አይደሉም።",
      bountyOpen: "ሽልማት ክፍት ነው",
      claimed: "ተጠይቋል",
      complete: "ተጠናቋል",
      translationBountyTitle: "የትርጉም ሽልማት",
      bountyDescription: "ሊያና ባንያንን ወደ {{language}} ተርጉሙ። {{marks}} Marks ያካሂዳሉ።",
      scopeWelcome: "እንኳን ደህና መጡ / የምትባ ዓለም ስክሪን",
      scopeCueCards: "ዋና የፍንጭ ካርድ ስብስብ (የኢኮኖሚ ሕጎች + አስተዳደር)",
      scopeNavigation: "የአሰሳ መለያዎች እና የስህተት መልዕክቶች",
      scopeWildfire: "Wildfire Beacon Run: ሥራ ፈልጉ",
      claimBounty: "ይህን የትርጉም ሽልማት ጠይቁ",
      baseLanguage: "መሠረታዊ ቋንቋ -- ሽልማት አያስፈልግም።",
      claimedBy: "@{{handle}} ጠየቁ -- በሂደት ላይ።",
      marksProvisional: "{{marks}} Marks (ጊዜያዊ)",
      speakFounderTitle: "የመስራቹ ድምፅ: ለምን እነዚህ ቃላቶች",
      speakFounderDesc: "ይህ መድረክ ላይ እያንዳንዱ ቃል ምክንያት አለው። 26 ዋና ስሞች ምንጭ።",
      howBountiesWork: "የትርጉም ሽልማቶች እንዴት ይሰራሉ",
      step1Title: "ሽልማቱን ጠይቁ",
      step1Body: "ከ Help Wanted ሰሌዳ የትርጉም ሽልማት ክፈቱ።",
      step2Title: "ተርጉሙ እና ያስረክቡ",
      step2Body: "ሁሉ የሚያስፈልጉ ሕብረቁምፊዎች ተርጉሙ። Bounty Poster በኩል ያስረክቡ።",
      step3Title: "Marks ያካሂዱ",
      step3Body: "ከተቀበሉ በኋላ Marks ያገኛሉ። IP Ledger ላይ ይመዘግባሉ።",
      hide: "ደብቅ",
      why: "ለምን?",
    },
    languageSwitcher: {
      changeLanguage: "ቋንቋ ቀይር",
      selectLanguage: "ቋንቋ ምረጥ",
      quickEnglish: "እንግሊዝኛ",
      tip: "ልዩ ተሞክሮዎችን ለማስጀመር Durin's Door ላይ የተለያዩ ቋንቋ ይለፍ ቃሎችን ተጠቀሙ!",
    },
  },
  "kn": {
    speakFriend: {
      title: "ಸ್ನೇಹಿತ ಎಂದು ಹೇಳಿ ಒಳಗೆ ಬಾ.",
      description: "ಲಿಯಾನಾ ಬನ್ಯಾನ್ ಎಲ್ಲ ಭಾಷೆಗಳಿಗೆ ತೆರೆದಿದೆ. ಪ್ರತಿ ಭಾಷೆಗೆ ಒಂದು ಅನುವಾದ ಬಹುಮಾನ ಇದೆ.",
      languages: "ಭಾಷೆಗಳು",
      openBounties: "ತೆರೆದ ಬಹುಮಾನಗಳು",
      marksAwarded: "Marks ನೀಡಲಾಗಿದೆ (ಭಾಗವಹಿಸುವ ಟೋಕನ್ಗಳು)",
      provisional: "ತಾತ್ಕಾಲಿಕ:",
      provisionalNotice: "ಭಾಷೆಗಳ ಪಟ್ಟಿ ಮತ್ತು Marks ದರಗಳು ತಾತ್ಕಾಲಿಕ. Marks ಭಾಗವಹಿಸುವ ಟೋಕನ್, ಇಕ್ವಿಟಿ ಅಲ್ಲ.",
      bountyOpen: "ಬಹುಮಾನ ತೆರೆದಿದೆ",
      claimed: "ಕ್ಲೈಮ್ ಮಾಡಲಾಗಿದೆ",
      complete: "ಪೂರ್ಣ",
      translationBountyTitle: "ಅನುವಾದ ಬಹುಮಾನ",
      bountyDescription: "ಲಿಯಾನಾ ಬನ್ಯಾನ್ ಅನ್ನು {{language}} ಗೆ ಅನುವಾದಿಸಿ. {{marks}} Marks ಗಳಿಸಿ.",
      scopeWelcome: "ಸ್ವಾಗತ / ಭೂತ ಜಗತ್ತು ಪರದೆಗಳು",
      scopeCueCards: "ಮೂಲ ಕ್ಯೂ ಕಾರ್ಡ್ ಸೆಟ್ (ಆರ್ಥಿಕ ಕಾನೂನುಗಳು + ಆಡಳಿತ)",
      scopeNavigation: "ನ್ಯಾವಿಗೇಶನ್ ಲೇಬಲ್ಗಳು ಮತ್ತು ದೋಷ ಸಂದೇಶಗಳು",
      scopeWildfire: "Wildfire Beacon Run: ಕೆಲಸ ಪಡೆಯಿರಿ",
      claimBounty: "ಈ ಅನುವಾದ ಬಹುಮಾನ ಕ್ಲೈಮ್ ಮಾಡಿ",
      baseLanguage: "ಮೂಲ ಭಾಷೆ -- ಬಹುಮಾನ ಅಗತ್ಯವಿಲ್ಲ.",
      claimedBy: "@{{handle}} ಕ್ಲೈಮ್ ಮಾಡಿದ್ದಾರೆ -- ಪ್ರಗತಿಯಲ್ಲಿದೆ.",
      marksProvisional: "{{marks}} Marks (ತಾತ್ಕಾಲಿಕ)",
      speakFounderTitle: "ಸಂಸ್ಥಾಪಕರ ಧ್ವನಿ: ಈ ಪದಗಳು ಏಕೆ",
      speakFounderDesc: "ಈ ವೇದಿಕೆಯ ಪ್ರತಿ ಪದಕ್ಕೂ ಒಂದು ಕಾರಣ ಇದೆ. 26 ಪ್ರಮುಖ ಹೆಸರುಗಳ ಮೂಲ.",
      howBountiesWork: "ಅನುವಾದ ಬಹುಮಾನಗಳು ಹೇಗೆ ಕಾರ್ಯ ನಿರ್ವಹಿಸುತ್ತವೆ",
      step1Title: "ಬಹುಮಾನ ಕ್ಲೈಮ್ ಮಾಡಿ",
      step1Body: "Help Wanted ಬೋರ್ಡ್‌ನಿಂದ ಅನುವಾದ ಬಹುಮಾನ ತೆರೆಯಿರಿ.",
      step2Title: "ಅನುವಾದಿಸಿ ಮತ್ತು ಸಲ್ಲಿಸಿ",
      step2Body: "ಎಲ್ಲ ಅಗತ್ಯ ಸ್ಟ್ರಿಂಗ್‌ಗಳನ್ನು ಅನುವಾದಿಸಿ. Bounty Poster ಮೂಲಕ ಸಲ್ಲಿಸಿ.",
      step3Title: "Marks ಗಳಿಸಿ",
      step3Body: "ಸ್ವೀಕೃತಿಯ ನಂತರ Marks ಸಿಗುತ್ತದೆ. IP Ledger ನಲ್ಲಿ ದಾಖಲಾಗುತ್ತೀರಿ.",
      hide: "ಮರೆಮಾಡು",
      why: "ಏಕೆ?",
    },
    languageSwitcher: {
      changeLanguage: "ಭಾಷೆ ಬದಲಿಸಿ",
      selectLanguage: "ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ",
      quickEnglish: "ಆಂಗ್ಲ",
      tip: "ಅನನ್ಯ ಅನುಭವಗಳನ್ನು ಅನ್‌ಲಾಕ್ ಮಾಡಲು Durin's Door ನಲ್ಲಿ ವಿವಿಧ ಭಾಷೆ ಪಾಸ್‌ವರ್ಡ್ ಬಳಸಿ!",
    },
  },
  "pa": {
    speakFriend: {
      title: "ਦੋਸਤ ਕਹੋ ਅਤੇ ਅੰਦਰ ਆਓ।",
      description: "Liana Banyan ਹਰ ਭਾਸ਼ਾ ਲਈ ਖੁੱਲੀ ਹੈ। ਹਰ ਭਾਸ਼ਾ ਲਈ ਇੱਕ ਅਨੁਵਾਦ ਇਨਾਮ ਹੈ।",
      languages: "ਭਾਸ਼ਾਵਾਂ",
      openBounties: "ਖੁੱਲੇ ਇਨਾਮ",
      marksAwarded: "Marks ਦਿੱਤੇ (ਭਾਗੀਦਾਰੀ ਟੋਕਨ)",
      provisional: "ਅਸਥਾਈ:",
      provisionalNotice: "ਭਾਸ਼ਾਵਾਂ ਦੀ ਸੂਚੀ ਅਤੇ Marks ਦਰਾਂ ਅਸਥਾਈ ਹਨ। Marks ਭਾਗੀਦਾਰੀ ਟੋਕਨ ਹਨ, ਹਿੱਸੇਦਾਰੀ ਨਹੀਂ।",
      bountyOpen: "ਇਨਾਮ ਖੁੱਲਾ",
      claimed: "ਦਾਅਵਾ ਕੀਤਾ",
      complete: "ਪੂਰਾ",
      translationBountyTitle: "ਅਨੁਵਾਦ ਇਨਾਮ",
      bountyDescription: "Liana Banyan ਨੂੰ {{language}} ਵਿੱਚ ਅਨੁਵਾਦ ਕਰੋ। {{marks}} Marks ਕਮਾਓ।",
      scopeWelcome: "ਜੀ ਆਇਆਂ / ਭੂਤ ਦੁਨੀਆ ਸਕਰੀਨ",
      scopeCueCards: "ਮੁੱਖ ਕਿਊ ਕਾਰਡ ਸੈੱਟ (ਆਰਥਿਕ ਕਾਨੂੰਨ + ਸ਼ਾਸਨ)",
      scopeNavigation: "ਨੈਵੀਗੇਸ਼ਨ ਲੇਬਲ ਅਤੇ ਗਲਤੀ ਸੁਨੇਹੇ",
      scopeWildfire: "Wildfire Beacon Run: ਨੌਕਰੀ ਮਿਲੋ",
      claimBounty: "ਇਹ ਅਨੁਵਾਦ ਇਨਾਮ ਦਾਅਵਾ ਕਰੋ",
      baseLanguage: "ਮੂਲ ਭਾਸ਼ਾ -- ਕੋਈ ਇਨਾਮ ਦੀ ਲੋੜ ਨਹੀਂ।",
      claimedBy: "@{{handle}} ਨੇ ਦਾਅਵਾ ਕੀਤਾ -- ਜਾਰੀ ਹੈ।",
      marksProvisional: "{{marks}} Marks (ਅਸਥਾਈ)",
      speakFounderTitle: "ਸੰਸਥਾਪਕ ਦੀ ਆਵਾਜ਼: ਇਹ ਸ਼ਬਦ ਕਿਉਂ",
      speakFounderDesc: "ਇਸ ਪਲੇਟਫਾਰਮ ਤੇ ਹਰ ਸ਼ਬਦ ਦਾ ਕਾਰਨ ਹੈ। 26 ਮਹੱਤਵਪੂਰਨ ਨਾਵਾਂ ਦਾ ਮੂਲ।",
      howBountiesWork: "ਅਨੁਵਾਦ ਇਨਾਮ ਕਿਵੇਂ ਕੰਮ ਕਰਦੇ ਹਨ",
      step1Title: "ਇਨਾਮ ਦਾਅਵਾ ਕਰੋ",
      step1Body: "Help Wanted ਬੋਰਡ ਤੋਂ ਅਨੁਵਾਦ ਇਨਾਮ ਖੋਲ੍ਹੋ।",
      step2Title: "ਅਨੁਵਾਦ ਕਰੋ ਅਤੇ ਜਮ੍ਹਾਂ ਕਰੋ",
      step2Body: "ਸਾਰੀਆਂ ਲੋੜੀਂਦੀਆਂ ਸਟ੍ਰਿੰਗਾਂ ਦਾ ਅਨੁਵਾਦ ਕਰੋ। Bounty Poster ਰਾਹੀਂ ਜਮ੍ਹਾਂ ਕਰੋ।",
      step3Title: "Marks ਕਮਾਓ",
      step3Body: "ਸਵੀਕ੍ਰਿਤੀ ਤੋਂ ਬਾਅਦ Marks ਮਿਲਦੇ ਹਨ। IP Ledger ਵਿੱਚ ਦਰਜ ਹੋ।",
      hide: "ਲੁਕਾਓ",
      why: "ਕਿਉਂ?",
    },
    languageSwitcher: {
      changeLanguage: "ਭਾਸ਼ਾ ਬਦਲੋ",
      selectLanguage: "ਭਾਸ਼ਾ ਚੁਣੋ",
      quickEnglish: "ਅੰਗਰੇਜ਼ੀ",
      tip: "ਵਿਲੱਖਣ ਅਨੁਭਵ ਲਈ Durin's Door ਤੇ ਵੱਖ ਭਾਸ਼ਾ ਪਾਸਵਰਡ ਵਰਤੋ!",
    },
  },
  "jv": {
    speakFriend: {
      title: "Kandha kanca, banjur mlebu.",
      description: "Liana Banyan dibangun kanggo mbukak saben basa. Saben basa duwe siji hadiah terjemahan.",
      languages: "basa",
      openBounties: "hadiah mbuka",
      marksAwarded: "Marks diwenehake (token partisipasi)",
      provisional: "Sementara:",
      provisionalNotice: "Daftar basa lan tarif Marks sementara. Marks token partisipasi, dudu ekuitas.",
      bountyOpen: "Hadiah mbuka",
      claimed: "Diklaim",
      complete: "Rampung",
      translationBountyTitle: "Hadiah Terjemahan",
      bountyDescription: "Terjemahake Liana Banyan menyang {{language}}. Entuk {{marks}} Marks.",
      scopeWelcome: "Layar Sugeng Rawuh / Donya Memedi",
      scopeCueCards: "Set Kartu Isyarat Inti",
      scopeNavigation: "Label navigasi lan pesen kesalahan",
      scopeWildfire: "Wildfire Beacon Run: Nggoleki Gawean",
      claimBounty: "Klaim Hadiah Terjemahan Iki",
      baseLanguage: "Basa dhasar -- ora butuh hadiah.",
      claimedBy: "@{{handle}} ngeklaim -- lagi mlaku.",
      marksProvisional: "{{marks}} Marks (sementara)",
      speakFounderTitle: "Suwara Pendiri: Kenapa Tembung-Tembung Iki",
      speakFounderDesc: "Saben istilah ana alasane. Asal-usul 26 jeneng sing paling penting.",
      howBountiesWork: "Kepiye Cara Kerja Hadiah Terjemahan",
      step1Title: "Klaim Hadiah",
      step1Body: "Bukak Hadiah Terjemahan saka papan Help Wanted.",
      step2Title: "Terjemahake lan Kirima",
      step2Body: "Terjemahake kabeh string sing dibutuhake. Kirima liwat alur Bounty Poster.",
      step3Title: "Entuk Marks",
      step3Body: "Sawise ditampa, kowe entuk Marks lan dicathet ing IP Ledger.",
      hide: "sembunyikake",
      why: "kenapa?",
    },
    languageSwitcher: {
      changeLanguage: "Ganti basa",
      selectLanguage: "Pilih basa",
      quickEnglish: "Inggris",
      tip: "Gunakake sandi basa beda-beda ing Gapura Durin kanggo mbukak pengalaman unik!",
    },
  },
  "or": {
    speakFriend: {
      title: "ବନ୍ଧୁ କୁହ ଏବଂ ଭିତରକୁ ଆସ।",
      description: "Liana Banyan ସମସ୍ତ ଭାଷା ପାଇଁ ଖୋଲା ଅଛି। ପ୍ରତ୍ୟେକ ଭାଷା ପାଇଁ ଏକ ଅନୁବାଦ ଇନାମ ଅଛି।",
      languages: "ଭାଷା",
      openBounties: "ଖୋଲା ଇନାମ",
      marksAwarded: "Marks ପ୍ରଦାନ ହୋଇଛି (ଅଂଶଗ୍ରହଣ ଟୋକେନ)",
      provisional: "ଅସ୍ଥାୟୀ:",
      provisionalNotice: "ଭାଷା ତାଲିକା ଓ Marks ହାର ଅସ୍ଥାୟୀ। Marks ଅଂଶଗ୍ରହଣ ଟୋକେନ, ଇକ୍ୱିଟି ନୁହେ।",
      bountyOpen: "ଇନାମ ଖୋଲା",
      claimed: "ଦାବି ହୋଇଛି",
      complete: "ସଂପୂର୍ଣ",
      translationBountyTitle: "ଅନୁବାଦ ଇନାମ",
      bountyDescription: "Liana Banyan କୁ {{language}} ରେ ଅନୁବାଦ କରନ୍ତୁ। {{marks}} Marks ଅର୍ଜନ କରନ୍ତୁ।",
      scopeWelcome: "ସ୍ୱାଗତ / ଭୂତ ଜଗତ ସ୍କ୍ରିନ",
      scopeCueCards: "ମୂଳ ସୂଚକ କାର୍ଡ ସେଟ",
      scopeNavigation: "ନ୍ୟାଭିଗେସନ ଲେବଲ ଓ ତ୍ରୁଟି ବାର୍ତ୍ତା",
      scopeWildfire: "Wildfire Beacon Run: ଚାକିରି ପାଆ",
      claimBounty: "ଏହି ଅନୁବାଦ ଇନାମ ଦାବି କରନ୍ତୁ",
      baseLanguage: "ମୂଳ ଭାଷା -- କୌଣସି ଇନାମ ଦରକାର ନାହିଁ।",
      claimedBy: "@{{handle}} ଦ୍ୱାରା ଦାବି -- ଚଲୁ ଅଛି।",
      marksProvisional: "{{marks}} Marks (ଅସ୍ଥାୟୀ)",
      speakFounderTitle: "ପ୍ରତିଷ୍ଠାତାଙ୍କ ସ୍ୱର: ଏହି ଶବ୍ଦ ଗୁଡ଼ିକ କାହିଁକି",
      speakFounderDesc: "ଏହି ପ୍ଲାଟଫର୍ମରେ ପ୍ରତ୍ୟେକ ଶବ୍ଦ ଏକ କାରଣ ସହ ନାମ ଦିଆ। 26 ଗୁରୁତ୍ୱପୂର୍ଣ ନାମ।",
      howBountiesWork: "ଅନୁବାଦ ଇନାମ କିପରି କାମ କରେ",
      step1Title: "ଇନାମ ଦାବି କରନ୍ତୁ",
      step1Body: "Help Wanted ବୋର୍ଡ଼ ରୁ ଅନୁବାଦ ଇନାମ ଖୋଲନ୍ତୁ।",
      step2Title: "ଅନୁବାଦ ଓ ଦାଖଲ",
      step2Body: "ଆବଶ୍ୟକ ସ୍ଟ୍ରିଂ ଅନୁବାଦ କରି Bounty Poster ବ୍ୟବହାର କରି ଦାଖଲ କରନ୍ତୁ।",
      step3Title: "Marks ଅର୍ଜନ",
      step3Body: "ଗ୍ରହଣ ହେଲେ Marks ଓ IP Ledger ଲେଖ।",
      hide: "ଲୁଚାନ୍ତୁ",
      why: "କାହିଁକି?",
    },
    languageSwitcher: {
      changeLanguage: "ଭାଷା ବଦଳାନ୍ତୁ",
      selectLanguage: "ଭାଷା ବଛାନ୍ତୁ",
      quickEnglish: "ଇଂରାଜୀ",
      tip: "ଅଦ୍ୱିତୀୟ ଅଭିଜ୍ଞତା ପାଇଁ Durin's Door ରେ ବିଭିନ୍ନ ଭାଷା ପାସୱର୍ଡ ବ୍ୟବହାର କରନ୍ତୁ!",
    },
  },
  "yo": {
    speakFriend: {
      title: "So ore, ki o wole.",
      description: "Liana Banyan ni a ko lati sii fun gbogbo ede. Ede kookan ni ebun itumoo kan.",
      languages: "ede",
      openBounties: "awon ebun ti o sii",
      marksAwarded: "Marks ti a fun (awon tokeni ikopa)",
      provisional: "Igba die:",
      provisionalNotice: "Atoko ede ati osu won Marks jẹ igba die. Marks jẹ awon tokeni ikopa, kii se ipin.",
      bountyOpen: "Ebun sii",
      claimed: "Ti gba",
      complete: "Pari",
      translationBountyTitle: "Ebun Itumo",
      bountyDescription: "Tumo Liana Banyan si {{language}}. Gba {{marks}} Marks lehin gbigba.",
      scopeWelcome: "Awon iboju Kaabo / Agbaye Iwin",
      scopeCueCards: "Eto Kaadi Itosoona Akoko (Awon Ofin Oro-aje + Ijoba)",
      scopeNavigation: "Awon aami itosoona ati awon ifiransẹ asise",
      scopeWildfire: "Wildfire Beacon Run: Gba Ise",
      claimBounty: "Gba Ebun Itumo Yii",
      baseLanguage: "Ede ipile -- ko si ebun ti a nilo.",
      claimedBy: "@{{handle}} ti gba -- n sisẹ.",
      marksProvisional: "{{marks}} Marks (igba die)",
      speakFounderTitle: "Ohun Oludasile: Idi Awon Oro Wonyi",
      speakFounderDesc: "Gbogbo oro ninu eto yii ni idi fun oruko re. Orisun awon oruko 26 pataki julọ.",
      howBountiesWork: "Bii Awon Ebun Itumo Se N Sisẹ",
      step1Title: "Gba Ebun",
      step1Body: "Sii Ebun Itumo lati Help Wanted.",
      step2Title: "Tumo ati Firansẹ",
      step2Body: "Tumo gbogbo awon okun ti a nilo. Firansẹ nipasẹ Bounty Poster.",
      step3Title: "Gba Marks",
      step3Body: "Lehin gbigba, o gba Marks ati ki a gbasilẹ re ni IP Ledger.",
      hide: "fi pamo",
      why: "kilode?",
    },
    languageSwitcher: {
      changeLanguage: "Yi ede pada",
      selectLanguage: "Yan ede",
      quickEnglish: "Geẹsi",
      tip: "Lo awon ọrọ igbaniwolo ede orisorisii ni Enu-ọna Durin lati sii awon iriri alailegbe!",
    },
  },
  "ml": {
    speakFriend: {
      title: "കൂട്ടുകാരൻ എന്ന് പറഞ്ഞ് അകത്ത് കടക്കൂ.",
      description: "ലിയാന ബന്യൻ എല്ലാ ഭാഷകൾക്കും തുറന്നിരിക്കുന്നു. ഓരോ ഭാഷക്കും ഒരു വിവർത്തന ബൗണ്ടി ഉണ്ട്.",
      languages: "ഭാഷകൾ",
      openBounties: "തുറന്ന ബൗണ്ടികൾ",
      marksAwarded: "Marks നൽകി (പങ്കാളിത്ത ടോക്കൺ)",
      provisional: "താൽക്കാലിക:",
      provisionalNotice: "ഭാഷകളുടെ പട്ടിക, Marks നിരക്കുകൾ താൽക്കാലികം. Marks പങ്കാളിത്ത ടോക്കൺ, ഇക്വിറ്റി അല്ല.",
      bountyOpen: "ബൗണ്ടി തുറന്നിരിക്കുന്നു",
      claimed: "ക്ലെയിം ചെയ്തു",
      complete: "പൂർണ്ണം",
      translationBountyTitle: "വിവർത്തന ബൗണ്ടി",
      bountyDescription: "ലിയാന ബന്യൻ {{language}} ലേക്ക് വിവർത്തനം ചെയ്യുക. {{marks}} Marks നേടുക.",
      scopeWelcome: "സ്വാഗതം / ഭൂത ലോകം സ്ക്രീനുകൾ",
      scopeCueCards: "കോർ ക്യൂ കാർഡ് സെറ്റ്",
      scopeNavigation: "നേവിഗേഷൻ ലേബലുകൾ, പിശക് സന്ദേശങ്ങൾ",
      scopeWildfire: "Wildfire Beacon Run: ജോലി നേടൂ",
      claimBounty: "ഈ വിവർത്തന ബൗണ്ടി ക്ലെയിം ചെയ്യുക",
      baseLanguage: "അടിസ്ഥാന ഭാഷ -- ബൗണ്ടി ആവശ്യമില്ല.",
      claimedBy: "@{{handle}} ക്ലെയിം ചെയ്തു -- പ്രവർത്തനത്തിലാണ്.",
      marksProvisional: "{{marks}} Marks (താൽക്കാലിക)",
      speakFounderTitle: "സ്ഥാപകൻ്റെ ശബ്ദം: ഈ വാക്കുകൾ എന്തുകൊണ്ട്",
      speakFounderDesc: "ഈ പ്ലാറ്റ്ഫോമിൽ ഓരോ പദവും ഒരു കാരണത്തിനായി നൽകിയ പേര്. 26 പ്രധാന പേരുകളുടെ ഉത്ഭവം.",
      howBountiesWork: "വിവർത്തന ബൗണ്ടികൾ എങ്ങനെ പ്രവർത്തിക്കുന്നു",
      step1Title: "ബൗണ്ടി ക്ലെയിം ചെയ്യുക",
      step1Body: "Help Wanted ബോർഡിൽ നിന്ന് ബൗണ്ടി തുറക്കുക.",
      step2Title: "വിവർത്തനം ചെയ്ത് സമർപ്പിക്കുക",
      step2Body: "ആവശ്യമായ സ്ട്രിങ്ങുകൾ വിവർത്തനം ചെയ്ത് Bounty Poster ഉപയോഗിച്ച് സമർപ്പിക്കുക.",
      step3Title: "Marks നേടൂ",
      step3Body: "സ്വീകരിക്കപ്പെട്ടാൽ Marks ലഭിക്കും. IP Ledger ൽ രേഖപ്പെടുത്തും.",
      hide: "മറയ്ക്കുക",
      why: "എന്തുകൊണ്ട്?",
    },
    languageSwitcher: {
      changeLanguage: "ഭാഷ മാറ്റുക",
      selectLanguage: "ഭാഷ തിരഞ്ഞെടുക്കുക",
      quickEnglish: "ഇംഗ്ലീഷ്",
      tip: "Durin's Door ൽ വ്യത്യസ്ത ഭാഷ പാസ്‌വേഡ് ഉപയോഗിക്കുക!",
    },
  },
  "ms": {
    speakFriend: {
      title: "Sebut kawan, dan masuk.",
      description: "Liana Banyan dibina untuk terbuka kepada setiap bahasa. Setiap bahasa mempunyai satu hadiah terjemahan.",
      languages: "bahasa",
      openBounties: "hadiah terbuka",
      marksAwarded: "Marks diberikan (token penyertaan)",
      provisional: "Sementara:",
      provisionalNotice: "Senarai bahasa dan kadar Marks adalah sementara. Marks adalah token penyertaan, bukan ekuiti.",
      bountyOpen: "Hadiah terbuka",
      claimed: "Dituntut",
      complete: "Selesai",
      translationBountyTitle: "Hadiah Terjemahan",
      bountyDescription: "Terjemahkan Liana Banyan ke {{language}}. Dapatkan {{marks}} Marks apabila diterima.",
      scopeWelcome: "Skrin Selamat Datang / Dunia Hantu",
      scopeCueCards: "Set Kad Isyarat Teras",
      scopeNavigation: "Label navigasi dan mesej ralat",
      scopeWildfire: "Wildfire Beacon Run: Cari Kerja",
      claimBounty: "Tuntut Hadiah Terjemahan Ini",
      baseLanguage: "Bahasa asas -- tiada hadiah diperlukan.",
      claimedBy: "@{{handle}} menuntut -- sedang berjalan.",
      marksProvisional: "{{marks}} Marks (sementara)",
      speakFounderTitle: "Suara Pengasas: Mengapa Perkataan-Perkataan Ini",
      speakFounderDesc: "Setiap istilah di platform ini dinamakan dengan sebab. Asal usul 26 nama terpenting.",
      howBountiesWork: "Cara Hadiah Terjemahan Berfungsi",
      step1Title: "Tuntut Hadiah",
      step1Body: "Buka Hadiah Terjemahan dari papan Help Wanted.",
      step2Title: "Terjemah dan Hantar",
      step2Body: "Terjemahkan semua rentetan yang diperlukan. Hantar melalui aliran Bounty Poster.",
      step3Title: "Dapatkan Marks",
      step3Body: "Selepas diterima, anda mendapat Marks dan direkodkan dalam IP Ledger.",
      hide: "sembunyikan",
      why: "mengapa?",
    },
    languageSwitcher: {
      changeLanguage: "Tukar bahasa",
      selectLanguage: "Pilih bahasa",
      quickEnglish: "Inggeris",
      tip: "Gunakan kata laluan bahasa berbeza di Pintu Durin untuk membuka pengalaman unik!",
    },
  },
  "uz": {
    speakFriend: {
      title: "Do'st de va kir.",
      description: "Liana Banyan har bir til uchun ochiq qurilgan. Har bir til uchun bitta tarjima mukofoti bor.",
      languages: "tillar",
      openBounties: "ochiq mukofotlar",
      marksAwarded: "Marks berildi (ishtirok tokenlari)",
      provisional: "Vaqtinchalik:",
      provisionalNotice: "Tillar ro'yxati va Marks stavkalari vaqtinchalik. Marks ishtirok tokenlari, kapital emas.",
      bountyOpen: "Mukofot ochiq",
      claimed: "Da'vo qilindi",
      complete: "Tugallandi",
      translationBountyTitle: "Tarjima Mukofoti",
      bountyDescription: "Liana Banyan'ni {{language}} tiliga tarjima qiling. {{marks}} Marks ishlang.",
      scopeWelcome: "Xush kelibsiz / Arvoh Dunyosi ekranlari",
      scopeCueCards: "Asosiy Ko'rsatma Karta to'plami",
      scopeNavigation: "Navigatsiya yorliqlari va xato xabarlari",
      scopeWildfire: "Wildfire Beacon Run: Ish toping",
      claimBounty: "Ushbu Tarjima Mukofotini da'vo qiling",
      baseLanguage: "Asosiy til -- mukofot kerak emas.",
      claimedBy: "@{{handle}} da'vo qildi -- jarayonda.",
      marksProvisional: "{{marks}} Marks (vaqtinchalik)",
      speakFounderTitle: "Asoschining Ovozi: Bu So'zlar Nima Uchun",
      speakFounderDesc: "Ushbu platformadagi har bir atama sabab bilan nomlangan. 26 muhim ismning kelib chiqishi.",
      howBountiesWork: "Tarjima Mukofotlari Qanday Ishlaydi",
      step1Title: "Mukofotni da'vo qiling",
      step1Body: "Help Wanted taxtasidan Tarjima Mukofotini oching.",
      step2Title: "Tarjima qiling va Yuboring",
      step2Body: "Barcha kerakli satrlarni tarjima qiling. Bounty Poster orqali yuboring.",
      step3Title: "Marks ishlang",
      step3Body: "Qabul qilingandan so'ng Marks olasiz. IP Ledger'da qayd etilasiz.",
      hide: "yashir",
      why: "nima uchun?",
    },
    languageSwitcher: {
      changeLanguage: "Tilni o'zgartir",
      selectLanguage: "Tilni tanlang",
      quickEnglish: "Inglizcha",
      tip: "Noyob tajribalar uchun Durin Darvozasida turli til parollarini ishlating!",
    },
  },
  "ig": {
    speakFriend: {
      title: "Kuo enyi, wee banye.",
      description: "E wuru Liana Banyan ka o mepee n'olu nile. Asusụ nosọbụ nọọ na ihe nrite ntụgharị otu.",
      languages: "asụsụ",
      openBounties: "ihe nrite mepere",
      marksAwarded: "E nyere Marks (tokens isonye)",
      provisional: "Nke oge a:",
      provisionalNotice: "Ndepụta asụsụ na ọnụahịa Marks bụ nke oge a. Marks bụ tokens isonye, ọ bụghị equity.",
      bountyOpen: "Ihe nrite mepere",
      claimed: "Achibidoola",
      complete: "Emechara",
      translationBountyTitle: "Ihe Nrite Ntụgharị",
      bountyDescription: "Tụgharịa Liana Banyan n'asụsụ {{language}}. Nweta {{marks}} Marks.",
      scopeWelcome: "Ihuenyo Nnabata / Ụwa Mmụọ",
      scopeCueCards: "Nhọrọ Kaadị Ntụziaka Isi",
      scopeNavigation: "Akara ntụzịaka na ọzụzụ njehie",
      scopeWildfire: "Wildfire Beacon Run: Nweta Ọrụ",
      claimBounty: "Chibido Ihe Nrite Ntụgharị a",
      baseLanguage: "Asụsụ isi -- enweghị mkpa ihe nrite.",
      claimedBy: "@{{handle}} chibidola -- na-aga n'ihu.",
      marksProvisional: "{{marks}} Marks (nke oge a)",
      speakFounderTitle: "Olu Onye Guzobe: Ihe Kpatara Okwu Ndị a",
      speakFounderDesc: "Okwu ọ bụla n'isi ihe a nwere ihe kpatara aha ya. Mbụ nke aha 26 dị mkpa.",
      howBountiesWork: "Otú Ihe Nrite Ntụgharị Si Arụ Ọrụ",
      step1Title: "Chibido Ihe Nrite",
      step1Body: "Mepee Ihe Nrite Ntụgharị site n'Help Wanted.",
      step2Title: "Tụgharịa ma Zipu",
      step2Body: "Tụgharịa eriri nile dị mkpa. Zipụ site na Bounty Poster.",
      step3Title: "Nweta Marks",
      step3Body: "Mgbe ọ nabatara, i nweta Marks ma a debanye aha gị na IP Ledger.",
      hide: "zoo",
      why: "gịnị mere?",
    },
    languageSwitcher: {
      changeLanguage: "Gbanwee asụsụ",
      selectLanguage: "Họrọ asụsụ",
      quickEnglish: "Bekee",
      tip: "Jiri paswọọdị asụsụ dị iche iche na Ọnụ ụzọ Durin ka i mepee ahụmahụ pụrụ iche!",
    },
  },
  "my": {
    speakFriend: {
      title: "မိတ်ဆွေဟု ပြောပြီး ဝင်လာပါ။",
      description: "Liana Banyan ကို ဘာသာစကားတိုင်းအတွက် ဖွင့်ဆောက်ထားသည်။ ဘာသာစကားတိုင်းတွင် ဘာသာပြန်ဆုတစ်ခုရှိသည်။",
      languages: "ဘာသာစကားများ",
      openBounties: "ဖွင့်ထားသောဆုများ",
      marksAwarded: "Marks ချီးမြှင့် (ပါဝင်မှု တိုကင်များ)",
      provisional: "ယာယီ:",
      provisionalNotice: "ဘာသာစကားစာရင်းနှင့် Marks နှုန်းများ ယာယီဖြစ်သည်။ Marks သည် ပါဝင်မှုတိုကင်များ၊ အစုရှယ်ယာ မဟုတ်ပါ။",
      bountyOpen: "ဆုဖွင့်ထားသည်",
      claimed: "တောင်းဆိုပြီး",
      complete: "ပြည့်စုံ",
      translationBountyTitle: "ဘာသာပြန်ဆု",
      bountyDescription: "Liana Banyan ကို {{language}} သို့ ဘာသာပြန်ပါ။ {{marks}} Marks ရရှိပါမည်။",
      scopeWelcome: "ကြိုဆိုခြင်း / ဝိညာဉ်ကမ္ဘာ မျက်နှာပြင်",
      scopeCueCards: "အဓိက လမ်းညွှန်ကတ်ဇုန်",
      scopeNavigation: "လမ်းညွှန် အညွှန်းများနှင့် အမှားစာများ",
      scopeWildfire: "Wildfire Beacon Run: အလုပ်ရှာ",
      claimBounty: "ဤဘာသာပြန်ဆုကို တောင်းဆိုပါ",
      baseLanguage: "အခြေခံဘာသာ -- ဆုမလိုပါ။",
      claimedBy: "@{{handle}} တောင်းဆိုသည် -- ဆောင်ရွက်ဆဲ။",
      marksProvisional: "{{marks}} Marks (ယာယီ)",
      speakFounderTitle: "တည်ထောင်သူ၏ အသံ: ဤစကားလုံးများ အဘယ်ကြောင့်",
      speakFounderDesc: "ဤပလပ်ဖောင်းရှိ စကားလုံးတိုင်းကို အကြောင်းကြောင့် အမည်ပေးသည်။ ၂၆ ခု အဓိကနာမည်၏ မူလ။",
      howBountiesWork: "ဘာသာပြန်ဆုများ မည်သို့ အလုပ်လုပ်သည်",
      step1Title: "ဆုတောင်းဆိုပါ",
      step1Body: "Help Wanted ဘုတ်ကနေ ဘာသာပြန်ဆုဖွင့်ပါ။",
      step2Title: "ဘာသာပြန်ပြီး တင်သွင်းပါ",
      step2Body: "လိုအပ်သော string တိုင်းကို ဘာသာပြန်ပြီး Bounty Poster မှတဆင့် တင်ပါ။",
      step3Title: "Marks ရရှိပါ",
      step3Body: "လက်ခံပြီးနောက် Marks ရမည်ဖြစ်ပြီး IP Ledger တွင် မှတ်တမ်းတင်ပါမည်။",
      hide: "ဖျောက်ထား",
      why: "ဘာကြောင့်?",
    },
    languageSwitcher: {
      changeLanguage: "ဘာသာပြောင်းပါ",
      selectLanguage: "ဘာသာရွေးပါ",
      quickEnglish: "အင်္ဂလိပ်",
      tip: "Durin's Door တွင် မတူသောဘာသာ စကားဝှက်များ သုံးပြီး ထူးခြားသောအတွေ့အကြုံများ ဖွင့်ပါ!",
    },
  },
  "ne": {
    speakFriend: {
      title: "साथी भन र भित्र आउ।",
      description: "Liana Banyan हरेक भाषाको लागि खुला बनाइएको छ। प्रत्येक भाषाको लागि एउटा अनुवाद पुरस्कार छ।",
      languages: "भाषाहरू",
      openBounties: "खुला पुरस्कारहरू",
      marksAwarded: "Marks दिइयो (सहभागिता टोकन)",
      provisional: "अस्थायी:",
      provisionalNotice: "भाषाहरूको सूची र Marks दरहरू अस्थायी छन्। Marks सहभागिता टोकन हुन्, शेयर होइन।",
      bountyOpen: "पुरस्कार खुला",
      claimed: "दाबी गरियो",
      complete: "पूर्ण",
      translationBountyTitle: "अनुवाद पुरस्कार",
      bountyDescription: "Liana Banyan लाई {{language}} मा अनुवाद गर्नुस्। {{marks}} Marks कमाउनुस्।",
      scopeWelcome: "स्वागत / भूत विश्व स्क्रिनहरू",
      scopeCueCards: "मुख्य क्यू कार्ड सेट",
      scopeNavigation: "नेभिगेशन लेबल र त्रुटि सन्देश",
      scopeWildfire: "Wildfire Beacon Run: काम पाउनुस्",
      claimBounty: "यो अनुवाद पुरस्कार दाबी गर्नुस्",
      baseLanguage: "आधार भाषा -- पुरस्कार आवश्यक छैन।",
      claimedBy: "@{{handle}} ले दाबी गरेको -- जारी छ।",
      marksProvisional: "{{marks}} Marks (अस्थायी)",
      speakFounderTitle: "संस्थापकको आवाज: यी शब्दहरू किन",
      speakFounderDesc: "यस प्लेटफर्ममा प्रत्येक शब्द कारणसहित नामाङ्कन गरिएको छ। २६ महत्त्वपूर्ण नामहरूको उत्पत्ति।",
      howBountiesWork: "अनुवाद पुरस्कारहरू कसरी काम गर्छन्",
      step1Title: "पुरस्कार दाबी गर्नुस्",
      step1Body: "Help Wanted बोर्डबाट अनुवाद पुरस्कार खोल्नुस्।",
      step2Title: "अनुवाद गर्नुस् र पेश गर्नुस्",
      step2Body: "सबै आवश्यक स्ट्रिङहरू अनुवाद गर्नुस्। Bounty Poster मार्फत पेश गर्नुस्।",
      step3Title: "Marks कमाउनुस्",
      step3Body: "स्वीकृतिपछि Marks पाउनुहुन्छ। IP Ledger मा दर्ता हुनुहुन्छ।",
      hide: "लुकाउनुस्",
      why: "किन?",
    },
    languageSwitcher: {
      changeLanguage: "भाषा परिवर्तन गर्नुस्",
      selectLanguage: "भाषा छान्नुस्",
      quickEnglish: "अंग्रेजी",
      tip: "अद्वितीय अनुभवहरू अनलक गर्न Durin's Door मा विभिन्न भाषाका पासवर्डहरू प्रयोग गर्नुस्!",
    },
  },
  "ps": {
    speakFriend: {
      title: "ملګری ووایه او ننوځه.",
      description: "لیانا بنیان د هرې ژبې لپاره پرانستي جوړ شوی دی. د هرې ژبې لپاره یو ژباړه جایزه شته.",
      languages: "ژبې",
      openBounties: "پرانستي جایزې",
      marksAwarded: "Marks ورکړل شوي (د ګډون ټوکنونه)",
      provisional: "لنډمهاله:",
      provisionalNotice: "د ژبو لیست او د Marks نرخونه لنډمهاله دي. Marks د ګډون ټوکنونه دي، ونډه نه دي.",
      bountyOpen: "جایزه پرانستې",
      claimed: "دعوه شوې",
      complete: "بشپړ",
      translationBountyTitle: "د ژباړې جایزه",
      bountyDescription: "لیانا بنیان {{language}} ته وژباړئ. {{marks}} Marks ترلاسه کړئ.",
      scopeWelcome: "د ښه راغلاست / د سیوري نړۍ سکرینونه",
      scopeCueCards: "اصلي د لارښوونې کارت ټولګه",
      scopeNavigation: "د ناوي لیبلونه او د تیروتنې پیغامونه",
      scopeWildfire: "Wildfire Beacon Run: کار پیدا کړئ",
      claimBounty: "دا د ژباړې جایزه دعوه کړئ",
      baseLanguage: "اصلي ژبه -- جایزې ته اړتیا نشته.",
      claimedBy: "@{{handle}} دعوه کړه -- روان دی.",
      marksProvisional: "{{marks}} Marks (لنډمهاله)",
      speakFounderTitle: "د بنسټ ایښودونکي غږ: ولې دا کلمې",
      speakFounderDesc: "پلیټ فارم کې هر اصطلاح د یوه دلیل لپاره نومول شوی دی. د ۲۶ مهمو نومونو اصل.",
      howBountiesWork: "د ژباړې جایزې څنګه کار کوي",
      step1Title: "جایزه دعوه کړئ",
      step1Body: "د Help Wanted تخته نه د ژباړې جایزه پرانستئ.",
      step2Title: "وژباړئ او واستوئ",
      step2Body: "ټول اړین تارونه وژباړئ. د Bounty Poster له لارې واستوئ.",
      step3Title: "Marks ترلاسه کړئ",
      step3Body: "د قبلولو وروسته Marks ترلاسه کوئ او IP Ledger کې ثبتیږئ.",
      hide: "پټ کړئ",
      why: "ولې؟",
    },
    languageSwitcher: {
      changeLanguage: "ژبه بدله کړئ",
      selectLanguage: "ژبه وټاکئ",
      quickEnglish: "انګریزي",
      tip: "د ځانګړو تجربو د خلاصولو لپاره د Durin دروازې کې مختلفې ژبې پاسورډونه وکاروئ!",
    },
  },
};
