"use strict";
// tdata-d.cjs -- Machine translations Group D (languages 82-108)
// tk ug yi mt eu gl cy ga is lb ht qu war nso lg ts ss sat doi kok mni as ckb ay sm mi fj
module.exports = {
  "tk": {
    speakFriend: {
      title: "Dost diý hem gir.",
      description: "Liana Banyan her dil ucin acyk guruldy. Her acyk diliň bir terjime sylagy bar.",
      languages: "diller",
      openBounties: "acyk sylaklar",
      marksAwarded: "Marks berildi (gatnaşyk tokenlar)",
      provisional: "Wagtlaýynça:",
      provisionalNotice: "Dilleriň sanawy we Marks derejesi wagtlaýyn. Marks gatnaşyk tokenlari, paý däl.",
      bountyOpen: "Sylak açyk",
      claimed: "Talap edildi",
      complete: "Tamamlandy",
      translationBountyTitle: "Terjime Sylagy",
      bountyDescription: "Liana Banyan {{language}} diline terjime ediň. {{marks}} Marks gazanyň.",
      scopeWelcome: "Hoş geldiňiz / Ruh Dünýäsi ekranlary",
      scopeCueCards: "Esasy Maslahat Kartasy toplumy",
      scopeNavigation: "Nawigasiýa bellikleri we ýalňyş habarlar",
      scopeWildfire: "Wildfire Beacon Run: Iş tap",
      claimBounty: "Bu Terjime Sylagyni Talap Et",
      baseLanguage: "Esasy dil -- sylak gerek däl.",
      claimedBy: "@{{handle}} talap etdi -- dowam edýär.",
      marksProvisional: "{{marks}} Marks (wagtlaýyn)",
      speakFounderTitle: "Esasçynyň Sesi: Näme Üçin Bu Sözler",
      speakFounderDesc: "Bu platformdaky her bir termin sebäp bilen atlandyrylan. 26 möhüm ady gelip çykmagy.",
      howBountiesWork: "Terjime Sylaklar Nähili Işleýär",
      step1Title: "Sylagy Talap Et",
      step1Body: "Help Wanted tagtasyndan Terjime Sylagyni aç.",
      step2Title: "Terjime et we Iberi",
      step2Body: "Zerur setirlerini terjime ediň. Bounty Poster arkaly iberiň.",
      step3Title: "Marks Gazan",
      step3Body: "Kabul edilenden soň Marks alýarsyňyz we IP Ledger-de hasaba alynýarsyňyz.",
      hide: "gizle",
      why: "näme üçin?",
    },
    languageSwitcher: {
      changeLanguage: "Dili üýtget",
      selectLanguage: "Dil saýla",
      quickEnglish: "Iňlisçe",
      tip: "Özboluşly tejribeler üçin Duriniň Gapysynda dürli dil paroly ulanyň!",
    },
  },
  "ug": {
    speakFriend: {
      title: "دوست دە، كىرىپ كەل.",
      description: "Liana Banyan ھەر بىر تىل ئۈچۈن ئوچۇق قۇرۇلغان. ھەر ئوچۇق تىلدا بىر تەرجىمە مۇكاپاتى بار.",
      languages: "تىللار",
      openBounties: "ئوچۇق مۇكاپاتلار",
      marksAwarded: "Marks بېرىلدى (ئىشتىراك تالونلىرى)",
      provisional: "ۋاقتىنچە:",
      provisionalNotice: "تىللار تىزىملىكى ۋە Marks نىسبىتى ۋاقتىنچە. Marks ئىشتىراك تالونلىرى، ھىسسە ئەمەس.",
      bountyOpen: "مۇكاپات ئوچۇق",
      claimed: "تەلەپ قىلىندى",
      complete: "تامام",
      translationBountyTitle: "تەرجىمە مۇكاپاتى",
      bountyDescription: "Liana Banyan نى {{language}} تىلىگە تەرجىمە قىلىڭ. {{marks}} Marks قازاندۇرۇلىدۇ.",
      scopeWelcome: "خوش كەلدىڭىز / روھ دۇنياسى ئېكرانلىرى",
      scopeCueCards: "ئاساسىي ئورۇنتۇتقۇچ كارتا توپلىمى",
      scopeNavigation: "يۆنىلىش بەلگىلىرى ۋە خاتالىق ئۇچۇرلىرى",
      scopeWildfire: "Wildfire Beacon Run: ئىش تاپىڭ",
      claimBounty: "بۇ تەرجىمە مۇكاپاتىنى تەلەپ قىلىڭ",
      baseLanguage: "ئاساسىي تىل -- مۇكاپات ھاجەت يوق.",
      claimedBy: "@{{handle}} تەلەپ قىلدى -- جەريانىدا.",
      marksProvisional: "{{marks}} Marks (ۋاقتىنچە)",
      speakFounderTitle: "ئاساسلاشتۇرغۇچىنىڭ ئاۋازى: نېمىشقا بۇ سۆزلەر",
      speakFounderDesc: "بۇ سۇپىدىكى ھەر بىر ئاتالغۇ سەۋەبى بىلەن ئاتالغان. 26 مۇھىم ئىسىمنىڭ كېلىپ چىقىشى.",
      howBountiesWork: "تەرجىمە مۇكاپاتلىرى قانداق ئىشلەيدۇ",
      step1Title: "مۇكاپاتنى تەلەپ قىلىڭ",
      step1Body: "Help Wanted تاختىسىدىن تەرجىمە مۇكاپاتىنى ئاچىڭ.",
      step2Title: "تەرجىمە قىلىڭ ۋە يوللاڭ",
      step2Body: "بارلىق زۆرۈر قۇرلارنى تەرجىمە قىلىڭ. Bounty Poster ئارقىلىق يوللاڭ.",
      step3Title: "Marks قازانا",
      step3Body: "قوبۇل قىلىنغاندىن كېيىن Marks ئالىسىز. IP Ledger گە تىزىملىتىسىز.",
      hide: "يوشۇر",
      why: "نېمىشقا؟",
    },
    languageSwitcher: {
      changeLanguage: "تىل ئالماشتۇر",
      selectLanguage: "تىل تاللاڭ",
      quickEnglish: "ئىنگلىزچە",
      tip: "Durin نىڭ دەرۋازىسىدا ھەر خىل تىل پارولىنى ئىشلىتىپ ئۆزگىچە تەجرىبىنى ئاچىڭ!",
    },
  },
  "yi": {
    speakFriend: {
      title: "זאָג פֿרײַנד, און אַרײַן.",
      description: "Liana Banyan איז אויפֿגעבויט אָפֿן פֿאַר יעדע שפּראַך. יעדע שפּראַך האָט איין איבערזעצונג-בראַוונטי.",
      languages: "שפּראַכן",
      openBounties: "אָפֿענע בראַוונטיס",
      marksAwarded: "Marks באַגאַבט (באַטייליקונג-טאָקענס)",
      provisional: "צייטווייליק:",
      provisionalNotice: "די שפּראַכן-ליסטע אין Marks-ראַטן זיינען צייטווייליק. Marks זיינען באַטייליקונג-טאָקענס, ניט אַקציעס.",
      bountyOpen: "בראַוונטי אָפֿן",
      claimed: "פֿאָדערט",
      complete: "גענדיקט",
      translationBountyTitle: "איבערזעצונג-בראַוונטי",
      bountyDescription: "איבערזעצן Liana Banyan אויף {{language}}. פֿאַרדינען {{marks}} Marks.",
      scopeWelcome: "ברוכים-הבאים / גייסטווענלט-שירמען",
      scopeCueCards: "גרונטלעכע ציגן-קארטן-זאמלונג",
      scopeNavigation: "נאַוויגאַציע-אַבצייכנס אין פֿעלער-מעלדונגן",
      scopeWildfire: "Wildfire Beacon Run: קריגן אַ אַרבעט",
      claimBounty: "פֿאָדערן דאָס איבערזעצונג-בראַוונטי",
      baseLanguage: "גרונטשפּראַך -- קיין בראַוונטי נויטיק ניט.",
      claimedBy: "@{{handle}} האָט פֿאָדערט -- אין גאַנג.",
      marksProvisional: "{{marks}} Marks (צייטווייליק)",
      speakFounderTitle: "דעם גרינדערס שטים: פֿאַר וואָס די ווערטער",
      speakFounderDesc: "יעדן טערמין אויף דעם פּלאַטפֿאָרם האָט אַ סיבה. דער אורשפּרונג פֿון 26 וויכטיקסטע נעמען.",
      howBountiesWork: "ווי איבערזעצונג-בראַוונטיס אַרבעטן",
      step1Title: "פֿאָדערן בראַוונטי",
      step1Body: "עפֿענען איין איבערזעצונג-בראַוונטי פֿון Help Wanted.",
      step2Title: "איבערזעצן אין שיקן",
      step2Body: "איבערזעצן אַלע נויטיקע סטרינגען. שיקן דורכן Bounty Poster.",
      step3Title: "פֿאַרדינען Marks",
      step3Body: "נאָך אַקצעפּטירן, קריגט מען Marks אין ווערט אייינגעשריבן אין IP Ledger.",
      hide: "באַהאַלטן",
      why: "פֿאַר וואָס?",
    },
    languageSwitcher: {
      changeLanguage: "בייטן שפּראַך",
      selectLanguage: "אויסקלייבן שפּראַך",
      quickEnglish: "ענגליש",
      tip: "נוצן שפּראַכן-פּאַסווערטן ביי דורינס טויערן פֿאַר ייחודיקע דערפֿאַרונגען!",
    },
  },
  "mt": {
    speakFriend: {
      title: "Ghid habib u idħol.",
      description: "Liana Banyan inbniet biex tkun miftuha ghal kull lingwa. Kull lingwa miftuha ghandha premju ta' traduzzjoni wiehed.",
      languages: "lingwi",
      openBounties: "premjijiet miftuhin",
      marksAwarded: "Marks moghtija (tokens ta' parteċipazzjoni)",
      provisional: "Provviżorjament:",
      provisionalNotice: "Il-lista tal-lingwi u r-rati tal-Marks huma provviżorji. Il-Marks huma tokens ta' parteċipazzjoni, mhux azzjonijiet.",
      bountyOpen: "Premju miftuh",
      claimed: "Mitlub",
      complete: "Lest",
      translationBountyTitle: "Premju tat-Traduzzjoni",
      bountyDescription: "Ittraduċi Liana Banyan ghal {{language}}. Aqla {{marks}} Marks.",
      scopeWelcome: "Skrinijiet ta' Merhba / Dinja tal-Ispirtu",
      scopeCueCards: "Sett ta' Karti ta' Suġġeriment Bażiku",
      scopeNavigation: "Tikketti ta' navigazzjoni u messaġġi ta' żball",
      scopeWildfire: "Wildfire Beacon Run: Sib Xogħol",
      claimBounty: "Itlob dan il-Premju tat-Traduzzjoni",
      baseLanguage: "Lingwa bażika -- l-ebda premju meħtieġ.",
      claimedBy: "@{{handle}} talab -- qed jkompli.",
      marksProvisional: "{{marks}} Marks (provviżorjament)",
      speakFounderTitle: "Leħen il-Fundatur: Ghala Dawn il-Kliem",
      speakFounderDesc: "Kull terminu fuq din il-pjattaforma huma msemmija għal raġuni. L-oriġini ta' 26 ismijiet importanti.",
      howBountiesWork: "Kif Jaħdmu l-Premjijiet tat-Traduzzjoni",
      step1Title: "Itlob il-Premju",
      step1Body: "Iftah Premju tat-Traduzzjoni mil-bord Help Wanted.",
      step2Title: "Ittraduċi u Ibghat",
      step2Body: "Ittraduċi s-sensiela kollha meħtieġa. Ibghat permezz ta' Bounty Poster.",
      step3Title: "Aqla Marks",
      step3Body: "Wara l-aċċettazzjoni, tirċievi Marks u tiddaħħal fil-IP Ledger.",
      hide: "ahbi",
      why: "ghala?",
    },
    languageSwitcher: {
      changeLanguage: "Ibdel il-lingwa",
      selectLanguage: "Agħżel il-lingwa",
      quickEnglish: "Ingliż",
      tip: "Uża passwords ta' lingwi differenti fil-Bieb ta' Durin biex tiftah esperjenzi uniċi!",
    },
  },
  "eu": {
    speakFriend: {
      title: "Esazu lagun eta sartu.",
      description: "Liana Banyan hizkuntza guztientzako irekia eraikia dago. Hizkuntza irekiak itzulpen sari bat du.",
      languages: "hizkuntzak",
      openBounties: "sari irekiak",
      marksAwarded: "Marks emanda (parte-hartze tokenak)",
      provisional: "Behin-behineko:",
      provisionalNotice: "Hizkuntzak zerrenda eta Marks tasak behin-behinekoak dira. Marks parte-hartze tokenak dira, ez akzioak.",
      bountyOpen: "Saria irekita",
      claimed: "Eskatuta",
      complete: "Osatuta",
      translationBountyTitle: "Itzulpen Saria",
      bountyDescription: "Itzuli Liana Banyan {{language}} hizkuntzara. Irabazi {{marks}} Marks.",
      scopeWelcome: "Ongi etorri / Mamuen Mundua pantailak",
      scopeCueCards: "Oinarrizko Pista Karta multzoa",
      scopeNavigation: "Nabigazio etiketak eta errore-mezuak",
      scopeWildfire: "Wildfire Beacon Run: Aurkitu lana",
      claimBounty: "Eskatu Itzulpen Sari hau",
      baseLanguage: "Oinarrizko hizkuntza -- ez da saririk behar.",
      claimedBy: "@{{handle}}-k eskatu du -- martxan.",
      marksProvisional: "{{marks}} Marks (behin-behineko)",
      speakFounderTitle: "Sortzailearen Ahotsa: Zergatik Hitz Hauek",
      speakFounderDesc: "Plataforma honetan hitz bakoitzak arrazoi bat du. 26 izen garrantzitsuenen jatorria.",
      howBountiesWork: "Nola Funtzionatzen Duten Itzulpen Sariak",
      step1Title: "Eskatu Saria",
      step1Body: "Ireki Itzulpen Sari bat Help Wanted-tik.",
      step2Title: "Itzuli eta Bidali",
      step2Body: "Itzuli beharrezko kate guztiak. Bidali Bounty Poster bidez.",
      step3Title: "Irabazi Marks",
      step3Body: "Onarpena jasotakoan, Marks jasoko dituzu eta IP Ledger-en erregistratuko zara.",
      hide: "ezkutatu",
      why: "zergatik?",
    },
    languageSwitcher: {
      changeLanguage: "Aldatu hizkuntza",
      selectLanguage: "Aukeratu hizkuntza",
      quickEnglish: "Ingelesa",
      tip: "Erabili hizkuntza desberdinetako pasahitzak Durinen Atean esperientzia bakarrak desblokeatzeko!",
    },
  },
  "gl": {
    speakFriend: {
      title: "Di amigo e entra.",
      description: "Liana Banyan está construída para ser aberta a cada idioma. Cada idioma aberto ten un premio de tradución.",
      languages: "idiomas",
      openBounties: "premios abertos",
      marksAwarded: "Marks outorgados (tokens de participación)",
      provisional: "Provisionalmente:",
      provisionalNotice: "A lista de idiomas e as taxas de Marks son provisionais. Os Marks son tokens de participación, non accións.",
      bountyOpen: "Premio aberto",
      claimed: "Reclamado",
      complete: "Completado",
      translationBountyTitle: "Premio de Tradución",
      bountyDescription: "Traduce Liana Banyan a {{language}}. Gaña {{marks}} Marks.",
      scopeWelcome: "Pantallas de Benvida / Mundo Fantasmal",
      scopeCueCards: "Conxunto básico de tarxetas de suxestión",
      scopeNavigation: "Etiquetas de navegación e mensaxes de erro",
      scopeWildfire: "Wildfire Beacon Run: Atopa traballo",
      claimBounty: "Reclama este Premio de Tradución",
      baseLanguage: "Idioma base -- non é preciso ningún premio.",
      claimedBy: "Premio reclamado por @{{handle}} -- en curso.",
      marksProvisional: "{{marks}} Marks (provisionalmente)",
      speakFounderTitle: "A Voz do Fundador: Por que Estas Palabras",
      speakFounderDesc: "Cada termo desta plataforma foi nomeado por un motivo. A orixe dos 26 nomes máis importantes.",
      howBountiesWork: "Como Funcionan os Premios de Tradución",
      step1Title: "Reclama o Premio",
      step1Body: "Abre un Premio de Tradución do taboleiro Help Wanted.",
      step2Title: "Traduce e Envía",
      step2Body: "Traduce todas as cadeas necesarias. Envía a través do fluxo Bounty Poster.",
      step3Title: "Gaña Marks",
      step3Body: "Após a aceptación, recibirás Marks e quedarás rexistrado no IP Ledger.",
      hide: "agochar",
      why: "por que?",
    },
    languageSwitcher: {
      changeLanguage: "Cambiar idioma",
      selectLanguage: "Seleccionar idioma",
      quickEnglish: "Inglés",
      tip: "Usa contrasinais en idiomas diferentes na Porta de Durin para desbloquear experiencias únicas!",
    },
  },
  "cy": {
    speakFriend: {
      title: "Dywed cyfaill ac enter.",
      description: "Mae Liana Banyan wedi'i hadeiladu i fod yn agored i bob iaith. Mae gan bob iaith agored un wobr cyfieithiad.",
      languages: "ieithoedd",
      openBounties: "gwobrau agored",
      marksAwarded: "Marks a roddir (tocynnau cyfranogi)",
      provisional: "Dros dro:",
      provisionalNotice: "Mae rhestr yr ieithoedd a chyfraddau Marks yn dros dro. Mae Marks yn docynnau cyfranogi, nid cyfranddaliadau.",
      bountyOpen: "Gwobr ar agor",
      claimed: "Hawliwyd",
      complete: "Wedi'i gwblhau",
      translationBountyTitle: "Gwobr Cyfieithiad",
      bountyDescription: "Cyfieithwch Liana Banyan i {{language}}. Enillwch {{marks}} Marks.",
      scopeWelcome: "Sgriniau Croeso / Byd Ysbrydion",
      scopeCueCards: "Casgliad Cerdyn Cliw Sylfaenol",
      scopeNavigation: "Labeli llywio a negeseuon gwall",
      scopeWildfire: "Wildfire Beacon Run: Canfod Gwaith",
      claimBounty: "Hawliwch y Wobr Cyfieithiad hon",
      baseLanguage: "Iaith sylfaen -- nid oes angen gwobr.",
      claimedBy: "Hawliwyd y wobr gan @{{handle}} -- ar waith.",
      marksProvisional: "{{marks}} Marks (dros dro)",
      speakFounderTitle: "Llais y Sylfaenydd: Pam y Geiriau Hyn",
      speakFounderDesc: "Mae pob term ar y platfform hwn wedi'i enwi am reswm. Tarddiad y 26 enw pwysicaf.",
      howBountiesWork: "Sut Mae Gwobrau Cyfieithiad yn Gweithio",
      step1Title: "Hawliwch y Wobr",
      step1Body: "Agorwch Wobr Cyfieithiad o'r bwrdd Help Wanted.",
      step2Title: "Cyfieithwch ac Anfonwch",
      step2Body: "Cyfieithwch yr holl linynni angenrheidiol. Anfonwch drwy lif Bounty Poster.",
      step3Title: "Enillwch Marks",
      step3Body: "Ar ôl derbyn, byddwch yn derbyn Marks ac yn cael eich cofnodi yn y IP Ledger.",
      hide: "cuddio",
      why: "pam?",
    },
    languageSwitcher: {
      changeLanguage: "Newid iaith",
      selectLanguage: "Dewiswch iaith",
      quickEnglish: "Saesneg",
      tip: "Defnyddiwch gyfrineiriau iaith wahanol wrth Ddrws Durin i ddatgloi profiadau unigryw!",
    },
  },
  "ga": {
    speakFriend: {
      title: "Abair cara agus isteach.",
      description: "Tá Liana Banyan tógtha le bheith oscailte do gach teanga. Tá duais amháin aistriúcháin ag gach teanga oscailte.",
      languages: "teangacha",
      openBounties: "duaisanna oscailte",
      marksAwarded: "Marks bronnta (comharthaí rannpháirtíochta)",
      provisional: "Sealadach:",
      provisionalNotice: "Tá liosta na dteangacha agus rátaí Marks sealadach. Is comharthaí rannpháirtíochta iad Marks, ní scaireanna.",
      bountyOpen: "Duais oscailte",
      claimed: "Éilíodh",
      complete: "Críochnaithe",
      translationBountyTitle: "Duais Aistriúcháin",
      bountyDescription: "Aistrigh Liana Banyan go {{language}}. Tuilleamh {{marks}} Marks.",
      scopeWelcome: "Scáileáin Fáilte / Domhan na Taibhsí",
      scopeCueCards: "Sraith Cárta Leide Bunúsaigh",
      scopeNavigation: "Lipéid nascleanúna agus teachtaireachtaí earráide",
      scopeWildfire: "Wildfire Beacon Run: Faigh Jab",
      claimBounty: "Éiligh an Duais Aistriúcháin seo",
      baseLanguage: "Teanga bhunúsach -- níl gá le duais.",
      claimedBy: "D'éiligh @{{handle}} an duais -- ar siúl.",
      marksProvisional: "{{marks}} Marks (sealadach)",
      speakFounderTitle: "Guth an Bhunaitheora: Cén Fáth na Focail Seo",
      speakFounderDesc: "Ainmníodh gach téarma ar an ardán seo ar chúis. Bunús na 26 ainm is tábhachtaí.",
      howBountiesWork: "Conas a Oibríonn Duaisanna Aistriúcháin",
      step1Title: "Éiligh an Duais",
      step1Body: "Oscail Duais Aistriúcháin ó chlár Help Wanted.",
      step2Title: "Aistrigh agus Cuir Isteach",
      step2Body: "Aistrigh gach sreabh riachtanach. Cuir isteach trí shruth Bounty Poster.",
      step3Title: "Tuilleamh Marks",
      step3Body: "Tar éis glacadh, gheobhaidh tú Marks agus déanfar thú a chlárú sa IP Ledger.",
      hide: "folaigh",
      why: "cén fáth?",
    },
    languageSwitcher: {
      changeLanguage: "Athraigh teanga",
      selectLanguage: "Roghnaigh teanga",
      quickEnglish: "Béarla",
      tip: "Úsáid pasfhocail i dteangacha éagsúla ag Doras Durin chun eispéiris uathúla a oscailt!",
    },
  },
  "is": {
    speakFriend: {
      title: "Segðu vin og farðu inn.",
      description: "Liana Banyan er byggð til að vera opin fyrir hvert mál. Hvert opið mál hefur eitt þýðingaverðlaun.",
      languages: "mál",
      openBounties: "opin verðlaun",
      marksAwarded: "Marks veitt (þátttökutókar)",
      provisional: "Tímabundið:",
      provisionalNotice: "Málalisti og Marks-hlutfall eru tímabundin. Marks eru þátttökutókar, ekki hlutabréf.",
      bountyOpen: "Verðlaun opin",
      claimed: "Krafist",
      complete: "Lokið",
      translationBountyTitle: "Þýðingaverðlaun",
      bountyDescription: "Þýddu Liana Banyan yfir á {{language}}. Þjónaðu {{marks}} Marks.",
      scopeWelcome: "Velkominn / Draugaheimur skjáir",
      scopeCueCards: "Grunnlegt vísbending-kortasett",
      scopeNavigation: "Leiðsagnarmerki og villuskilaboð",
      scopeWildfire: "Wildfire Beacon Run: Finndu starf",
      claimBounty: "Krefjast þessara Þýðingaverðlauna",
      baseLanguage: "Grunnmál -- engin verðlaun þörf.",
      claimedBy: "@{{handle}} krafðist -- í gangi.",
      marksProvisional: "{{marks}} Marks (tímabundið)",
      speakFounderTitle: "Rödd Stofnanda: Af Hverju Þessi Orð",
      speakFounderDesc: "Sérhver hugtak á þessum vettvangi er nafngift með ástæðu. Uppruni 26 mikilvægustu nafna.",
      howBountiesWork: "Hvernig Þýðingaverðlaun Virka",
      step1Title: "Krefjast Verðlauna",
      step1Body: "Opnaðu Þýðingaverðlaun frá Help Wanted-töflu.",
      step2Title: "Þýddu og Sendu",
      step2Body: "Þýddu allar nauðsynlegar strengjar. Sendu í gegnum Bounty Poster.",
      step3Title: "Þjónaðu Marks",
      step3Body: "Eftir samþykki færðu Marks og ert skráður í IP Ledger.",
      hide: "fela",
      why: "af hverju?",
    },
    languageSwitcher: {
      changeLanguage: "Skipta um mál",
      selectLanguage: "Veldu mál",
      quickEnglish: "Enska",
      tip: "Notaðu lykilorð á mismunandi málum við Dyr Durins til að opna einstæð reynsla!",
    },
  },
  "lb": {
    speakFriend: {
      title: "Soe Frënd, a goe erëm.",
      description: "Liana Banyan ass gebaut fir all Sprooch oppen ze sinn. All oppene Sprooch huet eng Iwwersetzungspräm.",
      languages: "Sproochen",
      openBounties: "oppen Prämen",
      marksAwarded: "Marks verdeelt (Participatiounstokens)",
      provisional: "Provesoresch:",
      provisionalNotice: "D'Sproochelëscht an Marks-Tariffer si provesoresch. Marks si Participatiounstokens, net Aktien.",
      bountyOpen: "Präm oppen",
      claimed: "Ugefuerdert",
      complete: "Fäerdeg",
      translationBountyTitle: "Iwwersetzungspräm",
      bountyDescription: "Iwwersetzt Liana Banyan an {{language}}. Verdéngt {{marks}} Marks.",
      scopeWelcome: "Wëllkommen / Geeschterwelt Schiirmer",
      scopeCueCards: "Grondsätzleche Hiweiskaartsëtz",
      scopeNavigation: "Navigatiounsetiketten a Fehlermeldungen",
      scopeWildfire: "Wildfire Beacon Run: Fannen enn Aarbecht",
      claimBounty: "Fuerdert dës Iwwersetzungspräm",
      baseLanguage: "Grondsproochen -- keng Präm noutwendeg.",
      claimedBy: "@{{handle}} huet ugefuerdert -- am Gaang.",
      marksProvisional: "{{marks}} Marks (provesoresch)",
      speakFounderTitle: "D'Stëmm vum Grënner: Firwat Dës Wierder",
      speakFounderDesc: "All Begrëff op dëser Plattform ass mat engem Grond benannt. D'Hierkonft vun de 26 wichtegste Nimm.",
      howBountiesWork: "Wéi Iwwersetzungspräme Fonctionéieren",
      step1Title: "Fuedert d'Präm",
      step1Body: "Öffnet eng Iwwersetzungspräm aus dem Help Wanted-Bord.",
      step2Title: "Iwwersetzt a Schéckt",
      step2Body: "Iwwersetzt all néidege Strings. Schéckt iwwer Bounty Poster.",
      step3Title: "Verdéngt Marks",
      step3Body: "No der Akzeptanz kritt Dir Marks a gitt am IP Ledger erfaasst.",
      hide: "verstoppen",
      why: "firwat?",
    },
    languageSwitcher: {
      changeLanguage: "Sprooch wiesselen",
      selectLanguage: "Sprooch auswiele",
      quickEnglish: "Englesch",
      tip: "Benotzt Passwierder a verschiddene Sproochen bei der Duerinstir fir eenzegaarteg Erfarungen opzeschloen!",
    },
  },
  "ht": {
    speakFriend: {
      title: "Di zanmi, epi antre.",
      description: "Liana Banyan bati pou li louvri pou chak lang. Chak lang ki louvri gen yon prim tradiksyon.",
      languages: "lang",
      openBounties: "prim louvri",
      marksAwarded: "Marks bay (tokèn patisipasyon)",
      provisional: "Pwovizoua:",
      provisionalNotice: "Lis lang ak pousantaj Marks yo pwovizoua. Marks se tokèn patisipasyon, pa aksyon.",
      bountyOpen: "Prim louvri",
      claimed: "Mande",
      complete: "Fini",
      translationBountyTitle: "Prim Tradiksyon",
      bountyDescription: "Tradui Liana Banyan nan {{language}}. Touche {{marks}} Marks.",
      scopeWelcome: "Ekran Byenveni / Mond Lespri",
      scopeCueCards: "Seri Kat Konsèy Debaz",
      scopeNavigation: "Etikèt navigasyon ak mesaj erè",
      scopeWildfire: "Wildfire Beacon Run: Jwenn Travay",
      claimBounty: "Mande Prim Tradiksyon Sa",
      baseLanguage: "Lang debaz -- pa gen prim ki nesesè.",
      claimedBy: "@{{handle}} mande -- ap kontinye.",
      marksProvisional: "{{marks}} Marks (pwovizoua)",
      speakFounderTitle: "Vwa Fondatè a: Poukisa Mo Sa Yo",
      speakFounderDesc: "Chak tèm sou platfòm sa a gen yon rezon. Orijin 26 non ki pi enpòtan.",
      howBountiesWork: "Kijan Prim Tradiksyon Travay",
      step1Title: "Mande Prim nan",
      step1Body: "Ouvri Prim Tradiksyon nan Help Wanted.",
      step2Title: "Tradui epi Soumèt",
      step2Body: "Tradui tout chaîn nesesè yo. Soumèt via Bounty Poster.",
      step3Title: "Touche Marks",
      step3Body: "Apre akseptasyon, ou resevwa Marks e ou anrejistre nan IP Ledger.",
      hide: "kache",
      why: "poukisa?",
    },
    languageSwitcher: {
      changeLanguage: "Chanje lang",
      selectLanguage: "Chwazi lang",
      quickEnglish: "Anglè",
      tip: "Itilize mo passe diferan lang nan Pòt Durin pou debloke eksperyans inik!",
    },
  },
  "qu": {
    speakFriend: {
      title: "Nispa amigo, yaykuy.",
      description: "Liana Banyan sapa simipi kicharisqa rurasqa. Sapa simi uj traduccion riwariywan.",
      languages: "simikuna",
      openBounties: "kicharisqa riwariy",
      marksAwarded: "Marks qusqa (llankay tokenkunam)",
      provisional: "Wasipim:",
      provisionalNotice: "Simi lista Marks preciokunawan wasipim. Marks llankay tokenkuna, manachus acciónkuna.",
      bountyOpen: "Riwariy kicharisqa",
      claimed: "Mañasqa",
      complete: "Tukusqa",
      translationBountyTitle: "Traduccion Riwariy",
      bountyDescription: "Liana Banyan {{language}} simiman tikray. {{marks}} Marks taripaykuspayki.",
      scopeWelcome: "Allinllachu / Supay Pacha pantalla",
      scopeCueCards: "Principal Kard Yuyaykuna",
      scopeNavigation: "Llankay siñalkuna rikuriy",
      scopeWildfire: "Wildfire Beacon Run: Llankayniyta taripay",
      claimBounty: "Kay Traduccion Riwariy mañakuy",
      baseLanguage: "Mama simi -- mana riwariy",
      claimedBy: "@{{handle}} mañasqa -- apaykachakuchkan.",
      marksProvisional: "{{marks}} Marks (wasipim)",
      speakFounderTitle: "Rurakuq Simy: Imanaqtintam Kay Simikunas",
      speakFounderDesc: "Kay plataformapin tukuy simikunam imaymanapi suticharisqa. Waranqa 26 sutikuna.",
      howBountiesWork: "Imaynatam Traduccion Riwariy Ruray",
      step1Title: "Riwariy mañakuy",
      step1Body: "Help Wanted lapitam Traduccion Riwariy kichariy.",
      step2Title: "Tikray haywaykuy",
      step2Body: "Tukuy string tikray. Bounty Poster ruway.",
      step3Title: "Marks taripaykuy",
      step3Body: "Chaskinaspayki Marks chaskiyta IP Ledger rikuchiy.",
      hide: "pakay",
      why: "imanaqtim?",
    },
    languageSwitcher: {
      changeLanguage: "Simi tikray",
      selectLanguage: "Simi akllay",
      quickEnglish: "Ingles",
      tip: "Durin Punkupi sapa simi gaveluwan kamayqa yakuspas!",
    },
  },
  "war": {
    speakFriend: {
      title: "Igsulti kaupod, ha pagsud.",
      description: "An Liana Banyan ginpatukod para mahimutang bukas ha bawat pinulongan. An kada bukas nga pinulongan may usa ka ganti ha paghubad.",
      languages: "mga pinulongan",
      openBounties: "bukas nga ganti",
      marksAwarded: "Marks ginhatag (mga token han pakikibayad)",
      provisional: "Temporaryo:",
      provisionalNotice: "An listahan han mga pinulongan ngan mga rate han Marks temporaryo. An Marks mga token han pakikibayad, diri equity.",
      bountyOpen: "Bukas an ganti",
      claimed: "Ginkuha na",
      complete: "Nahuman",
      translationBountyTitle: "Ganti han Paghubad",
      bountyDescription: "Hubara an Liana Banyan ngadto ha {{language}}. Makita an {{marks}} Marks.",
      scopeWelcome: "Mga screen han Maupay nga Pag-abot / Ghost World",
      scopeCueCards: "Core nga hanay han Cue Card",
      scopeNavigation: "Mga label han navigasyon ngan mensahe han sayop",
      scopeWildfire: "Wildfire Beacon Run: Pangita hin Trabaho",
      claimBounty: "I-claim ini nga Ganti han Paghubad",
      baseLanguage: "Sukaranan nga pinulongan -- waray ganti nga gikinahanglan.",
      claimedBy: "Ginkuha ni @{{handle}} -- nagpadayon.",
      marksProvisional: "{{marks}} Marks (temporaryo)",
      speakFounderTitle: "Tingog han Nagpatukod: Kay Ano Ini nga mga Pulong",
      speakFounderDesc: "An kada termino ginhinganlan tungod ha usa ka rason. An gigikanan han 26 pinaka-importante nga mga ngaran.",
      howBountiesWork: "Pira nga Pagtrabaho han mga Ganti han Paghubad",
      step1Title: "I-claim an Ganti",
      step1Body: "Abrihi an Ganti han Paghubad tikang ha Help Wanted.",
      step2Title: "Hubara ngan Isumite",
      step2Body: "Hubara an ngatanan nga string nga gikinahanglan. Isumite pinaagi han Bounty Poster.",
      step3Title: "Makita ang Marks",
      step3Body: "Ha pag-dawat, makakadawat ka hin Marks ngan ma-rekord ha IP Ledger.",
      hide: "itago",
      why: "kay ano?",
    },
    languageSwitcher: {
      changeLanguage: "Usba an pinulongan",
      selectLanguage: "Pilia an pinulongan",
      quickEnglish: "Ingles",
      tip: "Gamita in iba-iba nga password han pinulongan ha Pultahan ni Durin para ma-unlock an natatanging kasinatian!",
    },
  },
  "nso": {
    speakFriend: {
      title: "Bolela mogwera, go tsene.",
      description: "Liana Banyan e agwa go bula go polelo yohle. Polelo ye nngwe le ye nngwe e na le moputso o mongwe wa phetolelo.",
      languages: "dipolelo",
      openBounties: "meputso ye e bulegilego",
      marksAwarded: "Marks e neelwe (ditokene tsa go ba karolo)",
      provisional: "Ka nakoana:",
      provisionalNotice: "Lenaane la dipuo le diterefe tsa Marks ke tsa nakoana. Marks ke ditokene tsa go ba karolo, esego dikaelo.",
      bountyOpen: "Moputso o bulegilego",
      claimed: "Go kgopilwe",
      complete: "Go phethilwe",
      translationBountyTitle: "Moputso wa Phetolelo",
      bountyDescription: "Fetola Liana Banyan go {{language}}. Hwetsa {{marks}} Marks.",
      scopeWelcome: "Dikgato tsa Kamogelogong / Lefase la Mewa",
      scopeCueCards: "Sete ya Karata ya Maele",
      scopeNavigation: "Dietemisi tsa tsela le melaetsa ya mathata",
      scopeWildfire: "Wildfire Beacon Run: Hwetsa Mošomo",
      claimBounty: "Kgopela Moputso ono wa Phetolelo",
      baseLanguage: "Polelo ya motheo -- go hlokagala moputso.",
      claimedBy: "@{{handle}} o kgopile -- e sepela.",
      marksProvisional: "{{marks}} Marks (ka nakoana)",
      speakFounderTitle: "Lentšu la Mosadiši: Ke Goreng Mantšu Ao",
      speakFounderDesc: "Lentšu lefe lefe mo go phepefatšwa ka lebaka. Motheo wa mabitšo 26 a bohlokwa.",
      howBountiesWork: "Meputso ya Phetolelo e Dira Bjang",
      step1Title: "Kgopela Moputso",
      step1Body: "Bula Moputso wa Phetolelo go tswa Help Wanted.",
      step2Title: "Fetola le Romela",
      step2Body: "Fetola distring tšohle tše di hlokegago. Romela ka Bounty Poster.",
      step3Title: "Hwetsa Marks",
      step3Body: "Ka morago ga go amogelwa, o hwetsa Marks le go kwadišwa ho IP Ledger.",
      hide: "pata",
      why: "goreng?",
    },
    languageSwitcher: {
      changeLanguage: "Fetola polelo",
      selectLanguage: "Kgetola polelo",
      quickEnglish: "Sekgowa",
      tip: "Diriša diphasewete tša polelo tše di fapanago ka Kgoro ya Durin go bula maitemogelo a a ikgethago!",
    },
  },
  "lg": {
    speakFriend: {
      title: "Yogera mukwano, olinge okuyingira.",
      description: "Liana Banyan yazimbwa okuba evunaamu eri olulimi lulilwona. Olulimi oluwona olufunzibwa olulina musawo ogumu gwa kukyusa.",
      languages: "olulimi",
      openBounties: "emisawo efunzibwa",
      marksAwarded: "Marks yaweebwa (ebyuma bya kuyingira)",
      provisional: "Akabanga:",
      provisionalNotice: "Erinnya ery'olulimi ne Marks enkalu ya akabanga. Marks bwe byuma bya kuyingira, si bisina.",
      bountyOpen: "Omusawo gufunzibwa",
      claimed: "Gyakozesebwa",
      complete: "Okumalirira",
      translationBountyTitle: "Omusawo gwa Kukyusa",
      bountyDescription: "Kyusa Liana Banyan mu {{language}}. Wa {{marks}} Marks.",
      scopeWelcome: "Ebizika bya Musuze / Ensi ya Mizimu",
      scopeCueCards: "Setti ya Kaada Ennamba",
      scopeNavigation: "Emikutu gyokugendera n'obutebutebu",
      scopeWildfire: "Wildfire Beacon Run: Noonya Omulimu",
      claimBounty: "Saba Omusawo Guno gwa Kukyusa",
      baseLanguage: "Olulimi olw'ekifo -- tewali musawo gw'okwetaaga.",
      claimedBy: "@{{handle}} yagisaba -- esolera.",
      marksProvisional: "{{marks}} Marks (akabanga)",
      speakFounderTitle: "Eddoboozi ly'Omutondaali: Kye Kino Ebyavugibwa",
      speakFounderDesc: "Ekimu kyonna wano kisubizibwako erinnya olw'empaka. Ensibuko y'amannya 26 agatenderezebwa.",
      howBountiesWork: "Emisawo gya Kukyusa Gikola Gutya",
      step1Title: "Saba Omusawo",
      step1Body: "Fungula Omusawo gwa Kukyusa okuva Help Wanted.",
      step2Title: "Kyusa Owonawo",
      step2Body: "Kyusa ebimu byonna ebyetaagibwa. Wonawo Bounty Poster.",
      step3Title: "Wa Marks",
      step3Body: "Oluvannyuma lw'okuwaakana, ofuna Marks n'okukyusibwako ku IP Ledger.",
      hide: "kisa",
      why: "lwaki?",
    },
    languageSwitcher: {
      changeLanguage: "Kyusa olulimi",
      selectLanguage: "Londa olulimi",
      quickEnglish: "Olungereza",
      tip: "Kozesa ebigambo by'olulimi obukyufu ku Mulyango gwa Durin okusobola okufungula ebirungi bisooka!",
    },
  },
  "ts": {
    speakFriend: {
      title: "Hlamula xinghana, u nghena.",
      description: "Liana Banyan yakhiwe ku vula eka ririmi ra le henhla. Ririmi rin'wana na rin'wana ri na mholo un'we wa ku hundzuluxiwa.",
      languages: "tindzimi",
      openBounties: "tiholo ta ku vuliwa",
      marksAwarded: "Marks yi nyikhiwa (ti-token ta ku teka xiphemu)",
      provisional: "Ku henhla na nkarhi:",
      provisionalNotice: "Xilotana xa tindzimi na tirate ta Marks a ku henhla na nkarhi. Marks ti-token ta ku teka xiphemu, hakunene a tihisa.",
      bountyOpen: "Mholo wu vuliwa",
      claimed: "Ku kombela",
      complete: "Ku heteleriwa",
      translationBountyTitle: "Mholo wa Ku Hundzuluxiwa",
      bountyDescription: "Hundzuluxa Liana Banyan eka {{language}}. Kuma {{marks}} Marks.",
      scopeWelcome: "Swikombelo swa Amukeriweni / Misava ya Swikwembu",
      scopeCueCards: "Seti ya Makarata ya Matimba",
      scopeNavigation: "Manimelo ya ndlela na mitlhela ya swiboxi",
      scopeWildfire: "Wildfire Beacon Run: Kuma Ntirho",
      claimBounty: "Kombela Mholo Lowu wa Ku Hundzuluxiwa",
      baseLanguage: "Ririmi ra ntlawa -- a ku na mholo wu lavekaka.",
      claimedBy: "@{{handle}} u kombele -- ku hamba.",
      marksProvisional: "{{marks}} Marks (ku henhla na nkarhi)",
      speakFounderTitle: "Rito ra Musimisi: Hikwalaho ka Tinyimpi Leti",
      speakFounderDesc: "Rito ra le henhla na rin'wana eCross a ri vuliwile hi leswi. Ntlawa wa Mamingi 26 wa ntlawa.",
      howBountiesWork: "Tiholo ta Ku Hundzuluxiwa ti Tirhisa Njhani",
      step1Title: "Kombela Mholo",
      step1Body: "Vula Mholo wa Ku Hundzuluxiwa eka Help Wanted.",
      step2Title: "Hundzuluxa Tlhela u Rhumelela",
      step2Body: "Hundzuluxa swiringeti hinkwaswo. Rhumelela hi Bounty Poster.",
      step3Title: "Kuma Marks",
      step3Body: "Endzhaku ka ku amukeriweni, u kuma Marks u ŋwala eka IP Ledger.",
      hide: "fihla",
      why: "hikwalaho?",
    },
    languageSwitcher: {
      changeLanguage: "Hintsheka ririmi",
      selectLanguage: "Hlawula ririmi",
      quickEnglish: "Xinghezi",
      tip: "Tirhisa tisintha ta tindzimi tintshwa eka Ntsena wa Durin ku vula swiphiqo swa le henhla!",
    },
  },
  "ss": {
    speakFriend: {
      title: "Tsini umngani, ungenele.",
      description: "I-Liana Banyan yakhelwe ukuvulwa kululimi lonkhe. Lulimi ngalunye lolukhula lunebhizi lokuhumusha linye.",
      languages: "tilulwimi",
      openBounties: "tibhizi letivuliwe",
      marksAwarded: "Marks anikwe (ematokeni ekubamba inyanga)",
      provisional: "Kwesikhashana:",
      provisionalNotice: "Uhlu lwetilulwimi namazinga emaMark angesikashana. Marks ematokeni ekubamba inyanga, hhayi temali.",
      bountyOpen: "Ibhizi livuliwe",
      claimed: "Kukhanyelwe",
      complete: "Kuphelele",
      translationBountyTitle: "Ibhizi lokuHumusha",
      bountyDescription: "Humusha i-Liana Banyan ngelulwimi lwe-{{language}}. Thola {{marks}} Marks.",
      scopeWelcome: "Ama-screen Wamukela / Inhlabathi Yemimoya",
      scopeCueCards: "Isampula se-Cue Card Esiyinhloko",
      scopeNavigation: "Izilebula zokukhomba kanye nemilayezo yamaphoswa",
      scopeWildfire: "Wildfire Beacon Run: Thola Umsebenzi",
      claimBounty: "Khanyela le-Bhizi lokuHumusha",
      baseLanguage: "Lulwimi lwesisekelo -- akudingeki bhizi.",
      claimedBy: "@{{handle}} wakhanyela -- uyaqhubeka.",
      marksProvisional: "{{marks}} Marks (kwesikhashana)",
      speakFounderTitle: "Lizwi loMsunguli: Kungani Lamamagama",
      speakFounderDesc: "Igama ngalinye kule platform lanikezwa ibizo ngezizathu. Imvelaphi yamagama angama-26 abalulekile.",
      howBountiesWork: "Tibhizi TokuHumusha Timsebenti Kanjani",
      step1Title: "Khanyela Ibhizi",
      step1Body: "Vula i-Bhizi lokuHumusha ku-Help Wanted.",
      step2Title: "Humusha bese Uthumela",
      step2Body: "Humusha tonkhe izichazelo ezidzingekayo. Thumela nge-Bounty Poster.",
      step3Title: "Thola Marks",
      step3Body: "Uma samukela, uthola Marks futhi urekhodi ku-IP Ledger.",
      hide: "fihla",
      why: "kungani?",
    },
    languageSwitcher: {
      changeLanguage: "Shintsha lulwimi",
      selectLanguage: "Khetha lulwimi",
      quickEnglish: "IsiNgisi",
      tip: "Sebenzisa amagama aphasiwedhi etilulwimi tehlukene eMnyango kaDurin ukuvula izinto ezikhethekile!",
    },
  },
  "sat": {
    speakFriend: {
      title: "ᱢᱤᱛᱨᱚ ᱠᱟᱹᱫᱟ, ᱧᱟᱢ ᱮᱫ.",
      description: "Liana Banyan ᱥᱟᱞᱟ ᱫᱚ ᱱᱟᱶᱟ ᱥᱮᱬᱟᱜᱼᱟᱠᱟᱱ ᱢᱤᱛᱽ ᱥᱮᱬᱮᱡ ᱪᱤᱱᱟᱹᱭ ᱠᱟᱱᱟ। ᱡᱟᱦᱟᱸ ᱥᱮᱬᱟᱜᱼᱟᱠᱟᱱ ᱜᱟᱱᱛᱟ ᱥᱮᱬᱮᱡ ᱠᱟᱱᱟ।",
      languages: "ᱥᱮᱬᱮᱡ",
      openBounties: "ᱢᱤᱫᱽ ᱜᱟᱱᱛᱟ",
      marksAwarded: "Marks ᱠᱷᱚᱨᱱᱚᱜᱼᱟ (ᱥᱟᱢᱟᱱ ᱠᱚ)",
      provisional: "ᱩᱛᱟᱹᱨᱤᱡ:",
      provisionalNotice: "ᱥᱮᱬᱮᱡ ᱠᱚᱨᱤᱠᱟ ᱟᱨ Marks ᱦᱟᱲᱟᱢ ᱩᱛᱟᱹᱨᱤᱡ। Marks ᱥᱟᱢᱟᱱ ᱠᱚ, ᱜᱟᱦᱟᱸᱠᱤ ᱱᱚᱶᱟ ᱨᱮᱱᱟᱜ।",
      bountyOpen: "ᱜᱟᱱᱛᱟ ᱢᱤᱫᱽ ᱮᱱᱟ",
      claimed: "ᱫᱷᱟᱸᱠᱚᱣᱟ",
      complete: "ᱢᱩᱪᱟᱹᱫ",
      translationBountyTitle: "ᱧᱟᱢᱟᱜ ᱜᱟᱱᱛᱟ",
      bountyDescription: "Liana Banyan {{language}} ᱥᱮᱬᱮᱡ ᱨᱮ ᱧᱟᱢ। {{marks}} Marks ᱜᱮᱞ।",
      scopeWelcome: "ᱯᱟᱨᱥᱟᱞ / ᱥᱮᱸᱫᱽᱨᱟ ᱫᱩᱱᱤᱭᱟ",
      scopeCueCards: "ᱢᱩᱞᱟᱹ ᱠᱟᱹᱲᱦᱟ ᱠᱷᱟᱹᱛᱤᱨ",
      scopeNavigation: "ᱥᱟᱜᱟᱨ ᱟᱨ ᱦᱚᱲ ᱪᱮᱛᱟᱱ",
      scopeWildfire: "Wildfire Beacon Run: ᱚᱨᱠᱟ ᱡᱚᱜᱟᱲ",
      claimBounty: "ᱩᱱᱤ ᱧᱟᱢᱟᱜ ᱜᱟᱱᱛᱟ ᱫᱷᱟᱸᱠ",
      baseLanguage: "ᱢᱩᱞ ᱥᱮᱬᱮᱡ -- ᱜᱟᱱᱛᱟ ᱵᱟᱶᱟ ᱱᱚᱶᱟ।",
      claimedBy: "@{{handle}} ᱫᱷᱟᱸᱠᱮᱫ -- ᱟᱨᱮ ᱥᱟᱦᱮᱸ।",
      marksProvisional: "{{marks}} Marks (ᱩᱛᱟᱹᱨᱤᱡ)",
      speakFounderTitle: "ᱥᱟᱸᱦᱟᱸᱞᱟᱭ ᱜᱚᱱᱚ: ᱮᱸᱠᱷᱟᱹᱜ ᱠᱟᱦᱟᱸ ᱠᱚ",
      speakFounderDesc: "ᱤᱦᱩᱫ ᱯᱞᱮᱴᱯᱷᱚᱨᱢ ᱨᱮ ᱦᱚᱱᱟᱜ ᱫᱚ ᱠᱟᱹᱨᱣᱚ ᱵᱟᱫ। 26 ᱢᱩᱦᱩᱲ ᱱᱩᱛᱩᱢ।",
      howBountiesWork: "ᱧᱟᱢᱟᱜ ᱜᱟᱱᱛᱟ ᱠᱮᱫᱚᱭ",
      step1Title: "ᱜᱟᱱᱛᱟ ᱫᱷᱟᱸᱠ",
      step1Body: "Help Wanted ᱨᱮ ᱜᱟᱱᱛᱟ ᱛᱮᱰ।",
      step2Title: "ᱧᱟᱢ ᱟᱨ ᱡᱟᱱᱟᱣ",
      step2Body: "ᱥᱟᱵᱚ ᱡᱷᱟᱱ ᱧᱟᱢ। Bounty Poster ᱛᱮ ᱡᱟᱱᱟᱣ।",
      step3Title: "Marks ᱜᱮᱞ",
      step3Body: "ᱜᱮᱞᱮᱞᱮ Marks ᱟᱨ IP Ledger ᱨᱮ ᱞᱮᱠᱷᱟ।",
      hide: "ᱦᱩᱰᱤᱠ",
      why: "ᱮᱸᱠᱷᱟᱹᱜ?",
    },
    languageSwitcher: {
      changeLanguage: "ᱥᱮᱬᱮᱡ ᱵᱚᱫᱚᱞ",
      selectLanguage: "ᱥᱮᱬᱮᱡ ᱜᱩᱱᱟᱹ",
      quickEnglish: "ᱤᱝᱜᱽᱨᱮᱡᱤ",
      tip: "Durin ᱫᱟᱲ ᱨᱮ ᱪᱷᱟᱸᱫ ᱥᱮᱬᱮᱡ ᱥᱮᱬᱮᱡ ᱯᱟᱥᱣᱟᱲᱰ ᱢᱮᱛᱟᱣ!",
    },
  },
  "doi": {
    speakFriend: {
      title: "दोस्त बोलो, ते अंदर आओ।",
      description: "Liana Banyan हर भाषा लई खुल्ली बनाई गई है। हर भाषा दा इक अनुवाद इनाम है।",
      languages: "भाषाएँ",
      openBounties: "खुल्ले इनाम",
      marksAwarded: "Marks दित्ते (भागीदारी टोकन)",
      provisional: "अस्थाई:",
      provisionalNotice: "भाषाएँ दी लिस्ट ते Marks दर अस्थाई न। Marks भागीदारी टोकन न, शेयर नईं।",
      bountyOpen: "इनाम खुल्ला है",
      claimed: "दावा कित्ता",
      complete: "पूरा",
      translationBountyTitle: "अनुवाद इनाम",
      bountyDescription: "Liana Banyan कनू {{language}} च अनुवाद करो। {{marks}} Marks कमाओ।",
      scopeWelcome: "स्वागत / भूत दुनिया स्क्रीन",
      scopeCueCards: "मुख्य क्यू कार्ड सेट",
      scopeNavigation: "नेविगेशन लेबल ते गलती संदेश",
      scopeWildfire: "Wildfire Beacon Run: नौकरी पाओ",
      claimBounty: "इ अनुवाद इनाम दा दावा करो",
      baseLanguage: "मूल भाषा -- कोई इनाम दी लोड़ नईं।",
      claimedBy: "@{{handle}} ने दावा कित्ता -- जारी है।",
      marksProvisional: "{{marks}} Marks (अस्थाई)",
      speakFounderTitle: "संस्थापक दी आवाज़: इ शब्द किआलई",
      speakFounderDesc: "इस प्लेटफार्म पर हर शब्द कारण दे नाल नामित। 26 मुख्य नामें दा मूल।",
      howBountiesWork: "अनुवाद इनाम किस तरां काम करदे न",
      step1Title: "इनाम दावा करो",
      step1Body: "Help Wanted बोर्ड तों अनुवाद इनाम खोलो।",
      step2Title: "अनुवाद करो ते जमा करो",
      step2Body: "सब जरूरी स्ट्रिंग दा अनुवाद करो। Bounty Poster नाल जमा करो।",
      step3Title: "Marks कमाओ",
      step3Body: "कबूलने पर Marks मिलंगे। IP Ledger च दर्ज होवोगे।",
      hide: "लुकाओ",
      why: "किआलई?",
    },
    languageSwitcher: {
      changeLanguage: "भाषा बदलो",
      selectLanguage: "भाषा चुनो",
      quickEnglish: "अंग्रेजी",
      tip: "Durin's Door पर वखरी-वखरी भाषाएँ दे पासवर्ड वरतो!",
    },
  },
  "kok": {
    speakFriend: {
      title: "मित्र सांग आनी भितर ये.",
      description: "Liana Banyan सर्व भाशांखातीर उगती केल्ली आसा. प्रत्येक भाशेखातीर एक अनुवाद बक्षीस आसा.",
      languages: "भाशा",
      openBounties: "उगतीं बक्षिसां",
      marksAwarded: "Marks दिल्ले (सहभाग टोकन)",
      provisional: "तात्पुरतें:",
      provisionalNotice: "भाशांची यादी आनी Marks दर तात्पुरते आसात. Marks सहभाग टोकन जावन आसात, इक्विटी न्हय.",
      bountyOpen: "बक्षीस उगतें",
      claimed: "दावो केलो",
      complete: "पूर्ण",
      translationBountyTitle: "अनुवाद बक्षीस",
      bountyDescription: "Liana Banyan {{language}} भाशेत अनुवाद करा. {{marks}} Marks जोडा.",
      scopeWelcome: "स्वागत / भुताचें जग स्क्रीन",
      scopeCueCards: "मूळ क्यू कार्ड सेट",
      scopeNavigation: "नेव्हिगेशन लेबलां आनी चूक संदेश",
      scopeWildfire: "Wildfire Beacon Run: नोकरी मेळा",
      claimBounty: "हें अनुवाद बक्षीस दावो करा",
      baseLanguage: "मूळ भाशा -- बक्षीस नाका.",
      claimedBy: "@{{handle}} दावो केलो -- चालू.",
      marksProvisional: "{{marks}} Marks (तात्पुरतें)",
      speakFounderTitle: "संस्थापकाचो आवाज: हे शब्द कित्याक",
      speakFounderDesc: "ह्या प्लॅटफॉर्मार प्रत्येक शब्द कारणान नांव दिल्लें. 26 म्हत्वाच्या नावांचें मूळ.",
      howBountiesWork: "अनुवाद बक्षिसां कशीं काम करतात",
      step1Title: "बक्षीस दावो करा",
      step1Body: "Help Wanted बोर्डावेल्यान अनुवाद बक्षीस उगता करा.",
      step2Title: "अनुवाद करा आनी सादर करा",
      step2Body: "सर्व गरजेचे स्ट्रिंग अनुवाद करा. Bounty Poster जरिया सादर करा.",
      step3Title: "Marks जोडा",
      step3Body: "मान्यतेनंतर Marks मेळटात. IP Ledger त नोंद जाता.",
      hide: "लिपोवा",
      why: "कित्याक?",
    },
    languageSwitcher: {
      changeLanguage: "भाशा बदला",
      selectLanguage: "भाशा निवडा",
      quickEnglish: "इंग्लीश",
      tip: "Durin's Door वयर वेगवेगळ्या भाशांचे पासवर्ड वापरा!",
    },
  },
  "mni": {
    speakFriend: {
      title: "ꯃꯤꯇꯩ ꯁꯤꯖꯤꯡꯕꯥ, ꯍꯦꯟꯊꯤꯕ।",
      description: "Liana Banyan ꯑꯃꯨ�ꯛ ꯂꯣꯟ ꯑꯃꯗꯝ ꯑꯁꯤ ꯉꯁꯤꯅꯕꯥ ꯋꯥꯈꯜꯂꯣꯛꯄꯥ। ꯂꯣꯟ ꯃꯤꯠꯇꯅꯥ ꯑꯃꯥ ꯃꯈꯜ ꯑꯃꯥ ꯊꯕꯛ।",
      languages: "ꯂꯣꯟ",
      openBounties: "ꯌꯥꯎꯔꯤ ꯊꯕꯛ",
      marksAwarded: "Marks ꯄꯤꯔꯦ (ꯑꯣꯏꯅꯥ ꯂꯦꯞꯄꯥ)",
      provisional: "ꯇꯤꯃꯨꯗꯨ:",
      provisionalNotice: "ꯂꯣꯟ ꯑꯃꯁꯨꯡ Marks ꯐꯤꯔꯤ ꯇꯤꯃꯨꯗꯨ। Marks ꯑꯣꯏꯅꯥ ꯂꯦꯞꯄꯥ ꯁꯅꯥ, ꯈꯨꯗꯩ ꯱꯰꯰%।",
      bountyOpen: "ꯊꯕꯛ ꯌꯥꯎ",
      claimed: "ꯂꯨꯁꯤꯟꯅꯔꯤ",
      complete: "ꯄꯨꯔꯛ",
      translationBountyTitle: "ꯂꯣꯟꯁꯤꯡ ꯊꯕꯛ",
      bountyDescription: "Liana Banyan {{language}} ꯂꯣꯟꯗꯥ ꯂꯣꯟꯁꯤꯡ ꯇꯧ। {{marks}} Marks ꯍꯩꯔꯤꯕꯤ।",
      scopeWelcome: "ꯋꯥꯐꯝꯃꯤ / ꯃꯤꯠ ꯄꯨꯝꯕꯥ",
      scopeCueCards: "ꯃꯍꯩꯀꯤ ꯀꯥꯔꯗ ꯁꯦꯠ",
      scopeNavigation: "ꯅꯦꯚꯤꯒꯦꯁꯅ ꯂꯦꯕꯜ ꯑꯃꯁꯨꯡ ꯚꯨꯜ",
      scopeWildfire: "Wildfire Beacon Run: ꯀꯥꯟꯕꯥ ꯍꯩꯕꯤ",
      claimBounty: "ꯑꯁꯤ ꯂꯣꯟꯁꯤꯡ ꯊꯕꯛ ꯂꯨꯁꯤꯡꯕꯤ",
      baseLanguage: "ꯃꯔꯨ ꯂꯣꯟ -- ꯊꯕꯛ ꯅꯠꯇꯦ।",
      claimedBy: "@{{handle}} ꯂꯨꯁꯤꯟꯅꯔꯤ -- ꯑꯣꯏꯅꯥ।",
      marksProvisional: "{{marks}} Marks (ꯇꯤꯃꯨꯗꯨ)",
      speakFounderTitle: "ꯃꯉꯥꯡꯏꯕꯥ ꯀꯣꯜ: ꯑꯁꯤ ꯃꯥꯅꯤꯡ",
      speakFounderDesc: "ꯄꯜꯌꯦꯇꯐꯣꯔꯝ ꯑꯁꯤꯗꯥ ꯃꯥꯟ ꯊꯔꯤꯕꯥ ꯀꯣꯟꯕꯥ। 26 ꯅꯩꯡꯕꯥ ꯃꯤꯡ।",
      howBountiesWork: "ꯂꯣꯟꯁꯤꯡ ꯊꯕꯛ ꯑꯣꯏꯕꯥ",
      step1Title: "ꯊꯕꯛ ꯂꯨꯁꯤꯡꯕꯤ",
      step1Body: "Help Wanted ꯗꯥ ꯂꯣꯟꯁꯤꯡ ꯊꯕꯛ ꯕꯨꯄꯥ।",
      step2Title: "ꯂꯣꯟꯁꯤꯡ ꯑꯃꯁꯨꯡ ꯁꯦꯟꯗ",
      step2Body: "ꯊꯕꯛ ꯁ꯭ꯠꯔꯤꯡ ꯂꯣꯟꯁꯤꯡ ꯇꯧ। Bounty Poster ꯗꯥ ꯁꯦꯟꯗ।",
      step3Title: "Marks ꯍꯩꯔꯤꯕꯤ",
      step3Body: "ꯑꯃꯁꯨꯡ ꯄꯜꯌꯦꯇꯐꯣꯔꯝ Marks ꯑꯃꯁꯨꯡ IP Ledger ꯗꯥ ꯊꯩꯔꯤꯕꯤ।",
      hide: "ꯌꯦꯡꯕꯤ",
      why: "ꯀꯗꯥꯢ?",
    },
    languageSwitcher: {
      changeLanguage: "ꯂꯣꯟ ꯁꯤꯖꯤꯟꯕꯤ",
      selectLanguage: "ꯂꯣꯟ ꯁꯦꯂꯦꯛꯇ",
      quickEnglish: "ꯏꯡꯂꯤꯁ",
      tip: "Durin ꯁꯩꯄꯣꯛꯗꯥ ꯂꯣꯟ ꯐꯔꯣꯕꯥ ꯄꯥꯁꯋꯥꯔꯗ ꯇꯧꯒꯗꯕꯨ!",
    },
  },
  "as": {
    speakFriend: {
      title: "বন্ধু বুলি কোৱা আৰু সোমোৱা।",
      description: "লিয়ানা বান্যান প্ৰতিটো ভাষাৰ বাবে মুকলি। প্ৰতিটো ভাষাৰ বাবে এটা অনুবাদ পুৰস্কাৰ আছে।",
      languages: "ভাষা",
      openBounties: "মুকলি পুৰস্কাৰ",
      marksAwarded: "Marks দিয়া হৈছে (অংশগ্ৰহণ টোকেন)",
      provisional: "অস্থায়ী:",
      provisionalNotice: "ভাষাৰ তালিকা আৰু Marks হাৰ অস্থায়ী। Marks অংশগ্ৰহণ টোকেন, শ্বেয়াৰ নহয়।",
      bountyOpen: "পুৰস্কাৰ মুকলি",
      claimed: "দাবী কৰা হৈছে",
      complete: "সম্পূৰ্ণ",
      translationBountyTitle: "অনুবাদ পুৰস্কাৰ",
      bountyDescription: "লিয়ানা বান্যান {{language}} লৈ অনুবাদ কৰক। {{marks}} Marks উপাৰ্জন কৰক।",
      scopeWelcome: "স্বাগত / ভূত পৃথিৱী স্ক্ৰিন",
      scopeCueCards: "মূল কিউ কাৰ্ড ছেট",
      scopeNavigation: "নেভিগেশ্যন লেবেল আৰু ত্ৰুটি বাৰ্তা",
      scopeWildfire: "Wildfire Beacon Run: চাকৰি পাওক",
      claimBounty: "এই অনুবাদ পুৰস্কাৰ দাবী কৰক",
      baseLanguage: "মূল ভাষা -- কোনো পুৰস্কাৰ নালাগে।",
      claimedBy: "@{{handle}} দাবী কৰিছে -- চলি আছে।",
      marksProvisional: "{{marks}} Marks (অস্থায়ী)",
      speakFounderTitle: "প্ৰতিষ্ঠাপকৰ কথা: এই শব্দবোৰ কিয়",
      speakFounderDesc: "এই প্লেটফৰ্মত প্ৰতিটো শব্দ কাৰণ সহ নামকৰণ। ২৬ গুৰুত্বপূৰ্ণ নামৰ উৎপত্তি।",
      howBountiesWork: "অনুবাদ পুৰস্কাৰ কেনেকৈ কাম কৰে",
      step1Title: "পুৰস্কাৰ দাবী কৰক",
      step1Body: "Help Wanted বোৰ্ডৰ পৰা অনুবাদ পুৰস্কাৰ খোলক।",
      step2Title: "অনুবাদ কৰক আৰু দাখিল কৰক",
      step2Body: "সকলো প্ৰয়োজনীয় ষ্ট্ৰিং অনুবাদ কৰক। Bounty Poster মাধ্যমেৰে দাখিল কৰক।",
      step3Title: "Marks উপাৰ্জন কৰক",
      step3Body: "গ্ৰহণৰ পিছত Marks পাব। IP Ledger-ত নথিভুক্ত হ'ব।",
      hide: "লুকাওক",
      why: "কিয়?",
    },
    languageSwitcher: {
      changeLanguage: "ভাষা সলনি কৰক",
      selectLanguage: "ভাষা বাছক",
      quickEnglish: "ইংৰাজী",
      tip: "অনন্য অভিজ্ঞতাৰ বাবে Durin's Door-ত বিভিন্ন ভাষাৰ পাছৱৰ্ড ব্যৱহাৰ কৰক!",
    },
  },
  "ckb": {
    speakFriend: {
      title: "بڵێ هاوڕێ، دیکه بچۆ ژوورەوە.",
      description: "Liana Banyan بۆ هەموو زمانێک کراوەی دروست کراوە. هەر زمانێکی کراو یەک خەڵاتی وەرگێڕان هەیە.",
      languages: "زمانەکان",
      openBounties: "خەڵاتە کراوەکان",
      marksAwarded: "Marks دراوە (تۆکینی بەشداری)",
      provisional: "کاتی:",
      provisionalNotice: "لیستی زمانەکان و نرخی Marks کاتین. Marks تۆکینی بەشداری، نە سهامن.",
      bountyOpen: "خەڵات کراوەیە",
      claimed: "داواکراو",
      complete: "تەواو",
      translationBountyTitle: "خەڵاتی وەرگێڕان",
      bountyDescription: "Liana Banyan بۆ {{language}} وەرگێڕانی بکە. {{marks}} Marks بدەست بهێنە.",
      scopeWelcome: "خۆشی هاتنت / دنیای ڕوح",
      scopeCueCards: "سێتی کارتی ئیرشادی بنچینەیی",
      scopeNavigation: "نیشانەی ئاڕاستەکردن و پەیامی هەڵە",
      scopeWildfire: "Wildfire Beacon Run: کار بدۆزەرەوە",
      claimBounty: "ئەم خەڵاتی وەرگێڕانەی داوا بکە",
      baseLanguage: "زمانی بنچینە -- پێویستی بە خەڵات نییە.",
      claimedBy: "@{{handle}} داواکرد -- بەردەوامە.",
      marksProvisional: "{{marks}} Marks (کاتی)",
      speakFounderTitle: "دەنگی دامەزرێنەر: بۆچی ئەم وشانە",
      speakFounderDesc: "هەر تەرمێک لەسەر ئەم پلاتفۆرمە بۆ مەبەستێک ناوی لێناوە. بنەڕەتی 26 ناوی گرنگترین.",
      howBountiesWork: "خەڵاتەکانی وەرگێڕان چۆن کار دەکەن",
      step1Title: "داوای خەڵاتەکە بکە",
      step1Body: "خەڵاتی وەرگێڕان لە Help Wanted بکرەوە.",
      step2Title: "وەرگێڕان بکە و بنێرە",
      step2Body: "هەموو ستریگی پێویستی وەرگێڕانی بکە. ببنێرە ئەرێ Bounty Poster.",
      step3Title: "Marks بدەست بهێنە",
      step3Body: "دوای پەسەندکردن، Marks دەسپێی. لە IP Ledger تۆمار دەبیت.",
      hide: "شارێت بکە",
      why: "بۆچی?",
    },
    languageSwitcher: {
      changeLanguage: "زمان بگۆڕ",
      selectLanguage: "زمان هەڵبژێرە",
      quickEnglish: "ئینگلیزی",
      tip: "لە دەروازەی Durin پاسوردی زمانی جیاواز بەکاربهێنە بۆ کردنەوەی ئەزموونی بێهاوتا!",
    },
  },
  "ay": {
    speakFriend: {
      title: "Amuyu sata, manqhani.",
      description: "Liana Banyan aru aru armas mayacht'ayatawa. Uru aru ukham mayni utasiwa.",
      languages: "arukuna",
      openBounties: "katatawi ñanakiwa",
      marksAwarded: "Marks apaniwa (takikuna jach'a)",
      provisional: "Arumaki:",
      provisionalNotice: "Arukuna amtawi Marks janiwa arumakiw. Marks takikuna, janiwa akullakiwi.",
      bountyOpen: "Ñanaki jutiriwa",
      claimed: "Apaniwa",
      complete: "Tukuyi",
      translationBountyTitle: "Arunaka Ñanaki",
      bountyDescription: "Liana Banyan {{language}} arukt'ayapxisa. {{marks}} Marks luratawa.",
      scopeWelcome: "Waliki Jutimpi / Achachilanaka",
      scopeCueCards: "Jach'a Yatiyawi Qillqa",
      scopeNavigation: "Uñstawi mayniwa nayrawiñ",
      scopeWildfire: "Wildfire Beacon Run: Utjawayu",
      claimBounty: "Ukham Arunaka Ñanaki Apanipxata",
      baseLanguage: "Aru jiska -- ñanaki janiwa utjirikiti.",
      claimedBy: "@{{handle}} apanipxi -- jichhaki.",
      marksProvisional: "{{marks}} Marks (arumaki)",
      speakFounderTitle: "Yatichiri Kamachiri: Kunan Arunaka",
      speakFounderDesc: "Ukhamar layra aru mayjt'ayatanwa mayni kamachiriwa. 26 sutin yatiyani.",
      howBountiesWork: "Arunaka Ñanaki Kunjamakiwa",
      step1Title: "Ñanaki Apanipxta",
      step1Body: "Help Wanted aru qillqatata Arunaka Ñanaki uñt'ayapxta.",
      step2Title: "Arukt'ata Ulanipxta",
      step2Body: "Yäqikuna arukt'ata. Bounty Poster jiliriw ulanipxta.",
      step3Title: "Marks Lurapxta",
      step3Body: "Apanipxtana ukhamaki Marks luratawa, IP Ledger qillqatawa.",
      hide: "Kankayawi",
      why: "Kunjamsa?",
    },
    languageSwitcher: {
      changeLanguage: "Aru mayjt'ayapxta",
      selectLanguage: "Aru arunaka",
      quickEnglish: "Inglisaru",
      tip: "Durin Nayra arukuna jankuwi umanaña!",
    },
  },
  "sm": {
    speakFriend: {
      title: "Tautala uo, ona ulufale.",
      description: "Ua fausia Liana Banyan e tatala mo gagana uma. O gagana tatala taitasi e iai le tasi o le faafoi mea.",
      languages: "gagana",
      openBounties: "mea tatala",
      marksAwarded: "Marks tuuina atu (faailoga o auai)",
      provisional: "Faataunuuina:",
      provisionalNotice: "O le lisi o gagana ma aano o Marks e faataunuuina. Marks ni faailoga o auai, e le o saea.",
      bountyOpen: "Mea tatala",
      claimed: "Manaomia",
      complete: "Maea",
      translationBountyTitle: "Mea Faafoi",
      bountyDescription: "Faafoi Liana Banyan i le {{language}}. Maua {{marks}} Marks.",
      scopeWelcome: "Malo lava ia / Lalolagi Agaga",
      scopeCueCards: "Seti Kaade Faatonuga",
      scopeNavigation: "Faailoga faatonu ma fesilafai mea faasese",
      scopeWildfire: "Wildfire Beacon Run: Saili se galuega",
      claimBounty: "Manaomia le Mea Faafoi lenei",
      baseLanguage: "Gagana faavae -- e leai se mea manaomia.",
      claimedBy: "@{{handle}} na manaomia -- o lo'o faaauau.",
      marksProvisional: "{{marks}} Marks (faataunuuina)",
      speakFounderTitle: "Le Leo o le Faavae: Aisea nei Upu",
      speakFounderDesc: "O upu uma i luga o le faiga ua faaigoa i se mafuaaga. O le amataga o igoa 26 sili ona taua.",
      howBountiesWork: "Pe Faafefea Ona Galue Mea Faafoi",
      step1Title: "Manaomia le Mea",
      step1Body: "Tatala le Mea Faafoi mai le fao Help Wanted.",
      step2Title: "Faafoi ma Auina",
      step2Body: "Faafoi ni faamatalaga uma e manaomia. Auina atu e ala i le Bounty Poster.",
      step3Title: "Maua Marks",
      step3Body: "Ina ua mauaina, e maua Marks ma faamauina i le IP Ledger.",
      hide: "natia",
      why: "aisea?",
    },
    languageSwitcher: {
      changeLanguage: "Suia le gagana",
      selectLanguage: "Filifili le gagana",
      quickEnglish: "Igilisi",
      tip: "Faaaoga upu faasee o gagana eseese i le Faitotoa o Durin e tatala ai ni aafiaga ese!",
    },
  },
  "mi": {
    speakFriend: {
      title: "Ko te hoa, ka uru.",
      description: "I hangaia a Liana Banyan kia tuwhera ki ia reo katoa. He moni whakamahana kotahi mo ia reo tuwhera.",
      languages: "reo",
      openBounties: "moni whakamahana tuwhera",
      marksAwarded: "Marks homai (tohu urunga)",
      provisional: "Whai waa:",
      provisionalNotice: "Ko te rarangi reo me nga reiti Marks he whai waa. Ko Marks he tohu urunga, ehara i te hea.",
      bountyOpen: "Moni tuwhera",
      claimed: "Kua kiia",
      complete: "Oti",
      translationBountyTitle: "Moni Whakamāori",
      bountyDescription: "Whakamāori a Liana Banyan ki te {{language}}. Whiwhi {{marks}} Marks.",
      scopeWelcome: "Ngā mata Nau Mai / Te Ao Wairua",
      scopeCueCards: "Huinga Kaari Tohutohu",
      scopeNavigation: "Tohu arataki me nga korero hapa",
      scopeWildfire: "Wildfire Beacon Run: Kimi Mahi",
      claimBounty: "Kiia tenei Moni Whakamāori",
      baseLanguage: "Reo putake -- kaore he moni e hiahiatia ana.",
      claimedBy: "@{{handle}} i kiia -- kei te haere tonu.",
      marksProvisional: "{{marks}} Marks (whai waa)",
      speakFounderTitle: "Te Reo o te Kaiwhakaaro: He aha enei kupu",
      speakFounderDesc: "Ko ia kupu i tenei papanga he take ma tona ingoa. Ko te putake o nga ingoa 26 tino nui.",
      howBountiesWork: "Me pehea te mahi a nga Moni Whakamāori",
      step1Title: "Kiia te Moni",
      step1Body: "Huakina he Moni Whakamāori mai i te papa Help Wanted.",
      step2Title: "Whakamāori ka Tukua",
      step2Body: "Whakamāori i ngā raina katoa e hiahiatia ana. Tukua ma te ara Bounty Poster.",
      step3Title: "Whiwhi Marks",
      step3Body: "I muri i te whakaaetanga, ka whiwhi koe i Marks ka tohua ki te IP Ledger.",
      hide: "huna",
      why: "he aha?",
    },
    languageSwitcher: {
      changeLanguage: "Huri reo",
      selectLanguage: "Tohua he reo",
      quickEnglish: "Ingarihi",
      tip: "Whakamahia nga kupu huna reo rereke i te Kuaha o Durin hei whakatuwhera wheako ahurei!",
    },
  },
  "fj": {
    speakFriend: {
      title: "Tavuki vei gone, ka rawa.",
      description: "Liana Banyan e vakarautaki me vaka kena lewe mai vei ira kece na vosa. Na vosa kece tale ga e tiko na mereisi ni vosa-vaka-iwase.",
      languages: "vosa",
      openBounties: "mereisi veivosaki",
      marksAwarded: "Marks e solia (na koini ni veivukei)",
      provisional: "Vakayagataka tale:",
      provisionalNotice: "Na volau ni vosa kei na ivalue ni Marks e vakayagataka tale. Na Marks na koini ni veivukei, se siga yaco.",
      bountyOpen: "Mereisi e levu",
      claimed: "Kerei",
      complete: "Yaco sara",
      translationBountyTitle: "Mereisi ni Vosa-vaka-iwase",
      bountyDescription: "Vosavaka-iwase a Liana Banyan mai na {{language}}. Rawata {{marks}} Marks.",
      scopeWelcome: "Ni vinaka mai / Vanua ni Yalo",
      scopeCueCards: "Seti ni Kaadi Veivuke",
      scopeNavigation: "Ivakarau ni yaco kei na itukutuku ni sala ca",
      scopeWildfire: "Wildfire Beacon Run: Kuceci cakacaka",
      claimBounty: "Kerei na Mereisi Vosa-vaka-iwase oqo",
      baseLanguage: "Vosa ivakarau -- sega ni dikevi mereisi.",
      claimedBy: "@{{handle}} e kerei -- e yaco sara.",
      marksProvisional: "{{marks}} Marks (vakayagataka tale)",
      speakFounderTitle: "Na Levu-ni-sici: Na cava ko ira?",
      speakFounderDesc: "Na vosa kece mai na sitiseni oqo e vakatokai me vakasama. Ivakailevu 26 yacana.",
      howBountiesWork: "Veitalia na Mereisi ni Vosa-vaka-iwase",
      step1Title: "Kerei na Mereisi",
      step1Body: "Dolava na Mereisi ni Vosa-vaka-iwase mai na Help Wanted.",
      step2Title: "Vosavaka-iwase ka Solia",
      step2Body: "Vosavaka-iwase na strings kece e sega. Solia mai Bounty Poster.",
      step3Title: "Rawata Marks",
      step3Body: "Ni kerei yacova, o rawata Marks ka ni taukena mai na IP Ledger.",
      hide: "turia",
      why: "cava?",
    },
    languageSwitcher: {
      changeLanguage: "Solia na vosa",
      selectLanguage: "Digitaka na vosa",
      quickEnglish: "Vosa Peretania",
      tip: "Vakayagataka na ivurevure ni vosa tani mai na mataiValagi ni Durin me rawata na kena yavusa!",
    },
  },
};
